(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"PracticeCard_CRuiz_atlas_1", frames: [[0,0,2550,3300]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Myproject3pngcopy = function() {
	this.initialize(ss["PracticeCard_CRuiz_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.ilym = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgoTgatMBQnAAAMAAAA1bMhQnAAAg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgoTAauMAAAg1bMBQnAAAMAAAA1bg");
	this.shape_1.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-259,-171.9,518,343.9);


(lib.flap = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg6WgZOMA4uAydMA7/gydg");
	this.shape.setTransform(0.025,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99CCFF").s().p("Eg6WgZOMB0tAAAMg7/Aydg");
	this.shape_1.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-374.4,-162.5,748.9,325);


(lib.BasicButton = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMBTQgIgFgEgJQgEgJAAgVIAAgrIgSAAIAAgjIASAAIAAgXIAvgYIAAAvIAaAAIAAAjIgaAAIAAArQAAAIABADQADADAFAAQAGAAAJgDIAEAiQgSADgPAAQgRAAgJgEg");
	this.shape.setTransform(74.825,25.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAXA+IgXgoIgaAoIg0AAIAthAIgqg7IA4AAIATAiIAXgiIA0AAIgqA7IAuBAg");
	this.shape_1.setTransform(61.525,27.875);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgmA6QgPgHgJgPQgJgPAAgVQAAgcASgSQAUgSAgAAQAaAAAQAIQAPAIAIAQQAIAPAAAXIAAAGIheAAQABALAEAGQAIAIAJAAQAIAAAGgDQAEgDAFgFIAuAEQgLATgPAIQgPAIgcAAQgYAAgOgHgAgRgbQgFAGAAALIAuAAQgCgOgGgGQgGgGgKAAQgKAAgHAJg");
	this.shape_2.setTransform(46.15,27.875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAgBWIg/hdIAABdIgyAAIAAirIAxAAIBABeIAAheIAyAAIAACrg");
	this.shape_3.setTransform(28.1,25.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Rounded
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("AnBj5IODAAQAyAAAAAyIAAGPQAAAygyAAIuDAAQgyAAAAgyIAAmPQAAgyAyAAg");
	this.shape_4.setTransform(50,25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_5.setTransform(50,25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF99").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_6.setTransform(50,25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_7.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_6},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_4}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

	// Squared
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("Anzj5IPnAAIAAHzIvnAAg");
	this.shape_8.setTransform(50,25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCCCC").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_9.setTransform(50,25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFF99").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_10.setTransform(50,25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_11.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8}]}).to({state:[{t:this.shape_10},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_8}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,102,52);


// stage content:
(lib.PracticeCardCRuiz = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,19,29];
	// timeline functions:
	this.frame_0 = function() {
		this.stop(); // This will make the main timeline stop on the current frame
		
		
		this.btn_Next.addEventListener("click", fl_ClickToPlay.bind(this));
		
		function fl_ClickToPlay()
		{
			this.play();
		}
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(10).call(this.frame_29).wait(1));

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhNBfQADgXAOgUQANgVAmgbQAVgQAHgJQAFgJAAgIQAAgIgFgGQgHgGgKAAQgIAAgHAGQgGAGgCAQIg0gEQADgWAJgMQAHgMAPgHQAPgHAZAAQAbAAAQAHQAPAGAIANQAJANAAAQQAAARgKAPQgKAPgaASIgVAPIgLAMIBPAAIAAAqg");
	this.shape.setTransform(278.3,705.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhNBfQADgXANgUQAOgVAmgbQAVgQAGgJQAGgJABgIQgBgIgGgGQgGgGgKAAQgJAAgGAGQgGAGgCAQIg0gEQADgWAIgMQAIgMAQgHQAOgHAZAAQAcAAAPAHQAPAGAIANQAJANAAAQQAAARgKAPQgJAPgbASIgVAPIgLAMIBQAAIAAAqg");
	this.shape_1.setTransform(260.95,705.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglBZQgPgIgJgOQgHgKgDgSQgEgSAAgVQAAg1ATgVQATgVAmAAQATAAAMAFQAMAEAIAIQAHAHAFAIQAEAIADALQAFAVAAAXQAAAxgRAYQgRAXgqAAQgXAAgOgHgAgSgwQgGANAAAjQAAAjAHANQAGANALAAQAIAAAFgFQAGgGADgMQADgMAAgZQAAgkgHgNQgGgNgMAAQgMAAgGANg");
	this.shape_2.setTransform(243.825,705.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBfQACgXAOgUQANgVAlgbQAWgQAGgJQAHgJgBgIQABgIgHgGQgGgGgJAAQgKAAgFAGQgHAGgCAQIg0gEQADgWAIgMQAJgMAPgHQAOgHAZAAQAbAAAPAHQAQAGAJANQAIANAAAQQAAARgJAPQgLAPgaASIgVAPIgLAMIBQAAIAAAqg");
	this.shape_3.setTransform(226.25,705.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAdQAPgHAGgHQAFgGABgJIgbAAIAAgzIA3AAIAAAqQAAAXgKAOQgKAOgWAKg");
	this.shape_4.setTransform(204.825,715.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhDBcIgFgkQAMADANAAQAKAAAFgEQAGgEAEgLIg4iGIA2AAIAbBaIAahaIAyAAIg1CQQgKAYgJAJQgMAMgcAAQgLAAgXgDg");
	this.shape_5.setTransform(194.85,711.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhAA7QgNgLAAgQQABgPAIgLQAJgIAYgFIAlgIQAJgDAJgEQAAgJgDgEQgFgEgJAAQgMAAgHAFQgEACgEAJIgwgFQACgNAGgHQAFgHAJgGQAIgEAMgCQANgDAOABQAXAAAOACQAOADAJAIQAGAGAEAKQAEALAAAJIAAA7QAAAJABAGQABAFAFAIIgxAAIgEgIIgBgIQgKAKgLAEQgNAGgRAAQgZAAgMgMgAAAAKQgQAEgEAFQgFAEAAAFQAAAGAFAEQAEAEAIAAQAIAAAHgEQAIgEADgGQACgHAAgJIAAgJQgKAEgKADg");
	this.shape_6.setTransform(178.15,708.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA5BdIAAiNIgkCNIgqAAIgkiNIAACNIgvAAIAAi5IBMAAIAcBwIAdhwIBMAAIAAC5g");
	this.shape_7.setTransform(157.225,705.95);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBZQgJgEgEgLQgFgJAAgXIAAgvIgTAAIAAgmIATAAIAAgYIAzgaIAAAyIAdAAIAAAmIgdAAIAAAvQAAAJACADQACAEAHAAQAFAAALgEIAEAkQgUAEgQABQgTgBgJgFg");
	this.shape_8.setTransform(130.475,706.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag0BFIAAiGIAwAAIAAAWQAGgOAIgGQAHgFALAAQALAAAOAHIgQAlQgJgEgFAAQgLAAgFAJQgHAMAAAfIAAAtg");
	this.shape_9.setTransform(118.775,708.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AApBdIgJgfIhBAAIgJAfIg6AAIBGi5IA9AAIBGC5gAgUAWIAoAAIgUhCg");
	this.shape_10.setTransform(101.825,705.95);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhJBfIAAi6IAwAAIAAAUQAKgMAIgFQALgGANAAQAbAAAPAVQAPAVAAAeQAAAhgQASQgQARgZAAQgMAAgJgEQgJgEgIgIIAABBgAgPgwQgHAIAAARQAAAQAHAHQAHAIAJAAQAJAAAGgIQAGgGAAgSQAAgQgGgIQgGgIgJAAQgJAAgHAIg");
	this.shape_11.setTransform(74.675,710.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AA/BFIAAhMQgBgJgDgEQgFgIgIABQgJAAgFAGQgGAHAAAOIAABFIgzAAIAAhKIgBgMQgCgFgEgDQgEgCgGAAQgIAAgGAGQgFAHgBAOIAABFIg0AAIAAiGIAxAAIAAAUQAKgMALgGQAKgFAQAAQAQAAAIAGQAKAGAFALQAMgNALgFQAKgFAPAAQAVAAAMANQANANAAAbIAABUg");
	this.shape_12.setTransform(52.7,708.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag0A2QgYgUAAghQAAgfAUgUQAVgTAjAAQAogBAVAYQAQATAAAbQAAAfgUATQgVAVgkAAQgggBgUgQgAgRgZQgIAIAAASQAAASAIAIQAHAJAKAAQALAAAHgJQAHgIAAgTQAAgQgHgJQgHgJgLAAQgKAAgHAJg");
	this.shape_13.setTransform(30.975,708.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgrBYQgTgJgNgWQgOgXgBgiQABgtAYgZQAYgZAtAAQAiAAAVAOQAUAOAJAeIgyALQgDgIgDgEQgFgHgGgDQgIgEgIAAQgTAAgKAQQgIALAAAZQAAAeAKAMQAIALARAAQAQAAAJgJQAIgJAEgSIAyAPQgFAWgKAOQgLAOgQAHQgRAHgZAAQgdAAgUgIg");
	this.shape_14.setTransform(12.4,705.925);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhCBEIAAgiIBBhBIg8AAIAAgjIB8AAIAAAeIhDBEIBHAAIAAAkg");
	this.shape_15.setTransform(251.375,667.85);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZBdIAAiGIAzAAIAACGgAgZg5IAAgjIAzAAIAAAjg");
	this.shape_16.setTransform(239.875,665.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag6A4QgMgNAAgaIAAhVIA0AAIAABJQAAANAEAFQAFAGAJAAQAIAAAGgIQAGgGAAgSIAAhBIAzAAIAACGIgwAAIAAgWQgLANgLAHQgKAFgQAAQgVAAgMgNg");
	this.shape_17.setTransform(226.825,668);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAaBdIgdg5QgGgLgFgDQgGgFgIABIgFAAIAABLIg6AAIAAi5IBfAAQAbAAAOAFQAOAEAJANQAJAMAAARQAAAQgIALQgGAMgMAFQgHAFgMADQAKADAFAEIAJAKIAHALIAdA2gAghgQIAYAAIAOgDQAGgBAEgFQADgFAAgGQABgJgGgFQgGgEgPAAIgZAAg");
	this.shape_18.setTransform(209.6,665.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgqBYQgUgJgNgWQgPgXAAgiQAAgtAZgZQAYgZAtAAQAiAAAVAOQAUAOAJAeIgyALQgDgIgDgEQgFgHgGgDQgIgEgIAAQgTAAgKAQQgIALAAAZQAAAeAKAMQAIALARAAQAQAAAJgJQAIgJAEgSIAyAPQgFAWgKAOQgLAOgQAHQgRAHgZAAQgeAAgSgIg");
	this.shape_19.setTransform(179.9,665.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhEBcIgDgkQALADANAAQAKAAAFgEQAGgEAEgLIg4iGIA2AAIAbBaIAahaIAyAAIg1CQQgJAYgKAJQgMAMgcAAQgLAAgYgDg");
	this.shape_20.setTransform(153.1,670.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgGBYQgJgEgKgNIAAAVIgwAAIAAi5IA0AAIAABAQAIgIAJgEQAJgFAMAAQAZABAQARQAQASAAAgQAAAWgHARQgIARgNAIQgNAJgQAAQgNAAgKgHgAgPAAQgHAIAAAPQAAASAHAIQAGAIAKAAQAJAAAGgIQAGgHAAgTQAAgQgGgHQgGgHgJAAQgJAAgHAHg");
	this.shape_21.setTransform(136.725,665.45);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag7BKQgOgWAAgdQAAghAQgSQAQgRAZgBQAMAAAJAFQAKAEAHAIIAAhAIA0AAIAAC5IgwAAIAAgVQgKANgJAEQgKAHgNAAQgcgBgPgUgAgPAAQgGAHAAASQAAARAGAHQAGAIAJAAQAJAAAHgIQAHgIAAgSQAAgPgHgIQgHgHgJAAQgJAAgGAHg");
	this.shape_22.setTransform(110.025,665.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgqA/QgPgIgKgQQgKgQAAgXQAAgfAUgTQAUgUAkAAQAcABARAIQARAJAIARQAJAQAAAaIAAAGIhnAAQACAMAFAHQAIAIALAAQAHAAAHgEQAEgCAFgGIAzAFQgMAUgQAJQgRAJgeAAQgagBgQgHgAgSgdQgFAGgBAMIAxAAQgBgPgHgHQgGgGgLAAQgLAAgHAKg");
	this.shape_23.setTransform(93.075,667.85);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgNBZQgJgFgEgJQgFgLAAgWIAAguIgTAAIAAgmIATAAIAAgZIAzgaIAAAzIAdAAIAAAmIgdAAIAAAuQAAAJACACQACAFAHAAQAFAAALgEIAEAkQgUAFgQAAQgTAAgJgGg");
	this.shape_24.setTransform(78.575,665.45);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhAA8QgMgMAAgQQAAgPAJgKQAJgKAXgEIAlgJQAJgCAKgDQgBgKgEgEQgDgEgKABQgMAAgHADQgEAEgDAIIgygFQADgNAFgHQAFgHALgGQAGgEANgCQAMgCAPgBQAXAAANAEQAOACAKAIQAHAGADALQAEAJAAALIAAA6QAAAKABAFQACAFAEAJIgxAAIgEgIIgBgJQgLAKgJAEQgOAFgSABQgYgBgMgKgAgBAKQgQAFgDADQgFAEAAAGQAAAGAFAEQADAEAJAAQAIAAAHgFQAHgDADgHQADgFABgKIAAgJQgLAEgLADg");
	this.shape_25.setTransform(64.6,667.85);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgqA/QgPgIgKgQQgKgQAAgXQAAgfAUgTQAUgUAkAAQAcABARAIQARAJAIARQAJAQAAAaIAAAGIhnAAQACAMAFAHQAIAIALAAQAHAAAHgEQAEgCAFgGIAzAFQgMAUgQAJQgRAJgeAAQgagBgQgHgAgSgdQgFAGgBAMIAxAAQgBgPgHgHQgGgGgLAAQgLAAgHAKg");
	this.shape_26.setTransform(47.275,667.85);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag0BFIAAiGIAwAAIAAAXQAGgPAIgGQAHgFALAAQALAAAOAHIgQAlQgJgEgFAAQgLAAgFAIQgHAMAAAgIAAAtg");
	this.shape_27.setTransform(33.525,667.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgrBYQgTgJgNgWQgOgXAAgiQgBgtAZgZQAZgZArAAQAjAAAVAOQAUAOAKAeIgzALQgDgIgDgEQgEgHgIgDQgGgEgJAAQgTAAgKAQQgIALAAAZQAAAeAJAMQAKALAQAAQAQAAAJgJQAIgJAEgSIAyAPQgEAWgMAOQgKAOgRAHQgQAHgZAAQgdAAgUgIg");
	this.shape_28.setTransform(16.7,665.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},20).wait(10));

	// Layer_3
	this.instance = new lib.Myproject3pngcopy();
	this.instance.setTransform(313,40,0.2025,0.2041);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(23).to({_off:false},0).wait(7));

	// Layer_2
	this.instance_1 = new lib.ilym("synched",0);
	this.instance_1.setTransform(571,542.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).wait(1).to({y:429.5833},0).wait(1).to({y:316.2667},0).wait(1).to({y:202.95},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Layer_1
	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#000000").ss(1,1,1).p("EgoTgatMBQnAAAMAAAA1bMhQnAAAg");
	this.shape_29.setTransform(571,542.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("EgoTAauMAAAg1bMBQnAAAMAAAA1bg");
	this.shape_30.setTransform(571,542.925);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_30},{t:this.shape_29}]},20).wait(10));

	// Button
	this.btn_Next = new lib.BasicButton();
	this.btn_Next.name = "btn_Next";
	this.btn_Next.setTransform(890.15,684.65);
	new cjs.ButtonHelper(this.btn_Next, 0, 1, 2, false, new lib.BasicButton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_Next).wait(30));

	// s1 flap
	this.instance_2 = new lib.flap("synched",0);
	this.instance_2.setTransform(481.5,396.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(0.7,1,1).p("AAEAAQAAAFgBADQgCADgBAAQAAAAgCgDQgBgDAAgFQAAgDABgEQACgDAAAAQABAAACADQABAEAAADg");
	this.shape_31.setTransform(869.5,389.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#000000").ss(1,1,1).p("EApGg9yQABAFABAHQAOBBAcBJQAmBiBABvQCLDrDlDGQDkDFIXEEQIXEEK8heIAS2HgEBIBgeaIAAnbEAv6gl9IFKmoEA7KggpIDdmxEAlcgvfIGojDEAfWg7SIIFAAEA2LgBRQACgEAGgLQAGgJAFgFQAKgLAQgBQAQgCAOAHQALAGAMANQAGAHAMAOQAqAfAhAhEA1wgA6QAPgFALgRQAAAAABgBQAMgBAJAFQAIAFAFAHIAAABQAEAGAAABQABADABAJQAMgBAEAAQAaAAAOAOEA2zgAtQgFAAgFABQgEABgFAAQgGAAgDAAIAAABQAEAsAMAYQALAYAZATQAWATAkADQALABAMAAQAMAAAXgCQAEgBAEAAQAcgCAOAAQAEAAAEAAIARAAQAGgBALgFQALgEAHgFQgXgFgWgUQgCgCgDgCEA1wgA6IgBABIgBAAIApAPEA1wgA6QAKgDAHABQAQAAAAAAQAQABAMgFEA39gBPQAAABABABQABAAAAAAEA31gBUQADACAEADQAAAAABAAQgJgBgFAKQgEAIAAAIQAAANAAAJQAAAFAAAEQACARAHAKQAHAMAQAJQACABACACQAEACAEACIAAgOQAAgCADgCIACABQAIAGAIACQAEAAABgBQACgCAAgCIAAgUIAKAGQADAEAEAAQAEAAACgFQACgDgCgNQAJAKAJAKQAUAYALAMEBDeAG2QgBh+gMiLQAzASAdgRQgEBUgICpIgBADQghgFgVANgEBAzAGkIA7AGIBvAMIABAAEA/ZAMRIABCPQAWADAWADQAsAFBGAFQANABAOABQABABACAAQACABAFABQABAAABABQACACABADQAEALAAALQADAPABAWQAAAIAAAJQAAANAAAJQgBAFAAAEQAAADgBADIAAAAQAAACAAABQgCAEAAgGQAAgDAAgFQAAgEAAgFIAEABEBAGAMZIAACNEAzAAJ1QApADAsAGQB7AQDAAtQEOA+AvAJQAmAIAmAHQAXAEAWAEQAcAFAcAFQAaAEAaAFQAAAWABALQABAEABAIQADAKAAAHQABALAAATQAAAVgBATEBDZAIlQAIgBANABQAMABAeACQgKARAAAhQgCBqAHBWQAAAOAAABQgBAIgEAGQgZAJgDAAQgFgBgGgBEBBuAIZQA0AGA3AGIAOEZEBAzAIUQAdADAeACEBCfAO2IAAAAQAPgDgbgBEBCRAOuQAAADACABEBByAMsQA7AJA6AJEA/uAGcIAABwQAiAEAjAEEBAzAGkIAABwEA/uAGcIBFAIEBBuAGqIAABvEA6XARLQAhgGA3gcQA9geAbgIQANgEATgEQAHgBAIgBQAqgHAGgBQApgJBQgdQA3gRBJgEEA4XAAgQAGACAHADQAqALAtgFEA4FABbQgQAMgCACQgLAJgDABQgFADgMAAIggAAQgGAFABAGQADAGAIABIAdgDQATgCAGgEQAIgEAMgMQAMgMAMgHEA4/ABaIg8AnIAZAEQACABAEABQADABABACQACADgBADQgCADgDAAQgegIgdANQgCABgCABQgMAGgGACQgLAEgGgIQABgEAEgDQAEgEAJgDQAFgBATAAQgMgBgbAAQgGABgFgGIACgBEAypAFUQAGAAAGAAQA7gBA9AEQBuAHDrAYIFoAmEA3FACXQARAAARABQE/ALGrAKEAxHAFXQAbgCAcAAQAVgBAWAAIAABdQAHABAIABQADAAAEABQFHAkHoA0EAx+AFVIAABTEAxHAFXIAABPQAvAGAzAFEAxHAFXQhDAFhAAKQACheAIiHQDKALEtALEAxMAJwQhAgBhAAFQgFhZAAh9QA6AABGAIEAxMAJwQgCAWABALQABAGACAMIAAAvQAAACAAACQAXAFA5AQQAQAFAQAFQADABADABQALACAJADQF+BwGEA0EAppAMoQAIgCAJgDQALgDAUgIQAMgFAwgMIAygLQBDgQBvguQBBADBQAUQACAAACABEAybAJyQgBAjAAALQABAGABAMIAAAKQADAUgBAbEAxMAJwQAnAAAoACQARABASACQABAAABAAIAECCEA3GAZfQABgVAKgZQAAgDAYgxQASgkAziMQAlhmAog5EA3GAZfIhVgXQAGgoAbg4QAphUADgJQAGgQAUhAQAOgyAPgdQARgeAGgPQALgbgGgTEA6iAS5QhUCygmDLQAAACgBACIhhAtQAAgEAAgEEBCmAQtIACgBIAEgBEBA0ARRQACAAACgBIBugjEBA0ARRQAoAxAUAZQAGAHAMAOQAKAMAJAIQAfAcA3ATQAcAIAzAQQAJADAJADEBECARvIBdB+IgTAkEBCoAQsICkDlEBCqAP2IBYB5QGWCTGVESMAAAAlgMihZAAAMAAAglMQFoiyCVgvQKxjdKbg0EA7UATAQAxgYAhgNQA0gVAtgKQAagGA0gKQAZgFBGgWEAppAMoQApAFFYBwQGNCBEdAwIBAByIxNkvIgxgOQABg5ANghQACAAADgBgEAqbAOXQgBAJgEAMQgDAGgKAWQgaA3gTA5QgZBFgZBJQAEACAJAHQAIAHAFgDQAEgDBAAWIA0gdQgFgdADgWQADgXAQgiQAPgiALgUQAKgUACgEQAYgnAogmEAr/AOzQgTAngeA+QgKAVgMAYQgpBbgHBGEAnCARpQBNgbBNgWAZtYeQGwkgGliVEArzAQPQBkgYBjgPEggrg06QgGiHAthfQAqhbBXg1QAsgcA0gQQCHgsC1AgQAcAEAfAIQBIAPBZAcQBKAWCPAtQDaBDDvARQBZAHAaAEQBAAKAsAZQA1AeAZA3QAaA6gYAyQBzAFBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBjQBKBhADB0QADB0hFBlQhFBlhsAoQBRA2AUBqQAVBpg3BRQg3BQhqATQhqAShQg5QAuBLgPBeQgQBehDA4QhEA5hegCQhWgBg/gxQAbAbgIAwQgKA3grAbQgmAYg3AFQgkAChBgGQi3gQhugqQiMg1g6hnQgFgKAngYQgRARgRAREggrg06QAjgbAWgMQBCgnBMgRQBNgPBMALQBTALAeAxQATAdgLAjQgMAlggAEQAugEBggTQBdgSAxgEQBPgGBCARQBLASAxAvQA2A0AGBMQAGBQg1AvQBtgjBkBXQBiBVgEB1QgFBwhZBaQhVBVh1AWQAeBTgOBbQgOBbg3BGQg2BFhWAkQhVAjhXgKQh1BWiZgFQgGAAgFAAQiQgJhohWQhTHZCsBeQCqgWDVjXQAmgnAngsIAAECIAxA+Aq81rQgGgEgGgFA3n6aQhfgag7hBQg6hBgMhPQAAgDgBgCEgwDg4dQB3hLBNgeQB7gwBnATQA4AJAxAoQAvAnAaA1QAbA3gFA0QgEA1gkAlQgDADgCACEgnhghaQhLgVhIg5QiQhzgYitQgKhDAKhDQAJhFAbg+QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgYQBFgZAhgRQAkgTA+gwQAWgRASgNEgm9g1RQBLhHBxgBQB1gBBNBLQALAKAJALEg5Gg3VQBQhQBkg3QBng6BzgaQBsgYA4AnQAkAYADAxQACAngYAUQgGAEgHAEEgtVgfGQgGgSgFgTQgNgpgJgtIhFCWIi/AAQAUAbATAcQACCIgyBeQgyBdhZAtQhZAthogPQhpgPhIhFQg/BNhnAfQhfAdhqgRQhpgShQg8QhWg/giheQhAA2hMAUQhTAVhGgfQhKgggZhUQgahXA2g4Qg3AehCgYQhAgYgjg5QgggygKhFQgIg2AFhLQAYlRDLkiQDKkhE0iLQBWh/CAhaQCAhbCUglQBEgSAnAUQAZAOAHAeQAGAYgNAQQgCAEgFADEgnhghaQgvAigdAUQhcA+hFAWQhFAVhCgLQBTDuDCB9QAhAWAlASQAOAHAQAHQCMjYA4lbQALhEAIhJQABgKABgKQACgNABgNIASAkQgLAEgMAGA+//kQgDgCgCgCEgjugjvIBrDRIDhhVQgRBMgMBDEgkYghYQh4AVhRgXEgxTgd0QAGAIAFAJQJhOgqxc5QgkBegnBiQC9gPC7gBQKDgFJuCaQAPgGAPgGQg1ijivulQiruLJgpnAFIHJQAAgGgBgGQBIgdA0g+QAzg/AOhMQAFgfgKgOQgPgYgrADQgaADgYALQgFACgFACQgTAKgTAPQgOALgOAPQgOAPgPAWQAIgMAFgIQAVgbAXgQAJ/KyQgCgGgCgHQgIgegSgZQgHgJgJgJQgvgzhggdQgjgLgMgEQgZgKgSgJQgTgJgNgYAJ/LiQABgOgCgPQgEgwgZgnAJ/KyQASgDASAJQASAJAIASQAIASgGAnQAAACAAABQgFAjgQALQgMAJgZACQgXADgMgIIAAgGQAJgOAHgQQADgJADgIQAGgWABgWQAEgXgEgZgAEMNpQAAADACADQABAFADAFQAHAJAMAFQAMAFAjACQAZACAyAEQAsADAfgGQAtgKAkgeQAYgUAPgYAC5FDQABgBACAAQAAgZASgxQAahGAOgeQALgYAKgMQANgTAQgJQARgLAWABQAWABANAPQAKALAEAYQAGAeADAMAD3FhIAQgiQAVgpAOgXQgYAjgaAyAgeHrQgBgIABgIQACgQAIgOQAAgCABAAQAGgLAOgSQAageAHgHQATgUASgMQAmgYAwAAQALAAALABQADAAADABQAfAFAbARACEHUQAAAHgFAEQgEAFgHAAQgGAAgFgFQgEgEAAgHQAAgGAEgFQAFgEAGAAQAHAAAEAEQAFAFAAAGgAgeHrQAGgBAKAAQAGAAACACQAGADAAAKQgBAKgIAFQgDADgLAGQgFgMgBgNQgBgHAAgGgABoJrQgDgBgEAAQhFgNgiguQgLgOgGgQAB4MpQgNAJgHADQgLAEgBAAQgNAFgFAJQgHAQAKASQALAVATAEQAKAMAhAAQARAAAIgBQAOgBAKgFQATgKAUgnQABgCAAgBQALgWAAggQAAgEAAgDQAAgfgNgZAG1JmQglANgcASQgyAkgJAmQgGAZAIAgQABAEACAGQAFAPAKAYQAAABABAGQgKAAgIACQghAGgHAIQgIAJgBAKQAAADABADABoJrQAmAHAmgHQArgHAigYQAjgYATgmQARgiAAgjABoJrQgJArAEAjQAFAjARAeQALAQAHALQADAEACADQAGAJABADQAFAIgBAEQgCAHgLAGQgTAJgJAIQgOALAAAOQAAALADAMACKMdQgPAJgDACIAAABADqNWQAOAKAHAEQAFADAIACAGSNVQgogUgcgBA56S7IAxgMIAMgCA5JSvQA0gUA0gSIZZlgA56S7QLoC3HqC2AK/MPQOKAZN5FB");
	this.shape_32.setTransform(517.525,397.35);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#664C00").s().p("AgTABQACgDADgDIAiABIgFACQgLAFgFACIgIABQgGAAgEgFg");
	this.shape_33.setTransform(871.475,413.0279);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#66411C").s().p("AgCAIIgBgIIABgHQABgBAAAAQAAgBABAAQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAAAHIAAAIQgBAAAAABQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAgBQAAgBgBAAg");
	this.shape_34.setTransform(869.5,389.55);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AhPANIgBgNIAPAAQAHAAACABQAGADABAKQgDAKgHAGQgDACgMAGQgEgMgBgNgAA3gLQgFgEAAgHQAAgGAFgEQAFgFAGAAQAGAAAFAFQAFAEAAAGQAAAHgFAEQgFAFgGAAQgGAAgFgFg");
	this.shape_35.setTransform(522.55,446.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAuDlIhKgGQgjgCgLgFQgMgFgHgJQgEgFgBgFIABAAIAAAAQgBgBAAABIgCgGIAAgFIAAgBQAAgKAIgJQAIgHAggHIANgCIABAAIAAAAIAEAAIABAAIgCgHQgKgXgFgQIgDgKQgEgSAAgPQAAgNADgLQAJglAxgkQAbgSAmgNQgmANgbASQgxAkgJAlQgDALAAANQAAAPAEASIADAKQAFAQAKAXIACAHIgBAAIgEAAIAAAAIgBAAIgNACQggAHgIAHQgIAJAAAKIAAABIAAAFIgNgFIgVgOIACgDQAKgWABggIAAgEIAAgDQgBgfgMgZQAMAZABAfIAAADIAAAEQgBAggKAWIgCADQgTAngUAKQgKAFgOABIgZABQggAAgLgMQgDgMAAgLQAAgOAOgLQAKgIATgJQALgGABgHQABgEgFgIIgHgMIgFgHIgSgbQgRgegEgjQgFgiAKgrQAlAHAmgHQAsgHAigYQAigYAUgmQAQgiAAgjQANAZATAIQASAJAZAKIAuAPQBgAdAwAzQAIAJAHAJQAZAnAFAvQABAPAAAOQgCAWgGAWIgGARQgGAQgJAOQgQAYgXAUQglAegtAKQgWAEgcAAIgZgBgAAiCmQgngTgcgCQAcACAnATg");
	this.shape_36.setTransform(554.3751,466.0368);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#009900").s().p("EhQsAYyMAAAglLQFoiyCVguQKxjdKcg1QC8gOC7gCQKDgFJuCaIAxgLIAMgDIBcgkIZZlgQgNAKgHACIgMAFQgNAEgFAKQgHAQAKARQALAWATADQAKANAhAAIAZgBQAOgCAKgFQATgKAUgnIAVAOIANAGIACAGQABAEADAFQAHAKAMAEQAMAGAjACIBLAGQAsACAfgGQAtgJAkgfQAYgTAPgZIAAAHQAMAIAXgDQAZgCAMgJQAQgMAFgiQOKAYN5FCQmlCVmwEfQGwkfGliVQBNgbBNgXIgyCOIANAKQAIAHAFgDQAEgDBAAWIA0gdQgFgeADgWQADgWAQgiIAZg2IANgYQBkgYBjgQIiHgmIg0gPIhkgcIgUgGIRNEwQAxgYAhgNQA0gWAtgKIBOgQQAZgFBGgVIA8BKIASAVIATAUQAfAbA3ATIBPAZIASAFIATgjIhdh+QGWCSGVESMAAAAlfgEA4MgSCQgGAQgRAeQgPAdgOAxQgUBBgGAQIgsBdQgbA3gGAoIBVAYIAAAIIBhgtIABgEQAmjMBUiyIgogLIhpgdQAGAUgLAagAmosZQnqi1roi4QLoC4HqC1gAEO3RQAAgBAAAAIABABg");
	this.shape_37.setTransform(517.525,634.2875);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#000000").ss(1,1,1).p("EApGg9yQABAFABAHQAOBBAcBJQAmBiBABvQCLDrDlDGQDkDFIXEEQIXEEK8heIAS2HgEBIBgeaIAAnbEAv6gl9IFKmoEA7KggpIDdmxEAlcgvfIGojDEAfWg7SIIFAAEA2LgBRQACgEAGgLQAGgJAFgFQAKgLAQgBQAQgCAOAHQALAGAMANQAGAHAMAOQAqAfAhAhEA1wgA6QAPgFALgRQAAAAABgBQAMgBAJAFQAIAFAFAHIAAABQAEAGAAABQABADABAJQAMgBAEAAQAaAAAOAOEA2zgAtQgFAAgFABQgEABgFAAQgGAAgDAAIAAABQAEAsAMAYQALAYAZATQAWATAkADQALABAMAAQAMAAAXgCQAEgBAEAAQAcgCAOAAQAEAAAEAAIARAAQAGgBALgFQALgEAHgFQgXgFgWgUQgCgCgDgCEA1wgA6QAKgDAHABQAQAAAAAAQAQABAMgFEA1wgA6IgBABIgBAAIApAPEA39gBPQAAABABABQABAAAAAAEA31gBUQADACAEADQAAAAABAAQgJgBgFAKQgEAIAAAIQAAANAAAJQAAAFAAAEQACARAHAKQAHAMAQAJQACABACACQAEACAEACIAAgOQAAgCADgCIACABQAIAGAIACQAEAAABgBQACgCAAgCIAAgUIAKAGQADAEAEAAQAEAAACgFQACgDgCgNQAJAKAJAKQAUAYALAMEBDeAG2QgBh+gMiLQAzASAdgRQgEBUgICpIgBADQghgFgVANgEBAzAGkIA7AGIBvAMIABAAEA/ZAMRIABCPQAWADAWADQAsAFBGAFQANABAOABQABABACAAQACABAFABQABAAABABIAAAAQAPgDgbgBEBAGAMZIAACNEAzAAJ1QApADAsAGQB7AQDAAtQEOA+AvAJQAmAIAmAHQAXAEAWAEQAcAFAcAFQAaAEAaAFQAAAWABALQABAEABAIQADAKAAAHQABALAAATQAAAVgBATEBDZAIlQAIgBANABQAMABAeACQgKARAAAhQgCBqAHBWQAAAOAAABQgBAIgEAGQgZAJgDAAQgFgBgGgBEBBuAIZQA0AGA3AGIAOEZEBAzAIUQAdADAeACEBCfAO2QACACABADQAEALAAALQADAPABAWQAAAIAAAJQAAANAAAJQgBAFAAAEQAAADgBADIAAAAQAAACAAABQgCAEAAgGQAAgDAAgFQAAgEAAgFIAEABEBCRAOuQAAADACABEBByAMsQA7AJA6AJEA/uAGcIAABwQAiAEAjAEEBAzAGkIAABwEA/uAGcIBFAIEBBuAGqIAABvEA6XARLQAhgGA3gcQA9geAbgIQANgEATgEQAHgBAIgBQAqgHAGgBQApgJBQgdQA3gRBJgEEA4XAAgQAGACAHADQAqALAtgFEA4FABbQgQAMgCACQgLAJgDABQgFADgMAAIggAAQgGAFABAGQADAGAIABIAdgDQATgCAGgEQAIgEAMgMQAMgMAMgHEA4/ABaIg8AnIAZAEQACABAEABQADABABACQACADgBADQgCADgDAAQgegIgdANQgCABgCABQgMAGgGACQgLAEgGgIQABgEAEgDQAEgEAJgDQAFgBATAAQgMgBgbAAQgGABgFgGIACgBEAypAFUQAGAAAGAAQA7gBA9AEQBuAHDrAYIFoAmEA3FACXQARAAARABQE/ALGrAKEAxHAFXQAbgCAcAAQAVgBAWAAIAABdQAHABAIABQADAAAEABQFHAkHoA0EAx+AFVIAABTEAxHAFXIAABPQAvAGAzAFEAxHAFXQhDAFhAAKQACheAIiHQDKALEtALEAxMAJwQhAgBhAAFQgFhZAAh9QA6AABGAIEAxMAJwQgCAWABALQABAGACAMIAAAvQAAACAAACQAXAFA5AQQAQAFAQAFQADABADABQALACAJADQF+BwGEA0EAppAMoQAIgCAJgDQALgDAUgIQAMgFAwgMIAygLQBDgQBvguQBBADBQAUQACAAACABEAybAJyQgBAjAAALQABAGABAMIAAAKQADAUgBAbEAxMAJwQAnAAAoACQARABASACQABAAABAAIAECCEA3GAZfQABgVAKgZQAAgDAYgxQASgkAziMQAlhmAog5EA3GAZfIhVgXQAGgoAbg4QAphUADgJQAGgQAUhAQAOgyAPgdQARgeAGgPQALgbgGgTEA6iAS5QhUCygmDLQAAACgBACIhhAtQAAgEAAgEEBCmAQtIACgBIAEgBEBA0ARRQACAAACgBIBugjEBA0ARRQAoAxAUAZQAGAHAMAOQAKAMAJAIQAfAcA3ATQAcAIAzAQQAJADAJADEBECARvIBdB+IgTAkEBCoAQsICkDlEBCqAP2IBYB5QGWCTGVESMAAAAlgMihZAAAMAAAglMQFoiyCVgvQKxjdKbg0EA7UATAQAxgYAhgNQA0gVAtgKQAagGA0gKQAZgFBGgWEAppAMoQApAFFYBwQGNCBEdAwIBAByIxNkvIgxgOQABg5ANghQACAAADgBgEAqbAOXQgBAJgEAMQgDAGgKAWQgaA3gTA5QgZBFgZBJQAEACAJAHQAIAHAFgDQAEgDBAAWIA0gdQgFgdADgWQADgXAQgiQAPgiALgUQAKgUACgEQAYgnAogmEAr/AOzQgTAngeA+QgKAVgMAYQgpBbgHBGEAnCARpQBNgbBNgWAZtYeQGwkgGliVEArzAQPQBkgYBjgPEggrg06QgGiHAthfQAqhbBXg1QAsgcA0gQQCHgsC1AgQAcAEAfAIQBIAPBZAcQBKAWCPAtQDaBDDvARQBZAHAaAEQBAAKAsAZQA1AeAZA3QAaA6gYAyQBzAFBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBjQBKBhADB0QADB0hFBlQhFBlhsAoQBRA2AUBqQAVBpg3BRQg3BQhqATQhqAShQg5QAuBLgPBeQgQBehDA4QhEA5hegCQhWgBg/gxQAbAbgIAwQgKA3grAbQgmAYg3AFQgkAChBgGQi3gQhugqQiMg1g6hnQgFgKAngYQgRARgRAREggrg06QAjgbAWgMQBCgnBMgRQBNgPBMALQBTALAeAxQATAdgLAjQgMAlggAEQAugEBggTQBdgSAxgEQBPgGBCARQBLASAxAvQA2A0AGBMQAGBQg1AvQBtgjBkBXQBiBVgEB1QgFBwhZBaQhVBVh1AWQAeBTgOBbQgOBbg3BGQg2BFhWAkQhVAjhXgKQh1BWiZgFQgGAAgFAAQiQgJhohWQhTHZCsBeQCqgWDVjXQAmgnAngsIAAECIAxA+Aq81rQgGgEgGgFA3n6aQhfgag7hBQg6hBgMhPQAAgDgBgCEgwDg4dQB3hLBNgeQB7gwBnATQA4AJAxAoQAvAnAaA1QAbA3gFA0QgEA1gkAlQgDADgCACEgnhghaQhLgVhIg5QiQhzgYitQgKhDAKhDQAJhFAbg+QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgYQBFgZAhgRQAkgTA+gwQAWgRASgNEgm9g1RQBLhHBxgBQB1gBBNBLQALAKAJALEg5Gg3VQBQhQBkg3QBng6BzgaQBsgYA4AnQAkAYADAxQACAngYAUQgGAEgHAEEgtVgfGQgGgSgFgTQgNgpgJgtIhFCWIi/AAQAUAbATAcQACCIgyBeQgyBdhZAtQhZAthogPQhpgPhIhFQg/BNhnAfQhfAdhqgRQhpgShQg8QhWg/giheQhAA2hMAUQhTAVhGgfQhKgggZhUQgahXA2g4Qg3AehCgYQhAgYgjg5QgggygKhFQgIg2AFhLQAYlRDLkiQDKkhE0iLQBWh/CAhaQCAhbCUglQBEgSAnAUQAZAOAHAeQAGAYgNAQQgCAEgFADEgnhghaQgvAigdAUQhcA+hFAWQhFAVhCgLQBTDuDCB9QAhAWAlASQAOAHAQAHQCMjYA4lbQALhEAIhJQABgKABgKQACgNABgNIASAkQgLAEgMAGA+//kQgDgCgCgCEgjugjvIBrDRIDhhVQgRBMgMBDEgkYghYQh4AVhRgXEgxTgd0QAGAIAFAJQJhOgqxc5QgkBegnBiQC9gPC7gBQKDgFJuCaQAPgGAPgGQg1ijivulQiruLJgpnAFIHJQAAgGgBgGQBIgdA0g+QAzg/AOhMQAFgfgKgOQgPgYgrADQgaADgYALQgFACgFACQgTAKgTAPQgOALgOAPQgOAPgPAWQAIgMAFgIQAVgbAXgQAJ/KyQgCgGgCgHQgIgegSgZQgHgJgJgJQgvgzhggdQgjgLgMgEQgZgKgSgJQgTgJgNgYAJ/LiQABgOgCgPQgEgwgZgnAJ/KyQASgDASAJQASAJAIASQAIASgGAnQAAACAAABQgFAjgQALQgMAJgZACQgXADgMgIIAAgGQAJgOAHgQQADgJADgIQAGgWABgWQAEgXgEgZgAEMNpQAAADACADQABAFADAFQAHAJAMAFQAMAFAjACQAZACAyAEQAsADAfgGQAtgKAkgeQAYgUAPgYAC5FDQABgBACAAQAAgZASgxQAahGAOgeQALgYAKgMQANgTAQgJQARgLAWABQAWABANAPQAKALAEAYQAGAeADAMAD3FhIAQgiQAVgpAOgXQgYAjgaAyAgeHrQgBgIABgIQACgQAIgOQAAgCABAAQAGgLAOgSQAageAHgHQATgUASgMQAmgYAwAAQALAAALABQADAAADABQAfAFAbARACEHUQAAAHgFAEQgEAFgHAAQgGAAgFgFQgEgEAAgHQAAgGAEgFQAFgEAGAAQAHAAAEAEQAFAFAAAGgAgeHrQAGgBAKAAQAGAAACACQAGADAAAKQgBAKgIAFQgDADgLAGQgFgMgBgNQgBgHAAgGgABoJrQgDgBgEAAQhFgNgiguQgLgOgGgQAB4MpQgNAJgHADQgLAEgBAAQgNAFgFAJQgHAQAKASQALAVATAEQAKAMAhAAQARAAAIgBQAOgBAKgFQATgKAUgnQABgCAAgBQALgWAAggQAAgEAAgDQAAgfgNgZAG1JmQglANgcASQgyAkgJAmQgGAZAIAgQABAEACAGQAFAPAKAYQAAABABAGQgKAAgIACQghAGgHAIQgIAJgBAKQAAADABADABoJrQAmAHAmgHQArgHAigYQAjgYATgmQARgiAAgjABoJrQgJArAEAjQAFAjARAeQALAQAHALQADAEACADQAGAJABADQAFAIgBAEQgCAHgLAGQgTAJgJAIQgOALAAAOQAAALADAMACKMdQgPAJgDACIAAABADqNWQAOAKAHAEQAFADAIACAGSNVQgogUgcgBA56S7IAxgMIAMgCA5JSvQA0gUA0gSIZZlgA56S7QLoC3HqC2AK/MPQOKAZN5FB");
	this.shape_38.setTransform(517.525,397.35);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#663300").s().p("ApFZAQi6ACi9AOQAnhhAjhfQKx84pguhIgLgQIgng3IC+AAIBFiWQAKAsAMAqIAMAkQBSDuDCB+QAiAVAkATIAeAOQCMjYA4lbQALhEAIhKIAXgJIBqDQIDhhUQgRBLgMBEIgFgEIAFAEQhSHZCrBeQCqgWDWjYQAlgmAngsIAAECIAyA+QgoAXAGAKQpgJoCqOLQCwOkA0CkIgdALQpviaqCAFg");
	this.shape_39.setTransform(283.2625,343.475);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#000000").ss(1,1,1).p("EApGg9yQABAFABAHQAOBBAcBJQAmBiBABvQCLDrDlDGQDkDFIXEEQIXEEK8heIAS2HgEBIBgeaIAAnbEAv6gl9IFKmoEA7KggpIDdmxEAlcgvfIGojDEAfWg7SIIFAAEA2LgBRQACgEAGgLQAGgJAFgFQAKgLAQgBQAQgCAOAHQALAGAMANQAGAHAMAOQAqAfAhAhEA1wgA6QAPgFALgRQAAAAABgBQAMgBAJAFQAIAFAFAHIAAABEA2zgAtQgFAAgFABQgEABgFAAQgGAAgDAAIAAABQAEAsAMAYQALAYAZATQAWATAkADQALABAMAAQAMAAAXgCQAEgBAEAAQAcgCAOAAQAEAAAEAAIARAAQAGgBALgFQALgEAHgFQgXgFgWgUQgCgCgDgCEA1wgA6IgBABIgBAAIApAPEA1wgA6QAKgDAHABQAQAAAAAAQAQABAMgFQAEAGAAABQABADABAJQAMgBAEAAQAaAAAOAOEA39gBPQAAABABABQABAAAAAAEA31gBUQADACAEADQAAAAABAAQgJgBgFAKQgEAIAAAIQAAANAAAJQAAAFAAAEQACARAHAKQAHAMAQAJQACABACACQAEACAEACIAAgOQAAgCADgCIACABQAIAGAIACQAEAAABgBQACgCAAgCIAAgUIAKAGQADAEAEAAQAEAAACgFQACgDgCgNQAJAKAJAKQAUAYALAMEBDeAG2QgBh+gMiLQAzASAdgRQgEBUgICpIgBADQghgFgVANgEBAzAGkIA7AGIBvAMIABAAEA/ZAMRIABCPQAWADAWADQAsAFBGAFQANABAOABQABABACAAQACABAFABQABAAABABQACACABADQAEALAAALQADAPABAWQAAAIAAAJQAAANAAAJQgBAFAAAEQAAADgBADIAAAAQAAACAAABQgCAEAAgGQAAgDAAgFQAAgEAAgFIAEABEBAGAMZIAACNEAzAAJ1QApADAsAGQB7AQDAAtQEOA+AvAJQAmAIAmAHQAXAEAWAEQAcAFAcAFQAaAEAaAFQAAAWABALQABAEABAIQADAKAAAHQABALAAATQAAAVgBATEBDZAIlQAIgBANABQAMABAeACQgKARAAAhQgCBqAHBWQAAAOAAABQgBAIgEAGQgZAJgDAAQgFgBgGgBEBBuAIZQA0AGA3AGIAOEZEBAzAIUQAdADAeACEBCfAO2IAAAAQAPgDgbgBEBCRAOuQAAADACABEBByAMsQA7AJA6AJEA/uAGcIAABwQAiAEAjAEEBAzAGkIAABwEA/uAGcIBFAIEBBuAGqIAABvEA6XARLQAhgGA3gcQA9geAbgIQANgEATgEQAHgBAIgBQAqgHAGgBQApgJBQgdQA3gRBJgEEA4XAAgQAGACAHADQAqALAtgFEA4FABbQgQAMgCACQgLAJgDABQgFADgMAAIggAAQgGAFABAGQADAGAIABIAdgDQATgCAGgEQAIgEAMgMQAMgMAMgHEA4/ABaIg8AnIAZAEQACABAEABQADABABACQACADgBADQgCADgDAAQgegIgdANQgCABgCABQgMAGgGACQgLAEgGgIQABgEAEgDQAEgEAJgDQAFgBATAAQgMgBgbAAQgGABgFgGIACgBEAypAFUQAGAAAGAAQA7gBA9AEQBuAHDrAYIFoAmEA3FACXQARAAARABQE/ALGrAKEAxHAFXQAbgCAcAAQAVgBAWAAIAABdQAHABAIABQADAAAEABQFHAkHoA0EAx+AFVIAABTEAxHAFXIAABPQAvAGAzAFEAxHAFXQhDAFhAAKQACheAIiHQDKALEtALEAxMAJwQhAgBhAAFQgFhZAAh9QA6AABGAIEAxMAJwQgCAWABALQABAGACAMIAAAvQAAACAAACQAXAFA5AQQAQAFAQAFQADABADABQALACAJADQF+BwGEA0EAppAMoQAIgCAJgDQALgDAUgIQAMgFAwgMIAygLQBDgQBvguQBBADBQAUQACAAACABEAybAJyQgBAjAAALQABAGABAMIAAAKQADAUgBAbEAxMAJwQAnAAAoACQARABASACQABAAABAAIAECCEA3GAZfQABgVAKgZQAAgDAYgxQASgkAziMQAlhmAog5EA3GAZfIhVgXQAGgoAbg4QAphUADgJQAGgQAUhAQAOgyAPgdQARgeAGgPQALgbgGgTEA6iAS5QhUCygmDLQAAACgBACIhhAtQAAgEAAgEEBCmAQtIACgBIAEgBEBA0ARRQACAAACgBIBugjEBA0ARRQAoAxAUAZQAGAHAMAOQAKAMAJAIQAfAcA3ATQAcAIAzAQQAJADAJADEBECARvIBdB+IgTAkEBCoAQsICkDlEBCqAP2IBYB5QGWCTGVESMAAAAlgMihZAAAMAAAglMQFoiyCVgvQKxjdKbg0EA7UATAQAxgYAhgNQA0gVAtgKQAagGA0gKQAZgFBGgWEAppAMoQApAFFYBwQGNCBEdAwIBAByIxNkvIgxgOQABg5ANghQACAAADgBgEAqbAOXQgBAJgEAMQgDAGgKAWQgaA3gTA5QgZBFgZBJQAEACAJAHQAIAHAFgDQAEgDBAAWIA0gdQgFgdADgWQADgXAQgiQAPgiALgUQAKgUACgEQAYgnAogmEAr/AOzQgTAngeA+QgKAVgMAYQgpBbgHBGEAnCARpQBNgbBNgWAZtYeQGwkgGliVEArzAQPQBkgYBjgPEggrg06QgGiHAthfQAqhbBXg1QAsgcA0gQQCHgsC1AgQAcAEAfAIQBIAPBZAcQBKAWCPAtQDaBDDvARQBZAHAaAEQBAAKAsAZQA1AeAZA3QAaA6gYAyQBzAFBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBjQBKBhADB0QADB0hFBlQhFBlhsAoQBRA2AUBqQAVBpg3BRQg3BQhqATQhqAShQg5QAuBLgPBeQgQBehDA4QhEA5hegCQhWgBg/gxQAbAbgIAwQgKA3grAbQgmAYg3AFQgkAChBgGQi3gQhugqQiMg1g6hnEggrg06QAjgbAWgMQBCgnBMgRQBNgPBMALQBTALAeAxQATAdgLAjQgMAlggAEQAugEBggTQBdgSAxgEQBPgGBCARQBLASAxAvQA2A0AGBMQAGBQg1AvQBtgjBkBXQBiBVgEB1QgFBwhZBaQhVBVh1AWQAeBTgOBbQgOBbg3BGQg2BFhWAkQhVAjhXgKQh1BWiZgFQgGAAgFAAQiQgJhohWQhTHZCsBeQCqgWDVjXQAmgnAngsIAAECIAxA+QgRARgRARQgFgKAngYAq81rQgGgEgGgFA3n6aQhfgag7hBQg6hBgMhPQAAgDgBgCEgwDg4dQB3hLBNgeQB7gwBnATQA4AJAxAoQAvAnAaA1QAbA3gFA0QgEA1gkAlQgDADgCACEgnhghaQhLgVhIg5QiQhzgYitQgKhDAKhDQAJhFAbg+QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgYQBFgZAhgRQAkgTA+gwQAWgRASgNEgm9g1RQBLhHBxgBQB1gBBNBLQALAKAJALEgwDg4dQgGAEgHAEEg5Gg3VQBQhQBkg3QBng6BzgaQBsgYA4AnQAkAYADAxQACAngYAUEgtVgfGQgGgSgFgTQgNgpgJgtIhFCWIi/AAQAUAbATAcQACCIgyBeQgyBdhZAtQhZAthogPQhpgPhIhFQg/BNhnAfQhfAdhqgRQhpgShQg8QhWg/giheQhAA2hMAUQhTAVhGgfQhKgggZhUQgahXA2g4Qg3AehCgYQhAgYgjg5QgggygKhFQgIg2AFhLQAYlRDLkiQDKkhE0iLQBWh/CAhaQCAhbCUglQBEgSAnAUQAZAOAHAeQAGAYgNAQQgCAEgFADEgnhghaQgvAigdAUQhcA+hFAWQhFAVhCgLQBTDuDCB9QAhAWAlASQAOAHAQAHQCMjYA4lbQALhEAIhJEgjugjvQgLAEgMAGQABgKABgKQACgNABgNIASAkIBrDRIDhhVQgRBMgMBDQgDgCgCgCEgkYghYQh4AVhRgXEgxTgd0QAGAIAFAJQJhOgqxc5QgkBegnBiQC9gPC7gBQKDgFJuCaQAPgGAPgGQg1ijivulQiruLJgpnAFIHJQAAgGgBgGQBIgdA0g+QAzg/AOhMQAFgfgKgOQgPgYgrADQgaADgYALQgFACgFACQgTAKgTAPQgOALgOAPQgOAPgPAWQAIgMAFgIQAVgbAXgQAJ/KyQgCgGgCgHQgIgegSgZQgHgJgJgJQgvgzhggdQgjgLgMgEQgZgKgSgJQgTgJgNgYAJ/LiQABgOgCgPQgEgwgZgnAJ/KyQASgDASAJQASAJAIASQAIASgGAnQAAACAAABQgFAjgQALQgMAJgZACQgXADgMgIIAAgGAEMNpQAAADACADQABAFADAFQAHAJAMAFQAMAFAjACQAZACAyAEQAsADAfgGQAtgKAkgeQAYgUAPgYQAJgOAHgQQADgJADgIQAGgWABgWQAEgXgEgZAC5FDQABgBACAAQAAgZASgxQAahGAOgeQALgYAKgMQANgTAQgJQARgLAWABQAWABANAPQAKALAEAYQAGAeADAMAD3FhIAQgiQAVgpAOgXQgYAjgaAyAgeHrQgBgIABgIQACgQAIgOQAAgCABAAQAGgLAOgSQAageAHgHQATgUASgMQAmgYAwAAQALAAALABQADAAADABQAfAFAbARACEHUQAAAHgFAEQgEAFgHAAQgGAAgFgFQgEgEAAgHQAAgGAEgFQAFgEAGAAQAHAAAEAEQAFAFAAAGgAgeHrQAGgBAKAAQAGAAACACQAGADAAAKQgBAKgIAFQgDADgLAGQgFgMgBgNQgBgHAAgGgABoJrQgDgBgEAAQhFgNgiguQgLgOgGgQAB4MpQgNAJgHADQgLAEgBAAQgNAFgFAJQgHAQAKASQALAVATAEQAKAMAhAAQARAAAIgBQAOgBAKgFQATgKAUgnQABgCAAgBQALgWAAggQAAgEAAgDQAAgfgNgZAG1JmQglANgcASQgyAkgJAmQgGAZAIAgQABAEACAGQAFAPAKAYQAAABABAGQgKAAgIACQghAGgHAIQgIAJgBAKQAAADABADABoJrQAmAHAmgHQArgHAigYQAjgYATgmQARgiAAgjABoJrQgJArAEAjQAFAjARAeQALAQAHALQADAEACADQAGAJABADQAFAIgBAEQgCAHgLAGQgTAJgJAIQgOALAAAOQAAALADAMACKMdQgPAJgDACIAAABADqNWQAOAKAHAEQAFADAIACAGSNVQgogUgcgBA5JSvIAMgCA56S7IAxgMQA0gUA0gSIZZlgA56S7QLoC3HqC2AK/MPQOKAZN5FB");
	this.shape_40.setTransform(517.525,397.35);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("ABvGlIhLgGQgjgCgLgGQgMgEgHgKQgDgEgBgFIABAAIgBgBQAAAAAAABIgCgGIgBgFIAAgCQABgKAIgIQAHgIAggHIANgBIABAAIAAAAIADAAIABAAIgBgHQgKgYgFgPIgDgLQgFgRAAgPQAAgNADgLQAJgmAygkQAcgTAlgMQglAMgcATQgyAkgJAmQgDALAAANQAAAPAFARIADALQAFAPAKAYIABAHIgBAAIgDAAIAAAAIgBAAIgNABQggAHgHAIQgIAIgBAKIAAACIABAFIgNgGIgVgNIABgDQALgWAAghIAAgDIAAgEQAAgegNgZQANAZAAAeIAAAEIAAADQAAAhgLAWIgBADQgUAngTAJQgKAFgOACIgZABQghAAgKgNQgDgLAAgLQAAgOAOgMQAJgIATgJQALgFACgHQABgFgFgIIgHgLIgFgHIgSgcQgRgegFgjQgEgjAJgqIgHgCQhFgNgjgtQgLgOgGgRQALgFADgDQAIgGACgJQAAgKgHgDQgCgBgGAAIgQABIAAgQQACgQAIgPIABgCQAGgKAPgSIAhgmQATgUASgLQAmgZAwAAIAWACIAGAAIADgBQAAgYASgyQAahFAOgfQALgXAKgNQANgSAQgJQAQgMAWABQAWACANAPQAKALAEAXIAJArQgTAKgTAPQATgPATgKIAKgFQAYgKAagDQArgDAPAYQAKAOgFAfQgOBMgzA+Qg0A/hIAdIABAMQANAYATAJQASAIAZAJIAvAQQBgAdAvAzQAJAJAHAJQAZAnAEAwQACAPgBAOQgBAWgGAWIgGARQgHAQgJAOQgPAYgYATQgkAfgtAJQgWAFgcAAIgZgBgABiFmQgngUgdgBQAdABAnAUgAh7B8QArgIAigYQAjgXASgnQARggAAgjQAAAjgRAgQgSAngjAXQgiAYgrAIQgTADgTAAQgTAAgTgDQATADATAAQATAAATgDgAjGglQgEAEAAAHQAAAGAEAFQAFAEAGAAQAHAAAEgEQAFgFAAgGQAAgHgFgEQgEgFgHAAQgGAAgFAFgAgoivIgQAhIAQghQAVgpAOgXQAOgWAOgQQAOgOAOgLQgXAQgVAbIgMAUQgYAjgaAyQAagyAYgjQgOAXgVApgAg8iVQgbgRgfgGQAfAGAbARgAAeFRIAAAAg");
	this.shape_41.setTransform(547.9171,446.8578);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#663300").s().p("ApFZAQi6ACi9AOQAnhhAjhfQKx84pguhIgLgQIgng3IC+AAIBFiWQAKAsAMAqIAMAkQBSDuDCB+QAiAVAkATIAeAOQCMjYA4lbQALhEAIhKIAXgJIBqDQIDhhUQgRBLgMBEIgFgEIAFAEQhSHZCrBeQCqgWDWjYQAlgmAngsIAAECIAyA+QgoAXAGAKQpgJoCqOLQCwOkA0CkIgdALQpviaqCAFgAFm3JIAAAAg");
	this.shape_42.setTransform(283.2625,343.475);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#009900").s().p("EhQsA81MAAAglMQFoiyCVguQKxjdKcg1QC8gOC7gCQKDgFJuCaQLoC4HqC1Qnqi1roi4IAxgLIAMgDIBcgkIZZlgQgNAKgHACIgMAFQgNAEgFAKQgHAQAKARQALAWATADQAKANAhAAIAZgBQAOgCAKgFQATgKAUgnIAVAOIANAGIACAGQABAEADAFQAHAKAMAEQAMAGAjACIBLAGQAsACAfgGQAtgJAkgfQAYgTAPgZIAAAHQAMAIAXgDQAZgCAMgJQAQgMAFgiQOKAYN5FCQmlCVmwEfQGwkfGliVQBNgbBNgXIgyCOIANAKQAIAHAFgDQAEgDBAAWIA0gdQgFgeADgWQADgWAQgiIAZg2IANgYQBkgYBjgQIiHgmIg0gPIhkgcIgUgGIRNEwQAxgYAhgNQA0gWAtgKIBOgQQAZgFBGgVIA8BKIASAVIATAUQAfAbA3ATIBPAZIASAFIATgjIhdh+QGWCSGVESMAAAAlggEA4MASAQgGAQgRAeQgPAdgOAxQgUBBgGAQIgsBdQgbA3gGAoIBVAYIAAAIIBhgtIABgEQAmjMBUiyIgogLIhpgdQAGAUgLAagAEOMxQAAgBAAAAIABABgAugzzQi3gRhugpQiMg2g6hnIAighIgxg+IAAkCQgnAsgmAmQhfgZg7hCQg6hAgMhQIALABIACAAIAOAAIAAAAIABAAQCLAABshOIABgBIABAAIACgCIACgBIABAAQATACATAAIAAAAIABAAQA+AAA+gYIACAAIABgBIAEgBIABgBQBWgjA2hGQA3hFAOhbQAFgdAAgcQAAg9gVg5QB1gVBVhWQBZhZAFhwIAAgKQAAhvhehSIgGgFQhEg4hIAAIgBAAIAAAAQgdAAgeAJIAAAAIgDABQAvgqAAhEIAAgRQgGhNg2gzQgxgvhLgTIgEgBIgFgBQgtgKgyAAIAAAAIAAAAIgiABIgFAAIAAAAIgCABQgxAEhdASQhgASguAFQAggFAMgkQAEgOAAgMQAAgUgMgSQgegxhTgLIgEgBQgdgEgeAAIAAAAIgBAAQgsAAgtAJQhMAQhCAoQgWAMgjAaQAjgaAWgMQBCgoBMgQQAtgJAsAAIABAAIAAAAQAeAAAdAEIAEABQBTALAeAxQAMASAAAUQAAAMgEAOQgMAkggAFQAugFBggSQBdgSAxgEIACgBIAAAAIAFAAIAigBIAAAAIAAAAQAyAAAtAKIAFABIAEABQBLATAxAvQA2AzAGBNIAAARQAABEgvAqIADgBIAAAAQAegJAdAAIAAAAIABAAQBIAABEA4IAGAFQBeBSAABvIAAAKQgFBwhZBZQhVBWh1AVQAVA5AAA9QAAAcgFAdQgOBbg3BFQg2BGhWAjIgBABIgEABIgBABIgCAAQg+AYg+AAIgBAAIAAAAQgTAAgTgCIgBAAIgCABIgCACIgBAAIgBABQhsBOiLAAIgBAAIAAAAIgOAAIgCAAIgLgBIgBgEIABAEQiQgIhohWQAMhEARhLIjhBUIhrjQIgSgkIgDAaIgCATQgIBKgLBEQh4AUhRgWQhLgVhIg5QiQh0gYisQgFgiAAghQAAgiAFgiQAJhFAbg9QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgZQBFgYAhgRQAkgUA+gvIAogfQgGiGAthgQAqhaBXg1QAtgcAzgRQCHgrC1AfIA8AMQBHAQBZAbIDZBEQDaBCDvASQBZAHAaAEQBAAKAsAZQA1AdAZA3QAaA7gYAxQBzAGBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBiQBKBiADB0QADBzhFBlQhFBmhsAnQBRA3AUBpQAVBqg3BQQg3BRhqASQhqAThQg6QAuBLgPBeQgQBehDA4QhEA5hegBQhWgBg/gxQAbAbgIAvQgKA4grAbQgmAYg3AEIgYABQgfAAgugEgAq82pIgMgKIAMAKgEg/vgYBQhpgShQg7QhWg/giheQhAA2hMATQhTAVhGgeQhKgggZhVQgahWA2g4Qg3AehCgZQhAgYgjg4QgggygKhFQgIg2AFhMQAYlRDLkhQDKkiE0iKQBWh/CAhbQCAhaCUgmQBEgRAnAUQAZANAHAeQAGAYgNAQIgHAIIAHgIQBQhPBkg3QBng6BzgaQBsgZA4AoQAkAYADAwQACAogYATQgGAFgHAEQAHgEAGgFQB3hKBNgeQB7gwBnASQA4AKAxAoQAvAmAaA2QAbA3gFA0QgEA1gkAlQBLhHBxgBQB1gBBNBKQALAKAJALIgoAfQg+AvgkAUQghARhFAYQhHAZggAQQhDAjhCBDQgpArhEBXQgwA/gZAkQglA5gWAyQgbA9gJBFQgFAiAAAiQAAAhAFAiQAYCsCQB0QBIA5BLAVIhMA2QhcA+hFAVQhFAWhCgMIgLgkQgNgqgJgsIhFCWIi/AAIAnA3QACCIgyBdQgyBehZAtQhZAthogPQhpgQhIhEQg/BNhnAfQg7AShAAAQgmAAgogHgEgnCg2KIAFgFIgFAFgEggrg15IAAAAg");
	this.shape_43.setTransform(517.525,403.5907);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#000000").ss(1,1,1).p("EApGg9yQABAFABAHQAOBBAcBJQAmBiBABvQCLDrDlDGQDkDFIXEEQIXEEK8heIAS2HgEBIBgeaIAAnbEAv6gl9IFKmoEA7KggpIDdmxEAlcgvfIGojDEAfWg7SIIFAAEA2LgBRQACgEAGgLQAGgJAFgFQAKgLAQgBQAQgCAOAHQALAGAMANQAGAHAMAOQAqAfAhAhEA1wgA6QAPgFALgRQAAAAABgBQAMgBAJAFQAIAFAFAHIAAABQAEAGAAABQABADABAJQAMgBAEAAQAaAAAOAOEA2zgAtQgFAAgFABQgEABgFAAQgGAAgDAAIAAABQAEAsAMAYQALAYAZATQAWATAkADQALABAMAAEA1wgA6QAKgDAHABQAQAAAAAAQAQABAMgFEA1wgA6IgBABIgBAAIApAPEA39gBPQAAABABABQABAAAAAAEA31gBUQADACAEADQAAAAABAAQgJgBgFAKQgEAIAAAIQAAANAAAJQAAAFAAAEQACARAHAKQAHAMAQAJQACABACACQAEACAEACIAAgOQAAgCADgCIACABQAIAGAIACQAEAAABgBQACgCAAgCIAAgUIAKAGQADAEAEAAQAEAAACgFQACgDgCgNQAJAKAJAKQAUAYALAMEBDeAG2QgBh+gMiLQAzASAdgRQgEBUgICpIgBADQghgFgVANgEBAzAGkIA7AGIBvAMIABAAEA4/ABaQAEgBAEAAQAcgCAOAAQAEAAAEAAIARAAQAGgBALgFQALgEAHgFQgXgFgWgUQgCgCgDgCEA/ZAMRIABCPQAWADAWADQAsAFBGAFQANABAOABQABABACAAQACABAFABQABAAABABIAAAAQAPgDgbgBEBAGAMZIAACNEAzAAJ1QApADAsAGQB7AQDAAtQEOA+AvAJQAmAIAmAHQAXAEAWAEQAcAFAcAFQAaAEAaAFQAAAWABALQABAEABAIQADAKAAAHQABALAAATQAAAVgBATEBDZAIlQAIgBANABQAMABAeACQgKARAAAhQgCBqAHBWQAAAOAAABQgBAIgEAGQgZAJgDAAQgFgBgGgBEBBuAIZQA0AGA3AGIAOEZEBAzAIUQAdADAeACEBCfAO2QACACABADQAEALAAALQADAPABAWQAAAIAAAJQAAANAAAJQgBAFAAAEQAAADgBADIAAAAQAAACAAABQgCAEAAgGQAAgDAAgFQAAgEAAgFIAEABEBCRAOuQAAADACABEBByAMsQA7AJA6AJEA/uAGcIAABwQAiAEAjAEEBAzAGkIAABwEA/uAGcIBFAIEBBuAGqIAABvEA6XARLQAhgGA3gcQA9geAbgIQANgEATgEQAHgBAIgBQAqgHAGgBQApgJBQgdQA3gRBJgEEA4XAAgQAGACAHADQAqALAtgFEA4FABbQgQAMgCACQgLAJgDABQgFADgMAAIggAAQgGAFABAGQADAGAIABIAdgDQATgCAGgEQAIgEAMgMQAMgMAMgHQAMAAAXgCIg8AnIAZAEQACABAEABQADABABACQACADgBADQgCADgDAAQgegIgdANQgCABgCABQgMAGgGACQgLAEgGgIQABgEAEgDQAEgEAJgDQAFgBATAAQgMgBgbAAQgGABgFgGIACgBEAypAFUQAGAAAGAAQA7gBA9AEQBuAHDrAYIFoAmEA3FACXQARAAARABQE/ALGrAKEAxHAFXQAbgCAcAAQAVgBAWAAIAABdQAHABAIABQADAAAEABQFHAkHoA0EAx+AFVIAABTEAxHAFXIAABPQAvAGAzAFEAxHAFXQhDAFhAAKQACheAIiHQDKALEtALEAxMAJwQhAgBhAAFQgFhZAAh9QA6AABGAIEAxMAJwQgCAWABALQABAGACAMIAAAvQAAACAAACQAXAFA5AQQAQAFAQAFQADABADABQALACAJADQF+BwGEA0EAppAMoQAIgCAJgDQALgDAUgIQAMgFAwgMIAygLQBDgQBvguQBBADBQAUQACAAACABEAybAJyQgBAjAAALQABAGABAMIAAAKQADAUgBAbEAxMAJwQAnAAAoACQARABASACQABAAABAAIAECCEA3GAZfQABgVAKgZQAAgDAYgxQASgkAziMQAlhmAog5EA3GAZfIhVgXQAGgoAbg4QAphUADgJQAGgQAUhAQAOgyAPgdQARgeAGgPQALgbgGgTEA6iAS5QhUCygmDLQAAACgBACIhhAtQAAgEAAgEEBCmAQtIACgBIAEgBEBA0ARRQACAAACgBIBugjEBA0ARRQAoAxAUAZQAGAHAMAOQAKAMAJAIQAfAcA3ATQAcAIAzAQQAJADAJADEBECARvIBdB+IgTAkEBCoAQsICkDlEBCqAP2IBYB5QGWCTGVESMAAAAlgMihZAAAMAAAglMQFoiyCVgvQKxjdKbg0EA7UATAQAxgYAhgNQA0gVAtgKQAagGA0gKQAZgFBGgWEAppAMoQApAFFYBwQGNCBEdAwIBAByIxNkvIgxgOQABg5ANghQACAAADgBgEAqbAOXQgBAJgEAMQgDAGgKAWQgaA3gTA5QgZBFgZBJQAEACAJAHQAIAHAFgDQAEgDBAAWIA0gdQgFgdADgWQADgXAQgiQAPgiALgUQAKgUACgEQAYgnAogmEAr/AOzQgTAngeA+QgKAVgMAYQgpBbgHBGEAnCARpQBNgbBNgWAZtYeQGwkgGliVEArzAQPQBkgYBjgPEggrg06QgGiHAthfQAqhbBXg1QAsgcA0gQQCHgsC1AgQAcAEAfAIQBIAPBZAcQBKAWCPAtQDaBDDvARQBZAHAaAEQBAAKAsAZQA1AeAZA3QAaA6gYAyQBzAFBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBjQBKBhADB0QADB0hFBlQhFBlhsAoQBRA2AUBqQAVBpg3BRQg3BQhqATQhqAShQg5QAuBLgPBeQgQBehDA4QhEA5hegCQhWgBg/gxQAbAbgIAwQgKA3grAbQgmAYg3AFQgkAChBgGQi3gQhugqQiMg1g6hnQgFgKAngYQgRARgRAREggrg06QAjgbAWgMQBCgnBMgRQBNgPBMALQBTALAeAxQATAdgLAjQgMAlggAEQAugEBggTQBdgSAxgEQBPgGBCARQBLASAxAvQA2A0AGBMQAGBQg1AvQBtgjBkBXQBiBVgEB1QgFBwhZBaQhVBVh1AWQAeBTgOBbQgOBbg3BGQg2BFhWAkQhVAjhXgKQh1BWiZgFQgGAAgFAAQiQgJhohWQhTHZCsBeQCqgWDVjXQAmgnAngsIAAECIAxA+Aq81rQgGgEgGgFA3n6aQhfgag7hBQg6hBgMhPQAAgDgBgCEgwDg4dQB3hLBNgeQB7gwBnATQA4AJAxAoQAvAnAaA1QAbA3gFA0QgEA1gkAlQgDADgCACEgnhghaQhLgVhIg5QiQhzgYitQgKhDAKhDQAJhFAbg+QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgYQBFgZAhgRQAkgTA+gwQAWgRASgNEgm9g1RQBLhHBxgBQB1gBBNBLQALAKAJALEg5Gg3VQBQhQBkg3QBng6BzgaQBsgYA4AnQAkAYADAxQACAngYAUQgGAEgHAEEgtVgfGQgGgSgFgTQgNgpgJgtIhFCWIi/AAQAUAbATAcQACCIgyBeQgyBdhZAtQhZAthogPQhpgPhIhFQg/BNhnAfQhfAdhqgRQhpgShQg8QhWg/giheQhAA2hMAUQhTAVhGgfQhKgggZhUQgahXA2g4Qg3AehCgYQhAgYgjg5QgggygKhFQgIg2AFhLQAYlRDLkiQDKkhE0iLQBWh/CAhaQCAhbCUglQBEgSAnAUQAZAOAHAeQAGAYgNAQQgCAEgFADEgnhghaQgvAigdAUQhcA+hFAWQhFAVhCgLQBTDuDCB9QAhAWAlASQAOAHAQAHQCMjYA4lbQALhEAIhJQABgKABgKQACgNABgNIASAkQgLAEgMAGA+//kQgDgCgCgCEgjugjvIBrDRIDhhVQgRBMgMBDEgkYghYQh4AVhRgXEgxTgd0QAGAIAFAJQJhOgqxc5QgkBegnBiQC9gPC7gBQKDgFJuCaQAPgGAPgGQg1ijivulQiruLJgpnAFIHJQAAgGgBgGQBIgdA0g+QAzg/AOhMQAFgfgKgOQgPgYgrADQgaADgYALQgFACgFACQgTAKgTAPQgOALgOAPQgOAPgPAWQAIgMAFgIQAVgbAXgQAJ/KyQgCgGgCgHQgIgegSgZQgHgJgJgJQgvgzhggdQgjgLgMgEQgZgKgSgJQgTgJgNgYAJ/LiQABgOgCgPQgEgwgZgnAJ/KyQASgDASAJQASAJAIASQAIASgGAnQAAACAAABQgFAjgQALQgMAJgZACQgXADgMgIIAAgGQAJgOAHgQQADgJADgIQAGgWABgWQAEgXgEgZgAEMNpQAAADACADQABAFADAFQAHAJAMAFQAMAFAjACQAZACAyAEQAsADAfgGQAtgKAkgeQAYgUAPgYAC5FDQABgBACAAQAAgZASgxQAahGAOgeQALgYAKgMQANgTAQgJQARgLAWABQAWABANAPQAKALAEAYQAGAeADAMAD3FhIAQgiQAVgpAOgXQgYAjgaAyAgeHrQgBgIABgIQACgQAIgOQAAgCABAAQAGgLAOgSQAageAHgHQATgUASgMQAmgYAwAAQALAAALABQADAAADABQAfAFAbARACEHUQAAAHgFAEQgEAFgHAAQgGAAgFgFQgEgEAAgHQAAgGAEgFQAFgEAGAAQAHAAAEAEQAFAFAAAGgAgeHrQAGgBAKAAQAGAAACACQAGADAAAKQgBAKgIAFQgDADgLAGQgFgMgBgNQgBgHAAgGgABoJrQgDgBgEAAQhFgNgiguQgLgOgGgQAB4MpQgNAJgHADQgLAEgBAAQgNAFgFAJQgHAQAKASQALAVATAEQAKAMAhAAQARAAAIgBQAOgBAKgFQATgKAUgnQABgCAAgBQALgWAAggQAAgEAAgDQAAgfgNgZAG1JmQglANgcASQgyAkgJAmQgGAZAIAgQABAEACAGQAFAPAKAYQAAABABAGQgKAAgIACQghAGgHAIQgIAJgBAKQAAADABADABoJrQAmAHAmgHQArgHAigYQAjgYATgmQARgiAAgjABoJrQgJArAEAjQAFAjARAeQALAQAHALQADAEACADQAGAJABADQAFAIgBAEQgCAHgLAGQgTAJgJAIQgOALAAAOQAAALADAMACKMdQgPAJgDACIAAABADqNWQAOAKAHAEQAFADAIACAGSNVQgogUgcgBA56S7IAxgMIAMgCA5JSvQA0gUA0gSIZZlgA56S7QLoC3HqC2AK/MPQOKAZN5FB");
	this.shape_44.setTransform(517.525,397.35);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#009900").s().p("EhQsA81MAAAglMQFoiyCVguQKxjdKcg1QC8gOC7gCQKDgFJuCaIAxgLIAMgDIBcgkIZZlgQgNAKgHACIgMAFQgNAEgFAKQgHAQAKARQALAWATADQAKANAhAAIAZgBQAOgCAKgFQATgKAUgnIAVAOIANAGIACAGQABAEADAFQAHAKAMAEQAMAGAjACIBLAGQAsACAfgGQAtgJAkgfQAYgTAPgZIAAAHQAMAIAXgDQAZgCAMgJQAQgMAFgiQOKAYN5FCQmlCVmwEfQGwkfGliVQBNgbBNgXIgyCOIANAKQAIAHAFgDQAEgDBAAWIA0gdQgFgeADgWQADgWAQgiIAZg2IANgYQBkgYBjgQIiHgmIg0gPIhkgcIgUgGIRNEwQAxgYAhgNQA0gWAtgKIBOgQQAZgFBGgVIA8BKIASAVIATAUQAfAbA3ATIBPAZIASAFIATgjIhdh+QGWCSGVESMAAAAlggEA4MASAQgGAQgRAeQgPAdgOAxQgUBBgGAQIgsBdQgbA3gGAoIBVAYIAAAIIBhgtIABgEQAmjMBUiyIgogLIhpgdQAGAUgLAagAmoXpQnqi1roi4QLoC4HqC1gAEOMxQAAgBAAAAIABABgAugzzQi3gRhugpQiMg2g6hnIAighIgxg+IAAkCQgnAsgmAmQhfgZg7hCQg6hAgMhQIALABIACAAIAOAAIAAAAIABAAQCLAABshOIABgBIABAAIACgCIACgBIABAAQATACATAAIAAAAIABAAQA+AAA+gYIACAAIABgBIAEgBIABgBQBWgjA2hGQA3hFAOhbQAFgdAAgcQAAg9gVg5QB1gVBVhWQBZhZAFhwIAAgKQAAhvhehSIgGgFQhEg4hIAAIgBAAIAAAAQgdAAgeAJIAAAAIgDABQAvgqAAhEIAAgRQgGhNg2gzQgxgvhLgTIgEgBIgFgBQgtgKgyAAIAAAAIAAAAIgiABIgFAAIAAAAIgCABQgxAEhdASQhgASguAFQAggFAMgkQAEgOAAgMQAAgUgMgSQgegxhTgLIgEgBQgdgEgeAAIAAAAIgBAAQgsAAgtAJQhMAQhCAoQgWAMgjAaQAjgaAWgMQBCgoBMgQQAtgJAsAAIABAAIAAAAQAeAAAdAEIAEABQBTALAeAxQAMASAAAUQAAAMgEAOQgMAkggAFQAugFBggSQBdgSAxgEIACgBIAAAAIAFAAIAigBIAAAAIAAAAQAyAAAtAKIAFABIAEABQBLATAxAvQA2AzAGBNIAAARQAABEgvAqIADgBIAAAAQAegJAdAAIAAAAIABAAQBIAABEA4IAGAFQBeBSAABvIAAAKQgFBwhZBZQhVBWh1AVQAVA5AAA9QAAAcgFAdQgOBbg3BFQg2BGhWAjIgBABIgEABIgBABIgCAAQg+AYg+AAIgBAAIAAAAQgTAAgTgCIgBAAIgCABIgCACIgBAAIgBABQhsBOiLAAIgBAAIAAAAIgOAAIgCAAIgLgBIgBgEIABAEQiQgIhohWQAMhEARhLIjhBUIhrjQIgSgkIgDAaIgCATQgIBKgLBEQh4AUhRgWQhLgVhIg5QiQh0gYisQgFgiAAghQAAgiAFgiQAJhFAbg9QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgZQBFgYAhgRQAkgUA+gvIAogfQgGiGAthgQAqhaBXg1QAtgcAzgRQCHgrC1AfIA8AMQBHAQBZAbIDZBEQDaBCDvASQBZAHAaAEQBAAKAsAZQA1AdAZA3QAaA7gYAxQBzAGBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBiQBKBiADB0QADBzhFBlQhFBmhsAnQBRA3AUBpQAVBqg3BQQg3BRhqASQhqAThQg6QAuBLgPBeQgQBehDA4QhEA5hegBQhWgBg/gxQAbAbgIAvQgKA4grAbQgmAYg3AEIgYABQgfAAgugEgAq82pIgMgKIAMAKgEg/vgYBQhpgShQg7QhWg/giheQhAA2hMATQhTAVhGgeQhKgggZhVQgahWA2g4Qg3AehCgZQhAgYgjg4QgggygKhFQgIg2AFhMQAYlRDLkhQDKkiE0iKQBWh/CAhbQCAhaCUgmQBEgRAnAUQAZANAHAeQAGAYgNAQIgHAIIAHgIQBQhPBkg3QBng6BzgaQBsgZA4AoQAkAYADAwQACAogYATQB3hKBNgeQB7gwBnASQA4AKAxAoQAvAmAaA2QAbA3gFA0QgEA1gkAlIgFAFIAFgFQBLhHBxgBQB1gBBNBKQALAKAJALIgoAfQg+AvgkAUQghARhFAYQhHAZggAQQhDAjhCBDQgpArhEBXQgwA/gZAkQglA5gWAyQgbA9gJBFQgFAiAAAiQAAAhAFAiQAYCsCQB0QBIA5BLAVIhMA2QhcA+hFAVQhFAWhCgMIgLgkQgNgqgJgsIhFCWIi/AAIAnA3QACCIgyBdQgyBehZAtQhZAthogPQhpgQhIhEQg/BNhnAfQg7AShAAAQgmAAgogHgEgwQg5TQAHgEAGgFQgGAFgHAEgEggrg15IAAAAg");
	this.shape_45.setTransform(517.525,403.5907);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFF33").s().p("AANIRQoXkEjkjFQjkjEiMjsQhAhvgmhiQgchJgOhBIgCgMMAnhAAAIgRWGQi7AZivAAQnhAAmIi/g");
	this.shape_46.setTransform(907,73.8317);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#664D14").s().p("AAHG5QAGgoAbg3IAshdQAGgQAUhBQAOgxAPgdQARgeAGgQQALgagGgUIBpAdQgnA5glBmQgzCNgSAjIgYA0QgKAagBAVgAslBFQgFADgIgHIgNgKIAyiNQATg4Aag4IANgcQAEgLABgKIBkAcIgxBmIgWAsQgpBbgHBGQhAgWgEADgAEqhAQkdgvmMiCQlYhvgpgFIARgFIAfgMQAMgEAwgMIAygLQBDgRBvguQBBAEBQATIAEABIBQAWIAgAKIAGABIAUAGQF9BwGEA0IAsAGQAsAFBGAFIAbABIADABIAHADIACABQhJAEg3AQQhQAdgpAKIgwAHIgPADQgTADgNAEQgbAIg9AeQg3AcghAHQAhgHA3gcQA9geAbgIQANgEATgDIAPgDIAwgHQApgKBQgdQA3gQBJgEIADAFQAEAKAAALQADAQAAAWIABARIgBAVIgDgBIAAAJIAAAIIhuAkIgEABQhGAVgZAFIhOAQQgtAKg0AVQghANgxAYgArij8IgxgOQABg6ANggIAFgBQApAFFYBvQGMCCEdAvIBAByg");
	this.shape_47.setTransform(860.925,513.975);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#664D14").s().p("AABLrQABgVAKgZIAYg0QASgkAziNQAlhlAog5QgoA5glBlQgzCNgSAkIgYA0QgKAZgBAVIhUgYQAGgoAbg3IAthdQAFgQAThBQAPgxAPgdQARgeAGgQQAKgagFgUIBpAeIAnALQhUCygmDLIAAAEIhiAtIAAgIgAOIGdIikjlIAAAAIABgGIAAgKIgDgBIgBAKIAAAHIhtAkIgEABQhGAWgZAEIhPAQQgtAKg0AWQghANgwAYIhAhyQkcgwmNiBQlZhvgogFIARgFIAfgMQAMgEAwgMIAygLQBCgQBvgvQBBAEBRATIADABIAAgDIAAgvIgCgTQgCgKACgWQAoAAAoACIgBAnIAAAGIACATIAAAKIAAABQACAPAAASIAAANIAgAKIAGACIAUAFQF9BwGDAzIAtAGQArAFBGAFIAbACIADABIAIACIACABIADAFQAEAKAAAMQACAPABAWIAAARIAAAVIAAgVIAAgRIBZB5IBcB+IgSAkIAAAAgAJaBWQhQAdgpAKIgvAHIgQADQgTAEgNAEQgbAIg8AeQg3AcgiAGQAigGA3gcQA8geAbgIQANgEATgEIAQgDIAvgHQApgKBQgdQA3gQBKgEQhKAEg3AQgALkC4IAEgBgAkliIIhRgWIBRAWgAN1GXIhOgZQg4gSgfgcIgTgUIgRgVIg8hKIAEgBIBtgkQABACAAABQAAABAAAAQAAAAAAAAQABAAAAgBIABgDICkDlIgTgGgAs8FyIAAAAgAuAFfQgEADgJgHIgMgKIAxiOQAUg4Aag3IAMgcQAEgMABgJIBlAcIAzAOQgnAngYAnIgNAYIgaA2QgPAigDAXQgEAWAGAdIg1AdQAIhGAphbIAVgtIAyhlIgyBlIgVAtQgpBbgIBGQg/gWgFADgAs8AdIgygOQACg5AMggIAGgBQAoAFFZBvQGNCBEcAwIBABygAJCAyIAAiMIgugIIhMgPQgvgJkNg/Qi/gth8gQQgrgFgqgDIAFCCIgGgCIgggKIAAgNQAAgSgCgPIAAgBIAAgKIgCgTIAAgGIABgnIAiACIACABIgCgBIgigCQgogCgoAAQhAgBhAAEQgFhYAAh9QA7AABGAIIAAhPIA3gDIg3ADQhEAFg/AJQABhdAJiHQDJALEsAKQgCAEgCAEQAFAIAMgFQAGgBALgGIAFgCQE/ALGqAKQA0ASAcgRIgLD9IgBADQgigFgUAMQgCh9gMiLQAMCLACB9IgBAAIhwgLIg6gHIA6AHIAABvIBrAMIAPEZIgPkZQAJgBAMABIAqADQgKARAAAgQgBBrAGBWIAAAPQgBAIgEAGQgYAJgDAAIgLgCIh1gSIg0gJIg4gKIA4AKIA0AJQgBAWABALIADAMQACAJAAAIQACAKgBATIgBAoQhGgFgrgFgAkanCIAOACIAIABQFGAkHnA0IBGAIIA6AFIg6gFIAAhxIhGgHIlngmQjqgYhvgHQg9gEg6AAIgNAAIABBeIhigLIBiALgAlFofIAABUIAAhUIAqgBIgqABgAJCAyIAAAAgAJCAyIgtgGIgBiOIAuAIIAACMIAAAAgAKuhHIAAAAgAIUhiIAAAAgAIplnIAAhwIBGAHIAABxIhGgIgAIpnXg");
	this.shape_48.setTransform(869.975,485.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f().s("#000000").ss(1,1,1).p("EBBAgprIDGAxQFqBKGmg5IAAgBEBIBgfYIAAnbEAv6gm7IFKmoEA7KghoIDdmxEAlcgweIGojDEAfWg8QIIFAAEA2LgCQQACgEAGgKQAGgKAFgEQAKgLAQgCQAQgCAOAHQALAGAMAOQAGAHAMAOQAqAfAhAhEA1wgB4QAPgFALgRQAAgBABgBQAMAAAJAEQAIAFAFAIIAAAAEA2zgBsQgFABgFABQgEABgFAAQgGAAgDAAIAAAAQAEAtAMAZQALAYAZASQAWASAkAEQALABAMgBQAMAAAXgCQAEAAAEAAQAcgDAOAAQAEAAAEAAIARAAQAGgBALgEQALgFAHgFQgXgEgWgTQgCgCgDgDEA1wgB4IgBAAIgBAAIApAPEA1wgB4QAKgDAHAAQAQABAAAAQAQABAMgGQAEAGAAABQABAEABAIQAMgBAEAAQAaAAAOAOQAAAFAAAEQACARAHAMQAHAMAQAJQACABACABQAEACAEACIAAgOQAAgCADgBIACABQAIAGAIABQAEAAABgBQACgBAAgDIAAgVIAKAIQADADAEAAQAEAAACgFQACgCgCgOQAJAKAJAKQAUAYALAMEA31gCSQADACAEACQAAAAABABQAAAAABABQABAAAAABEA39gCNQgJgBgFAKQgEAIAAAIQAAANAAAIEBDeAF3QgBh+gMiLQAzATAdgRQgEBTgICpIgBAEQghgFgVAMgEBBuAFrIBvAMIABAAEBAzAFlIA7AGIAABwQA0AGA3AGQAIgBANABQAMAAAeACQgKASAAAgQgCBqAHBXQAAAOAAABQgBAIgEAFQgZAJgDAAQgFgBgGAAEAzAAI2QApADAsAGQB7AQDAAtQEOA+AvAKQAmAHAmAHIABCQQAWADAWACQAsAGBGAFQANAAAOABQABABACAAQACABAFACQABAAABABIAAAAQAPgDgbgCEBAGALbIAACMEA/ZALSQAXAFAWAEQAcAFAcAFQAaAEAaAEQAAAXABALQABAEABAHQADAKAAAIQABALAAATQAAAVgBATEBAzAHVQAdADAeADEBCfAN4QACABABAEQAEAKAAALQADAQABAWQAAAIAAAJQAAAMAAAJQgBAFAAAEQAAAEgBACIAAABQAAABAAACQgCADAAgGIACgBIAEgBEBByALtQA7AKA6AJEBCRANvQAAADACABEBDZAHnIAOEZEA6XAQNQAhgHA3gcQA9geAbgIQANgEATgDQAHgCAIgBQAqgGAGgBQApgKBQgdQA3gRBJgDEA/uAFeIBFAHIAABwEA/uAHOQAiADAjAEEA/uAFeIAABwEA4XgAeQAGADAHACQAqAMAtgGEA4FAAdQgQALgCADQgLAIgDACQgFACgMAAIggAAQgGAFABAHQADAGAIABIAdgEQATgCAGgEQAIgDAMgNQAMgMAMgHEA4/AAbIg8AoIAZADQACABAEABQADABABACQACADgBADQgCADgDAAQgegHgdAMQgCABgCACQgMAGgGABQgLAFgGgJQABgEAEgDQAEgEAJgCQAFgCATAAQgMgBgbAAQgGACgFgHIACAAEA3FABYQARABARAAQE/ALGrAKEAypAEVQAGAAAGAAQA7AAA9AEQBuAGDrAZIFoAmEAxHAEZQAbgCAcgBIAABUEAypAFzQAHABAIABQADAAAEAAQFHAlHoA0EAxHAFoQAvAFAzAGEAxHAEZIAABPEAx+AEWQAVgBAWAAIAABeEAxHAEZQhDAEhAAKQAChdAIiHQDKALEtAKEAxMAIxQhAAAhAAEQgFhYAAh9QA6AABGAIEAxMAIxQgCAXABAKQABAGACANIAAAuQAAACAAACQAXAGA5AQQAQAFAQAFQADAAADABQALADAJADQF+BwGEA0EAppALqQAIgCAJgDQALgEAUgIQAMgEAwgMIAygLQBDgRBvguQBBAEBQATQACAAACABEAybAI0QgBAjAAAKQABAGABANIAAAKQADATgBAcEAxMAIxQAnABAoACQARABASABQABAAABAAIAECCEA3GAYhQABgVAKgaQAAgCAYgyQASgjAziNQAlhmAog5EA3GAYhIhVgYQAGgoAbg3QAphUADgJQAGgQAUhBQAOgxAPgdQARgeAGgQQALgagGgUEA6iAR6QhUCygmDMQAAACgBACIhhAtQAAgEAAgEEBCmAPuQAAgDAAgFQAAgEAAgFIAEABEBA0AQTQACgBACAAIBugkEBA0AQTQAoAxAUAZQAGAHAMAOQAKAMAJAIQAfAbA3ATQAcAJAzAQQAJACAJADEBECAQxIBdB+IgTAjEBCoAPuICkDkEBCqAO4IBYB5QGWCSGVESMAAAAlgMihZAAAMAAAglMQFoiyCVguQKxjdKbg1EA7UASCQAxgYAhgNQA0gWAtgKQAagGA0gKQAZgFBGgVEAppALqQApAEFYBwQGNCBEdAwIBABzIxNkwIgxgNQABg6ANggQACgBADAAgEAqbANYQgBAKgEALQgDAGgKAWQgaA4gTA4QgZBGgZBIQAEADAJAHQAIAHAFgDQAEgDBAAWIA0gdQgFgeADgWQADgWAQgiQAPgiALgUQAKgUACgEQAYgoAogmEAr/AN0QgTAngeA/QgKAVgMAXQgpBcgHBGEAnCAQrQBNgbBNgXAZtXfQGwkfGliVEArzAPRQBkgYBjgQEggrg15QgGiGAthgQAqhaBXg1QAsgcA0gRQCHgrC1AfQAcAFAfAHQBIAQBZAbQBKAXCPAtQDaBCDvASQBZAHAaAEQBAAKAsAZQA1AdAZA3QAaA7gYAxQBzAGBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBiQBKBiADB0QADBzhFBlQhFBmhsAnQBRA3AUBpQAVBqg3BQQg3BRhqASQhqAThQg6QAuBLgPBeQgQBehDA4QhEA5hegBQhWgBg/gxQAbAbgIAvQgKA4grAbQgmAYg3AEQgkADhBgGQi3gRhugpQiMg2g6hnEggrg15QAjgaAWgMQBCgoBMgQQBNgPBMALQBTALAeAxQATAdgLAjQgMAkggAFQAugFBggSQBdgSAxgEQBPgGBCAQQBLATAxAvQA2AzAGBNQAGBQg1AvQBtgjBkBWQBiBVgEB2QgFBwhZBZQhVBWh1AVQAeBUgOBbQgOBbg3BFQg2BGhWAjQhVAkhXgLQh1BXiZgFQgGgBgFAAQAAgCgBgCAq82pQgGgFgGgFA3n7ZQAmgmAngsIAAECIAxA+QgRAQgRARQgFgKAngXA3n7ZQhfgZg7hCQg6hAgMhQQiQgIhohWQhTHZCsBeQCqgWDVjYgEgwDg5cQB3hKBNgeQB7gwBnASQA4AKAxAoQAvAmAaA2QAbA3gFA0QgEA1gkAlQgDACgCADEgnhgiYQhLgVhIg5QiQh0gYisQgKhDAKhEQAJhFAbg9QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgZQBFgYAhgRQAkgUA+gvQAWgSASgNEgm9g2PQBLhHBxgBQB1gBBNBKQALAKAJALEgwDg5cQgGAFgHAEEg5Gg4UQBQhPBkg3QBng6BzgaQBsgZA4AoQAkAYADAwQACAogYATEgtVggFQgGgSgFgSQgNgqgJgsIhFCWIi/AAQAUAbATAcQACCIgyBdQgyBehZAtQhZAthogPQhpgQhIhEQg/BNhnAfQhfAdhqgSQhpgShQg7QhWg/giheQhAA2hMATQhTAVhGgeQhKgggZhVQgahWA2g4Qg3AehCgZQhAgYgjg4QgggygKhFQgIg2AFhMQAYlRDLkhQDKkiE0iKQBWh/CAhbQCAhaCUgmQBEgRAnAUQAZANAHAeQAGAYgNAQQgCAEgFAEEgnhgiYQgvAhgdAVQhcA+hFAVQhFAWhCgMQBTDuDCB+QAhAVAlATQAOAHAQAHQCMjYA4lbQALhEAIhKQABgJABgKQACgNABgNIASAkQgLAEgMAFEgjugktIBrDQIDhhUQgRBLgMBEQgDgCgCgCEgkYgiWQh4AUhRgWEgxTgeyQAGAIAFAIQJhOgqxc5QgkBfgnBhQC9gOC7gCQKDgFJuCaQAPgGAPgFQg1ikivukQiruLJgpoAFIGLQAAgFAAgFQBHgdA0g/QAzg+AOhMQAFgfgKgOQgPgYgrADQgaACgYALQgFACgcAPAJ/J0QASgEASAJQASAKAIARQAIASgGAoQAAABAAACQgFAigQAMQgMAJgZACQgXADgMgIIAAgHQAJgOAHgPQADgJADgJQAGgVABgXQAEgWgEgZQgCgHgCgGQgIgegSgZAJ/KjQABgOgCgOQgEgwgZgnQgHgKgJgIQgvgzhggdQgjgLgMgFQgZgJgSgJQgTgJgNgYAEMMrQAAADACADQABAEADAFQAHAKAMAEQAMAGAjACQAZABAyAFQAsACAfgGQAtgJAkgfQAYgTAPgZAC5EEQABAAACgBQAAgYASgyQAahFAOgfQALgXAKgNQANgSAQgJQARgMAWABQAWACANAPQAKALAEAXQAGAeADANQgBAAgWAOQADgEgSAOQgOAMgOAOQgLAMgtBHIgcAtQgbgSgfgFQAAAAAAAAgAgXHSQgIguABgIQACgQAIgPQAAgBABgBQAGgKAOgSQAageAHgIQATgUASgLQAmgZAwAAQALAAALACQADAAADABACEGWQAAAGgFAFQgEAEgHAAQgGAAgFgEQgEgFAAgGQAAgHAEgEQAFgFAGAAQAHAAAEAFQAFAEAAAHgAEPDuQAkg8AEgFQAVgbAXgRABtLxQgCADgHACQgLAEgBABQgNAEgFAKQgHAQAKARQALAWATADQAKANAhAAQARAAAIgBQAOgCAKgFQATgKAUgnQABgBAAgBQALgWAAghQAAgDAAgEQAAgegNgZABoItQgDgBgEgBQhFgNgigtQgLgPgGgQQgBgmAKAAQAGAAACABQAGAEAAAKQgBAJgIAGQgDACgLAGAG1IoQglAMgcATQgyAkgJAmQgGAZAIAfQABAFACAGQAFAPAKAYQAAAAABAHQgKgBgIACQghAHgHAIQgIAIgBAKQAAADABAEABoItQgJAqAEAjQAFAjARAeQALARAHAKQABABABACQABACACADQAGAJABACQAFAIgBAFQgCAHgLAFQgTAJgJAIQgOAMAAAOQAAAKADAMABoItQAmAGAmgGQArgIAigYQAjgXATgnQARgiAAgiACNLZQgSAPgOAJADqMXQAOAKAHAEQAFADAIADAGSMXQgogUgcgBA5JRxIAMgDA56R8IAxgLQA0gUA0gTIZOlZA56R8QLoC4HqC1AK/LRQOKAYN5FC");
	this.shape_49.setTransform(517.525,403.5907);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AhEAAQAGAAADABQAGADAAAKQgCAKgIAGQgDACgLAGQgBgmAKAAgAA0gLQgFgEAAgHQAAgGAFgEQAEgFAHAAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAQgHAAgEgFg");
	this.shape_50.setTransform(522.8941,446.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#009900").s().p("EhQsA81MAAAglMQFoiyCVguQKxjdKcg1QC8gOC7gCQKDgFJuCaQLoC4HqC1Qnqi1roi4IAxgLIAMgDIBcgkIZOlZQgCADgHACIgMAFQgNAEgFAKQgHAQAKARQALAWATADQAKANAhAAIAZgBQAOgCAKgFQATgKAUgnIAVAOIANAGIACAGQABAEADAFQAHAKAMAEQAMAGAjACIBLAGQAsACAfgGQAtgJAkgfQAYgTAPgZIAAAHQAMAIAXgDQAZgCAMgJQAQgMAFgiQOKAYN5FCQmlCVmwEfQGwkfGliVQBNgbBNgXIgyCOIANAKQAIAHAFgDQAEgDBAAWIA0gdQgFgeADgWQADgWAQgiIAZg2IANgYQBkgYBjgQIiHgmIg0gPIhkgcIgUgGIRNEwQAxgYAhgNQA0gWAtgKIBOgQQAZgFBGgVIA8BKIASAVIATAUQAfAbA3ATIBPAZIASAFIATgjIhdh+QGWCSGVESMAAAAlggEA4MASAQgGAQgRAeQgPAdgOAxQgUBBgGAQIgsBdQgbA3gGAoIBVAYIAAAIIBhgtIABgEQAmjMBUiyIgogLIhpgdQAGAUgLAagAEOMxQAAgBAAAAIABABgAugzzQi3gRhugpQiMg2g6hnIAighIgxg+IAAkCQgnAsgmAmQhfgZg7hCQg6hAgMhQIALABIACAAIAOAAIAAAAIABAAQCLAABshOIABgBIABAAIACgCIACgBIABAAQATACATAAIAAAAIABAAQA+AAA+gYIACAAIABgBIAEgBIABgBQBWgjA2hGQA3hFAOhbQAFgdAAgcQAAg9gVg5QB1gVBVhWQBZhZAFhwIAAgKQAAhvhehSIgGgFQhEg4hIAAIgBAAIAAAAQgdAAgeAJIAAAAIgDABQAvgqAAhEIAAgRQgGhNg2gzQgxgvhLgTIgEgBIgFgBQgtgKgyAAIAAAAIAAAAIgiABIgFAAIAAAAIgCABQgxAEhdASQhgASguAFQAggFAMgkQAEgOAAgMQAAgUgMgSQgegxhTgLIgEgBQgdgEgeAAIAAAAIgBAAQgsAAgtAJQhMAQhCAoQgWAMgjAaQAjgaAWgMQBCgoBMgQQAtgJAsAAIABAAIAAAAQAeAAAdAEIAEABQBTALAeAxQAMASAAAUQAAAMgEAOQgMAkggAFQAugFBggSQBdgSAxgEIACgBIAAAAIAFAAIAigBIAAAAIAAAAQAyAAAtAKIAFABIAEABQBLATAxAvQA2AzAGBNIAAARQAABEgvAqIADgBIAAAAQAegJAdAAIAAAAIABAAQBIAABEA4IAGAFQBeBSAABvIAAAKQgFBwhZBZQhVBWh1AVQAVA5AAA9QAAAcgFAdQgOBbg3BFQg2BGhWAjIgBABIgEABIgBABIgCAAQg+AYg+AAIgBAAIAAAAQgTAAgTgCIgBAAIgCABIgCACIgBAAIgBABQhsBOiLAAIgBAAIAAAAIgOAAIgCAAIgLgBIgBgEIABAEQiQgIhohWQAMhEARhLIjhBUIhrjQIgSgkIgDAaIgCATQgIBKgLBEQh4AUhRgWQhLgVhIg5QiQh0gYisQgFgiAAghQAAgiAFgiQAJhFAbg9QAWgyAlg5QAZgkAwg/QBEhXApgrQBChDBDgjQAggQBHgZQBFgYAhgRQAkgUA+gvIAogfQgGiGAthgQAqhaBXg1QAtgcAzgRQCHgrC1AfIA8AMQBHAQBZAbIDZBEQDaBCDvASQBZAHAaAEQBAAKAsAZQA1AdAZA3QAaA7gYAxQBzAGBfAwQBpA1AxBaQA2BhgmByQgmB1hmAZQBtAjBKBiQBKBiADB0QADBzhFBlQhFBmhsAnQBRA3AUBpQAVBqg3BQQg3BRhqASQhqAThQg6QAuBLgPBeQgQBehDA4QhEA5hegBQhWgBg/gxQAbAbgIAvQgKA4grAbQgmAYg3AEIgYABQgfAAgugEgAq82pIgMgKIAMAKgEg/vgYBQhpgShQg7QhWg/giheQhAA2hMATQhTAVhGgeQhKgggZhVQgahWA2g4Qg3AehCgZQhAgYgjg4QgggygKhFQgIg2AFhMQAYlRDLkhQDKkiE0iKQBWh/CAhbQCAhaCUgmQBEgRAnAUQAZANAHAeQAGAYgNAQIgHAIIAHgIQBQhPBkg3QBng6BzgaQBsgZA4AoQAkAYADAwQACAogYATQgGAFgHAEQAHgEAGgFQB3hKBNgeQB7gwBnASQA4AKAxAoQAvAmAaA2QAbA3gFA0QgEA1gkAlQBLhHBxgBQB1gBBNBKQALAKAJALIgoAfQg+AvgkAUQghARhFAYQhHAZggAQQhDAjhCBDQgpArhEBXQgwA/gZAkQglA5gWAyQgbA9gJBFQgFAiAAAiQAAAhAFAiQAYCsCQB0QBIA5BLAVIhMA2QhcA+hFAVQhFAWhCgMIgLgkQgNgqgJgsIhFCWIi/AAIAnA3QACCIgyBdQgyBehZAtQhZAthogPQhpgQhIhEQg/BNhnAfQg7AShAAAQgmAAgogHgEgnCg2KIAFgFIgFAFg");
	this.shape_51.setTransform(517.525,403.5907);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("A2OHRIhLgGQgjgCgMgGQgMgEgHgKQgEgFAAgEIABAAIgBgBQAAAAAAABIgCgGIgBgFIAAgCQABgKAIgIQAHgIAhgHIAMgBIACAAIAAAAIADAAIABAAIgCgHQgKgYgEgPIgDgLQgFgRAAgQQAAgMADgLQAJgmAygkQAcgTAlgMQglAMgcATQgyAkgJAmQgDALAAAMQAAAQAFARIADALQAEAPAKAYIACAHIgBAAIgDAAIAAAAIgCAAIgMABQghAHgHAIQgIAIgBAKIAAACIABAFIgNgGIgVgOIABgCQALgWAAghIAAgEIAAgDQAAgegNgZQANAZAAAeIAAADIAAAEQAAAhgLAWIgBACQgUAngTAKQgKAFgOACIgZABQghAAgKgNQgDgMAAgKQAAgOAOgMQAJgIATgJQALgFACgHIAAgCQAAgEgEgHIgHgLIgEgFIAEAFIAHALQAEAHAAAEIAAACQgCAHgLAFQgTAJgJAIQgOAMAAAOQAAAKADAMQgTgEgLgVQgKgRAHgQQAFgKANgEIAMgFQAHgCACgDQAOgKARgOIgBgDIgSgbQgRgegFgjQgEgjAJgqIgHgCQhFgNgjgtQgLgPgGgQQALgGADgCQAIgGACgJQAAgKgHgEQgCgBgGAAQgLAAACAmQgIguABgIQACgQAIgOIABgCQAGgKAPgSIAhgmQATgUASgLQAmgZAwAAQALAAALACIAGABIgBAAQAgAFAbASIAcgtQAthHALgMQAOgOAOgMIACgBIACgCIABgBIAKgHIAAAAIAAAAIAAABIAhgRQAYgLAagCQArgDAPAYQAKAOgFAfQgOBMgzA+Qg0A+hIAeIABAJQANAYASAJQATAJAZAJIAvAQQBgAdAvAzQAIAIAHAKQAaAnAEAwQABAOAAAOQgBAXgGAVIgGASQgHAPgJAOQgPAZgYATQgkAfgtAJQgWAEgdAAIgYAAgA2bGSQgogUgcgBQAcABAoAUgA55CoQArgIAigYQAjgXATgnQARgiAAgiQAAAigRAiQgTAngjAXQgiAYgrAIQgTADgTAAQgTAAgTgDQATADATAAQATAAATgDgA7EAGQgEAEAAAHQAAAGAEAFQAFAEAGAAQAHAAAEgEQAFgFAAgGQAAgHgFgEQgEgFgHAAQgGAAgFAFgAzLGAIAAgHQAJgOAHgPIAGgSQAGgVABgXQAEgXgFgYQATgEASAJQASAJAIASQAIASgGAoIAAADQgGAigPAMQgMAJgZACIgMAAQgPAAgIgFgA46hpQgbgSgggFIABAAIADgBQAAgYASgyQAahFAOgfQALgXAKgNQANgSAQgJQARgMAWABQAWACANAPQAKALAEAXIAJArIgXAOIAAgBIAAAAIAAAAIgKAHIgBABIgCACIgCABQgXARgVAbIgoBBIgcAtIAAAAgA27kNIAAAAgAb2meIgNgFIAAgOQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAABAAIACABQAIAGAIABQAEAAABgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgVIAKAIQADADAEAAQAEAAACgFQACgCgDgOIATAUQATAYAMAMQgPACgOAAQgeAAgcgIg");
	this.shape_52.setTransform(701.3441,442.4993);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#664D14").s().p("AABL/IhUgYQAGgoAbg3IAthdQAFgQAThBQAPgxAPgdQARgeAGgQQAKgagFgUIBpAdQgoA5glBmQgzCNgSAjIgYA0QgKAagBAVQABgVAKgaIAYg0QASgjAziNQAlhmAog5IAnALQhUCygmDMIAAAEIhiAtIAAgIgAOIGwIikjkICkDkIgTgFIhOgZQg4gTgfgbIgTgUIgRgVIg8hKIAEgBIBtgkQABACAAABQAAAAAAABQAAAAAAAAQABAAAAgBIABgDIAAgBIABgGIAAgJIgDgBIgBAJIAAAIIhtAkIgEABQhGAVgZAFIhPAQQgtAKg0AWQghANgwAYIhAhzQkcgwmNiBQlZhvgogEIARgFIAfgMQAMgEAwgMIAygLQBCgRBvguQBBAEBRATIADABIAAgEIAAguIgCgTQgCgKACgXQhAAAhAAEQgFhYAAh9QA7AABGAIIAAhPQhEAEg/AKQABhdAJiHQDJALEsAKQgCADgCAEQAFAJAMgFQAGgBALgGIAFgDIgjgBQAFgEAJgCQAEgCAUAAIgmgBQgHACgEgHIABAAIAdgEQATgCAGgEQAHgDAMgNQAMgMANgHIAigCIg7AoIAZADIAFACQADABACACQACADgCADQgBADgDAAQgfgHgcAMQE/ALGqAKQA0ATAcgRIgLD8IgBAEQgigFgUAMQgCh+gMiLQAMCLACB+IgBAAIhwgMIg6gGIA6AGIAABwIg6gGIAAhwIhGgHIlngmQjqgZhvgGQg9gEg6AAIgNAAIgqABIAqgBIABBeIhigLIBiALIAOACIAIAAQFGAlHnA0IAAhwIBGAHIAABwIA6AGIBrAMIAPEZIh1gTIg0gIIg4gKIA4AKIA0AIQgBAXABALIADALQACAJAAAIQACALgBATIgBAoQhGgFgrgGIAAiLIgugJIhMgOQgvgKkNg+Qi/gth8gQQgrgGgqgDIgCAAIgigCQgogCgogBQAoABAoACIAiACIACAAIAFCCIgGgBIgggKIAAgNQAAgTgCgOIAAgBIAAgKIgCgTIAAgHIABgmIgBAmIAAAHIACATIAAAKIAAABQACAOAAATIAAANIhRgWIBRAWIAgAKIAGABIAUAGQF9BvGDA0IAtAFQArAGBGAFIAbABIADABIAIADIACABQhKAEg3AQQhQAdgpAKIgvAHIgQADQgTADgNAEQgbAIg8AeQg3AcgiAHQAigHA3gcQA8geAbgIQANgEATgDIAQgDIAvgHQApgKBQgdQA3gQBKgEIADAFQAEAKAAALQACAQABAWIAAARIAAAVIAAgVIAAgRIBZB5IBcB+IgSAjIAAAAgALkDLIAEgBgAJvlMIhGgHIBGAHgAlFm3IAAhUIg3ADIA3gDgAs8GGIAAAAgAuAFzQgEADgJgHIgMgKIAxiOQAUg4Aag4IAMgcQAEgLABgKIBlAcIAzAPQgnAmgYAoIgNAYIgaA2QgPAigDAWQgEAWAGAeIg1AdQAIhGAphcIAVgsIAyhmIgyBmIgVAsQgpBcgIBGQg/gWgFADgAs8AwIgygNQACg5AMggIAGgBQAoAEFZBvQGNCBEcAwIBABzgAC2FNIAAAAgAJCBFIAAAAgAJCBFIgtgFIgBiPIAuAJIAACLIAAAAgAMjghIgPkZQAJgBAMABIAqACQgKASAAAgQgBBqAGBXIAAAPQgBAIgEAFQgYAJgDAAIgLgBgAIUhPIAAAAgAklh0IAAAAgAJvlMIAAAAgAgUreQgCgHAHgFIAeAAQANAAAFgCIANgKIASgOQALABANgBQgNAHgMAMQgMANgHADQgGAEgTACIgdAEQgIgBgCgGgABYsEIAAAAg");
	this.shape_53.setTransform(869.975,483.7875);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#666699").s().p("AgWBrQgkgDgWgTQgZgSgLgZQgMgYgEgsIAAgBIAJAAIAJgBIAKgBIAQgBQAaAAAOAOIAAAJQACAQAHALQAHAMAQAJIAEADIAIAEIgIgEIgEgDQgQgJgHgMQgHgLgCgQIAAgJIAAgDIAAgTQAAgIAEgIIABgBQAEgHAGgBIABAAIAAAAIAAAAIACAAIgCAAIAAAAIAAAAIgBAAQgGABgEAHIgBABQgEAIAAAIIAAATIAAADQgOgOgaAAIgQABIgCgMIgEgHIAAgBQgFgHgIgFQgJgFgMABIAIgPQAGgJAFgFQAKgLAQgBQAQgCAOAHQALAGAMANIASAVQApAfAhAgQACAOgCADQgCAFgEAAQgEAAgDgEIgKgHIAAAVQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBABQgBABgEAAQgIgCgIgGIgBgBQgBABAAAAQgBAAAAABQAAAAAAABQgBAAAAABIAAAOIAMAFQAqALAtgFIAFAEQAWAUAXAFQgHAFgLAEIgRAGIgRAAIgIAAQgOAAgcACIgIABIgjACIgHAAIgPgBgAhehFIgBAIIABAIQABABAAAAQAAABAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIABgIIgBgIQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAgBABgAgfg/IABAAIABACIABAAIgBAAIgBgCIgBAAIgHgFIAHAFg");
	this.shape_54.setTransform(878.7125,395.7358);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFF33").s().p("AoJeaIAAAAIABgBQAQgFAKgRIABgBQAMgBAJAFQAIAEAFAIIAAAAIAEAIIACALIgKACIgJABIgJAAIAAABgAoIeZIACAAIAJgCIABAAIADgBIABAAIAAAAIABAAIABABIAPAAIACAAIAEAAIABAAIAAAAQAMAAAJgFQgJAFgMAAIAAAAIgBAAIgEAAIgCAAIgPAAIgBgBIgBAAIAAAAIgBAAIgDABIgBAAIgJACIgCAAgAHqooIjFgxIhBgVQhvglhpgyQoWkFjkjFQjljFiLjsQg3hggkhVIgLgcQgchJgOhCIgCgMMAnhAAAIgSWIIhBAIIgrAFQiEAMh+AAQjLAAi8ghg");
	this.shape_55.setTransform(913.6,196.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]},1).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_39},{t:this.shape_38},{t:this.shape_31}]},1).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_35},{t:this.shape_40},{t:this.shape_31}]},1).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_45},{t:this.shape_39},{t:this.shape_36},{t:this.shape_35},{t:this.shape_44},{t:this.shape_31}]},1).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_45},{t:this.shape_39},{t:this.shape_36},{t:this.shape_35},{t:this.shape_46},{t:this.shape_32},{t:this.shape_31}]},1).to({state:[{t:this.shape_46},{t:this.shape_34},{t:this.shape_33},{t:this.shape_45},{t:this.shape_39},{t:this.shape_36},{t:this.shape_35},{t:this.shape_47},{t:this.shape_38},{t:this.shape_31}]},1).to({state:[{t:this.shape_46},{t:this.shape_34},{t:this.shape_48},{t:this.shape_33},{t:this.shape_45},{t:this.shape_39},{t:this.shape_36},{t:this.shape_35},{t:this.shape_32},{t:this.shape_31}]},1).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_34},{t:this.shape_53},{t:this.shape_52},{t:this.shape_33},{t:this.shape_51},{t:this.shape_42},{t:this.shape_50},{t:this.shape_49},{t:this.shape_31}]},1).to({state:[]},3).wait(10));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({scaleY:0.7778,y:360.5111},0).wait(1).to({scaleY:0.5556,y:324.6222},0).wait(1).to({scaleY:0.3333,y:288.7333},0).wait(1).to({scaleY:0.1111,y:252.8444},0).wait(1).to({skewX:180,y:216.9556},0).wait(1).to({scaleY:0.3333,y:181.0667},0).wait(1).to({scaleY:0.5556,y:145.1778},0).wait(1).to({scaleY:0.7778,y:109.2889},0).wait(1).to({scaleY:1,y:73.4},0).to({_off:true},1).wait(20));

	// envelope
	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f().s("#000000").ss(1,1,1).p("EA6XglQMAAABKhMh0tAAAMAAAhKhMA01AsaIEDDZIE3j6gEg6WAlRMA01geHEg6WglQMB0tAAAADZGpMA2+Aeo");
	this.shape_56.setTransform(481.525,473.375);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#99F1F7").s().p("AlhUgMg01gsZMB0tAAAMg2+Ar5Ik3D6g");
	this.shape_57.setTransform(481.525,387.9);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#99CCFF").s().p("Eg6WAlRMA01geHMg01AeHMAAAhKhMA01AsaIEDDZIE3j6MA2+AeoMg2+geoMA2+gr5MAAABKhg");
	this.shape_58.setTransform(481.525,473.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56}]}).to({state:[]},10).wait(20));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(512,294.9,528.0999999999999,499);
// library properties:
lib.properties = {
	id: '4131846B358CA446A09963DCBD224D03',
	width: 1024,
	height: 768,
	fps: 10,
	color: "#00BDD9",
	opacity: 1.00,
	manifest: [
		{src:"images/PracticeCard_CRuiz_atlas_1.png?1652127696685", id:"PracticeCard_CRuiz_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4131846B358CA446A09963DCBD224D03'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;