(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.BasicButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMBTQgIgFgEgJQgEgJAAgVIAAgrIgSAAIAAgjIASAAIAAgXIAvgYIAAAvIAaAAIAAAjIgaAAIAAArQAAAIABADQADADAFAAQAGAAAJgDIAEAiQgSADgPAAQgRAAgJgEg");
	this.shape.setTransform(74.8,25.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAXA+IgXgoIgaAoIg0AAIAthAIgqg7IA4AAIATAiIAXgiIA0AAIgqA7IAuBAg");
	this.shape_1.setTransform(61.5,27.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgmA6QgPgHgJgPQgJgPAAgVQAAgcASgSQAUgSAgAAQAaAAAQAIQAPAIAIAQQAIAPAAAXIAAAGIheAAQABALAEAGQAIAIAJAAQAIAAAGgDQAEgDAFgFIAuAEQgLATgPAIQgPAIgcAAQgYAAgOgHgAgRgbQgFAGAAALIAuAAQgCgOgGgGQgGgGgKAAQgKAAgHAJg");
	this.shape_2.setTransform(46.2,27.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAgBWIg/hdIAABdIgyAAIAAirIAxAAIBABeIAAheIAyAAIAACrg");
	this.shape_3.setTransform(28.1,25.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Rounded
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("AnBj5IODAAQAyAAAAAyIAAGPQAAAygyAAIuDAAQgyAAAAgyIAAmPQAAgyAyAAg");
	this.shape_4.setTransform(50,25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_5.setTransform(50,25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF99").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_6.setTransform(50,25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_7.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_6},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_4}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

	// Squared
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("Anzj5IPnAAIAAHzIvnAAg");
	this.shape_8.setTransform(50,25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCCCC").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_9.setTransform(50,25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFF99").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_10.setTransform(50,25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_11.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8}]}).to({state:[{t:this.shape_10},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_8}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,102,52);


// stage content:
(lib.AnimatedCardAMerida = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bunny
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0099FF").ss(1,1,1).p("Aj/AAQAAAdgVAUQgVAVgdAAQgdAAgVgVQgUgUAAgdQAAgcAUgVQADgDADgCQATgQAZAAQAdAAAVAVQAOAOAFATQACAIAAAIgAGNAEQAAASgIAOQgEAIgHAHQgTATgcAAQgbAAgUgTQgTgTAAgcQAAgaATgUQAUgTAbAAQAcAAATATQAHAHAEAIQAIAPAAAQg");
	this.shape.setTransform(342.7,473.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AIZk5QAGhFAGhRQAFhUAjh6QAhh6AqhZQAqhZA6AAQA8AAApBZQAqBZAAB9QAAB+gqBYQgpBZhuBeQglAfgZANQg0AagGgvQgCgNABgPQg+AjAGhGQAAgCAAgCQAdASAbAVQAbAUAaAXQADADADADQBuA4BrFAQBrFBkVEOQiaCUiiBIQgeAOgfAKQgPAGgPAEALynfQAAA5gWApQgWAogpAPQgoAPgLg3QgMg4AAg5QAAg4AWgpQAVgoAfAAQAfAAAVAoQAWApAAA4gApqiXQgRgFgTgKQiLhHg5hwQg4hwAAidQAAicA3hvQA4hvBOAAQBNAAA3BvQA4BvAACcQAACdAHC3QAAARAAAQQgFB6hbgcQAkgpArgnQAJgHAIgHQDwjKFPAAQESAADSCGAp9m3QAAA3ARBFQASBFg6gWQg6gWgegvQgfgvAAg3QAAg4AVgnQAVgoAdAAQAeAAAUAoQAVAnAAA4gAs4JeQgfgogShDQgShEAphuQAohuAAgSQACgbAth8QAuh8BjhFAhzDGQAABCgvAvQgvAvhCAAQhDAAgwgvQgvgvAAhCQAAhDAvgwQAwgvBDAAQBCAAAvAvQAvAwAABDgAkRI0QiWBxiWhxAkRI0QgqCpiUgKAsEJbIAAgCIAAAAQgBgBgFgBQgMAAgiAHAsTJ1QAEALADAGIAAgDIAAgBIACgrAsEJZQgDgCgFArQAAgmgsACAjpPXQjNhGjaitQhAgzgzgtAjoPXIAGAAIgHAAAjoPXQgBAAAAAAAi9PkQgQgEgRgGQgFgBgFgCAkRI0IjSirAIADdQAAA7grAqQgpAqg7AAQg7AAgqgqQgpgqAAg7QAAg6ApgrQAqgpA7AAQA7AAApApQArArAAA6gAEWJvQDNgIgbC8AEWJvQCnheCDBeAhIJLIhVhGIEHAAIhsBNIgnAdIgfgkIgKgBQiQBzgviJAEWJvQjJBwhPiNAEWJvQBcjiDiAGAjiPXIJhgVAFCPaIokgD");
	this.shape_1.setTransform(344.5,450.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ai9PlIghgKIgKgEIAGAAIgHAAQjNhGjaitQhBgygyguQABgNgBgdIgBgBIAAAAIgGgBQgMgBgiAIQgggpgRhDQgShEAohuQAphuABgRQABgbAth9QAuh8BjhFQAkgpArgnIARgOIgRAOQgrAngkApQgRgFgTgJQiLhIg5hwQg4hwAAidQAAicA3hvQA4hvBOAAQBOAAA3BvQA3BvAACcQAACdAHC3IAAAhQDwjKFPAAQERAADTCGIAMiWQAGhUAhh6QAih6AphZQArhZA7AAQA6AAAqBZQAqBZAAB9QAAB+gqBZQgqBYhuBeQgkAfgZANIgGgGQgagWgbgUQAbAUAaAWIAGAGQBuA4BrFAQBrFBkWEOQiZCUiiBIIphAVIJhgVQgeAOgfALIokgEIIkAEIgfAKgAHHMjIABgEQAYixi7AAIgBAAIAAAAIgOAAQCnhdCDBdQiDhdinBdQBajbDYAAIAAAAIAAAAIAMAAIgMAAIAAAAIAAAAQjYAAhaDbIgDACIgCABIgBABIgDABQhUAtg+ABIAAAAIAAAAQhRgBgrhMIgBgBIAAgBIBrhNIkHAAIBWBGIgJgBIgCABIgBABQhAAygtABIAAAAIAAAAQg2gBgZhIIgBgBIAAAAIAAAAIABABQAZBIA2ABIAAAAIAAAAQAtgBBAgyIABgBIACgBIAJABIAfAjIAngcIAAABIABABQArBMBRABIAAAAIAAAAQA+gBBUgtIADgBIABgBIACgBIADgCIAOAAIAAAAIABAAQC7AAgYCxIgBAEgAm/LUQCEgBApiZIABgEIAAgBQiWBwiWhwQCWBwCWhwIAAABIgBAEQgpCZiEABIAAAAIAAAAIgRgBIARABIAAAAIAAAAgAkRI1IjSisgADjDeQAAA6ApAqQAqAqA7AAQA7AAAqgqQAqgqAAg6QAAg8gqgpQgqgqg7AAQg7AAgqAqQgpApAAA8IAAAAgAm1DFQABBDAuAvQAwAwBCgBQBDABAvgwQAwgvAAhDQAAhCgwgwQgvguhDgBQhCABgwAuQguAwgBBCIAAAAgApMiRQA8gBAGhbIAAgFIAAgDIAAADIAAAFQgGBbg8ABIAAAAIAAAAQgMAAgPgFIgBAAIgBAAIAAAAIgBAAIAAgBIAAABIABAAIAAAAIABAAIABAAQAPAFAMAAIAAAAIAAAAgAJtjYQAMAAARgIIAAAAIABAAIABgBIgBABIgBAAIAAAAQgRAIgMAAIAAAAIAAAAQgXAAgEgeIgBgSIAAgJQgcgVgcgTIAAAEQgEAvAaAAIAAAAIAAAAQAOAAAUgLIAAAJIABASQAEAeAXAAIAAAAIAAAAgAp9kGQAdAAgLgxIAAgEQgShEAAg4QAAA4ASBEIAAAEQALAxgdAAIAAAAIAAAAQgIAAgKgEIgBAAIAAAAIAAAAIgBAAIgEgCQg5gVgfgvQgegwAAg3QAAg3AUgoQAWgoAdAAQAeAAAUAoQAVAoAAA3QAAg3gVgoQgUgogeAAQgdAAgWAoQgUAoAAA3QAAA3AeAwQAfAvA5AVIAEACIABAAIAAAAIAAAAIABAAQAKAEAIAAIAAAAIAAAAgAKOlCQAHAAAIgDIAAAAQApgPAWgpQAWgpAAg4QAAg5gWgpQgWgngeAAQgfAAgWAnQgVApAAA5QAAA4ALA4IABACQAJApAaABIABAAIAAAAgAFCPbgAjoPXIgBAAIAHAAIgGAAIAAAAgAF/PCIAAAAgAsMKGIAJgCQgBAKgCAAQgDAAgDgIgAhIJLIhWhGIEHAAIhrBNIgnAcgAgCJSIAAAAgAEMFCQgpgqAAg6QAAg8ApgpQAqgqA7AAQA7AAAqAqQAqApAAA8QAAA6gqAqQgqAqg7AAQg7AAgqgqgAD3DmQABAbASATQAUAUAcgBQAbABATgUQAHgHAFgIQAIgOAAgRQAAgSgIgPQgFgHgHgIQgTgTgbAAQgcAAgUATQgSAUgBAcIAAAAgAmGE3QgugvgBhDQABhCAugwQAwguBCgBQBDABAvAuQAwAwAABCQAABDgwAvQgvAwhDgBQhCABgwgwgAmeDhQAAAdAVAVQAUAUAdAAQAeAAAUgUQAVgVAAgdQAAgJgCgIQgFgSgOgPQgUgUgegBQgZAAgTAQIgFAFQgVAVAAAdIAAAAgAEKEUQgSgTgBgbQABgcASgUQAUgTAcAAQAbAAATATQAHAIAFAHQAIAPAAASQAAARgIAOQgFAIgHAHQgTAUgbgBQgcABgUgUgAmJETQgVgVAAgdQAAgdAVgVIAFgFQATgQAZAAQAeABAUAUQAOAPAFASQACAIAAAJQAAAdgVAVQgUAUgeAAQgdAAgUgUgAF8DmIAAAAgAkRDhIAAAAgAIADeIAAAAgAhyDFIAAAAgAIvkGQgaAAAEgvIAAgEQAcATAcAVQgUALgOAAIAAAAIAAAAgAJRkRIAAAAgAKNlCQgagBgJgpIgBgCQgLg4AAg4QAAg5AVgpQAWgnAfAAQAeAAAWAnQAWApAAA5QAAA4gWApQgWApgpAPIAAAAQgIADgHAAIAAAAIgBAAgALyneIAAAAg");
	this.shape_2.setTransform(344.5,450.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("Egb8ghSIhuAAAXbMKQAGhFAGhRQAGhUAih5QAhh5AqhYQAqhXA7ACQA7ACApBZQAqBbAAB9QAAB+gqBXQgmBQheBSQgqAagnAgQgDgDgDgDQgagYgbgVQgbgVgdgTgAHdOAQAAAFAAAFQABARgBAQQgFAEgFAFQgNAigeAFQASgRASgRQAEgDADgCAFVP4QiIhHg3huQg5hwAAidQAAicA3hvQA4hvBOAAQBOAAA3BvQA3BvAACcQAACVAHCtQAAABAAAAQAAAEAAADAHdN5QAAADAAAEAN1U0QAABDgwAvQgvAvhCAAQhDAAgvgvQgvgvAAhDQAAhCAvgwQAvgvBDAAQBCAAAvAvQAwAwAABCgEAUMAhTQAPgEAPgGQDDhEC2iwQEVkOhrlBQhrlBhug4Qg0AagGgvQgCgNABgPQg+AjAGhGQAAgCAAgCQjSiGkSAAQkZAAjWCOAFqLpQAAAcAFAfQADAWAFAYQACAJADAKQARBFg6gWQg6gWgegvQgfgvAAg3QAAg4AVgnQAVgoAdAAQAeAAAUAoQAVAnAAA4gADkbJIgBgBIAAAAQgBgBgFgBQgMAAgiAHQgfgogShDQgShEAphuQAohuABgSQABgbAth8QAkhiBFg/AGoPbQgXAXgUAXQgRgFgTgKQgCgBgCgBEAMqAhTQgQgEgRgGQjShEjgiyQhAgzgzgtAOfa6IhVhGIEIAAIhtBNIgnAcIgfgjIgJgBQiRBzgviJAa0J2QAAgQgWgNQgWgMgogGQgpgFgLAPQgMAQAAARQAAAQAWANQAWAMAeABQAfABAVgLQAWgMAAgQgAXoVMQAAA7gqAqQgqAqg7AAQg7AAgqgqQgpgqAAg7QAAg7ApgqQAqgpA7AAQA7AAAqApQAqAqAAA7gATgbdQirBxhQiN");
	this.shape_3.setTransform(361.9,174.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ai5PpIghgKQjShEjgiyQhAgzgzgtQABgNgBgdIgBgBIAAAAIgGgCQgMAAgiAHQgfgogShDQgShEAphuQAohuABgSQABgbAth8QAkhhBEg/QiHhHg3huQg5hwAAidQAAicA3hvQA4hvBOAAQBOAAA3BvQA3BvAACcQAACVAGCtIAAABIAAAAIABAHIAAAKIAAARIAAAQIgKAJIAKgJIAAgQIAAgRIAAgKIAAgHQAnghAqgbQDWiOEYAAQESAADSCGIAAAEQgGBGA+gjQgBAPACANQAGAvA0gaQBuA4BrFAQBrFBkVEOQi2CwjDBEIgeAKgAB2KlQA4AABHguIABAAIAEgCIACgCIgCACIgEACIgBAAQhHAug4AAIAAAAIAAAAQhIAAgshMIgBgCIBthNIkHAAIBVBGIAfAjIAmgcIABACQAsBMBIAAIAAAAIAAAAgAi9KDQAtAABAgyIABgBIACgBIAJABIgJgBIgCABIgBABQhAAygtAAIAAAAIAAAAQg0AAgahEIAAAAIAAgBIAAAAIgBgDIAAAAIgBgCIABACIAAAAIABADIAAAAIAAABIAAAAQAaBEA0AAIAAAAIAAAAgADnDiQAAA7ApAqQAqAqA7AAQA7AAAqgqQAqgqAAg7QAAg7gqgqQgqgpg7AAQg7AAgqApQgpAqAAA7IAAAAgAmwDKQAABDAvAvQAvAvBDAAQBCAAAvgvQAwgvAAhDQAAhCgwgwQgvgvhCAAQhDAAgvAvQgvAwAABCIAAAAgAqKhvQATAKARAFQAUgXAXgXQAdgFAOgiIgHAFIgkAiQgXAXgUAXQgRgFgTgKIgFgCIAFACgAp5jPQAdgBgKgvIgBgDIAAgCIgFgTQgFgYgDgWQgFgfAAgcQAAAcAFAfQADAWAFAYIAFATIAAACIABADQAKAvgdABIAAAAIAAAAQgJAAgNgFIAAAAIgBgBIAAAAQg6gWgegvQgfgvAAg3QAAg4AVgnQAVgoAdAAQAeAAAUAoQAVAnAAA4QAAg4gVgnQgUgogeAAQgdAAgVAoQgVAnAAA4QAAA3AfAvQAeAvA6AWIAAAAIABABIAAAAQANAFAJAAIAAAAIAAAAgAhEJQIhVhGIEHAAIhtBNIgmAcgAEQFHQgpgqAAg7QAAg7ApgqQAqgpA7AAQA7AAAqApQAqAqAAA7QAAA7gqAqQgqAqg7AAQg7AAgqgqgAD8DqQAAAcATATQATATAcAAQAbAAATgTQAHgHAFgIQAIgOAAgSQAAgRgIgPQgFgIgHgHQgTgTgbAAQgcAAgTATQgTAUAAAbIAAAAgAmBE8QgvgvAAhDQAAhCAvgwQAvgvBDAAQBCAAAvAvQAwAwAABCQAABDgwAvQgvAvhCAAQhDAAgvgvgAmaDmQAAAdAVAUQAVAVAdAAQAdAAAUgVQAVgUAAgdQAAgJgCgIQgEgTgPgOQgUgVgdAAQgaAAgTAQIgFAFQgVAVAAAdIAAAAgAEPEZQgTgTAAgcQAAgbATgUQATgTAcAAQAbAAATATQAHAHAFAIQAIAPAAARQAAASgIAOQgFAIgHAHQgTATgbAAQgcAAgTgTgAmFEXQgVgUAAgdQAAgdAVgVIAFgFQATgQAaAAQAdAAAUAVQAPAOAEATQACAIAAAJQAAAdgVAUQgUAVgdAAQgdAAgVgVgAGADqIAAAAgAkNDmIAAAAgAIEDiIAAAAgAhuDKIAAAAgAoHjwIAAgBIABABIgBAAIAAAAgAJkkKQgagYgbgVQgbgVgdgTIAMiWQAGhUAih5QAhh5AqhYQAqhXA7ACQA7ACApBZQAqBbAAB9QAAB+gqBXQgmBQheBSQgqAagnAgIgGgGgAKMnNQAYAAATgJIABAAIAAAAIACgBQAWgMAAgQQAAgQgWgNQgWgMgogGIgTgBIgBAAIAAAAQgWAAgJAKIgBABIAAAAQgMAQAAARQAAAQAWANQAWAMAeABIADAAIACAAIAAAAIABAAgAKLnNIgCAAIgDAAQgegBgWgMQgWgNAAgQQAAgRAMgQIAAAAIABgBQAJgKAWAAIAAAAIABAAIATABQAoAGAWAMQAWANAAAQQAAAQgWAMIgCABIAAAAIgBAAQgTAJgYAAIgBAAIAAAAgALQnzIAAAAg");
	this.shape_4.setTransform(461.5,287.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#0099FF").ss(1,1,1).p("AGNAAQAAARAAAPQAAAOgFARQgGARgpgHQgpgHgUgTQgTgTAAgcQAAgaATgUQAUgTAbAAQAcAAATATQAHAHAEAIQAIAPAAAQgAj/gDQAAAcgVAUQgVAVgdAAQgdAAgVgVQgUgUAAgcQAAgdAUgVQADgDADgCQATgQAZAAQAdAAAVAVQAOAOAFATQACAIAAAJg");
	this.shape_5.setTransform(342.7,308.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(1,1,1).p("EgS1ghIIhuAAAOyMrQAGhFAGhRQAFhUAih6QAih6AphZQAqhZA7AAQA7AAAqBZQAqBZAAB9QAAB+gqBYQgqBZhuBeQgkAfgZANQg0AagGgvQgCgNABgPQAbAUAaAXQADADADADQBtA4BsFBQBrFBkWEOQi1CwjDBEQgQAGgPAEASLKFQAAA5gWApQgWAogpAPQgoAPgMg3QgLg4AAg5QAAg4AVgpQAWgoAfAAQAeAAAWAoQAWApAAA4gAPqNSQg/AjAHhGQAAgCAAgCQAcASAcAVgAhxNvQDvjKFQAAQERAADTCGAOYVCQAAA7gqAqQgpAqg7AAQg7AAgqgqQgqgqAAg7QAAg7AqgqQAqgpA7AAQA7AAApApQAqAqAAA7gAElUqQAABDgvAvQgvAvhDAAQhCAAgwgvQgugvAAhDQAAhCAugwQAwgvBCAAQBDAAAvAvQAvAwAABCgAFQawIhWhGIEIAAIhsBNIgTDhQBAghA7gKIBHACAFQawIgKgBIgqC1IABAAQA1ANAxAnAIHa/IAAgEAIHa/IhxgIIgnAcIgfgjAHJdsIA1ABQAEgBAFAAQBGgNBFggQAAAAABAAIAOh2IgLgBIiPgJAEadjIACABIABAAIBmA0AEadjQABABABAAIAAAAAKhbJIgLgBAKhbJIAAAAAKTc/QBVgnBShFIiZgKAICdxICLADAIHdsIAAitAjSPNQgQgFgTgKQiLhHg5hwQg4hwgIiaQgHiZAUhhQAUhhB5gRQB4gRA3BvQA4BvAACcQAACdAHC3QAAARAAAQAjkKtQAAA3ARBFQARBFg6gWQg6gWgegvQgegvAAg3QAAg4AUgnQAVgoAeAAQAdAAAVAoQAVAnAAA4gAmfbDQgggogRhDQgShEAohuQAphuAAgSQABgbAuh8QAth9BjhFQAkgpAsgnQAIgHAJgHQgFB6hcgcAlra/IAAgBIAAAAQgCgBgEgBQgMAAgiAHEADbAhJQgRgEgQgGQjShEjfiyQhBgzgygtAl6baQADALADAGIABgEIAAAAQAAgmgsACACPczIABAAICKAwACPczQhRglhSg6ICsgTgAlra+QgDgCgFArIACgrACQczQBGAgBEAQACYbBICugS");
	this.shape_6.setTransform(303.6,173.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ai4PdIghgKQjThEjfiyQhBgzgygtQgCATgIgRIAKgCQABgNgCgdIAAgBIAAAAIgGgCQgMAAgiAHQgggogRhDQgShEAohuQAphuAAgSQABgbAuh8QAth8BjhFQgQgFgTgKQiLhHg5hwQg4hwgIiaQgHiZAUhhQAUhhB5gRQB4gRA3BvQA4BvAACcQAACdAHC3IAAAhQDwjKFPAAQERAADTCGIAMiWQAFhUAih6QAih6AphZQAqhZA7AAQA7AAAqBZQAqBZAAB9QAAB+gqBYQgqBZhuBeQgkAfgZANQBtA4BsFAQBrFBkWEOQi1CwjDBEIgfAKgAgQMsQA/ghA7gKIBHACIhHgCIAJgCQBGgMBFggIABAAIgBAAQhFAghGAMIAAisIAACsIgJACIg1gBIA1ABQg7AKg/AhIASjhIgmAcIgfgjIAfAjIAmgcIgSDhgAgQMsQgxgog1gMIgBAAIAqi1IiuASICugSIgqC1IABAAIgBAAIAAAAIgCgBIiKgwIgBAAIAJhyIitATQBTA6BRAlQhRglhTg6ICtgTIgJByIABAAQBGAgBEAQIACABIABAAIBmA0IAAAAgAD5MIIiLgDgAD/LTQBVgnBShFIiZgKICZAKQhSBFhVAngAD/LTIAOh2IAAAAIAAAAIgLgBIALABIgLgBIALABgAECJcIiPgJgAACJLIBxAIIAAgEIAAAEIhxgIIBshNIkHAAIBWBGIgKgBIAKABIhWhGIEHAAIhsBNgADnDWQAAA7AqAqQAqAqA7AAQA7AAApgqQAqgqAAg7QAAg7gqgqQgpgpg7AAQg7AAgqApQgqAqAAA7IAAAAgAmwC+QAABDAvAvQAwAvBCAAQBDAAAvgvQAvgvAAhDQAAhCgvgwQgvgvhDAAQhCAAgwAvQgvAwAABCIAAAAgApHiZQA7AAAGhcIABgEIAAgDIgRAOQgsAngkApIABAAIABABIAAAAIABAAIABAAQAOAEANAAIAAAAIAAAAgAJyjfQALAAARgIIAAAAIABAAIABgBIAAAAIAAAAIABAAIgGgGQgagXgbgUQAbAUAaAXIAGAGIgBAAIAAAAIAAAAIgBABIgBAAIAAAAQgRAIgLAAIgBAAIAAAAQgVAAgFgcIAAgCIgCgSIABgKQgcgVgcgSIAAAEIgBADQgCArAZABIAAAAIABAAQAMgBASgJIACgBIABgBIgBAKIACASIAAACQAFAcAVAAIAAAAIABAAgAp4kOQAdAAgLgxIgBgDQgRhFAAg3QAAA3ARBFIABADQALAxgdAAIAAAAIAAAAQgIAAgLgDIAAAAIAAAAIAAAAIgBgBIgEgBQg6gWgegvQgegvAAg3QAAg4AUgnQAVgoAeAAQAdAAAVAoQAVAnAAA4QAAg4gVgnQgVgogdAAQgeAAgVAoQgUAnAAA4QAAA3AeAvQAeAvA6AWIAEABIABABIAAAAIAAAAIAAAAQALADAIAAIAAAAIAAAAgAKSlKQAHAAAIgDIABAAQApgPAWgoQAWgpAAg5QAAg4gWgpQgWgogeAAQgfAAgWAoQgVApAAA4QAAA5ALA4IABACQAJApAaAAIAAAAIAAAAgAh2L4QA1AMAxAogAgQMsgABqMBgABqMBgABzL/gAh5L3IACABIAAAAgAh3L4gAh3L4gAkDLHICKAwQhEgQhGgggAkELHgAERE7QgqgqAAg7QAAg7AqgqQAqgpA7AAQA7AAApApQAqAqAAA7QAAA7gqAqQgpAqg7AAQg7AAgqgqgAFhEpQAWAAAEgMIAAAAQAFgRAAgOIAAgPIAAgRIAAARIAAAPQAAAOgFARIAAAAQgEAMgWAAIAAAAIAAAAQgJAAgLgCIgBAAQgpgHgUgTQgTgTAAgcQAAgbATgUQAUgTAbAAQAcAAATATQAHAHAEAIQAIAPAAARQAAgRgIgPQgEgIgHgHQgTgTgcAAQgbAAgUATQgTAUAAAbQAAAcATATQAUATApAHIABAAQALACAJAAIAAAAIAAAAgAmBEwQgvgvAAhDQAAhCAvgwQAwgvBCAAQBDAAAvAvQAvAwAABCQAABDgvAvQgvAvhDAAQhCAAgwgvgAmZDaQAAAdAUAUQAVAVAdAAQAdAAAVgVQAVgUAAgdQAAgJgCgIQgFgTgOgOQgVgVgdAAQgZAAgTAQIgGAFQgUAVAAAdIAAAAgAmFELQgUgUAAgdQAAgdAUgVIAGgFQATgQAZAAQAdAAAVAVQAOAOAFATQACAIAAAJQAAAdgVAUQgVAVgdAAQgdAAgVgVgAkMDaIAAAAgAIEDWIAAAAgAhuC+IAAAAgApHiZQgNAAgOgEIgBAAIgBAAIAAAAIgBgBIgBAAQAkgpAsgnIARgOIAAADIgBAEQgGBcg7AAIAAAAIAAAAgAI0kNQgZgBACgrIABgDIAAgEQAcASAcAVIgBABIgCABQgSAJgMABIgBAAIAAAAgAJWkZIAAAAgAKSlKQgaAAgJgpIgBgCQgLg4AAg5QAAg4AVgpQAWgoAfAAQAeAAAWAoQAWApAAA4QAAA5gWApQgWAogpAPIgBAAQgIADgHAAIAAAAIAAAAgAL3nmIAAAAg");
	this.shape_7.setTransform(344,286.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape,p:{x:342.7,y:473.1}}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape,p:{x:460.2,y:310.1}}]},1).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},1).to({state:[]},14).wait(14));

	// lid
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("A6YQ2QC/oSGKqFQL5zoKdFhQKdFhGUOEQC8GkBlGS");
	this.shape_8.setTransform(469.6,284.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0066FF").s().p("AxPhhQL5zoKdFhQKdFhGUOEQC8GkBlGSMg0xAADQC/oSGKqFg");
	this.shape_9.setTransform(469.6,284.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(1,1,1).p("A5PEkQFWnAI9n1QRUvNIUIWQITIXBvPRQA0HJgbGd");
	this.shape_10.setTransform(473.6,263.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0066FF").s().p("A5PEkQFWnAI9n1QRUvNIUIWQITIXBvPRQA0HJgbGdg");
	this.shape_11.setTransform(473.6,263.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(1,1,1).p("A4cjKQGkl5KQmCQT2rtGnJwQGmJwhKPWQgiHKhnGQ");
	this.shape_12.setTransform(492.7,254.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0066FF").s().p("A4cjKQGkl5KQmCQT2rtGnJwQGmJwhKPWQgiHKhnGQg");
	this.shape_13.setTransform(492.7,254.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(1,1,1).p("A3gtPQH2kALdjLQWNmKD3LIQD3LIlGOhQiXGyjLFo");
	this.shape_14.setTransform(536.7,247.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0066FF").s().p("A3gtPQH2kALdjLQWNmKD3LIQD3LIlGOhQiXGyjLFog");
	this.shape_15.setTransform(536.7,247.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0066FF").s().p("Avt6VQIMDSJ7GiQTSMpl1KNQl1KPuRFxQmpCrmUBWg");
	this.shape_16.setTransform(746.3,223.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8}]}).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16}]},1).to({state:[]},12).wait(14));

	// Layer_1
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF0033").s().p("AjoKbIAA0XIDUAAIAADVQAeiLAhg0QAhg0AvAAQAzAAA7BEIhGFlQgoglgXAAQguAAgYBRQgiBzAAE3IAAG2g");
	this.shape_17.setTransform(873.6,302.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0033").s().p("Ai6JhQhDhJgsifQgtigAAjXQAAkxBZi9QBZi9CdAAQB+AABJBVQBKBVAnChQAmCgAAEBIAAA5InGAAQAGB4AXA7QAhBVA0AAQAiAAAeglQASgXAWg7IDfAtQgzDFhJBWQhIBViHAAQh1AAhEhJgAhUkiQgVA7gGB0IDfAAQgHiRgcg+Qgdg/gvAAQg1AAggBfg");
	this.shape_18.setTransform(805.3,303.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FF0033").s().p("Ag7NjQgogwgThhQgThiAAjZIAAnLIhVAAIAAluIBVAAIAAjwIDikAIAAHwIB9AAIAAFuIh9AAIAAHNQAABUAIAbQAKApAcAAQAZAAAuggIARFaQhVAohJAAQhUAAgogwg");
	this.shape_19.setTransform(741.6,280.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF0033").s().p("AjhJEQhFhmgUi8IDhgvQAOBZAZAmQAaAmApAAQAtAAAZgrQAUggAAgwQgBg2gZgeQgSgVhPgeQh2gugtgmQgvgngfhaQgghcAAh2QAAiBAihdQAiheA8gvQA8gtBkAAQBpAAAyAkQAzAjAiBLQAhBLAXCAIjXAvQgJg/gTgeQgbgnglAAQgnAAgRAeQgSAeAAArQAAAwAXAZQAVAYBLAUQBxAcA3AzQA3AyAeBcQAdBdAABvQAABxgfBrQgfBrhCBAQhDA/h0AAQihAAhEhmg");
	this.shape_20.setTransform(680.8,303.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FF0033").s().p("AkdI+Qg3hsAAifQAAiVAohfQAnhfBrgvQB/g4AlgXQAmgXArglQAAhcgSglQgRglgrAAQg3AAgcAoQgWAegNBVIjZgyQAMh+AYhHQAWhIAsg1QAfgmA3gVQA2gVBAAAQBlAAA+AaQA+AYApBQQAdA4ARBmQARBkAABcIAAJAQAABcAFA1QAFAzASBRIjVAAQgNgygEgaQgEgbgDg4QgtBegsApQg7A2hQAAQhqAAg3hsgAgGBiQhFApgSAnQgTApAAAzQAAA7ATAmQASAlAkAAQAmAAAggoQAggpAOg6QAOg7AAhdIAAhQQgvAlgyAcg");
	this.shape_21.setTransform(608.4,303.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF0033").s().p("Ai6JhQhDhJgsifQgtigAAjXQAAkxBZi9QBZi9CdAAQB+AABJBVQBKBVAnChQAmCgAAEBIAAA5InGAAQAGB4AXA7QAhBVA0AAQAiAAAeglQASgXAWg7IDfAtQgzDFhJBWQhIBViHAAQh1AAhEhJgAhUkiQgVA7gGB0IDfAAQgHiRgcg+Qgdg/gvAAQg1AAggBfg");
	this.shape_22.setTransform(532.4,303.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF0033").s().p("AkqN4IgTldQAyAiA8AAQAoAAAZgpQAZgoARhpIj50XIDvAAIB7NlIBwtlIDgAAIjrVxQgoDugpBUQg6B2h5AAQgyAAhmgdg");
	this.shape_23.setTransform(421.5,330);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF0033").s().p("AlFOTIAA8IIDVAAIAADBQAsh6AkgrQAxg5A8AAQB3AABBDIQBBDIAAEnQAAFEhHCsQhHCrhsAAQg0AAgqgnQgsgngihOIAAJvgAhEnYQgdBLAACoQAACbAdBKQAeBLAsAAQAoAAAahIQAbhHAAisQAAiegchKQgchLgoAAQgqAAgdBLg");
	this.shape_24.setTransform(351.4,326.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF0033").s().p("AlFOTIAA8IIDVAAIAADBQAsh6AkgrQAxg5A8AAQB3AABBDIQBBDIAAEnQAAFEhHCsQhHCrhsAAQg0AAgqgnQgsgngihOIAAJvgAhEnYQgdBLAACoQAACbAdBKQAeBLAsAAQAoAAAahIQAbhHAAisQAAiegchKQgchLgoAAQgqAAgdBLg");
	this.shape_25.setTransform(275.3,326.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FF0033").s().p("AkdI+Qg3hsAAifQAAiVAohfQAnhfBrgvQB/g4AlgXQAmgXArglQAAhcgSglQgRglgrAAQg3AAgcAoQgWAegNBVIjZgyQAMh+AYhHQAWhIAsg1QAfgmA3gVQA2gVBAAAQBlAAA+AaQA+AYApBQQAdA4ARBmQARBkAABcIAAJAQAABcAFA1QAFAzASBRIjVAAQgNgygEgaQgEgbgDg4QgtBegsApQg7A2hQAAQhqAAg3hsgAgGBiQhFApgSAnQgTApAAAzQAAA7ATAmQASAlAkAAQAmAAAggoQAggpAOg6QAOg7AAhdIAAhQQgvAlgyAcg");
	this.shape_26.setTransform(196.6,303.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FF0033").s().p("ABVOEIAArNQAAh7gUgyQgVgzglAAQgpAAgZBEQgaBFAACyIAAJyIjjAAIAA8IIDjAAIAAKYQAuhqAtguQAugsA+gBQBdABA1B8QA1B8AAD/IAAM9g");
	this.shape_27.setTransform(120.4,278.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17}]},6).wait(24));

	// egg
	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#000000").ss(1,1,1).p("Aa62OQByHKAAGvQAAMqoaI9QoaI9r4AAQr4AAoZo9Qg1g5gxg7QgWgdgWgdQgDgDgDgEQgEgGgFgHQl5oAAAqlQAAmIC0nx");
	this.shape_28.setTransform(466,534.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0066FF").s().p("A0RNSQg1g5gxg7Igsg6IgFgHIgKgNQl4oAAAqlQAAmICznxMA0wAAAQByHKABGvQAAMqoaI9QoaI9r4AAQr3AAoao9g");
	this.shape_29.setTransform(466,534.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28}]}).to({state:[]},16).wait(14));

	// Label
	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AipDcIAAmtICbAAIAABGQAVgtAYgRQAYgSAiAAQAlAAArAWIgzB2QgdgMgRAAQghAAgRAbQgZAmAABmIAACQg");
	this.shape_30.setTransform(774.6,182);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AiHDJQgxgYggg1Qggg0AAhHQAAhkBBg+QBAg/ByAAQBbAAA2AcQA1AcAcA1QAcA1AABUIAAATIlJAAQAEAoARATQAYAcAmAAQAYAAAWgMQANgIAQgTICiAPQglBBg1AcQg1AchhAAQhWAAgxgYgAg9hfQgPATgEAnICiAAQgFgwgVgVQgVgUgiAAQgmAAgYAfg");
	this.shape_31.setTransform(725,182.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgqEeQgdgQgPggQgOggAAhIIAAiWIg8AAIAAh5IA8AAIAAhPIClhVIAACkIBbAAIAAB5IhbAAIAACXQAAAcAFAIQAIAOAVAAQASAAAggKIANByQg+ANg0AAQg9AAgdgQg");
	this.shape_32.setTransform(678.7,174.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AijC/QgyghgPg+ICkgQQAKAdATANQASANAdAAQAhAAATgPQAOgKAAgQQAAgSgTgJQgNgHg5gLQhWgPghgMQgigNgWgdQgXgeAAgnQAAgrAYgfQAZgeArgQQAsgPBJAAQBMAAAlAMQAkAMAZAYQAYAZAQAqIicAQQgGgVgOgKQgUgNgaAAQgcAAgNAKQgNAKAAAOQAAAQAQAIQARAIA1AHQBSAJAoARQAoAQAWAeQAVAfAAAkQAAAmgWAjQgXAjgwAVQgxAVhTAAQh1AAgygig");
	this.shape_33.setTransform(634.5,182.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AjPC9QgogjAAg1QAAgxAdgfQAdgfBNgPQBdgTAbgHQAbgIAfgMQAAgegNgNQgMgMggAAQgnAAgVANQgPAKgKAcIiegQQAJgqARgXQARgYAfgSQAXgMAogHQAogHAuAAQBJAAAtAJQAtAIAeAaQAVASAMAiQAMAhAAAfIAAC9QAAAeAEARQAEASANAaIibAAQgJgQgDgJQgDgJgDgSQggAfggANQgrASg6AAQhNAAgogkgAgEAgQgyAOgOANQgNANAAARQAAAUANAMQAOAMAaAAQAcAAAXgNQAXgNAKgTQAKgUAAgfIAAgaQgiAMgkAJg");
	this.shape_34.setTransform(582,182.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AiHDJQgxgYggg1Qggg0AAhHQAAhkBBg+QBAg/ByAAQBbAAA2AcQA1AcAcA1QAcA1AABUIAAATIlJAAQAEAoARATQAYAcAmAAQAYAAAWgMQANgIAQgTICiAPQglBBg1AcQg1AchhAAQhWAAgxgYgAg9hfQgPATgEAnICiAAQgFgwgVgVQgVgUgiAAQgmAAgYAfg");
	this.shape_35.setTransform(526.7,182.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AjYElIgNhzQAjALAsAAQAdAAASgNQASgNANgjIi1mtICuAAIBYEeIBSkeICjAAIirHLQgdBOgeAcQgqAmhYAAQgkAAhKgJg");
	this.shape_36.setTransform(446.1,191.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AjsEuIAApRICbAAIAAA/QAfgoAbgOQAkgTArAAQBXAAAvBCQAvBCAABiQAABqg0A5QgzA4hOAAQgnAAgegNQgggNgYgZIAADNgAgyibQgUAZAAA3QgBAzAWAYQAVAZAgAAQAdAAAUgYQATgXAAg4QAAg1gVgYQgTgZgeAAQgeAAgWAZg");
	this.shape_37.setTransform(395.3,190.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AjsEuIAApRICbAAIAAA/QAfgoAbgOQAkgTArAAQBXAAAvBCQAvBCAABiQAABqg0A5QgzA4hOAAQgnAAgegNQgggNgYgZIAADNgAgyibQgUAZAAA3QgBAzAWAYQAVAZAgAAQAdAAAUgYQATgXAAg4QAAg1gVgYQgTgZgeAAQgeAAgWAZg");
	this.shape_38.setTransform(340,190.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AjPC9QgogjAAg1QAAgxAdgfQAdgfBNgPQBdgTAbgHQAbgIAfgMQAAgegNgNQgMgMggAAQgnAAgVANQgPAKgKAcIiegQQAJgqARgXQARgYAfgSQAXgMAogHQAogHAuAAQBJAAAtAJQAtAIAeAaQAVASAMAiQAMAhAAAfIAAC9QAAAeAEARQAEASANAaIibAAQgJgQgDgJQgDgJgDgSQggAfggANQgrASg6AAQhNAAgogkgAgEAgQgyAOgOANQgNANAAARQAAAUANAMQAOAMAaAAQAcAAAXgNQAXgNAKgTQAKgUAAgfIAAgaQgiAMgkAJg");
	this.shape_39.setTransform(282.8,182.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AA+EpIAAjtQAAgogPgRQgPgQgcAAQgcAAgTAWQgSAWAAA8IAADOIimAAIAApRICmAAIAADbQAhgjAggPQAhgPAuAAQBDAAAnApQAmApAABTIAAESg");
	this.shape_40.setTransform(227.5,174.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#000000").ss(1,1,1).p("EAplgB1QAghBA4gzQAvgsA/ghQBKgnBggaQH+EZhyIFQBthkDhAxQAHABAIACQADgPAEgPQAYhbAwggQAxghBLAgQABAAACABQCPA+BRCCQABABABABQAMAUALAUQAuBSAKA+QACAQABAPQACBXhIBRQgsAxg6AQIgGAAIgZAAIhoAAQhUgShAg4QgCgBgCgCQhOhHgKhcQgCgYABgfQAEhNAeh1AfVWYQokzqMKlZQFAiPBqDFQBHCDgFC4EAoyABnQASAQAQASQADAEADADQAXAcAUAgQAHAKAGALQAKgPALgMQAJgLAGgFQAFgGAYgVQAXgUAjAVQAjAVAGACQACABACABQAcAMAZAPQA+AjAwAzQAiAjAbArQANAWAMAUQAtBSALA/QACAQAAAOQACBXhIBSQgPAQgQANQgUAQgXAKQgXAKgZAEIhYAAQgWgDgUgFQgqgLglgVQgQgJgPgLQgMgJgLgJQgCgCgBgBQgcgagTgbQgEgFgCgFQgOgWgJgYQg3AehJgGQgGAAgGgBQhsgMhNhEQgCgBgCgCQhOhHgKhcQgCgYABgfQACgpAKgzQAKg6AThIQAAgBAAgBQAYhbAwggQAEgCAEgDQAsgXA/AXQAEACAFACQABAAACABQAUAJASAKQA5AeAuAqQAXEnARj+QAGheAFinEApmAFiIAAAAQAAABAAABQAlh3AHgMEAi1AFnIGwAAIgDAQQAEgTAAAAEApmAFiQACgHACgIQAEgRAFgSQAFgUAGgRQADgIgbBfgEAipAD6QADAJACAIQADAKABAKQACAQABAPQABAkgNAkEAipAEjIAJgEEApKAIPQACglAIguIAOhFEApXAJ9QgJgagDgcQgDgZACgfIHphxEAp1ALNQAAAAAAABIAALKIqgAAEAp1ALNQgEgRgDgREAp0AK1QAAALABANEAkOAJBIFGiFAftKsQgigsAKMYEBBuAGgQAxgpBKgLQKPDSlWMpQgGAPgHAQI0EAAQgbo6AHiSQAIi/BchUQgdCEhHCPQAWBZACEHQgCgPgCF7IqcASEA71AMTIHIi7EA6cAI5IHphxEA0TAVEQAKjaACgaQgFgcgFgaQABCAgDCqIgCBCEBAOANgQgKCVg9C/QAMjBAiiTEAqjALqIHIi7Eg9LgUMQAphEA1gkQAVgOAXgIQAGgDAHgCQACgBABAAQAkgLAgAJQAFACAGACQAEABAFADQAqAVAiA8QAYAsAVAtQANAfAMAfQAUAxAOAzQAkB6hFBDQgFAEgFAEQglAegrASQg1AWg/AEQhLAFg4gfQgggSgagcQgQgRgMgRQguhBAAhFQAAgVAEgYQAMhIAxheQAHgOAIgMIC7C9IjdC2EgvsgKeQAMAWAKAVEg0+gOWQAlgHAwAUQACABACABQCPA+BRCBQANAWAMAUEg2ZgNGQAJgUAMgQQAOgUARgLQAOgJAPgEQAFgCAFAAEg2sgNjQAIALAHAMQACADACADEg2sgMOQABgGACgFEg2sgGLIABj/IACiPQAHgZAJgUEg6xgEPQAUgqAegUQAxghBLAfQABABACABQCPA+BRCBQAOAWALAUQAuBSAKA+QACAQABAOQACBXhIBSQhJBRhzgJQhzgJhShIQgCgCgCgBQhOhIgKhbQgCgZABgfQAFhVAkiJQAEgOAEgMQAAgBAOiWQgogLgBAVIApgKQgbBRgJgDQg7BthAgFQhzgJhShIQgCgBgCgCQhOhHgKhcQgCgYABgfQAFhXAkiJQAYhbAwggQAxghBLAgQABAAACABQCCA5BPBwEg18gFUQgdgagTgdIHAkTEg0+gEoQgfgRgcgYQgCgCgBgBIGmirEgxJAAAQAEhWAliJQAYhbAvggQAyghBKAfQACABACABQBDAcA1AsQANALANANQAsAqAiA1QANAWAMAUQAgA7APAwEgvWgFzQgOAXgUAWQgfAjgoATQgGACgFACQgvATg6gFQhNgGg+giEgw/gDMQgHgWgDgYQgBgIAAgKEhGaAAAQAEhVAliJQAYhbAvggQAyghBKAfQACABACABQCPA+BRCBQANAWAMAUQAtBSALA+QACAQAAAOQACBXhIBSQhIBRhzgJQh0gJhShIQgCgCgBgBQhPhIgJhbQgDgZACgfIHphwEg6xgDVQgIgMgGgLEg7VgE1QgDgCgBgLQgDgYArgpQgSAsgSAigEhAZgEhIFohiEhBygH7IHBAAEg/QAJJQAFhXAkiJQAYhbAwggQAxghBLAgQABAAACABQCPA+BRCCQAOAVALAVQAuBSAKA+QACAQABAPQACBXhIBRQhJBShzgKQhzgJhShIQgCgBgCgCQhOhHgKhcQgCgYABgfIHphxEhKWAIQQAFhXAkiJQAYhbAwggQAxghBLAgQABAAACABQCPA+BRCCQAOAVALAVQAuBSAKA+QACAQABAPQACBXhIBRQhJBShzgKQhzgJhShIQgCgBgCgCQhOhHgKhcQgCgYABgfIHphxEhFBADbIHIi7EhI9ALqIHIi7EgpCACrQAtgSA+AaQABAAACABQBtAvBIBWQAYAbATAgQAOAVALAVEgq5AG3QAFghAJglQACgKADgKQAFgWAGgYQAGgXAIgTQhAAwhagHQh0gJhShIQgCgCgBgBQhPhIgJhbQgDgZACgeIHphxEgpCACrQgQAegaAdQgPARgSAOEgoxACGQgHATgKASEgx5ADRIAxAJIAMAEQADABADABQABABACABQCPA+BRCBQAOAWALAUQAuBSAKA/QACAQABAOQACBXhIBSQhJBRhzgJQhzgJhShIQgCgCgCgBQhOhIgKhbQgCgZABgfIHjhvIAGgCEginAKFQgPA5gwA3QgaAdgfASQg4AfhLgGQhzgJhShIQgCgBgCgCQg6g1gUhAEgprALpIHEi5Egq5AIMIHehuQAnBFANA4EgvwADaIG/i3EgzKAMXIHIi7Eg93AMjIHIi7Eg6QgRPIDKDOEg3ggTgIiwCREg7wAAMIHphwEg6XADnIHIi7AF1h+QACAQAAAOQABAcgHAcAFxiSQACAKACAKAFxh8IAEgC");
	this.shape_41.setTransform(533.6,602);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#CC0000").s().p("AgFFVQgWgDgUgFQgqgLglgVQgQgJgPgLIgXgTIgDgDIHHi7InHC7QgcgZgTgcIgGgJQgOgXgJgXQgJgbgDgcQgDgYACgfIHohwInoBwQACglAIgtIAOhGIAEgTQAlh2AHgMQAKgQALgLIAOgRIAdgaQAYgUAjAVQAjAUAGADIAEABQAcAMAYAPQA+AkAwAyQAiAkAbArIAZAqQAtBRALA+IACAfQACBXhIBRQgPARgQANQgUAPgXAKQgXAKgZAFgAjwiSIAJgkQAEgTAHgRIgYBXIAEgPg");
	this.shape_42.setTransform(824.3,650.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#0033CC").s().p("AA0FNIgMgBQhrgMhOhEIgDgDIFEiFQgIAtgCAmQgBAeACAZQADAcAKAaQguAZg7AAIgXAAgAjsBVQgDgYACgfIGuAAIgDAQIgOBGIlECFQhPhIgJhcgADBAeImuAAQACgnAJg0QAKg5AThIIABgDQAYhaAvggIAJgGQAsgYA/AYIAIAEIADACQATAIATAKQA5AeAtAqIABAEIAAADIABAOIAAABIAAADQALCDAKADIAAAAIABAAQAJgDAHhqIAAAAIAAgEIAAgFQAYAcAUAgIANAVQgIAMglB2IABgBIAAgBIAAABIgBABIgEATgADbg9QgHARgFAUIgJAiIgDAPIAYhWIAAAAgADCAbIAAAAgAClhCQgKgDgLiDIAAgDIAAgBIgBgOIAAgDIgBgEQASARAQASIAGAGIAAAFIAAAEIAAAAQgHBqgJADIgBAAIAAAAg");
	this.shape_43.setTransform(780.4,634.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#CC3300").s().p("AAzCEIgZAAIhmAAQhVgShAg4IgDgDIHHi6IACAeQACBXhIBRQgrAxg7AQg");
	this.shape_44.setTransform(939.5,675.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#00FF00").s().p("Aq4IRIAChCIAMj0IgKg2QgCkGgWhZQBHiPAdiEQBthkDhAxIAPADQgeB1gEBNQgBAfACAYQAKBcBOBHIAEADQBAA4BUASIBnAAQgiCSgLDBQA8i/AKiUIAGAAQA6gQAsgxQBIhRgChXIgDgfQgKg+guhSIgXgoQAxgpBKgLQKPDSlWMoIgNAfg");
	this.shape_45.setTransform(937.8,690.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#00FF33").s().p("Al3C+IAAgBIgCgYQATAbAcAaIAEADIAWASQAQALAQAJQAkAVAqALQAVAFAVADIBZAAQAZgEAXgKQAVgKAUgQQARgNAPgQQBIhSgChXIgDgeQgKg+guhSIgZgqQgbgrgggjQgwgzg+gjQgagPgcgMIgDgCQgGgCgjgVQgkgVgXAUIgdAbIgPAQQAGi4hHiEQAghBA3gzQAvgsA/ghQBKgnBggaQH9EZhyIGQhcBUgIC+QgGCSAaI6IqaASg");
	this.shape_46.setTransform(839,654.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FF3366").s().p("AkOCAQgDgZACgfIHohwQAtBRALA/InHC7QhPhIgJhbgAjuh4IAIgeQAYhbAvggQAyghBKAfIAEACQCOA+BRCBIABACIAYAoInoBwQAEhMAdh0g");
	this.shape_47.setTransform(934.9,651.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FF0000").s().p("Ah9EZQgfgSgbgcQgPgRgMgRIDbi2IDLDOIgKAIQglAegrASQg1AWhAAEIgTABQg+AAgxgbgAAJATICwiQIiwCQIi6i8IC6C8IjbC2QguhBAAhFQAAgVAEgYQAMhHAxheIAOgaQAphEA2gkQAUgOAYgIIAMgFIAEgBQAjgLAgAJIAKAEIAJAEQArAVAhA8QAYAsAVAtQAOAfAMAfQATAxAPAyQAjB6hEBDgAAJATg");
	this.shape_48.setTransform(159.8,489.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#3333CC").s().p("AAOFMQhMgGg+giIAAgCQgfgRgcgYIgDgDIGlirIAACNQgOAWgTAWQggAkgoASIgKAFQgmAPgsAAIgYgCgAjqDAIG/kSQAMAWAKAVIAAByImlCrQgdgagTgcgAjpg/IACiOQAHgZAKgUQAIgVAMgPQAOgUARgMQAOgJAPgEIAKgCIAAACQAmgHAvAVIAEABQCOA+BRCCIAZAqIm/ESgADrBLg");
	this.shape_49.setTransform(207,543.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#996666").s().p("ABCFNQhygJhShIIgEgDIFnhiQgrApADAYQABALADABQg5Bpg8AAIgGAAgAjeBWQgCgZABgfQAFhVAkiJQAYhbAwggQAxghBKAfIADACQCCA4BPBwIAACxInAAAIHAAAIAAB5QgogLgBAUIApgJIlnBiQhOhIgKhbgADhCXgADhAeg");
	this.shape_50.setTransform(134.9,548.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#0066CC").s().p("AAWFMQhygJhShIIgEgDIG+i3IAABjQgGATgKATQgRAdgZAdQgQASgRANQg4AqhLAAIgYgBgAiyD4QhOhHgKhcQgCgYABgfIHohwQAhA6AOAwIAAApIm+C3IAAAAgAjijBQAYhbAwggQAxghBLAgIADABQBCAdA1AsIAbAXQAsAqAhA2IAZAqInoBwQAFhWAkiJg");
	this.shape_51.setTransform(245.8,599);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#33CC99").s().p("AARFfQhzgJhShIIgDgDIHHi7InHC7QhPhIgJhbQgDgZACgfQAEhVAliJQADgOAFgMIANAXIgNgXIANiXIAAB0QAVgqAdgUQAyghBKAfIAEACQCOA+BRCBIAZAqQAtBRALA/IACAeQACBXhIBSQhBBJhjAAIgXgBgAkQAwIHohwgAj2kRQASgiASgsQgZBOgKAAIgBAAgAj6keQgCgYAqgpQgSAsgSAiQgDgBgBgMgAjSlfgAjSlfIAAAAg");
	this.shape_52.setTransform(178.5,598.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#9999CC").s().p("AARFMQhzgJhShIIgDgDQhPhHgJhcQgDgYACgfIHohwQAtBSALA9InHC7IHHi7IACAfQACBXhIBRQhBBJhjAAIgXgBgAjnjBQAYhbAvggQAyghBKAgIAEABQCOA+BRCCIAZAqInoBwQAEhWAliJg");
	this.shape_53.setTransform(110.2,599.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#6699FF").s().p("A0AHoQh0gJhShIIgDgDIHEi5IAABUQgPA6gxA3QgZAdgfARQgwAag8AAIgXAAgA3JGUQg6g1gVhAIAAhoIHfhvQAmBGAOA3IAAAWInEC5IAAAAgA4YBhQAGghAIglIAFgUIAMgsQAGgXAIgUQARgNAQgSQAZgdARgdQAsgTA+AaIAEACQBsAvBJBVQAXAcAUAeIAZAqInfBvgAYSnSIAEgCIADAfQAAAcgHAcgAYSnnIAEATIgEACg");
	this.shape_54.setTransform(415.1,636.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FF0066").s().p("AARFMQhzgJhShIIgDgDIHHi7InHC7QhPhHgJhcQgDgYACgfIHohwQAtBSALA9IACAfQACBXhIBRQhBBJhjAAIgXgBgAjnjBQAYhbAvggQAyghBKAgIAEABQCOA+BRCCIAZAqInoBwQAEhWAliJgADYhSIAAAAg");
	this.shape_55.setTransform(156.1,657.5);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#CCFF99").s().p("AARFNQhzgKhShHIgDgDIHHi7InHC7QhPhIgJhbQgDgZACgfIgBAAQAFhVAkiJQAYhbAwggQAGgFAHgDIAsgJIAxAJIAMAEIAGACIADACQCOA+BRCBIAZAqIgFACIniBuIHihuIAGgCQAtBSALA+IACAeQACBXhIBSQhBBIhjAAIgXAAg");
	this.shape_56.setTransform(224.6,656.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#CC9900").s().p("AARFMQhzgJhShIIgDgDIHHi7IACAfQACBXhIBRQhBBJhjAAIgXgBgAkPBVQgDgYACgfQAEhWAliJQAYhbAvggQAyghBKAgIAEABQCOA+BRCCIAZAqQAtBSALA9InHC7QhPhHgJhcgAkQAeIHohwgAEQA9IAAAAg");
	this.shape_57.setTransform(85.1,651.8);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#00CC00").s().p("EAiSAR+QgJrrAdgDIABAAIAAAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABABAAIAAAAIAAAAQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAAAAAAAIAAAAIgBAAQgdADAJLrQokzpMKlaQFAiPBqDFQBHCEgFC4QgLAMgKAPIgMgVQgUgggYgcQAGheAFioQgFCogGBeIgGgHQgQgSgSgQQgugqg5geQgSgKgTgJIgEgBIgJgEQg+gYgsAYIgJAFQgwAggXBbIgBACQgTBIgKA6QgKAygCApQgBAfACAYQAKBcBPBHIADADQBOBEBrAMIAMABQBJAGA4geQAIAYAOAWIAIAiIAAABIAALKgEAlnABsQALghAAgiIAAgFIgCgfIgFgTIgEgRIAEARIAFATIACAfIAAAFQAAAigLAhgEAlnAAJIAJgEgEA4eACNQgdCEhHCPQAIi/BchUgEguLgIUIgBgSIAKgEIAABEQgHgWgCgYgEg30gKdIgpAKQABgVAoALgEgzvgQoIADgLIgCCPgEgzvgQoIAAhVIAPAXIAFAGQgKAUgHAZIgDALgEgzsgQzg");
	this.shape_58.setTransform(514.7,630.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FF0033").s().p("AijC/QgyghgPg+ICkgQQAKAdATANQASANAdAAQAhAAATgPQAOgKAAgQQAAgSgTgJQgNgHg5gLQhWgPghgMQgigNgWgdQgXgeAAgnQAAgrAYgfQAZgeArgQQAsgPBJAAQBMAAAlAMQAkAMAZAYQAYAZAQAqIicAQQgGgVgOgKQgUgNgaAAQgcAAgNAKQgNAKAAAOQAAAQAQAIQARAIA1AHQBSAJAoARQAoAQAWAeQAVAfAAAkQAAAmgWAjQgXAjgwAVQgxAVhTAAQh1AAgygig");
	this.shape_59.setTransform(632.6,700.6);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#9966FF").s().p("AioDcIAAmuICaAAIAABHQAVgtAYgRQAYgSAiAAQAlAAArAWIgzB2QgdgMgRAAQggAAgSAaQgZAmAABnIAACQg");
	this.shape_60.setTransform(590.9,700.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#00FF00").s().p("AiHDJQgxgYggg1Qggg0AAhHQAAhkBBg+QBAg/ByAAQBbAAA2AcQA1AcAcA1QAcA1AABUIAAATIlJAAQAEAoARATQAYAcAmAAQAYAAAWgMQANgIAQgTICiAPQglBBg1AcQg1AchhAAQhWAAgxgYgAg9hfQgPATgEAnICiAAQgFgwgVgVQgVgUgiAAQgmAAgYAfg");
	this.shape_61.setTransform(541.2,700.6);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#0033FF").s().p("AgrEeQgdgQgOggQgOggABhIIAAiWIg+AAIAAh5IA+AAIAAhPICkhVIAACkIBaAAIAAB5IhaAAIAACXQAAAcAFAIQAIAOAVAAQARAAAigKIAMByQg+ANg1AAQg8AAgegQg");
	this.shape_62.setTransform(495,692.9);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FF3399").s().p("AijC/QgyghgPg+ICkgQQAKAdATANQASANAdAAQAhAAATgPQAOgKAAgQQAAgSgTgJQgNgHg5gLQhWgPghgMQgigNgWgdQgXgeAAgnQAAgrAYgfQAZgeArgQQAsgPBJAAQBMAAAlAMQAkAMAZAYQAYAZAQAqIicAQQgGgVgOgKQgUgNgaAAQgcAAgNAKQgNAKAAAOQAAAQAQAIQARAIA1AHQBSAJAoARQAoAQAWAeQAVAfAAAkQAAAmgWAjQgXAjgwAVQgxAVhTAAQh1AAgygig");
	this.shape_63.setTransform(450.8,700.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#66CC33").s().p("AjPC9QgogjAAg1QAAgxAdgfQAdgfBNgPQBdgTAbgHQAbgIAfgMQAAgegNgNQgMgMggAAQgnAAgVANQgPAKgKAcIiegQQAJgqARgXQARgYAfgSQAXgMAogHQAogHAuAAQBJAAAtAJQAtAIAeAaQAVASAMAiQAMAhAAAfIAAC9QAAAeAEARQAEASANAaIibAAQgJgQgDgJQgDgJgDgSQggAfggANQgrASg6AAQhNAAgogkgAgEAgQgyAOgOANQgNANAAARQAAAUANAMQAOAMAaAAQAcAAAXgNQAXgNAKgTQAKgUAAgfIAAgaQgiAMgkAJg");
	this.shape_64.setTransform(398.2,700.6);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFF00").s().p("AiHDJQgxgYggg1Qggg0AAhHQAAhkBBg+QBAg/ByAAQBbAAA2AcQA1AcAcA1QAcA1AABUIAAATIlJAAQAEAoARATQAYAcAmAAQAYAAAWgMQANgIAQgTICiAPQglBBg1AcQg1AchhAAQhWAAgxgYgAg9hfQgPATgEAnICiAAQgFgwgVgVQgVgUgiAAQgmAAgYAfg");
	this.shape_65.setTransform(343,700.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#6633CC").s().p("AjYElIgNhzQAjALAsAAQAdAAASgNQASgNANgjIi1muICuAAIBYEfIBSkfICjAAIirHLQgdBPgeAcQgqAmhYAAQgkAAhKgJg");
	this.shape_66.setTransform(262.4,709.3);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FF3399").s().p("AjsEuIAApRICbAAIAAA/QAfgoAbgOQAkgTArAAQBWAAAwBCQAvBCAABiQAABqgzA5Qg0A4hPAAQgmAAgegNQgfgNgagZIAADNgAgyibQgUAZgBA3QAAAzAWAYQAWAZAgAAQAcAAAUgYQATgXAAg4QAAg1gUgYQgVgZgdAAQgeAAgWAZg");
	this.shape_67.setTransform(211.6,708.3);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#00FF00").s().p("AjsEuIAApRICbAAIAAA/QAfgoAbgOQAkgTArAAQBWAAAwBCQAvBCAABiQAABqgzA5Qg0A4hPAAQgmAAgegNQgfgNgagZIAADNgAgyibQgUAZgBA3QAAAzAWAYQAWAZAgAAQAcAAAUgYQATgXAAg4QAAg1gUgYQgVgZgdAAQgeAAgWAZg");
	this.shape_68.setTransform(156.2,708.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#0033FF").s().p("AjPC9QgogjAAg1QAAgxAdgfQAdgfBNgPQBdgTAbgHQAbgIAfgMQAAgegNgNQgMgMggAAQgnAAgVANQgPAKgKAcIiegQQAJgqARgXQARgYAfgSQAXgMAogHQAogHAuAAQBJAAAtAJQAtAIAeAaQAVASAMAiQAMAhAAAfIAAC9QAAAeAEARQAEASANAaIibAAQgJgQgDgJQgDgJgDgSQggAfggANQgrASg6AAQhNAAgogkgAgEAgQgyAOgOANQgNANAAARQAAAUANAMQAOAMAaAAQAcAAAXgNQAXgNAKgTQAKgUAAgfIAAgaQgiAMgkAJg");
	this.shape_69.setTransform(99,700.6);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FF0000").s().p("AA+EpIAAjsQgBgpgPgRQgOgQgbAAQgeAAgSAWQgTAWAAA8IAADOIikAAIAApRICkAAIAADaQAigiAggPQAhgPAuAAQBDAAAnApQAmAoAABUIAAESg");
	this.shape_70.setTransform(43.7,692.4);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f().s("#0099FF").ss(1,1,1).p("AEJAAQAACThNBoQhOBohuAAQhtAAhOhoQhNhoAAiTQAAiSBNhoQBOhoBtAAQBuAABOBoQBNBoAACSg");
	this.shape_71.setTransform(790.5,112.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f().s("#000000").ss(1,1,1).p("EAtjAJ9QALgMAMgLQAvgsA/ghQBKgnBggaQCGBKBcBbEArfAJ9QA7AcAjBBQAZgzAngqEAhFAfhQlowIK1k1QA3gZAxgOEAngAJ9QCNgqBYAqEAsJAO3QASAQAQASQADAEADADQAYAcAUAgQAGAKAHALQAJgPALgMQAJgKAGgGQAGgGAXgUQAXgVAkAVQAjAVAGACQABABACABQAcAMAaAPQA+AjAwAzQAhAjAbArQAOAWALAUQAuBSAKA/QACAQABAOQACBXhIBSQgPAQgRANQgUAQgWAKQgXAKgZAEIhZAAQgVgDgVgFQgqgLgkgVQgQgJgQgLQgLgJgLgJQgCgCgCgBQgcgagTgbQgDgFgDgFQgOgWgIgYQg4AehIgGQgGAAgGgBQhsgMhOhEQgCgBgBgCQhPhHgJhcQgDgYACgfQACgpAJgzQAKg6AThIQAAgBABgBQAYhbAvggQAEgCAFgDQAsgYA/AYQAEACAEACQACAAACABQATAJATAKQA5AeAtAqQAYEnAQj+QAHheAFioQBHCEgGC4EAs9ASzQAAAAABgBIAAABgEAmNAS3IGvAAIgDAQQAEgTAAAAQAAgBAAAAEAs+ASyQABgHACgIQAEgRAFgSQAFgUAHgRQADgIgbBfQAkh1AIgMEAmKARvQACAQAAAPQABAkgMAkEAmBARzIAJgEEAmBARKQACAJADAIQACAKACAKEAshAVfQACglAIguIAOhFEAsvAXNQgKgagDgcQgCgZABgfIHphxEAtNAYdQgFgRgDgREAtNAYdQAAAAAAABIAAHDEAtLAYFQABALABANEAnmAWRIFFiFEAszAfhIAAEHIqhAAQg8iJgrh+EAiQAfhQAAB1ACCSEAjEAX8QgbgkABIJEA+VATHQAEgPAEgPQAYhbAvggQAyghBKAgQACAAACABQCPA+BRCCQAAABABABQANAUALAUQAtBSALA+QACAQAAAPQACBXhIBRQgrAxg7AQIgGAAIgZAAIhnAAQhVgShAg4QgCgBgBgCQhPhHgJhcQgDgYACgfQAEhNAdh1gEA44AT3QBthkDiAxQAHABAHACEBFFATwQAxgpBKgLQBQAaBBAiEA/NAZjIHIi7EA90AWJIHphxEA3UAYKQAIi/BchUQgdCEhHCPQAXBZACEHQAAA4AAA/EA3zAfhQADg1AAgMQgFgbgEgbQgCgIgBB/EA3TAfhQgBBTgCBgQAGh1ADg+EA3OAjWQgGiGgFhvEA3QAfhQgBBZgBCcIqbASEA3QAiUIgCBCEBCPAfhQgFARgGASQABgSACgREA3eAfhQgPloAFhvEBDlAawQgICHg0CqEBChAfhQAMisAfiFEA2OAJ9QD+D9hUF9EAt6AY6IHIi7EBJRAUHQGyD+kjKyQgHAPgHAQI0EAAEhAKghdQAphEA2gjQAUgOAYgJQAGgDAGgCQACAAACgBQAkgLAgAJQAFACAFACQAFACAEACQAaANAWAbQAPASANAYQAYArAVAuQAOAeAMAfQATAxAPAzQAjB7hEBCQgFAFgFAEQglAdgrASQg1AWhAAFQhKAFg5ggQgfgRgbgdQgPgRgMgRQguhBAAhEQAAgWAEgXQAMhJAxheQAGgMAHgMQABgBAAgBIC7C+IjcC1EhD+gVMQguhWAliJQAYhbAvggQAyghBKAfQACABACABQCCA4BOBwEhCAgQ5QgugUgmghQgCgCgBgBQhPhIgJhbQgDgZA0gfIFvAAIAfAAEg5XgaWQAJgVALgPQAOgUASgMQANgJAPgEQAFgBAFgBEg6fggwIiwCRIDLDNEg9wgTTQgogLgBAUIApgJQgRAsgSAhQgEgBgBgLQgCgYAqgpQgaBRgJgEQg8Bug/gFQg+gFg0gXIDxkTIAfgjEg5rgTbIABkAIACiOQAHgZAKgUEg5rgZfQACgFABgFEg5rgazQAIALAIAMQACADACADEg39gbnQAmgHAwAVQABAAACABQCPA+BRCCQAOAVALAVQANAWAJAVEg5rgTbIHAkTEgmZgGxQAmBFAOA4EgrEgKqQAWAEAYAKQACAAACABQAFADAFACQBmAuBFBSQAXAbAUAgQANAVAMAVEgsfgPBQAhA6AOAxEg0IgNQQAFhXAkiJQAYhbAwggQAxghBLAgQABAAACABQBDAdA1AsQAOALANAMQAsAqAhA2QAOAVALAVEgz+gQcQgHgXgCgXQgBgJAAgJQgwASg6gFQhNgGg+giEgyVgTDQgOAWgTAWQggAkgoASQgFADgFACEg3FgO0QAtBSALA+QACAQAAAPQACBXhIBRQhIBShzgKQh0gJhShIQgCgBgBgCQhPhHgJhcQgDgYACgfQAEhXAliJQADgOAFgMQgBgBAOiVEgyvgJ2QhOhHgKhcQgCgYABgfIHphxEgtLgJLQhBAxhagIQhzgJhShIQgCgBgCgCIG/i3Eg04gJ/IAxAJIAMAFQADAAADACQACAAACABQCPA+BRCCQANAVAMAVEgt4gGZQAGggAJgmQACgKACgKQAGgWAGgXQAGgXAIgUEgrwgLKQgGATgKATQAbgLAhAFEgsAgKkQgRAdgZAdQgQASgRANEg2IgA5QhPhHgJhcQgDgYACgfIHjhwIAGgBQAtBSALA+QACAQAAAPQACBXhIBRQhIBRhzgKQh0gJhShHQgCgBgBgCIHIi7EgrEgAoQg2gUgsgnQgCgCgBgBQg6g1gVhAEgllgDKQgPA5gxA3QAAABgBABQgZAcgeARQg5AfhKgGQgVgBgTgEQgfgGgdgKEgspgBmIHEi5Egt4gFDIHfhuEg9wgRfQAVgrAdgUQAyghBKAgQACAAACABQCPA+BRCCQANAVAMAVEg39gR5QgfgRgbgYQgCgBgCgCIGmirEg9wgQmQgHgLgGgMEhCjgQQIAjgpEhCjgQQQAOASAMAUQAOAVALAVQAuBSAKA+QACAQABAPQACBXhIBRQhJBShzgKQhzgJhShIQgCgBgCgCQhOhHgKhcQgCgYABgfQAFhXAkiJQAYhbAwggQAxghBLAgQABAAACABQB5A1BNBlgEhDXgPVIA0g7EhCOgEHQAEhWAliJQAYhbAvggQAyghBKAfQACABACABQCPA+BRCBQANAWAMAUQAtBSALA/QACAQAAAOQACBXhIBSQhIBQhzgJQh0gJhShHQgCgCgBgBQhPhIgJhbQgDgZACgfIHphxEhM2gE9QgagzAliJQAQg9AbgjQANgRAPgKQATgNAWgDEhM2gE9IB7AAEhL7gA/QhPhIgJhbQgDgZAghCEhK7gKqQAlgFAuATQACABACABQCPA+BRCBQANAWAMAUQAtBSALA/QACAQAAAOQACBXhIBSQhIBRhzgJQhMgGg9ghEhK7gFjIFQhOEhK7gASQgggRgdgZQgCgCgBgBIBAgaEhA1gAsIHIi7EhJZgNPIHphxEhK7gB/IGIihEhIAgJ1IHIi7Eg+ugNDIHphxEg9VgJpIHIi7AIyLRQACAQABAOQAAAcgHAcAIuK9QADAKABAKAIuLTIAEgCEg47gSlQgcgagUgc");
	this.shape_72.setTransform(514.7,517.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#CCFF99").s().p("AARFNQhzgKhShHIgDgDIHHi7IACAeQACBXhIBSQhBBIhjAAIgXAAgAkPBWQgDgZACgfIgBAAQAFhVAkiJQAYhbAwggQAGgFAHgDIAsgJIAxAJIAMAEIAGACIADACQCOA+BRCBIAZAqIgFACIniBuIHihuIAGgCQAtBSALA+InHC7QhPhIgJhbg");
	this.shape_73.setTransform(186.6,486.6);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#6699FF").s().p("AbQKWIAEgCIADAeQAAAcgHAcgAbQKAIAEAUIgEACgA2+hPQgVgBgTgEQgfgGgdgKIAAgBQg2gUgsgnIgDgDIHEi5InEC5Qg6g1gVhAIAAhoIAAhWQAGggAJgmIAEgUIAMgtQAGgXAIgUQARgNAQgSQAZgdARgdQAbgLAhAFIAAAAQAWAEAYAKIAEABIAKAFQBmAuBFBSQAXAbAUAgIAZAqInfBuIHfhuQAmBFAOA4IAAAVIAABVQgPA5gxA3IgBACQgZAcgeARQgwAag8AAIgXgBg");
	this.shape_74.setTransform(396.1,523.3);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#CC9900").s().p("AAQFMQhLgGg9ggIAAAmQgggSgdgZIgDgDIBAgaIhAAaQhPhHgJhcQgDgYAghCIB7AAIh7AAQgagzAliJQAQg9AbgiQANgRAPgLQATgMAWgDIAAgmQAlgGAuAUIAEABQCOA+BRCCIAZAqQAtBSALA9ImHChIGHihIACAfQACBXhIBRQhBBJhjAAIgXgBgAh4gEIFPhOg");
	this.shape_75.setTransform(47.2,482.2);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FF0066").s().p("AARFMQhzgJhShIIgDgDIHHi7IACAfQACBXhIBRQhBBJhjAAIgXgBgAkPBVQgDgYACgfIHohwQAtBSALA9InHC7QhPhHgJhcgAjnjBQAYhbAvggQAyghBKAgIAEABQCOA+BRCCIAZAqInoBwQAEhWAliJgADYhSIAAAAg");
	this.shape_76.setTransform(118.1,487.9);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#9999CC").s().p("AARFMQhzgJhShIIgDgDIHHi7IACAfQACBXhIBRQhBBJhjAAIgXgBgAi3D4QhPhHgJhcQgDgYACgfIHohwQAtBSALA9InHC7IAAAAgAjnjBQAYhbAvggQAyghBKAgIAEABQB4A1BMBlIg0A7IA0g7QAOASANAUIAZAqInoBwQAEhWAliJg");
	this.shape_77.setTransform(72.2,429.4);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#996666").s().p("ABBFNQg9gFgzgXIDwkTIjwETQgugUgmghIgEgDQhOhIgKhbQgCgZAzgfIFvAAIAfAAIgfAAIAfgiIAAAiIAAB5QgogLgBAUIApgJQgrApADAYQABALADABQg4Bpg9AAIgGAAgADBAeIlvAAQgthVAkiJQAYhbAwggQAxghBKAfIADACQCCA4BPBwIAACPIgfAigADggEg");
	this.shape_78.setTransform(97,378.5);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#0066CC").s().p("AAWFMQhygJhShIIgEgDIG+i3IAABjQgGATgKATQgRAdgZAdQgQASgRANQg4AqhLAAIgYgBgAiyD4QhOhHgKhcQgCgYABgfQAFhWAkiJQAYhbAwggQAxghBLAgIADABQBCAdA1AsIAbAXQAsAqAhA2IAZAqQAhA6AOAwIAAApIm+C3IAAAAgAkLAeIHohwgAEMBBg");
	this.shape_79.setTransform(207.8,429.3);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#33CC99").s().p("AgOAnQARgiARgrQgYBNgKAAIAAAAgAgTAaQgCgYApgoQgRArgRAiQgEgBgBgMgAAUgmIAAAAg");
	this.shape_80.setTransform(117.4,397.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#3333CC").s().p("AAOFMQhMgGg+giIAAgCQgfgRgbgYIgEgDIGlirIAACNQgOAWgTAWQggAkgoASIgKAFQgmAPgsAAIgYgCgAi6D2QgdgagTgcIG/kSQAMAWAKAVIAAByImlCrIAAAAgAjpg/IACiOQAHgZAJgUQAJgVAMgPQAOgUARgMQAOgJAPgEIAKgCIAAACQAlgHAxAVIADABQCOA+BRCCIAZAqIm/ESgADVhSIAAAAg");
	this.shape_81.setTransform(169,373.6);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FF0000").s().p("ABmNpQhzgJhShIIgDgDIHHi7InHC7QhPhIgJhbQgDgZACgfQAEhWAliJQADgOAFgMIANAXIgNgXIANiXIAAB0QAVgqAdgUQAyghBJAfIAEACQCPA+BRCBIAZAqQAtBSALA/IACAeQACBXhIBSQhBBJhjAAIgXgBgAi7I6IHohxgAjjkbQgfgSgbgcQgPgRgMgRIDci2Ii7i9IC7C9IjcC2QguhBAAhFQAAgVAEgYQAMhIAxheIANgYIABgCQAphEA2gkQAUgOAYgIIAMgFIAEgBQAkgLAgAJIAKAEIAJAEQAaAMAVAcQAPARANAYQAYAsAVAtQAOAfAMAfQATAxAPAzQAjB6hEBDIjKjOICviRIivCRIDKDOIgKAIQglAegrASQg0AWhAAEIgUABQg+AAgxgbgABulTgAhcohg");
	this.shape_82.setTransform(132,376.6);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#00FF00").s().p("EgC6A0FIAChDIAJizIAFAAIAMAAIADAAIAGAAIADhBIgJg2QgCkHgXhZQBHiPAdiEQBshkDiAxIAOADQgdB1gEBNQgCAfADAZQAJBbBPBIIADACQBAA4BVASIBnAAQgfCFgMCsIAIAAQA0iqAIiHIAGAAQA7gPArgyQBIhRgChXIgCgfQgLg+gthSIgYgoQAxgoBKgLQBQAZBBAjIAAAOQGyD+kjKyIgOAggEAH7AwyIALgjIgIAAIgDAjgEgR9gqmQhOhnAAiUQAAiSBOhoQBNhoBugBQBuABBOBoQBNBoAACSQAACUhNBnQhOBphuAAQhuAAhNhpg");
	this.shape_83.setTransform(886.8,410.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FF3366").s().p("AkOCAQgDgZACgfIHohwQAtBRALA/InHC7QhPhIgJhbgAjuh4IAIgeQAYhbAvggQAyghBKAfIAEACQCOA+BRCBIABACIAYAoInoBwQAEhMAdh0gADZgoIAAAAg");
	this.shape_84.setTransform(937.5,651.7);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#CC0000").s().p("AgFFVQgWgDgUgFQgqgLglgVQgQgJgPgLIgXgTIgDgDIHHi7InHC7QgdgZgSgcIgGgJQgOgXgJgXQgJgbgDgcQgDgYACgfIHohwInoBwQACglAIgtIAOhGIAEgTIAAAAIAAgBIAAAAIAEgPIAJgkQAEgTAHgRQADgIgbBfQAlh1AHgMQAKgQALgLIAPgRQAFgGAYgUQAWgUAkAVQAjAUAGADIAEABQAcAMAYAPQA+AkAwAyQAiAkAbArIAZAqQAtBRALA+IACAfQACBXhIBRQgPARgQANQgUAPgXAKQgXAKgZAFg");
	this.shape_85.setTransform(826.9,650.7);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#0033CC").s().p("AA0FNIgMgBQhrgMhOhEIgDgDIFEiFQgIAtgCAmQgBAeACAZQADAcAKAaQguAZg7AAIgXAAgAjsBVQgDgYACgfIGuAAIgDAQIgOBGIlECFQhPhIgJhcgADBAeImuAAQACgnAJg0QAKg5AThIIABgDQAYhaAvggIAJgGQAsgYA/AYIAIAEIADACQATAIATAKQA5AeAtAqIABAMIAAAAIAAACIABADQALCMAKACIABAAIAAAAQAIgDAHheIAAgFIABgLIAAgCIAAgDQAYAcAUAgIANAVQgIAMgkB1QAbhegDAHQgHARgFAUIgJAiIgDAQIAAAAIgBABIgEATgAjtAegADDAaIAAAAIAAAAIAAAAgADDAagAClhCQgKgCgLiMIgBgDIAAgCIAAAAIgBgMQASARAQASIAGAGIAAADIAAACIgBALIAAAFQgHBegIADIAAAAIgBAAg");
	this.shape_86.setTransform(783,634.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#00CC00").s().p("EAlDAfOIgCkHIACEHQg8iJgrh+IAaAAQlowIK1k1QA3gZAxgOIgaAAQCNgqBYAqIAaAAQA6AcAjBBQBHCEgFC4QgLAMgKAPIgMgVQgVgggXgcQAHheAEioQgECogHBeIgGgGQgQgSgSgRQgugqg4geQgTgKgTgIIgEgCIgJgEQg+gYgtAYIgIAGQgwAggXBaIgBADQgTBIgKA5QgKA0gCAoQgBAfACAYQAKBcBPBIIADADQBNBEBtAMIALABQBJAFA3geQAJAYAOAWIAIAiIAAABIAAHDIgaAAIAAEHgEAlbAbHIAAgXQgBnLAXgFIABAAIAAAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIAAAAIAAAAIAAAAIAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAAAAAIAAAAIgBAAQgXAFABHLIAAAXIAAAAgEAoyAO9QALgiAAghIAAgGIgCgfIgFgUIgEgRIAEARIAFAUIgJAFIAJgFIACAfIAAAGQAAAhgLAigEA7pAPdQgdCEhHCPQAIi/BchUgEAo7ANVIAAAAgEgxWgVkIgBgSIAKgEIAABEQgHgXgCgXgEg6/gXtIgpAKQABgVAoALgEg26gd4IADgLIgCCPgEg26gd4IAAhVIAQAXIADAGQgJAUgHAZIgDALgEg23geDg");
	this.shape_87.setTransform(497,545.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#00FF33").s().p("AmMKBIAaAAIAAnDIAAgBIgCgYQATAbAcAaIAEADIAWASQAQALAQAJQAkAVAqALQAVAFAVADIBZAAQAZgEAXgKQAVgKAUgQQARgNAPgQQBIhSgChXIgDgeQgKg+guhSIgZgqQgbgrgggjQgwgzg+gjQgagPgcgMIgDgCQgGgCgjgVQgkgVgXAVQgXAUgGAGIgPAQQAGi4hHiEQAZgzAngqIgaAAIAXgXQAvgsA/ghQBKgnBggaQCGBKBbBbIAaAAQD+D9hUF9QhcBUgIC+QgFBvAPFoIgFAAIgGAAIgDAAIgMAAIAKD1IqaASg");
	this.shape_88.setTransform(841.1,654.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44,p:{x:939.5}},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30}]}).to({state:[{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_44,p:{x:942.1}},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59}]},1).to({state:[]},9).to({state:[]},10).wait(10));

	// Button
	this.next_btn = new lib.BasicButton();
	this.next_btn.name = "next_btn";
	this.next_btn.parent = this;
	this.next_btn.setTransform(878.7,557.3);
	new cjs.ButtonHelper(this.next_btn, 0, 1, 2, false, new lib.BasicButton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.next_btn).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(568.7,494.6,953.9,635.6);
// library properties:
lib.properties = {
	id: '107876370D25E544892989AD2F7A981E',
	width: 1024,
	height: 768,
	fps: 10,
	color: "#66FFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['107876370D25E544892989AD2F7A981E'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;