(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.StartBtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.text = new cjs.Text("P L A Y", "50px 'Tw Cen MT Condensed Extra Bold'");
	this.text.lineHeight = 56;
	this.text.lineWidth = 221;
	this.text.parent = this;
	this.text.setTransform(97.5,128.6);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("AAbgzQgPgTgKgNQgOgSgEgDQgHgGgMgDQgHgCgOgDQgegFgUABQgbABgRAPQgRAPgCAcQgCAZANAXQALASAUASQAMALAcATIB7BYQA/gYAlg6QAhg2ABgyQAAgLgEghQgCgUgGgJQgIgLgOgEQgNgEgPABQgoADgWAWQgNAMgFARQgGARAFAQg");
	this.shape.setTransform(57.2,13.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#7E15F0").ss(2,1,1).p("AgFgQQADANAAACQABACAAAHQABACAAADQAAAFACAFAARgYIADAKQAGANABAEAgagMIAAAl");
	this.shape_1.setTransform(285.1,140.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(3,1,1).p("AKsjtQApAZAkAhQBJBBAsBWQAXArAbBOQAhBcANAgQAOAeAQAfQAZAuAgAvQgCADgCACQgEAEgLALQgMAMgbgBQgbgBgggQQgfgQgNgKQgCgCgTgQQgogngNgPQgFgEgEgFQgCgCgCgDQgBgBAAAAQgUgXgLgaAKsjtQBWAKBMAPQArAIAZAJQAlANAZAUQAzAqATBiQAVB9g7A2QgEAmAXA3QAGAPAFANQAVA1ADAMQAEASgFAKQAoA6A0A8AlppVQAbgnAngOQAsgOApADQAtAFAkAZQAmAbAOAnQAMgeAggRQAggRAgAHQAgAGAWAdQAWAcgBAhQAlgRApAZQAoAZAHAqQAGAogXAoQgPAbgYASQAWARAQAOQGXAeBAAcAjUnNQAjgNAiAJQAiAJATAJQAUAKAZAaQAhAgAMAcQAMADABAAQAIgJAGgDQAFgCAMAAIAnAAQAZAAANACQAOAGAQALQAMAJAMAIADVknQAIB8gCBtQAABGgIArQgNBAgnBFQAAACgDAOQgEAOAIBAQAAAEABAEQAAgEAAgEQgCgsAAgyADVknQBlgRBigBQBigBBZAiQAtASAoAZAIqEFQgHAIgIAJQgPAQgTARQgmAkgyAWQhXAnhugFQgGgBgGAAQABAFgLgHQgCgBgBgBQgPgKgJgfQgJgfgBgoAMsEQIipAAQgnAAgygLAI3DiQgHAPgGAUAxHDnQADABACAAIADACIA0AMQBgASBgAOQHGBBHOgkQACAAABAAQAHgBAHAAIBHgUAR3HoIgLBYQgEATAAAJQgBAPAFAMQAFALAKAKQAIAIADABQAEABAGAAQADAAAGAAQAIAAAQAAQANAAAJgEQAXgKAKgjQAKgogRggQgIgRgPgMQgQgMgSgDQgSAAgIgBQgJgCgOgGgAlppVQATgEAWgBQAVgBAKABQAQABALAIQANAIAIAQQAGAKAFATQALAnAHAoQAHAwACAzAmkpCQAZgNAigGArwm3QgJgTAAgTQgBgSAHgSQAPgfAhgXQA4gqBngSQAngJAcAFQASAEAOAKQAQALANAcArwm3QgDAAgDABQiLAahkA0QhcAwhCBMIgXAdQgFAHgFAHQhOByAJB5QAHBSAtAxQAdAfAxASQAHADAIACIARAEQALgeANg3QAMg3AHg3QALhbg0haQg1hagJgBAmCkYQhLg3gYhDQgLglAEglQAAgCABgDQAGgqAbgcQAPgQAXgLAnsncQipAUhbARAoMh5QAAAtggAgQggAhguAAQgtAAghghQggggAAgtQAAguAgggQAhggAtAAQAuAAAgAgQAgAgAAAugApRh4QAAASgNANQgNAOgTAAQgSAAgOgOQgNgNAAgSQAAgTANgNQAOgNASAAQATAAANANQANANAAATgAyQgzQAFAJACALQAIATAAAU");
	this.shape_2.setTransform(166,80);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC0000").s().p("AhXAzQgcgTgMgLQgUgSgLgSQgNgXACgZQACgcARgPQARgPAbgBQAUgBAeAFIAVAFQAMADAHAGQAEADAOASIAZAgQgFgQAGgRQAFgRANgMQAWgWAogDQAPgBANAEQAOAEAIALQAGAJACAUQAEAhAAALQgBAyghA2QglA6g/AYg");
	this.shape_3.setTransform(57.2,13.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF33CC").s().p("AAqDmIgPgFQgwgTgdgeQgtgxgHhSQgJh5BOhyIAKgOIAXgdQAIABA1BaQA0BagLBaQgHA4gMA3QgNA2gLAfgAgGgcQAHATAAAUQAAgUgHgTQgCgLgFgJQAFAJACALg");
	this.shape_4.setTransform(50.5,79.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgfAgQgNgOAAgSQAAgRANgOQAOgNARAAQASAAANANQAOAOAAARQAAASgOAOQgNANgSAAQgRAAgOgNg");
	this.shape_5.setTransform(102.1,67.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhNBOQggggAAguQAAgsAgghQAhggAsAAQAuAAAgAgQAgAhAAAsQAAAuggAgQggAgguAAQgsAAghgggAgjgeQgNAOAAARQAAASANAOQAOANASAAQARAAANgNQAOgOAAgSQAAgRgOgOQgNgNgRAAQgSAAgOANg");
	this.shape_6.setTransform(102.5,67.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFCC").s().p("A5BH0IAAvnIMwAAQHGBBHOgkIADAAIAOgBIBGgTQACAnAJAgQAJAeAOAKIADACQAMAHgBgFIAMABQBtAGBXgnQAygXAngkQASgRAQgQIEVAAIAJAKQANAOApAnIAVATQAMAJAgARQAfAPAcACQAbAAALgMIAPgPIAFgFQAEgKgEgSQgDgMgVg1IH7AAIAAPngATqhzQANAAAKgDQAXgKAJgjQAKgogQghQgJgRgPgMQgPgMgTgDIgagBQgIgBgOgHIgMBYIgEAcQgBAQAFALQAGALAJAKQAIAIAEABQADABAGAAIAJAAIAYAAgAS7kgQg0g7gog7QAoA7A0A7g");
	this.shape_7.setTransform(160.2,157.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#8CCCFF").s().p("Al2GkQhhgOhfgSIg0gMIgDgCIgGgBQAMgeAMg3QANg3AHg3QALhcg1hZQg1hagJgBQBChMBcgwQBlg0CLgaIAGgBQBagRCqgUIgCAVQAAAaAJAbQAWBDBMA3QhMg3gWhDQgJgbAAgaIACgVIAAgFQAHgqAZgcQAQgQAXgLQAZgNAigGQATgEAWgBQAVgBAJABQARABAKAIQANAIAIAQQAGAKAGATQALAnAGAoQAjgNAiAJQAiAJAUAJQATAKAaAaQAhAgAMAcIANADQAJgJAFgDQAFgCANAAIAnAAQAZAAAMACQAPAGAPALIAYARQAXARAQAOQAIB8gCBsQAABHgJArQgMBAgnBFIgEAQQgEAOAIBAIABAIIhGAUIgOABIgDAAQikANiiAAQkpAAklgqgAjzg5QggAgAAAtQAAAtAgAgQAgAhAuAAQAtAAAgghQAhggAAgtQAAgtghggQgggggtAAQguAAggAggAEIjcQgBgzgIgwQAIAwABAzg");
	this.shape_8.setTransform(119.1,65.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#9966FF").s().p("AOgKWIgJAAQgGAAgDgBQgEgBgIgIQgJgKgGgLQgFgMABgPIAEgcIAMhYQAOAGAIACIAaABQATADAPAMQAPAMAJARQAQAggKAoQgJAjgXAKQgKAEgNAAIgYAAgAOUJ3IAAgmgAOsJcIABAJQABADAAADIADAJIgDgJQAAgDgBgDIgBgJIgDgPIADAPgAPDJPIAHARIgHgRIgDgKgAhhlXQgPgLgPgGQgMgCgZAAIgnAAQgNAAgFACQgFADgJAJIgNgDQgMgcghggQgagagTgKQgUgJgigJQgigJgjANQgGgogLgnQgGgTgGgKQgIgQgNgIQgKgIgRgBQgJgBgVABQgWABgTAEQAagnAogOQAsgOApADQAsAFAlAZQAmAbANAnQANgeAfgRQAggRAhAHQAhAGAVAdQAWAcgBAhQAmgRApAZQAnAZAHAqQAGAogWAoQgQAbgYASIgYgRgAvyndQAAgSAHgSQAOgfAhgXQA4gqBngSQAngJAdAFQASAEAOAKQAPALAOAcQgXALgQAQQgaAcgHAqIAAAFQiqAUhaARQgKgTAAgTg");
	this.shape_9.setTransform(190.8,80);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D9BBFF").s().p("AmdFaIgDgCQgOgKgJgfQgJgfgCgoIAAgIQgCgsABgyQAnhFAMg/QAJgrAAhHQAChtgIh8QGVAeBBAcQAoAZAlAhQBJBBAsBWQAWAsAcBNQAgBcAOAgQANAeARAfQAZAuAgAvIgFAFIgPAPQgLAMgbgBQgcgBgfgQQgggQgMgKIgVgSQgpgngNgPIgJgJIgEgFIgBgBQgUgXgLgaQALAaAUAXIioAAQgnAAgygLQAGgUAHgPQgHAPgGAUIgOARQgQAQgSARQgnAkgyAWQhXAnhtgFIgMgBQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAQgCAAgHgEgAHCE9IAAAAgAGJDgQgRgfgNgeQgOgggghcQgchNgWgsQgshWhJhBQglghgogZQBWAKBLAPQAsAIAZAJQAlANAYAUQA0AqASBiQAWB9g7A2QgFAmAXA3IALAcQAVA1ADAMQAEASgEAKQgggvgZgug");
	this.shape_10.setTransform(227.1,85.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.text}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,320.5,241.9);


(lib.ReplayBtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAkCgIgqgBIgrABIgQABIgCgBIgBgDIAAgLIABgCIACgBIAWAAQAJAAADgDQAEgDAAgFIABgPIAAgeIABgnIAAgaIgMgTIgVgjIgZgqIgWgkQgKgQgFgFQgEgFgGgDQgHgDgFAAIgMAAIgDgBIAAgCIAAgMIAAgCIADgBIARABIAjABIAlgBIAWAAIAJgBIACABIABACIAAALIgBADIgCABIgPAAQgKAAgCADQgDAEACAIIAGAOIAPAbIATAiIARAhIALAVIAPgVIAVggIAVghIASgbIAHgOIABgHQAAgFgEgCQgCgDgKAAIgMAAIgDgBIgBgDIAAgLIABgCIADgBIARABIAkABIAcgBIANgBIACABIABACIAAALIgBADQAAAAAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgMAAQgFAAgGACQgFADgGAFIgNAQIgXAhIgcAoIgaAkIgRAYIAAA7IABAUIAAAUIABALQACALAEADQAFACAJAAIASAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAABABIAAACIAAALIAAACQgBABAAAAQAAAAAAAAQgBABAAAAQgBAAAAAAIgSgBg");
	this.shape.setTransform(256.2,31.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACZCnIgQAAIgcgBIgqABIgWABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgCIAAgLQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAIADgBIALAAQAKAAADgEQADgEgCgJIgGgTIgHgaIgJgbIgGgUIhuAAIgHASIgKAbIgJAcIgGAQIgBAFIAAAFQAAAFADACQAFADAHAAIAVAAIADABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAIAAALQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgCABIgSgBIghgBIgaABIgPAAIgIABIgDgBIAAgDIAAgLIABgCIACgBIAQAAQAKAAAFgFQAHgFAEgLIAHgRIAOgjIAQgpIAMgiIAGgOIAKgbIALggIALgcIAGgQIABgHQACgEgDgEIgCgDIgBgDIABgCIADgCQAGgBAJgFIAMgIQAHgFACgEIAEgCQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIACAGIAIAZIAMAjIANAmIALAjIAIAZIALAhIAOAoIANAlIAIAVQAGALAJAEQAHAFAJAAIAOAAQABAAABAAQAAAAABAAQAAAAAAAAQAAAAABABIABACIAAALIgBADIgEABIgKgBgAAlAZIgGgSIgLggIgLgkIgJgfIgFgPIgCgEIgCgCIgCACIgCAFIgGAPIgLAfIgOAkIgLAfIgHASIBjAAIAAAAg");
	this.shape_1.setTransform(224.3,30.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ABkCgIgeAAIglAAIgngBIgmAAIgeAAIgXAAIgRABIgLAAIgGABIgEgBIgBgDIAAgLIABgCIADgBIAVAAQAMAAAEgEQAEgDgBgFIABgQIAAggIAAgnIABgkIAAgYIAAgZIAAghIgBghIgBgTQABgJgEgDQgDgEgKAAIgVAAIgCgBQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAIACgBIARABIAqABIAwgBIASgBIADABIABADIAAAKIgBADIgEABIgbAAQgKAAgCAEQgEAEAAAJIAAAPIAAAdIgBAhIAAAdIAAAlIAAAOIAAAcIAAAgIABAfIAAATIAPAAIAaABIAdAAIAaAAIARgBQAKgCAJgJQAKgKAIgMQAIgNAHgLIAHgTIACgCIACAAIAIADIABABIAAADIgFAOIgGAbIgHAeIgFATIgOgBg");
	this.shape_2.setTransform(193.2,31.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgCCgIgUAAIghgBIgsABIgSABQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAAAIgBgDIAAgLIABgCQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIATAAQALAAAEgDQAEgDABgIIAAgPIABgfIAAgoIABgpIAAgzIAAgZIgBgaIAAgVIAAgLQgBgHgEgCQgEgBgJAAIgaAAIgCgBIAAgDIAAgLIAAgCIACgBIASABIAuABIAOgBIASAAIASgBQAYAAASACQARACAOAFQANAFANAJQAQALAJARQAJARAAAUQAAArgeAYQgeAXg2ABIgYgBIgYgBIAAAXIAAAWIAAAcIABAZIAAAOQABAHADADQAEAEAHAAIAcAAIADABIAAACIAAALIAAADIgEABIgIgBgAgaiQIgLACIAACOQAHACALABIAWABQAVAAARgIQARgJAJgMQAHgKACgMQADgMgBgMQAAgWgJgOQgIgPgNgIQgNgIgOgEQgOgDgJAAIgKAAIgOABg");
	this.shape_3.setTransform(164.4,31.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABdCgIgdAAIg2gBIhVAAIgWAAIgRABIgLAAIgIABQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgMQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAEAAIASAAQAOAAAEgEQAEgEAAgMIAAhrIAAgrIAAgeIAAgfIgBgZIAAgMQgBgKgFgEQgFgDgMAAIgQAAIgDgBIgBgCIAAgMIABgCIACgBIAUABIAjABIAUAAIBCgBIBDAAIALAAIAHgBIACABIABACIAFANIAHAXIAHAYIAEAMIAAACIgBACIgHAEIgCAAIgBgCIgGgIIgNgQIgPgQIgLgLQgIgFgJgDQgJgEgJAAIhPgCIAACEIAKAAIASgBIATgBIAJgBQAKgBAEgEQAEgFADgKIACgJIACgNIABgCIACgBIALABIACABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBAPIAAAWIgBAOIABARIABARIABAMIAAADIgDABIgKABQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIgBgEIgCgLIgDgKQgCgHgEgFQgFgEgIgCIgWgBIgXgBIgOAAIAAAcIAAAdIABAeIAAASQABARAHAIQAHAIALACIAQACIAQABIAMAAIAPAAIANgBIALgCIAOgFQAIgEAGgFIAKgMIAQgTIALgQIACgDQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAHAEQABABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBAEIgYBCQgBADgCACQgCACgFAAIgKgBg");
	this.shape_4.setTransform(135.3,31.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("ACFCgIgXgBIgWABIgPABIgGgIIgHgKIgGgIIgGgKIgJgRIgKgQIgGgJIgHgLIgLgSIgJgNQgIgLgLgHQgLgHgTgBIgGABIgIABIAAAZIAAAXIAAAaIAAAWIABAMQAAAIADAFQADAFAEAAIAdAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIABADIAAAKIgBADQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgHgBIgSAAIghgBIggABIgRAAIgIABQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIAAgDIAAgKIAAgDIACgBIASAAQAJAAAEgDQAFgDAAgJIABhCIAAg/IAAgsIAAgtIgBgeQAAgLgDgFQgFgGgJAAIgSAAIgCgBIAAgCIAAgLIAAgDIACgBIAQABIApABIAcgBIAdAAIASgBQAaABAWAHQAVAHANANQALALAHAOQAGANAAANQAAAcgJASQgIARgTALQgSAJgdAGIAAABQAIADAEAFIAJAJIAIALIAMASIANASIAHALIAGAJIAMAQIANAQQAFAIAEACQAHAFAIACQAIABAJAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIAAADIAAAKIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgLgBgAg3iRIgHADQgCACgCAEQgCADABAGIAAB/IAJAAIALABQAegBATgHQATgJALgNQAKgMADgNQAFgMAAgHQgBgQgGgOQgGgNgKgJQgNgKgQgFQgSgFgbAAIgIAAg");
	this.shape_5.setTransform(105.2,31.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(3,1,1).p("A8DkrMA4HAAAIAAJXMg4HAAAg");
	this.shape_6.setTransform(179.6,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFCC").s().p("A8DEsIAApXMA4HAAAIAAJXg");
	this.shape_7.setTransform(179.6,30);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,362.1,82.1);


(lib.newtarget = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("AGFnzQAqgbATgsQATgtgMgqQgGgXgQgMQgLgMgbgEQg8gKgvAhQguAggMA+Qg+gPg8gGQgygGgzACQg3AAg1AKQADgXAMgkQAJgeAOgQQAUgVAygOQAlgNAUANQALALAIAYQAUBEAFAfAHImWQg8AYgTAdQgYAyAQAnQAPAjAoAPQAiAPAtgHQAAgzgOg6QgLgvgWgsQgMgXgPgWQgTgbgVgVQghgegngSAGtnDQg6AKgiAwQgaAjgEA7QAAA2ASAaQAQAaAtAdQAtAdBFgYAgBjCQgrgog5AGQg3AGgrAiQgbAUgIAYQgGAgASAdQAOAWAfAWQBRBBBzAfQBggwBBhPQAkgvAGgkQADgbgHgWQgKgYgVgLQgPgKgXgBQgPgCgaAEQhTALgaApgABuiVQgXAVgIAVAGHD5IgKgrQAAgGgCgEIgGgMQgEgRgFgHQgEgEgBgFQgCgFABgBQAAgCAsgrQAsgrAjh6QAMgoAHg2QADgXAAgYAmGn0QgNgNgFgUQgNgmAAgtQAAgpANgSQAVgdA7gEQAcAAAMAFQATAJASAaQAgAoAGAsQA7gOA3gIAmxnDQAQAAAUAGQALAEAcANQAiAPAYAVQAZAZAJAjQAJAigIAiQgOBCg/A8AmxnDQAWgeAVgTQAxgwA3gMAnEmjQAbAGAFACQAhALAWAXQAZAYAFAfQAEAbgHATQgGAYggAzQARAeARAhQAjBGAfBTQAbBMApCPQAEARAGATQDfAPDbgMQA3gDAagFQAegFAYgHQAGgDAGgBQAeAbARAjQALAYAVAzQAKAVAWAqQARAmAAAdQADAYgLAMQgLAUgPAHQgPAHhHgDAmoEEQgehChljpQgRgogHgUQgKghABgdQAAgdAMgbQAMgcAUgTQAPgPAQgHQAhhUAcgxQAKgSAJgOAoBkeQAUgKAXADQAXADAWAUQAOANASAcQAJANAIAPAhqiAQALAFAHAKQANAOAGATAnYLGQAAgRgCgLQgBgMABgFQACgIAKgNQAHgNAPgOQgWhSAAhMQgDhxAwhGQgDgGgEgKAjLEOQACAAADAAAnYLGQhEgPg+gTQj5hNAAhtQAAhuD5hNQBTgaBfgRAiSLuQAmgBAngDIACgVIB3gGQgGARAGARQgaAAgaAAQhKAAhIgDgAnYLGQCgAqCmgCAFmGKQASAWADAqIAMA/QAGAmACAYQAAAGAAAEQgBApgRAbQAQANAEAFQALAMACAMQACAEACAIQABACABADAGmLWQABACAPgLQgJABgJACQABADABADQhIAIhAAFIgUACQg/AGhdAEIgRABQgZAAgQABIAAABQAQgBAZgBAGHD5QB2AZBeAdQD5BNAABuQAABtj5BNQhOAYhXAR");
	this.shape.setTransform(85.2,75.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D9BBFF").s().p("ABWHqIh3AGIgBAVQgnADgmABQiygJiUgfIgCgcQgBgMABgFQACgIAJgNQAIgNAPgOQgXhSAAhMQgDhxAwhGIgHgQIiDkrQgRgogGgUQgLghACgdQAAgdALgbQANgcAUgTQAPgPAPgHQAVgKAWADQAYADAVAUQAOANATAcIARAcIAiA/QAjBGAeBUQAbBMApCOIAKAkIgEAAIAEAAQDgAPDagMQA3gDAbgFQAdgFAYgHIANgEQAeAbAQAjQAMAYAVAzIAfA/QARAmAAAdQAEAYgLAMQgMAUgPAHQgOAHhIgDQgBgYgGgmIgMg/QgEgqgSgWQASAWAEAqIAMA/QAGAmABAYIAAAKQAAApgRAbQAPANAFAFQALAMACAMIAEAMIABAFQhAALhGAIIgUACQg/AGhdAEIgRABIgpABQgFgRAFgRg");
	this.shape_1.setTransform(81.8,98.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF33CC").s().p("AirA4QgegWgPgWQgSgbAHghQAHgYAcgUQAqgiA4gGQA4gGAqAoQAcgpBTgLQAZgEAQACQAWABAQAKQAVALAJAYQAIAWgDAbQgGAkglAuQhBBQhfAwQhzgfhShCgAhSgRQANAOAHASQgHgSgNgOQgHgKgLgFQALAFAHAKgABVgLQAIgVAXgVQgXAVgIAVg");
	this.shape_2.setTransform(84.6,65.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#9966FF").s().p("AhZAPQAJgeAOgQQAUgUAygPQAmgNATANQALAMAJAXQAUBEAEAeQgygFgzABQg2ABg2AJQADgWAMgkg");
	this.shape_3.setTransform(85.7,7.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AmRBdQAhgzAFgXQAIgTgEgbQgGgfgYgYQgXgXghgLIgggHQAKgTAJgOQAQAAAVAHQALADAbANQAjAPAYAWQAZAZAJAiQAIAigHAiQgOBBhAA9IgihAgAFpCCQgtgcgQgbQgSgaAAg0QAFg7AZgkQAigwA7gKQAOAXANAXQg9AXgTAdQgYAyAQAnQAPAiAoAQQAiAPAtgHQAAAYgDAWQgfALgaAAQggAAgZgQg");
	this.shape_4.setTransform(87.7,45.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAAJKQhKAAhIgDQAmAAAngDIACgVIB3gHQgGARAGARIg0AAgAGiIlIgEgMQgCgMgLgMQgEgGgQgNQARgbABgoIAAgKQBHADAPgHQAPgIALgTQALgNgDgYQAAgcgRgmIgghAQgVgygLgZQgRgjgegbQB2AaBeAcQD5BOAABtQAABtj5BNQhOAYhXARIgSADIgCgEgApaH9Qj5hNAAhtQAAhtD5hOQBTgZBfgRIAHAPQgwBGADByQAABMAWBRQgPAPgHAMQgKANgCAIQgBAGABAMIACAbQhEgPg+gTgAmJmMQgSgbgOgOQgWgUgXgCQgXgDgUAKQAhhUAcgxIAgAHQAhALAWAXQAZAYAFAfQAEAcgHATQgGAXggAzIgRgcgAGol8QgogQgPgiQgQgoAYgyQATgdA8gXQAWArALAwQAOA6AAAzQgPACgNAAQgcAAgXgKg");
	this.shape_5.setTransform(85.2,92);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#8CCCFF").s().p("AjnHmIgKgkQgpiPgbhMQgfhUgjhGQA/g8AOhBQAIgigJgiQgJgjgZgZQgYgVgigPQgcgNgLgDQgUgHgQAAQAWgeAVgTQgNgNgFgUQgNgmAAgtQAAgpANgSQAVgdA7gDQAcAAAMAEQATAJASAaQAgApAGAsQA7gOA3gJQA1gKA4AAQAygBAyAFQA8AGA+APQAMg+AuggQAvggA8AKQAbADALAMQAQANAGAWQAMArgTAtQgTArgqAbQAVAVATAbQg6AKgiAwQgaAjgEA7QAAA2ASAaQAQAZAtAdQAtAdBFgYQgHA2gMAoQgjB7gsArQgsArAAACIABAGQABAFAEAEQAFAHAEARIAGAMQACAEAAAGIAKArIgMAEQgYAHgeAFQgaAFg3ADQhhAGhjAAQh6AAh8gJgAiGgMQg3AGgrAhQgbAUgIAYQgGAhASAcQAOAWAfAWQBRBCB0AfQBfgwBBhQQAkgvAGgkQADgbgHgWQgKgXgVgLQgPgKgXgBQgPgCgaAEQhSALgbAoQgmgigvAAIgPABgAFkkbQghgegngSQAnASAhAegAmnkcQAxgvA3gNQg3ANgxAvg");
	this.shape_6.setTransform(88.5,53.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(2,1,1).p("AGFnzQAqgbATgsQATgtgMgqQgGgXgQgMQgLgMgbgEQg8gKgvAhQguAggMA+Qg+gPg8gGQgygGgzACQg3AAg1AKQADgXAMgkQAJgeAOgQQAUgVAygOQAlgNAUANQALALAIAYQAUBEAFAfAGtnDQgTgbgVgVQghgegngSAHImWQgMgXgPgWQg6AKgiAwQgaAjgEA7QAAA2ASAaQAQAaAtAdQAMAHAOAEAHImWQg8AYgTAdQgYAyAQAnQAPAjAoAPQAHADAHACQANgVARgWQALgPAQgTQgCgOgEgPQgLgvgWgsgAHvkeQAVgYAeggQAYgaATgKQAagPAXAJQAjAOAFA/QANCMgoClQgeB5hOCnQAIAEgBADAgBjCQgrgog5AGQg3AGgrAiQgbAUgIAYQgGAgASAdQAOAWAfAWQBRBBBzAfQBggwBBhPQAkgvAGgkQADgbgHgWQgKgYgVgLQgPgKgXgBQgPgCgaAEQhTALgaApgABuiVQgXAVgIAVAF/DTIgCgFQAAgGgCgEIgGgMQgEgRgFgHQgEgEgBgFQgCgFABgBQAAgCAegeQAAgdAAgiQgDiDAZhEQABgCABgCQAKgbAQgdAF/DTQAEgnABg7AmGn0QgNgNgFgUQgNgmAAgtQAAgpANgSQAVgdA7gEQAcAAAMAFQATAJASAaQAgAoAGAsQA7gOA3gIAmxnDQAQAAAUAGQALAEAcANQAiAPAYAVQAZAZAJAjQAJAigIAiQgOBCg/A8AmxnDQAWgeAVgTQAxgwA3gMAnEmjQAbAGAFACQAhALAWAXQAZAYAFAfQAEAbgHATQgGAYggAzQARAeARAhQAjBGAfBTQAbBMApCPQAEARAGATQDfAPDbgMQA3gDAagFQAYgEAhgJIAAAAIgDABQABgBACAAAqpoGQgDAAgYgEQgPgDgIAGQgIAFgFAOQgHANACAMQADAKALALQAOAMAVAJQAMAFAbAJQASAFAlANQAMgFgEh1QgBgZgEgUQgBgGgEgFQgFgFgKAAQgOgBgNAKQgMAKgHAPQgJAWgDAKgAoBkeQAUgKAXADQAXADAWAUQAOANASAcQAJANAIAPAoBkeQAhhUAcgxQAKgSAJgOAoBkeQgrAWgRAsQgRAogDAuQgDBPAmBdQAYA5AoA/QAdAuAxBBAhqiAQALAFAHAKQANAOAGATAnYLGQAAgRgCgLQgBgMABgFQACgIAKgNQAHgNAPgOQgWhSAAhMQgDhxAwhGQgDgGAEgBAnYLGQhEgPg+gTQj5hNAAhtQAAhuD5hNQBTgaBngIAiSLuQAmgBAngDIACgVIB3gGQgGARAGARQgaAAgaAAQhKAAhIgDgAnYLGQCgAqCmgCAGFD5QABAAABAAIgBAAIgEABIAAAAIgEACQADgCAEgBQgDAAAAgJIAAAAQgBABgDALIAEgMIAAAAQgEgVABgIAGHD5QgDgEgCgFAGGD5IgEABAIfEeQg3BIgqBFIACAkQACAJABAMQAQByABA2QABAAACABAHDH8QgBAAAAAAIABAAgAGkLQQABADABADQABACAPgLQgJABgJACgAHUKMQACAjAIAJQABABABABQAFAFAFgGQAEgEgOAFQgGABgHADQgcALgTAHAIfEeQAjAJAZAIQD5BNAABuQAABtj5BNQhOAYhXARAHAHPIADAtQgOh8ALBPgAA0LxIAAABQAQgBAZgBQgZAAgQABgAGmLWQhIAIhAAFIgUACQg/AGhdAEIgRAB");
	this.shape_7.setTransform(85.2,75.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC0000").s().p("AAMBKIgmgOQgVgKgOgLQgLgLgDgKQgCgMAHgMQAFgOAIgFQAIgGAPADIAbAEIALggQAHgPAMgKQANgKAOABQAKAAAFAFQAEAFABAGQAEAUABAZQAEBzgMAFQglgMgSgFg");
	this.shape_8.setTransform(17.8,26);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#D9BBFF").s().p("AAIIYIh3AHIgBAVQgnADgmAAQinADifgrIgCgbQgBgMABgGQACgIAJgNQAIgMAPgPQgXhRAAhMQgDhyAwhGQgCgGADAAQgxhCgdgtQgng/gYg5QgnhdAEhPQADguAQgpQASgrAqgWQAVgKAWADQAYACAVAUQAOAOATAbIARAcIAiBAQAjBGAeBTQAbBNApCNIAKAlQDhAPDZgMQA3gEAbgFQAYgDAggKIgDABIADgBIAEgBIAEgBIACgBIgGgIIAAAAQgEgVABgIQAFgnAAg6IAAhAQgCiDAZhEIABgEQAKgbARgdQANgVAQgXIAcghIAzg5QAYgZASgKQAagPAXAJQAjAOAFA+QAOCNgpClQgdB6hPClQg2BJgqBEIACAlQgMhPAOB8IgCgtIADAVQAQByAAA2QADAjAHAIIACACIgMAFIgwARIADAGQhIAIhBAGIgUABQg/AGhdAFIgRAAIgpABQgFgRAFgRgAGUFHQgDABgBABQgBAAABAAQAAAAACgBQABAAADgCIABAAIAAAAIAAAAIgDABgAFWA6IAGAIIgCABQgEAAAAgJgAFcBCIAAAAg");
	this.shape_9.setTransform(89.6,93.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Al5BdQAggzAFgXQAIgTgEgbQgFgfgZgYQgXgXgggLIghgHQAKgTAKgOQAPAAAVAHQALADAcANQAiAPAYAWQAZAZAJAiQAIAigHAiQgOBBg/A9IgihAgAGBCCQgugcgPgbQgSgaAAg0QAEg7AZgkQAigwA7gKQAOAXANAXQg9AXgSAdQgYAyAQAnQAPAiAnAQIAPAFQgRAcgKAcQgNgEgMgIg");
	this.shape_10.setTransform(85.4,45.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAAJKQhKAAhIgDQAmAAAngDIACgVIB3gHQgGARAGARIg0AAgAHTIYIAMgFQADADADAAIAAAAIAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAAAIAAAAIABgBIAAAAQABgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIAAAAIgJACIgCAAIgCgCQgHgIgCgjIADABIgDgBQgBg2gQhyIgDgVIgCglQAqhEA3hJQAHAEAAADIAAAAIAAAAQAAgDgHgEIA8ARQD5BOAABtQAABtj5BNQhOAYhXARIgSADIAvgRgApaH9Qj5hNAAhtQAAhtD5hOQBTgZBngIQgEAAADAGQgwBGADByQAABMAWBRQgPAPgHAMQgKANgCAIQgBAGABAMIACAbQhEgPg+gTgAHlIWQgDAAgDgDIACAAIAJgCIAAAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAgBABIAAAAIgBABIAAAAQAAAAgBAAQAAABgBAAQAAAAgBABQAAAAgBAAIAAAAIAAAAgAHAFWIACAAIAAAAIgHADIAFgDgAmJmMQgSgbgOgOQgWgUgXgCQgXgDgUAKQAhhUAcgxIAgAHQAhALAWAXQAZAYAFAfQAEAcgHATQgGAXggAzIgRgcgAGol8QgogQgPgiQgQgoAYgyQATgdA8gXQAWArALAwIAGAdIgbAhQgRAWgMAWIgPgFg");
	this.shape_11.setTransform(85.2,92);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#8CCCFF").s().p("AjUHmIgKgkQgpiPgbhMQgfhUgjhGQA/g8AOhBQAIgigJgiQgJgjgZgZQgYgVgigPQgcgNgLgDQgUgHgQAAQAWgeAVgTQgNgNgFgUQgNgmAAgtQAAgpANgSQAVgdA7gDQAcAAAMAEQATAJASAaQAgApAGAsQA7gOA3gJQA1gKA4AAQAygBAyAFQA8AGA+APQAMg+AuggQAvggA8AKQAbADALAMQAQANAGAWQAMArgTAtQgTArgqAbQghgegngSQAnASAhAeQAVAVATAbQg6AKgiAwQgaAjgEA7QAAA2ASAaQAQAZAtAdQAMAHAOAEIgCAEQgZBEADCEIAAA/QgeAfAAABIABAGQABAFAEAEQAFAHAEARIAGAMQACAEAAAGIACAGQgBAHAEAVIAAABQAAAIADAAIACAAIgBAAIgEABIAAABIgEABIAHgDIgHADIAEgMIAAAAIAAAAIgEAMIAEgMIgEAMIAAAAQghAJgYAEQgaAFg3ADQhhAGhjAAQh5AAh9gJgAhzgMQg3AGgrAhQgbAUgIAYQgGAhASAcQAOAWAfAWQBRBCBzAfQBggwBBhQQAkgvAGgkQADgbgHgWQgKgXgVgLQgPgKgXgBQgPgCgaAEQhTALgaAoQgmgigvAAIgPABgAmUkcQAxgvA3gNQg3ANgxAvgAFwHUIAAAAgAFwHUIAAAAg");
	this.shape_12.setTransform(86.6,53.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_3},{t:this.shape_2},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,172.5,152.7);


// stage content:
(lib.ClickGame1JNones = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{Start:0,Game:10,GameOver:20});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		this.startBtn.addEventListener("click", fl_ClickStart.bind(this));
		
		function fl_ClickStart()
		{
			// Actions you want the button to do go here
			this.gotoAndStop("Game"); // jump to the frame with the label "Game"
		}
	}
	this.frame_10 = function() {
		// Storyboard for the game
		
		function hitTarget()
		{
			// Score increases by 1
			// Target disappears / moves to new location
			// Hit sound plays
			// Hit effect plays / appears
			// Time interval that the target appears is shortened
		}
		
		// Countdown Timer
		var secondsLeft = 15; // Creates a variable to store the seconds 
		// Text field with Instance name countdown_txt will display the seconds 
		this.countdown_txt.text = secondsLeft; 
		// Use the setInterval to call the countdown function every 1000 ms 
		var timerId = setInterval(countdown.bind(this), 1000); 
		function countdown() {
			if (secondsLeft == 0) {
				// doStuff such as end game
				clearInterval(timerId); // Should stop the timer 
				this.gotoAndStop("GameOver");
			} else {
				secondsLeft--; // reduce seconds by 1. Same as secondsLeft -= 1;
				this.countdown_txt.text = secondsLeft; // update the text field 
			}
		}
		
		var score = 0; // Create a variable to hold a number, set it to 0
		this.scoreDisplay.text = score;
		function increaseScore()
		{
			score += 1;
			this.scoreDisplay.text = score;
		}
		
		function random(min, max) {
			return Math.floor(Math.random()*(max-min+1)+min);
		};
		
		
		var moveInterval = 12; // Tenths of a second until target moves (12 = 2 sec)
		var moveTimer = setInterval(moveTarget.bind(this), 100);
		
		function moveTarget() {
			if (moveInterval <= 0) {
				// Randomly move target to a new location
				this.target.x = random(0, stage.canvas.width * 0.7);
				this.target.y = random(0, stage.canvas.height * 0.7);
				moveInterval = 12; // This could gradually be lowered
			} else {
				moveInterval--;
			}
		}
		
		this.target.addEventListener("click", hitTarget.bind(this));
		
		function hitTarget()
		{
			// Score increases and updates scoreDisplay text on screen
			this.increaseScore(); 
			// Target disappears / moves to new location
			moveInterval = 0;
		}
		
		var _this = this;
		var score = 0; // Create a variable to hold a number, set it to 0
		
		this.increaseScore = function() {
			score += 1;
			this.scoreDisplay.text = score;
		}
	}
	this.frame_20 = function() {
		this.replayBtn.addEventListener("click", fl_ClickReplay.bind(this));
		
		function fl_ClickReplay()
		{
			// Actions you want the button to do go here
			this.gotoAndStop("Start"); // jump to the frame with the label "Game"
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10).call(this.frame_20).wait(10));

	// Directions
	this.startBtn = new lib.StartBtn();
	this.startBtn.name = "startBtn";
	this.startBtn.parent = this;
	this.startBtn.setTransform(770.2,514.2,1,1,0,0,0,160.2,120);
	new cjs.ButtonHelper(this.startBtn, 0, 1, 1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgGBnQgEgCgDgEQgEgDAAgHIACgHQABgEAEgDQAFgDAGAAQAHAAAFAFQAFAEAAAJQAAAHgFAFQgFAEgHAAIgHgBgAgCAnIgCgBIAAgCIgBgXIgCgcIgDgeIgCgaIgBgPQAAgHAEgFQAEgFAFAAQAHAAAEAEQAFAEAAAJIgCANIgCAZIgDAgIgDAeIgBAXIgBABIgCABg");
	this.shape.setTransform(137.2,417.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgIBNQgGgEgEgGQgEgFAAgGIAAgQIAAgRIAAgKIAAgHIABgIIAAgPIAAgOIgSAAIgEgBIgBgDIACgDIAEgCQAEgCAHgHIAOgPQAGgIADgGIABgCIADAAIABABIABADIgCAdIAqAAIACABIAAACIgDALIgBABIgCABIgmAAIAAAVIAAAUIAAAeQAAALACAGQADAGADACQAEACACAAIALgBQAGgBADgCIACgBIACABIABADQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABIgGAFQgFADgHACQgGACgJAAQgHAAgHgEg");
	this.shape_1.setTransform(129,420.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgaA/QgIgDgHgJQgGgIgCgHQgDgHAAgKIgBgaIAAgjQAAgGgDgCQgDgDgFAAIgFgBIgCgBIAAgGIABgCIADAAIAaAAIADAAIABgBIACAAIACAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIgBALIAAAXIAAAWIgBANIABAPQACAJAEAHQAGAHAGACQAGACAGAAQAGAAAHgFQAIgEAEgGIACgEIABgEIAAhHQAAgGgDgCQgEgCgGAAIgFgBIgBgBIAAgFIAAgDIADAAIAcAAIADAAIACgBIACAAIACAAIACABIABACIgBAFIgBAMIAAAXIAAAVIAAAVIAAAPQABAHACABQACACADAAIAEAAIAGgBIADAAIABABIABAEIgBACIgBABIgfALIgDAAIgDABIgCgBIgBgDIgCgRIgBAAQgHAJgLAGQgKAFgMABIgCAAQgFAAgGgCg");
	this.shape_2.setTransform(116.3,421.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_3.setTransform(101.2,421.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgXA/QgHgDgEgDIgBgBIAAgDIgGgdIABgBIABgBIAFgBQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAHAPIAHAKQADADAEADQAEACAIABQAFgBAFgCQAGgCADgEQAEgFAAgHQABgKgHgGQgGgHgQgEQgJgDgIgEQgIgEgFgIQgFgHAAgMQAAgKAFgIQAHgIAJgFQAKgFAKAAQAKAAAHACIAKAEIAFADIABADIAEAVIgBABIgBABIgDABIgCAAIgBgBIgLgNQgCgGgFgDQgFgEgIAAQgFAAgFADQgGACgDAEQgDAFgBAHQABAIAEAEQAEAFAHADIAMAEQARAFAJAHQAKAIAAASQAAALgGAKQgGAJgKAEQgKAFgMAAQgLgBgJgCg");
	this.shape_4.setTransform(490.4,368.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AA8BAIgUAAIgSAAIgJABIgCgBIAAgDIAAgEIABgDIADAAIAIAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIABgNIAAgMIAAgnIgBgQQgBgGgHgFQgFgEgFAAIgLgBIgKACQgHACgHAIQgEAEgCAGIgBAKIAAA9IABAIQACACAEAAIAIAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIABACIAAAFIAAACIgCABIgIgBIgSAAIgTAAIgIABQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIgBgCIAAgFIABgCQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAJAAIAEgBQACgBAAgEIAAhFQAAgHgEgEQgDgEgGgDIgCgBIgCgCIAAgBIAAgBIAAgCIACgBIAagPIADgBIACgBIACABIABADIACASIABAAQAGgJAMgGQALgHALAAIANACQAHABAFAEQAFADADAFQAEAFACAGQADAFAAAEIAABMQAAAEABABQACACADAAIAKAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIABACIAAAEIgBADQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgJgBg");
	this.shape_5.setTransform(477.3,368.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgaA/QgIgDgHgJQgGgIgCgHQgDgHAAgKIgBgaIAAgjQAAgGgDgCQgDgDgFAAIgFgBIgCgBIAAgGIABgCIADAAIAaAAIADAAIABgBIACAAIACAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIgBALIAAAXIAAAWIgBANIABAPQACAJAEAHQAGAHAGACQAGACAGAAQAGAAAHgFQAIgEAEgGIACgEIABgEIAAhHQAAgGgDgCQgEgCgGAAIgFgBIgBgBIAAgFIAAgDIADAAIAcAAIADAAIACgBIACAAIACAAIACABIABACIgBAFIgBAMIAAAXIAAAVIAAAVIAAAPQABAHACABQACACADAAIAEAAIAGgBIADAAIABABIABAEIgBACIgBABIgfALIgDAAIgDABIgCgBIgBgDIgCgRIgBAAQgHAJgLAGQgKAFgMABIgCAAQgFAAgGgCg");
	this.shape_6.setTransform(461.4,368.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAJBBIgVAAIgXAAIgKABIgBgBIAAgDIAAgEQgBgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIADgBIAMAAQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBIAAgQIAAgUIAAgbIAAgMIgEgGIgGgFIgGgDIgCgBIAAgBIAAgCIAAgCIACgBIAegPIACgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIABADIABAVIACAAQAFgLAKgIQAKgHAKgBQAHAAAEAFQAEAEAAAFQgBAGgDAFQgEADgFAAIgEgBIgEgBIgFgBIgFgBQgEAAgFADQgFACgDAHIgCAGIgBAEIAAA9QAAAHACADQABACAEAAIAOAAIACACIABACIAAAEIgBADIgBABIgKgBg");
	this.shape_7.setTransform(449,368.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_8.setTransform(429.7,368.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("ABmBAIgRAAIgTAAIgJABIgDgBIAAgCIAAgFIABgDIADAAIAIAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBIABgMIAAgMIAAgrQAAgIgCgGQgBgGgGgFQgDgDgHgBQgFgCgGAAQgIAAgIAFQgHAEgEAHQgDAGAAAHIgBARIAAAzQAAADACACQAAAAAAABQABAAAAAAQABABAAAAQABAAABAAIAKAAIADAAIABADIAAAEIgBADIgBABIgIgBIgTAAIgTAAIgJABIgBgBIgBgCIAAgFIABgDIADAAIAIAAIAFgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAg9IgBgRQgBgHgCgDIgEgFQgDgDgGgBIgLgCQgFAAgIAEQgJAEgGAKIgEAJIgBALIAAA6QAAAEACACQAAAAABABQAAAAABAAQAAABABAAQABAAAAAAIALAAIADAAIABADIAAAEIgBADIgCABIgJgBIgTAAIgTAAIgJABIgBgBIgBgCIAAgFIABgDIADAAIAKAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABgBIABgGIAAgHIAAgIIAAg1QAAgEgBgEQgCgEgGgDIgGgDIgCgBIAAgCIAAgCIABgBIABgBIAagOIAEgBIACgBQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAADIACARIABAAQAHgKAMgGQALgHAOAAQAMAAAJAGQAHAGAEALIACAAQAHgJAMgHQAMgHANAAQAJAAAGACQAHACAFAFIAHAIQADAEADAHQACAHAAALIAABCQAAABAAAAQAAABAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQABABABAAQAAAAABAAIAIAAIADAAIABADIAAAFIgBACIgCABIgHgBg");
	this.shape_9.setTransform(411.2,368.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAZBiIgLAAIgNAAIgUAAIgKABIgDgBIAAgCIAAgGIAAgCIADgBIAOAAIAEgBIACgEIAAgOIAAgNIAAgtQAAgHgDgDQgDgFgLgBIgCgBIgBgCIAAgDIABgBIABgBIAQgGIAPgJIAEgBIACAAIABABIAAADIAAARIAAAeIAAAhIAAAQIAAAKIACAGQAAAAABABQAAAAAAAAQABAAAAAAQABAAABAAIANAAQABAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIAAACIAAAEIAAADIgDABIgFgBgAgOhDQgEgCgCgDQgEgEAAgFQABgGAEgFQAFgGAJABQAHgBAFAGQADAFAAAFQAAAGgDAGQgFAGgJAAQgDAAgEgDg");
	this.shape_10.setTransform(395.1,365.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgIBNQgGgEgEgGQgEgFAAgGIAAgQIAAgRIAAgKIAAgHIABgIIAAgPIAAgOIgSAAIgEgBIgBgDIACgDIAEgCQAEgCAHgHIAOgPQAGgIADgGIABgCIADAAIABABIABADIgCAdIAqAAIACABIAAACIgDALIgBABIgCABIgmAAIAAAVIAAAUIAAAeQAAALACAGQADAGADACQAEACACAAIALgBQAGgBADgCIACgBIACABIABADQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABIgGAFQgFADgHACQgGACgJAAQgHAAgHgEg");
	this.shape_11.setTransform(386.6,367.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_12.setTransform(367.6,368.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AA/BsIgUAAIgTAAIgJABIgCgBIgBgCIAAgGIAAgCIACAAIAHAAIAHgBQAEgBAAgEIABgHIAAgMIgBgKIAAgZQABgMgCgJQgCgJgHgHQgEgDgFgCQgFgCgFAAQgGAAgHADQgIADgGAGIgEAGQgCAFAAADIAABCIABAKQABACAEAAIAJAAIADAAIABACIAAAGIgBACIgCABIgKgBIgSAAIgTAAIgKABIgCgBIAAgCIAAgGIABgCIADAAIAGAAIAHgBQADgBAAgDIABgJIAAgOIAAgSIAAgRIAAhZQAAgKgBgEQgBgFgEgCQgDgDgFgCIgFgBIgCgBIAAgBIAAgDIAAgCIADgBIAfgRIAEgBIADgBQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAQABACAAAEIgBAJIAAARIAAAVIAAAUIAAAOIAAATIABAAQAIgJAMgGQAKgEAKAAQAKAAAHACQAHADAGAGQAHAHACAGQADAHABAHIAAAQIAAASIAAARIAAAOIABAJQAAABAAABQAAAAABABQAAAAAAAAQABABABAAIAIABIAFAAIACAAQAAABABAAQAAAAAAAAQAAABAAAAQAAABAAAAIAAAEIAAADIgCABIgJgBg");
	this.shape_13.setTransform(353.1,364.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgIBNQgGgEgEgGQgEgFAAgGIAAgQIAAgRIAAgKIAAgHIABgIIAAgPIAAgOIgSAAIgEgBIgBgDIACgDIAEgCQAEgCAHgHIAOgPQAGgIADgGIABgCIADAAIABABIABADIgCAdIAqAAIACABIAAACIgDALIgBABIgCABIgmAAIAAAVIAAAUIAAAeQAAALACAGQADAGADACQAEACACAAIALgBQAGgBADgCIACgBIACABIABADQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABIgGAFQgFADgHACQgGACgJAAQgHAAgHgEg");
	this.shape_14.setTransform(340.5,367.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_15.setTransform(321.5,368.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AAJBBIgVAAIgXAAIgKABIgBgBIAAgDIAAgEQgBgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIADgBIAMAAQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBIAAgQIAAgUIAAgbIAAgMIgEgGIgGgFIgGgDIgCgBIAAgBIAAgCIAAgCIACgBIAegPIACgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIABADIABAVIACAAQAFgLAKgIQAKgHAKgBQAHAAAEAFQAEAEAAAFQgBAGgDAFQgEADgFAAIgEgBIgEgBIgFgBIgFgBQgEAAgFADQgFACgDAHIgCAGIgBAEIAAA9QAAAHACADQABACAEAAIAOAAIACACIABACIAAAEIgBADIgBABIgKgBg");
	this.shape_16.setTransform(310.1,368.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_17.setTransform(297.2,368.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AACBsIgZAAIgQAAIgMAAIgGABIgCgBIAAgBIAAgHIAAgCIACAAIAPAAQAEAAABgCQACgDAAgFIAAg5IAAghIgVAAIgBAAIAAgEIABgJIABgBIADgBIARAAIAAgFQAAgWAGgPQAFgPAJgKQAMgNAMgFQALgGANAAQAHAAAHACQAGACAEAEQADAEAAAFQABAGgFADQgEAEgEAAIgFgBIgEgBIgDgDIgEgEQgDgDgDgCQgDgBgEAAQgHgBgFADQgGACgEAGQgGAHgCAKQgCALAAALIAAAWIAAAFIAjAAIACABIAAACIgCALIAAABIgDAAIggAAIAAAaIAAAgIAAAYIAAAKQAAAEABACQACACAFAAIAQAAIACAAIABACIAAAFIgBADIgBABIgKgBg");
	this.shape_18.setTransform(287.2,364.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_19.setTransform(274.2,368.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgOBsQgIgCgFgEIgNAHIgBABIgCAAIgDgBIgCgBIAAgBIAAgLIAAgSIAAgWIAAhuIgBgPQgBgGgDgCQgDgDgFgCIgDgBIgEgBIgBgBIAAgDIABgBIACgBIALgFIALgGIAKgFIADgCIADgBQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAIAAAMIgBAYIAAAbIAAAjQAIgHALgEQAKgEALAAQAOAAAMAHQANAHAIAOQAIAOABAVQgBASgIAPQgJAQgOAJQgOAKgRAAQgLAAgKgCgAgNgEQgHADgGAEIAAAnIABAUIABAOIADAKQACAFAIAFQAIAEAJABQAKAAAJgFQAIgFAHgLQAGgLAAgUQABgPgGgNQgFgMgKgIQgJgHgQgBQgHAAgHADg");
	this.shape_20.setTransform(259.5,364.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_21.setTransform(238.7,368.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgIA/IgCgEIgDgHIgFgPIgHgQIgGgPIgDgHIgCgHIgFgMIgFgOIgDgJIgFgIQgDgCgEgBIgGAAIgCgBIAAgBIAAgGIABgCIACgBIAIABIARAAIATAAIAIgBIADABIAAACIAAAGIAAABIgCABIgGAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAABIABAHIADAKIADALIADAHIADAJIAFANIAGAOIADAJIAAAAIAHgPIAJgVIAIgXIAFgOQACgHgCgDQgBgDgEgBIgGAAIgBgBIAAgBIAAgGIAAgCIABgBIAJABIAPAAIAPAAIAHgBIACABIABACIAAAGIAAACIgCAAIgFAAIgFABIgFADQgCABgDAGIgHAPIgHAPIgFALIgFAMIgJAVIgJATIgEAJIgCAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBgBQgBAAAAAAQgBAAAAgBQAAAAgBgBg");
	this.shape_22.setTransform(225.8,368.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_23.setTransform(211.6,368.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAXBsIgXAAIgWAAIgLABIgCgBIAAgCIAAgFIABgDIADAAIAOAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABAAQACgDAAgEIAAgNIAAgXIAAgYIAAgSIAAgSIAAgWIAAgUIAAgOQgBgIgEgDQgDgFgIgCIgFgCIgCAAIgBgBIAAgDIABgBIADgBIARgIQAJgEAIgGIADgBIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAAAFIAAATIgBAcIAAAdIAAATIAAAZIAAARIAAAVIAAAUIAAANIACAHQABACAFAAIAOAAQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABACIAAAFIgBACIgBABIgLgBg");
	this.shape_24.setTransform(200.4,364.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAJBBIgVAAIgXAAIgKABIgBgBIAAgDIAAgEQgBgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIADgBIAMAAQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBIAAgQIAAgUIAAgbIAAgMIgEgGIgGgFIgGgDIgCgBIAAgBIAAgCIAAgCIACgBIAegPIACgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIABADIABAVIACAAQAFgLAKgIQAKgHAKgBQAHAAAEAFQAEAEAAAFQgBAGgDAFQgEADgFAAIgEgBIgEgBIgFgBIgFgBQgEAAgFADQgFACgDAHIgCAGIgBAEIAAA9QAAAHACADQABACAEAAIAOAAIACACIABACIAAAEIgBADIgBABIgKgBg");
	this.shape_25.setTransform(184.1,368.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_26.setTransform(172.4,368.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AA/BsIgUAAIgTAAIgJABIgCgBIgBgCIAAgGIAAgCIACAAIAHAAIAHgBQAEgBAAgEIABgHIAAgMIgBgKIAAgZQABgMgCgJQgCgJgHgHQgEgDgFgCQgFgCgFAAQgGAAgHADQgIADgGAGIgEAGQgCAFAAADIAABCQAAAHABADQABACAEAAIAJAAIADAAIABACIAAAGIgBACIgCABIgKgBIgSAAIgTAAIgKABIgCgBIAAgCIAAgGIABgCIADAAIAGAAIAHgBQADgBAAgDIABgJIAAgOIAAgSIAAgRIAAhZQAAgKgBgEQgBgFgEgCQgDgDgFgCIgFgBIgCgBIAAgBIAAgDIAAgCIADgBIAfgRIAEgBIADgBQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAQABACAAAEIgBAJIAAARIAAAVIAAAUIAAAOIAAATIABAAQAIgJAMgGQAKgEAKAAQAKAAAHACQAHADAGAGQAHAHACAGQADAHABAHIAAAQIAAASIAAARIAAAOIABAJQAAABAAABQAAAAAAABQABAAAAAAQABABABAAIAIABIAFAAIACAAIABADIAAAEIAAADIgCABIgJgBg");
	this.shape_27.setTransform(157.9,364.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_28.setTransform(135.8,368.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgIA/IgCgEIgDgHIgFgPIgHgQIgGgPIgDgHIgCgHIgFgMIgFgOIgDgJIgFgIQgDgCgEgBIgGAAIgCgBIAAgBIAAgGIABgCIACgBIAIABIARAAIATAAIAIgBIADABIAAACIAAAGIAAABIgCABIgGAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAABIABAHIADAKIADALIADAHIADAJIAFANIAGAOIADAJIAAAAIAHgPIAJgVIAIgXIAFgOQACgHgCgDQgBgDgEgBIgGAAIgBgBIAAgBIAAgGIAAgCIABgBIAJABIAPAAIAPAAIAHgBIACABIABACIAAAGIAAACIgCAAIgFAAIgFABIgFADQgCABgDAGIgHAPIgHAPIgFALIgFAMIgJAVIgJATIgEAJIgCAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBgBQgBAAAAAAQgBAAAAgBQAAAAgBgBg");
	this.shape_29.setTransform(122.9,368.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AAZBiIgLAAIgMAAIgVAAIgLABIgCgBIAAgCIAAgGIAAgCIADgBIAOAAIAEgBIACgEIAAgOIAAgNIAAgtQAAgHgDgDQgDgFgLgBIgCgBIgBgCIAAgDIABgBIABgBIAPgGIAQgJIAEgBIADAAIAAABIAAADIAAARIAAAeIAAAhIAAAQIAAAKIACAGQAAAAABABQAAAAAAAAQABAAAAAAQABAAABAAIANAAQABAAAAABQAAAAABAAQAAAAAAAAQAAAAAAABIABACIAAAEIgBADIgCABIgFgBgAgOhDQgEgCgDgDQgDgEAAgFQABgGAEgFQAFgGAJABQAHgBAFAGQAEAFAAAFQAAAGgEAGQgFAGgJAAQgDAAgEgDg");
	this.shape_30.setTransform(112.4,365.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AggBnQgMgCgLgFQgIgGgDgGQgEgFAAgIQAAgIAFgIQAFgGAHgFIAOgJIAAgBQgJgCgFgGQgFgGgBgHQABgHAEgGQAFgFAGgDQAGgEAFgDIAAAAQgGgDgGgGQgGgFgFgJQgEgKAAgNQAAgJAFgKQAGgLALgGQAMgHARAAQAKAAAIAEQAIADAEAEIAGAGIAOgIQAHgDAIAAQAHAAAEADQADAEAAAFQAAAEgDAEQgEADgFAAQgEAAgCgCIgEgDIgDgBIgEgBIgEAAIgFACIADAJQABAGAAAHQAAAJgCAJQgDAIgGAHQgEAEgGAEIgNAFQgGACgFAAIgIAAIgHgBIgHADIgGAGQgDACAAAEQAAAGAFACQAEADAIAAIASAAQASgCAMADQAMACAJAIQAJAGADAIQADAJAAAFQAAAKgFAJQgEAKgMAIQgGAEgNAFQgNAEgSABIgXgCgAAAAkIgcABQgFABgFAFQgGADgEAGQgEAGAAAIQAAAGAEAGQADAGAFADQAHAFAJACQAKACAPAAIALgCIAPgFQAHgEAFgGQAFgGgBgJQAAgNgKgIQgJgIgSAAIgGABgAgRhfQgFACgFAFQgHAJgCAJQgDAJABAJQAAAHACAIQADAGAEAFQAEAEAFACQAEABAFABQAKAAAFgIQAGgHADgKQACgKAAgJQAAgKgCgHQgCgGgEgEIgHgFQgDgCgDAAIgLABg");
	this.shape_31.setTransform(101.2,372.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_32.setTransform(479,315.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgIBNQgGgEgEgGQgEgFAAgGIAAgQIAAgRIAAgKIAAgHIABgIIAAgPIAAgOIgSAAIgEgBIgBgDIACgDIAEgCQAEgCAHgHIAOgPQAGgIADgGIABgCIADAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIABADIgCAdIAqAAIACABIAAACIgDALIgBABIgCABIgmAAIAAAVIAAAUIAAAeQAAALACAGQADAGADACQAEACACAAIALgBQAGgBADgCIACgBIACABIABADQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABIgGAFQgFADgHACQgGACgJAAQgHAAgHgEg");
	this.shape_33.setTransform(467.2,314.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AA8BAIgUAAIgSAAIgJABIgCgBIAAgDIAAgEIABgDIADAAIAIAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIABgNIAAgMIAAgnIgBgQQgBgGgHgFQgFgEgFAAIgLgBIgKACQgHACgHAIQgEAEgCAGIgBAKIAAA9IABAIQACACAEAAIAIAAIACABIABACIAAAFIAAACIgCABIgIgBIgSAAIgTAAIgIABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIgBgCIAAgFIABgCIACgBIAJAAIAEgBQACgBAAgEIAAhFQAAgHgEgEQgDgEgGgDIgCgBIgCgCIAAgBIAAgBIAAgCIACgBIAagPIADgBIACgBIACABIABADIACASIABAAQAGgJAMgGQALgHALAAIANACQAHABAFAEQAFADADAFQAEAFACAGQADAFAAAEIAABMQAAAEABABQACACADAAIAKAAIACABIABACIAAAEIgBADQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgJgBg");
	this.shape_34.setTransform(446.7,315.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AATA9QgGgGgCgJIgBAAQgEAGgHAEQgHAFgKADIgJABIgJABQgEAAgEgCQgEgDgDgFQgDgGAAgJQAAgKAGgJQAHgJARgIIAOgGIALgGIAIgEIAAgTIgBgJQgBgGgCgCQgDgDgDgCQgFgCgGAAIgLABQgFADgEADQgDACABADIABAIQAAAIgEAFQgDAEgJAAQgEAAgCgCQgBgDAAgFQAAgHAFgIQAGgHAJgGQAKgFAIgDQAJgCAJAAQAKAAAGACQAFADADADQAEAFACAFIABALIAAAtIAAASQAAANACAEQACAFAEAAQAEAAADgCIAEgDIABgBIACAAIADADIABACQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAABIgEAFQgDADgEADQgFADgIAAQgIAAgFgFgAgBACIgOAIQgGAEgFAGQgEAGgBAJQABAJAEAEQAEAEAHAAQAEAAAGgDIAJgHQAEgFABgDIAAgkIgKAEg");
	this.shape_35.setTransform(432.7,315.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgSA+QgMgEgKgNQgIgLgDgKQgDgKAAgKQABgRAHgQQAIgQAOgKQAPgKATAAQAPAAAJAFQAJAEAEAGQAEAGgBADQAAAFgDADQgDADgFAAQgFAAgEgEQgEgDgDgGQgFgIgFgDQgFgCgFAAQgIAAgIAFQgIAGgFAKQgFAKgBAQQABALAEAMQAEANAHAIQAHAKAJADQAHADAIAAQALAAAIgDQAHgDAHgHIABgBIACABIADADIABABIgBADQgFAFgHAEQgIAFgJADQgJAEgLAAIgCAAQgKAAgLgEg");
	this.shape_36.setTransform(419.9,315.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgaA/QgIgDgHgJQgGgIgCgHQgDgHAAgKIgBgaIAAgjQAAgGgDgCQgDgDgFAAIgFgBIgCgBIAAgGIABgCIADAAIAaAAIADAAIABgBIACAAIACAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIgBALIAAAXIAAAWIgBANIABAPQACAJAEAHQAGAHAGACQAGACAGAAQAGAAAHgFQAIgEAEgGIACgEIABgEIAAhHQAAgGgDgCQgEgCgGAAIgFgBIgBgBIAAgFIAAgDIADAAIAcAAIADAAIACgBIACAAIACAAIACABIABACIgBAFIgBAMIAAAXIAAAVIAAAVIAAAPQABAHACABQACACADAAIAEAAIAGgBIADAAIABABIABAEIgBACIgBABIgfALIgDAAIgDABIgCgBIgBgDIgCgRIgBAAQgHAJgLAGQgKAFgMABIgCAAQgFAAgGgCg");
	this.shape_37.setTransform(398.1,315.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_38.setTransform(383,315.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("Ag/BkQgEgFAAgGQAAgFAEgDQAEgEAGAAIAIABIAFADIAEgBIADgCIAFgIIAHgOIAHgRIAFgLIgEgOIgJgZIgKgeIgIgaIgFgMIgFgJQgDgEgGAAIgIAAIgCgBIAAgCIAAgGIAAgBIACgBIAIAAIAUABIASgBIAKAAIACABIAAABIAAAGIAAACIgBABIgGAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAIAAAFIADALIAFASIAHAWIAFATIAEAKIABAAIAEgIIAHgSIAJgUIAHgSIAEgKQABgGgBgDQgCgDgDAAIgFAAIgCgBIAAgCIAAgGIAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAIAQABIALgBIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAABIAAAGIAAACIgBABIgFAAIgFABIgGAFIgKATIgRAkIgUAsIgMAgIgLAYIgIAPIgEAJQgDAFgFADQgFADgIAAQgJAAgEgEg");
	this.shape_39.setTransform(369.2,319.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgWA+QgJgDgCgCIgCgCIgBgCIgEgcIAAgCIACgBIADAAQABgBAAAAQABAAAAABQAAAAAAAAQABAAAAABIAIAOIAFAKQADAEAFADQAFACAGAAQAGAAAGgCQAFgCAEgFQADgEAAgHQAAgKgGgHQgGgGgQgFQgJgCgIgFQgIgDgFgIQgFgHAAgLQAAgLAGgIQAFgIAKgFQAJgFALAAQALAAAGACIALAEIADADIACACIAFAVIgBACIgCACIgEABIgBAAIgBgCIgKgOQgDgEgFgEQgEgDgJAAQgFgBgGADQgEACgEAFQgDAEAAAGQAAAJADAFQAFAEAGACIAOAFQAQAFAKAHQAJAIAAARQAAANgGAIQgGAKgKAEQgLAFgLAAQgLgBgIgDg");
	this.shape_40.setTransform(349.6,315.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AggBoQgMgCgLgHQgIgFgDgFQgEgHAAgHQAAgIAFgHQAFgHAHgGIAOgIIAAgBQgJgCgFgGQgFgGgBgHQABgHAEgGQAFgEAGgFQAGgDAFgCIAAgBQgGgDgGgFQgGgGgFgJQgEgKAAgNQAAgKAFgKQAGgJALgHQAMgHARAAQAKAAAIADQAIAEAEAEIAGAGIAOgIQAHgEAIAAQAHABAEAEQADADAAAFQAAAFgDADQgEADgFAAQgEAAgCgBIgEgDIgDgCIgEgBIgEAAIgFACIADAKQABAFAAAHQAAAKgCAIQgDAIgGAHQgEAEgGAEIgNAFQgGACgFAAIgIgBIgHgBIgHAEIgGAFQgDADAAAEQAAAHAFACQAEACAIAAIASgBQASAAAMACQAMADAJAGQAJAHADAIQADAJAAAFQAAALgFAJQgEAIgMAJQgGAEgNAFQgNAEgSABIgXgBgAAAAjIgcADQgFABgFADQgGAEgEAGQgEAGAAAJQAAAFAEAGQADAFAFAEQAHAFAJACQAKACAPgBIALgBIAPgGQAHgDAFgGQAFgGgBgIQAAgOgKgJQgJgHgSAAIgGAAgAgRheQgFABgFAGQgHAHgCAKQgDAJABAJQAAAIACAGQADAHAEAFQAEAEAFACQAEABAFAAQAKAAAFgGQAGgIADgJQACgKAAgKQAAgKgCgGQgCgHgEgEIgHgFQgDgCgDAAIgLACg");
	this.shape_41.setTransform(337.1,319.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AA8BAIgUAAIgSAAIgJABIgCgBIAAgDIAAgEIABgDIADAAIAIAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIABgNIAAgMIAAgnIgBgQQgBgGgHgFQgFgEgFAAIgLgBIgKACQgHACgHAIQgEAEgCAGIgBAKIAAA9IABAIQACACAEAAIAIAAIACABIABACIAAAFIAAACIgCABIgIgBIgSAAIgTAAIgIABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIgBgCIAAgFIABgCIACgBIAJAAIAEgBQACgBAAgEIAAhFQAAgHgEgEQgDgEgGgDIgCgBIgCgCIAAgBIAAgBIAAgCIACgBIAagPIADgBIACgBIACABIABADIACASIABAAQAGgJAMgGQALgHALAAIANACQAHABAFAEQAFADADAFQAEAFACAGQADAFAAAEIAABMQAAAEABABQACACADAAIAKAAIACABIABACIAAAEIgBADQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgJgBg");
	this.shape_42.setTransform(321.9,315.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AATA9QgGgGgCgJIgBAAQgEAGgHAEQgHAFgKADIgJABIgJABQgEAAgEgCQgEgDgDgFQgDgGAAgJQAAgKAGgJQAHgJARgIIAOgGIALgGIAIgEIAAgTIgBgJQgBgGgCgCQgDgDgDgCQgFgCgGAAIgLABQgFADgEADQgDACABADIABAIQAAAIgEAFQgDAEgJAAQgEAAgCgCQgBgDAAgFQAAgHAFgIQAGgHAJgGQAKgFAIgDQAJgCAJAAQAKAAAGACQAFADADADQAEAFACAFIABALIAAAtIAAASQAAANACAEQACAFAEAAQAEAAADgCIAEgDIABgBIACAAIADADIABACQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAABIgEAFQgDADgEADQgFADgIAAQgIAAgFgFgAgBACIgOAIQgGAEgFAGQgEAGgBAJQABAJAEAEQAEAEAHAAQAEAAAGgDIAJgHQAEgFABgDIAAgkIgKAEg");
	this.shape_43.setTransform(307.9,315.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("ACFBrIgMAAIgZgBIgeABIgNAAIgCgBIAAgCIAAgHIAAgBIACgBIAVAAQAEABACgDQACgCAAgGIAAgLIABgVIAAgZIAAgVIAAgTIAAgTIAAgZIgBgVIAAgKIgBAAIgGALIgLAZIgOAdIgLAYIgFALIgEAKIgJAUIgKAXIgJAUIgDAKIgDAEQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgCgEIgDgHIgHgTIgKgXIgJgYIgIgSIgEgIIgFgOIgJgVIgJgWIgJgTIgFgJIAAAKIgBAVIAAAXIAAAUIAAAKIAAAIIAAARIAAAVIAAATIAAAMQABAMADAFQADAFAHgBIAPAAIACABIAAABIAAAIIAAACIgDAAIgFAAIgLAAIgUgBIgcABIgLAAIgCAAIAAgDIAAgHIAAgBIABgBIAQAAQAJAAADgFQADgFABgIIACgSIABgaIABgaIABgVIAAgLIAAgKIAAgRIAAgTIgBgMIAAgGQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgDgBgGAAIgSAAIgCgBIAAgBIAAgIIAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAFAAIALABIAUAAIARgBIAJAAIAFABQACABABADIBBCfIAGgJIAIgUIAKgWIAJgSIAEgKIAEgJIAJgTIAKgXIAJgTIAEgKQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBIAFAAIAeAAIAQgBIAHAAIABABIABABIAAAHIgBACIgCABIgNAAQgGAAgCADQgCAEAAAFIAAAMIAAATIgBAWIAAATIAAAUIAAAQIABAWIAAAUIAAALQAAAJACAEQADADAFAAIASAAIACABIAAABIAAAHIAAACIgDABIgFAAg");
	this.shape_44.setTransform(285.8,311.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("Ag/BkQgEgFAAgGQAAgFAEgDQAEgEAGAAIAIABIAFADIAEgBIADgCIAFgIIAHgOIAHgRIAFgLIgEgOIgJgZIgKgeIgIgaIgFgMIgFgJQgDgEgGAAIgIAAIgCgBIAAgCIAAgGIAAgBIACgBIAIAAIAUABIASgBIAKAAIACABIAAABIAAAGIAAACIgBABIgGAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBAAIAAAFIADALIAFASIAHAWIAFATIAEAKIABAAIAEgIIAHgSIAJgUIAHgSIAEgKQABgGgBgDQgCgDgDAAIgFAAIgCgBIAAgCIAAgGIAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAIAQABIALgBIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAABIAAAGIAAACIgBABIgFAAIgFABIgGAFIgKATIgRAkIgUAsIgMAgIgLAYIgIAPIgEAJQgDAFgFADQgFADgIAAQgJAAgEgEg");
	this.shape_45.setTransform(257.5,319.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AA8BAIgUAAIgSAAIgJABIgCgBIAAgDIAAgEIABgDIADAAIAIAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIABgNIAAgMIAAgnIgBgQQgBgGgHgFQgFgEgFAAIgLgBIgKACQgHACgHAIQgEAEgCAGIgBAKIAAA9IABAIQACACAEAAIAIAAIACABIABACIAAAFIAAACIgCABIgIgBIgSAAIgTAAIgIABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIgBgCIAAgFIABgCIACgBIAJAAIAEgBQACgBAAgEIAAhFQAAgHgEgEQgDgEgGgDIgCgBIgCgCIAAgBIAAgBIAAgCIACgBIAagPIADgBIACgBIACABIABADIACASIABAAQAGgJAMgGQALgHALAAIANACQAHABAFAEQAFADADAFQAEAFACAGQADAFAAAEIAABMQAAAEABABQACACADAAIAKAAIACABIABACIAAAEIgBADQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgJgBg");
	this.shape_46.setTransform(243,315.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AATA9QgGgGgCgJIgBAAQgEAGgHAEQgHAFgKADIgJABIgJABQgEAAgEgCQgEgDgDgFQgDgGAAgJQAAgKAGgJQAHgJARgIIAOgGIALgGIAIgEIAAgTIgBgJQgBgGgCgCQgDgDgDgCQgFgCgGAAIgLABQgFADgEADQgDACABADIABAIQAAAIgEAFQgDAEgJAAQgEAAgCgCQgBgDAAgFQAAgHAFgIQAGgHAJgGQAKgFAIgDQAJgCAJAAQAKAAAGACQAFADADADQAEAFACAFIABALIAAAtIAAASQAAANACAEQACAFAEAAQAEAAADgCIAEgDIABgBIACAAIADADIABACQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAABIgEAFQgDADgEADQgFADgIAAQgIAAgFgFgAgBACIgOAIQgGAEgFAGQgEAGgBAJQABAJAEAEQAEAEAHAAQAEAAAGgDIAJgHQAEgFABgDIAAgkIgKAEg");
	this.shape_47.setTransform(229,315.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("ABlBAIgRAAIgTAAIgJABIgBgBIgBgCIAAgFIABgDIADAAIAHAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQABgBAAgBIAAgMIAAgMIAAgrQAAgIgBgGQgCgGgFgFQgEgDgGgBQgGgCgHAAQgHAAgHAFQgIAEgEAHQgDAGgBAHIAAARIAAAzQAAADABACQABAAAAABQABAAAAAAQABABAAAAQABAAABAAIAKAAIADAAIAAADIAAAEIAAADIgCABIgIgBIgTAAIgSAAIgIABIgCgBIAAgCIAAgFIAAgDIACAAIAJAAIAFgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAg9IgBgRQgCgHgCgDIgEgFQgDgDgGgBIgKgCQgGAAgJAEQgIAEgHAKIgDAJIAAALIAAA6QgBAEACACQAAAAABABQAAAAABAAQAAABABAAQABAAABAAIALAAIACAAIAAADIAAAEIAAADIgCABIgIgBIgTAAIgTAAIgJABIgCgBIgBgCIAAgFIABgDIADAAIAKAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBIABgGIABgHIAAgIIAAg1QAAgEgCgEQgBgEgFgDIgGgDIgCgBIgBgCIAAgCIABgBIABgBIAbgOIACgBIADgBQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAABIABADIABARIABAAQAHgKALgGQAMgHAOAAQALAAAJAGQAIAGAFALIACAAQAGgJAMgHQAMgHAOAAQAHAAAHACQAHACAGAFIAGAIQADAEACAHQACAHAAALIAABCQAAABABAAQAAABAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQABABABAAQAAAAABAAIAIAAIACAAIABADIAAAFIAAACIgCABIgIgBg");
	this.shape_48.setTransform(210,315.5);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgWA+QgJgDgCgCIgCgCIgBgCIgEgcIAAgCIABgBIAEAAQABgBAAAAQABAAAAABQAAAAAAAAQABAAAAABIAIAOIAFAKQADAEAFADQAFACAGAAQAGAAAGgCQAFgCAEgFQADgEAAgHQAAgKgGgHQgGgGgQgFQgJgCgIgFQgIgDgFgIQgFgHAAgLQAAgLAGgIQAFgIAKgFQAJgFALAAQALAAAGACIALAEIADADIACACIAFAVIgBACIgCACIgEABIgBAAIgBgCIgKgOQgDgEgFgEQgEgDgJAAQgFgBgGADQgEACgEAFQgDAEAAAGQAAAJADAFQAFAEAGACIANAFQARAFAKAHQAJAIABARQgBANgGAIQgGAKgKAEQgLAFgLAAQgLgBgIgDg");
	this.shape_49.setTransform(184.9,315.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AATA9QgGgGgCgJIgBAAQgEAGgHAEQgHAFgKADIgJABIgJABQgEAAgEgCQgEgDgDgFQgDgGAAgJQAAgKAGgJQAHgJARgIIAOgGIALgGIAIgEIAAgTIgBgJQgBgGgCgCQgDgDgDgCQgFgCgGAAIgLABQgFADgEADQgDACABADIABAIQAAAIgEAFQgDAEgJAAQgEAAgCgCQgBgDAAgFQAAgHAFgIQAGgHAJgGQAKgFAIgDQAJgCAJAAQAKAAAGACQAFADADADQAEAFACAFIABALIAAAtIAAASQAAANACAEQACAFAEAAQAEAAADgCIAEgDIABgBIACAAIADADIABACQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAABIgEAFQgDADgEADQgFADgIAAQgIAAgFgFgAgBACIgOAIQgGAEgFAGQgEAGgBAJQABAJAEAEQAEAEAHAAQAEAAAGgDIAJgHQAEgFABgDIAAgkIgKAEg");
	this.shape_50.setTransform(173.7,315.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AA/BtIgQgBIgXABIgKAAIgCgBIAAgCIAAgFIAAgBIADgBIACAAIADgCQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIgGgHIgMgOIgNgOIgIgJQgCgCgEAAIgHAAIAAAMIAAAQIABAQQAAADABABQABABAAAAQABAAAAABQABAAAAAAQABAAABAAIAIAAIACABIABACIAAAEIgBADQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgJAAIgSgBIgUABIgJAAIgBgBIAAgCIAAgFIAAgCIADgBIALAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBIABgFIABgXIAAghIAAhiIgBgKQgBgEgDgDQgEgDgHgCIgDgBIgBAAIAAgDIABgCIADgCIAegMIAEgCIADgBIACACIAAADIgBAXIgBAiIAAAmIAAAuIAIAAIAHgDIAHgGIAKgLIAIgLIAGgGIABgDIgBgCIgEgCIgEAAIgCgBIgBgCIAAgGIABgBIABgBIAJAAIATABIARgBIAIAAIABABIAAACIAAAFIAAACIgCABIgCAAQgFAAgFACQgGABgFADIgKAHIgPAPIgNANIAKAMIAUATIATATIALAJIAJADIAHABIACABIAAACIAAAFIAAACIgDABIgIAAg");
	this.shape_51.setTransform(152.4,311.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgSA+QgMgEgKgNQgIgLgDgKQgDgKAAgKQABgRAHgQQAIgQAOgKQAPgKATAAQAPAAAJAFQAJAEAEAGQAEAGgBADQAAAFgDADQgDADgFAAQgFAAgEgEQgEgDgDgGQgFgIgFgDQgFgCgFAAQgIAAgIAFQgIAGgFAKQgFAKgBAQQABALAEAMQAEANAHAIQAHAKAJADQAHADAIAAQALAAAIgDQAHgDAHgHIABgBIACABIADADIABABIgBADQgFAFgHAEQgIAFgJADQgJAEgLAAIgCAAQgKAAgLgEg");
	this.shape_52.setTransform(138.4,315.6);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AAYBiIgKAAIgMgBIgVABIgLAAIgBAAIgBgCIAAgGIABgCIACAAIAPAAIADgBIABgGIAAgNIAAgOIAAgsQABgIgDgDQgDgEgLgCIgDgBIAAgBIAAgCIAAgBIACgBIAPgHIAQgJIADAAIAEgBIABABIAAACIgBARIAAAgIAAAgIAAAQIABAKIABAGQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAOAAIACAAIABACIAAAGIgBABIgCABIgGAAgAgOhCQgEgCgDgEQgCgEAAgFQAAgGAEgFQAFgGAJAAQAIAAADAGQAFAFAAAFQAAAGgFAGQgEAFgIABQgEAAgEgCg");
	this.shape_53.setTransform(127.9,312.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAXBtIgXgBIgWABIgLAAIgCgBIAAgCIAAgFIABgCIADgBIAOAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQACgCAAgDIAAgOIAAgWIAAgYIAAgTIAAgRIAAgXIAAgVIgBgNQAAgHgDgFQgFgEgHgCIgFgCIgCgBIAAgBIAAgCIABgBIACgBIARgIQAJgEAIgFIADgCIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAADIAAAUIAAAcIgBAdIAAATIAAAaIAAAQIAAAVIAAAUIAAANIACAGQABADAFAAIANAAIADABIABACIAAAFIgBACIgBABIgLAAg");
	this.shape_54.setTransform(120.1,311.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgiBnQgSgHgOgNQgLgKgHgOQgHgOgDgQQgEgPAAgOQAAgVAHgUQAIgVAQgRQAHgIAMgHQALgHAOgEQAOgEAQgBQANABAMACIAVAHIAOAHIAFACIABgCIADgJIABgBIADgBIACABIABAEIABALIACARIADATIABALIAAACIgBABIgEACIgCgBIgBgCIgJgRQgFgKgKgKQgJgKgNgGQgMgHgSAAQgTAAgOAIQgPAIgJANQgJANgEARQgEAQAAAQQAAAIACANQADANAGAPQAGAOAMANQAKAMAJAFQAKAFAJACQAJACAKAAQARgBAOgFQAOgFALgJQALgJAHgKIABgBIABABIAEADIABABIgBABQgJANgMAMQgNALgRAHQgRAHgVABQgZgBgSgHg");
	this.shape_55.setTransform(105,311.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgGBBQgEgCgEgEQgDgDAAgIIACgHQABgDAEgDQAEgEAHAAQAGAAAFAGQAFAEABAIQgBAIgEAFQgFAEgHAAIgHgBgAgGggQgEgCgEgEQgDgDAAgIIACgGQABgEAEgDQAEgDAHAAQAGAAAFAFQAFAEABAJQgBAHgEAFQgFAFgHgBIgHgBg");
	this.shape_56.setTransform(224.5,262.6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgWA/QgIgEgEgCIgBgBIgBgDIgEgdIAAgBIACgBIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAHAPIAGAJQADAEAFADQAFACAGAAQAGAAAGgCQAFgCAEgFQADgEAAgHQAAgKgGgGQgGgHgQgEQgJgDgIgEQgIgEgFgHQgFgIAAgMQAAgKAFgIQAHgIAJgFQAJgFALAAQAKAAAHACIALAEIADADIACADIAFAUIgBACIgCABIgEABIgBAAIgBgBIgKgNQgDgFgFgEQgEgEgJAAQgFAAgGADQgEACgEAEQgDAFAAAHQAAAIADAEQAFAFAGADIAOAEQAQAFAKAHQAJAIABASQgBALgGAJQgGAKgKAEQgLAFgLAAQgMAAgHgDg");
	this.shape_57.setTransform(215.4,262.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AA8BAIgUAAIgSAAIgJABIgCgBIAAgDIAAgEQAAgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADAAIAIAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIABgNIAAgMIAAgnIgBgQQgBgGgHgFQgFgEgFAAIgLgBIgKACQgHACgHAIQgEAEgCAGIgBAKIAAA9IABAIQACACAEAAIAIAAIACABIABACIAAAFIAAACIgCABIgIgBIgSAAIgTAAIgIABQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIgBgCIAAgFIABgCIACgBIAJAAIAEgBQACgBAAgEIAAhFQAAgHgEgEQgDgEgGgDIgCgBIgCgCIAAgBIAAgBIAAgCIACgBIAagPIADgBIACgBIACABIABADIACASIABAAQAGgJAMgGQALgHALAAIANACQAHABAFAEQAFADADAFQAEAFACAGQADAFAAAEIAABMQAAAEABABQACACADAAIAKAAIACABIABACIAAAEIgBADQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgJgBg");
	this.shape_58.setTransform(202.3,262.4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgZA+QgMgFgKgLQgHgIgDgIQgEgHgBgIIgBgRQAAgMAGgNQAGgNAOgLQALgIALgDQAKgDAHAAQAMAAAMAFQALAGAHAGQAKALAFAMQAFAMAAANQAAARgJAPQgJAPgPAJQgOAKgSAAQgLAAgNgEgAgLg2QgGACgGAGQgIAIgEALQgEALAAAQQAAAMACAKQADAKAHAKQAFAHAHAEQAHAEAJAAQAMAAAIgIQAJgIAEgOQAFgNAAgQQAAgQgHgNQgHgMgJgGQgJgHgHAAIgCAAQgFAAgEACg");
	this.shape_59.setTransform(186.5,262.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AAYBiIgKAAIgMAAIgVAAIgLABIgCgBIAAgCIAAgGIAAgCIADAAIAPAAIADgCIABgEIAAgOIAAgNIAAgtQABgHgDgDQgDgFgLgCIgDAAIAAgCIAAgDIAAgBIACgBIAPgGIAQgIIADgCIAEAAIABABIAAADIgBARIAAAeIAAAhIAAAQIABAKIABAGQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAOAAIACABIABACIAAAEIgBADIgCABIgGgBgAgOhDQgEgCgDgDQgCgEAAgFQAAgGAEgFQAFgFAJAAQAIAAADAFQAFAFAAAFQAAAHgFAFQgEAGgIAAQgEAAgEgDg");
	this.shape_60.setTransform(175.2,259.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgIBNQgGgEgEgGQgEgFAAgGIAAgQIAAgRIAAgKIAAgHIABgIIAAgPIAAgOIgSAAIgEgBIgBgDIACgDIAEgCQAEgCAHgHIAOgPQAGgIADgGIABgCIADAAIABABIABADIgCAdIAqAAIACABIAAACIgDALIgBABIgCABIgmAAIAAAVIAAAUIAAAeQAAALACAGQADAGADACQAEACACAAIALgBQAGgBADgCIACgBIACABIABADQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABIgGAFQgFADgHACQgGACgJAAQgHAAgHgEg");
	this.shape_61.setTransform(166.7,261);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgSA+QgMgEgKgNQgIgLgDgKQgDgKAAgKQABgRAHgQQAIgQAOgKQAPgKATAAQAPAAAJAFQAJAEAEAGQAEAGgBADQAAAFgDADQgDADgFAAQgFAAgEgEQgEgDgDgGQgFgIgFgDQgFgCgFAAQgIAAgIAFQgIAGgFAKQgFAKgBAQQABALAEAMQAEANAHAIQAHAKAJADQAHADAIAAQALAAAIgDQAHgDAHgHIABgBIACABIADADIABABIgBADQgFAFgHAEQgIAFgJADQgJAEgLAAIgCAAQgKAAgLgEg");
	this.shape_62.setTransform(155.7,262.6);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgTA+QgNgFgIgMQgGgIgCgGQgDgHgBgIQgCgIAAgJIACgOQABgIAEgJQAFgJAHgIQAKgKALgDQALgDAKAAQANAAAJAFQAIAFAFAIQAFAHACAHIACAMQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAQgCABgEAAIhJAAIgBAOQAAAOAGAMQAFALAKAHQAJAHAMAAQANAAAKgHQAJgGAEgIIABgBIACAAIADACIABABQABAAAAABQAAAAgBAAQAAABAAAAQAAABgBABQgCAGgGAHQgHAIgJAFQgKAGgNAAQgMAAgNgEgAgQgxQgIAHgFARIAuAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgCgKQgCgGgFgGQgFgFgKAAIgBAAQgIAAgIAHg");
	this.shape_63.setTransform(142.9,262.5);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AAJBBIgVAAIgXAAIgKABIgBgBIAAgDIAAgEQgBgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIADAAIAMAAQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBIAAgQIAAgUIAAgbIAAgMIgEgGIgGgFIgGgDIgCgBIAAgBIAAgCIAAgCIACgBIAegPIACgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIABADIABAUIACAAQAFgKAKgIQAKgHAKgBQAHAAAEAFQAEAEAAAFQgBAHgDAEQgEADgFAAIgEgBIgEgBIgFgBIgFgBQgEAAgFACQgFADgDAHIgCAGIgBAEIAAA9QAAAHACADQABADAEAAIAOAAIACABIABACIAAAEIgBADIgBABIgKgBg");
	this.shape_64.setTransform(131.6,262.4);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AAZBiIgLAAIgNAAIgUAAIgKABIgCgBIgBgCIAAgGIABgCIACAAIAPAAIADgCIABgEIAAgOIAAgNIAAgtQABgHgDgDQgDgFgLgCIgDAAIAAgCIAAgDIAAgBIACgBIAQgGIAQgIIACgCIADAAIACABIAAADIgBARIAAAeIAAAhIAAAQIABAKIABAGQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIAOAAIADABIAAACIAAAEIAAADIgCABIgGgBgAgOhDQgEgCgCgDQgDgEAAgFQgBgGAFgFQAFgFAKAAQAGAAAEAFQAEAFAAAFQAAAHgEAFQgEAGgJAAQgDAAgEgDg");
	this.shape_65.setTransform(122.2,259.1);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgfBrIgTAAIgQgBIgeABIgMAAIgCAAIAAgCIAAgIIAAgBIACgBIAUAAQAEAAADgBQACgCABgEIAAgKIABgUIAAgYIABgYIAAgSIAAgWIAAgMIgBgRIAAgRIgBgKQgBgFgDgCQgDgBgGAAIgQAAIgCgBIgBgBIAAgJIABgBIABAAIAOAAIAfABIAJAAIANgBIANAAIAJAAQATAAARACQARACAPAGQAQAGANALQAPANAJASQAJATAAAaQAAAZgHATQgIASgPAQQgOAQgRAHQgSAGgQACIgbABIgUAAgAgkhfQgEAAgDACQgDACgBADIgBAJIgBANIAAASIAAAQIAAAJIAAAWIAAAJIAAAVIABAXIAAATIABAIQABAEADAFQAEAFAIACQAIACAMAAQAWAAASgIQASgJALgPQAKgMAGgRQAGgSAAgTQAAgMgDgMQgDgNgGgLQgFgLgHgIQgMgNgUgHQgTgIgYAAIgIAAIgJABg");
	this.shape_66.setTransform(105.7,258.2);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AghC6QgOgOAAgUQAAgUAOgOQAOgOATAAQAUAAAPAOQANAOAAAUQAAAUgNAOQgPAPgUAAQgTAAgOgPgAgqBQIAAkYIBUAAIAAEYg");
	this.shape_67.setTransform(460.9,175.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AhQBpQgdgnAAhEQAAhAAdgmQAegnAyAAQAdAAAbATQAcATAMAeQANAfABBBIiNAAQACA8AfAAQALAAAIgIQAJgHABgNIBIAAQgUBbhSAAQgzAAgegngAgWhCQgHANAAAdIA8AAQgBgcgHgOQgHgOgPAAQgQAAgHAOg");
	this.shape_68.setTransform(439,181.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgiCHIhTkNIBTAAIAiCRIAAAAIAiiRIBUAAIhUENg");
	this.shape_69.setTransform(413.8,181.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AhVBrQgggmAAhCQAAhFAegmQAegnA5AAQA5AAAeAnQAfAmAABFQAABDggAmQgfAkg3AAQg2AAgfglgAgYg0QgIAPAAAlQAABEAgAAQAQAAAIgPQAJgQAAglQAAglgJgOQgIgPgQAAQgPAAgJAOg");
	this.shape_70.setTransform(387.8,181.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AhPDEIAAmHIBYAAIAAEsIBHAAIAABbg");
	this.shape_71.setTransform(364.6,175.2);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AhJCvQgggUgKguIBNAAQANAVATAAQAQAAALgNQAMgOAAgTIAAgmQgZAlgiAAQgrAAgXgkQgZglAAhBQAAhBAYglQAXgkApAAQAjAAAZAkIACAAIAAgcIBUAAIAAD4QABAjgMAeQgNAfgfASQgeARgkAAQgkAAghgTgAgZhqQgJAQAAAcQAABJAiAAQAhAAAAhDQAAhBghAAQgPAAgKAPg");
	this.shape_72.setTransform(322.7,186.4);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AAZCLIAAilQAAgOgGgIQgHgJgKAAQgaAAAAAiIAACiIhVAAIAAkMIBVAAIAAAkIABAAQAdgtArAAQAcAAARATQAQASAAAgIAADQg");
	this.shape_73.setTransform(295.1,180.8);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AheBpQgWgoAAhCQAAhBAXgmQAXgnAmAAQAUAAANALQAOAKAPAWIABAAIAAgiIBWAAIAAENIhVAAIAAgkIgBAAQgPAXgPALQgOALgTAAQgnAAgXgngAghAAQAABEAhAAQAgAAAAhEQAAhEggAAQghAAAABEg");
	this.shape_74.setTransform(265.9,181.3);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("ABrDEIgXkNIg3ENIg7AAIg6kNIgWENIhVAAIArmHIBwAAQAYB/AOBaIAJg7IAMhGIARhYIBzAAIAtGHg");
	this.shape_75.setTransform(230.1,175.2);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AhQBpQgdgnAAhEQAAhAAdgmQAegnAyAAQAdAAAbATQAcATAMAeQANAfABBBIiNAAQACA8AfAAQALAAAIgIQAJgHABgNIBIAAQgUBbhSAAQgzAAgegngAgWhCQgHANAAAdIA8AAQgBgcgHgOQgHgOgPAAQgQAAgHAOg");
	this.shape_76.setTransform(180.3,181.2);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgiCHIhTkNIBTAAIAiCRIAAAAIAiiRIBUAAIhUENg");
	this.shape_77.setTransform(155.1,181.3);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgpDGIAAkNIBTAAIAAENgAgeh4QgOgNAAgTQAAgSANgOQAOgNARAAQASAAAOANQANAOAAASQAAATgNANQgOANgSAAQgRAAgNgNg");
	this.shape_78.setTransform(134.9,175);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AhoCYQgng2ABhiQgBhlAng0QAng0BKAAQBTAAAmBaIhUAjQgLgTgJgJQgJgJgQAAQgaAAgLAdQgMAcAAA+QAAA7AOAcQAMAcAbAAQAtAAABhAIgpAAIAAhLICGAAIAABBQgBBMgkAsQglArhAAAQhGAAgog2g");
	this.shape_79.setTransform(110.5,175.1);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f().s("#CC0000").ss(2,1,1).p("ABC7jQDMBGCMAhQEmBID2gPQH9gdI1mXAg18NQA+AXA5ATIAABtEgg4gZeQB/jlEOh8QD3hxEiAFQDyADEnBUQCkAuFkCEQAfALAdAKAg19IIAAA7IAAB5ABC9IIAABlACSWvIAABbIAABjAgrZjIAABHAgrZjQgcAPgfAPQh+BBj6CDQjaBtimA1QjSBEjBACQjbACi3hcQjJhlhPizACSYKQhXAmhmAzEAg5AbjQh3i/j2hpQjMhXkRgUQj+gSj0AgQj9AgjlBVQhAAXhJAgAgrYJIAABa");
	this.shape_80.setTransform(266.4,290.5);

	this.replayBtn = new lib.ReplayBtn();
	this.replayBtn.name = "replayBtn";
	this.replayBtn.parent = this;
	this.replayBtn.setTransform(612.8,375.9,1,1,0,0,0,179.6,39.6);
	new cjs.ButtonHelper(this.replayBtn, 0, 1, 1);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f().s("#000000").ss(3,1,1).p("AMGrmQgHgrgLgYQgPgjgbgNQgWgMgoAAQgcgBgQADQgZADgQAMQgdAYgCA1QgCBQBEBjQAGAIA0BGQAdAoAXAqQAmg4BFgtQAKgHB5hLQAbgRAPgMQAVgRANgTQAPgWACgaQACgbgOgVQgegqhZAKQgxAEgfAQQgTAKgNARQgNASgNAFgAqXDEQjDgVhmBNQg+AtgQBOQgRBSAwA1QAdAhAzARQAjAMA+AIQETAnCUAmQB8AehSFHQgIAdABASQAAAZAOAOQANANAVADQAOACAZgDQCYgMDVgUQAwgEAegJQApgOAUgdQAGgKAJgbQAJgZAIgLQAMgSAVgFQAWgGALAPQgEAbAUAZQASAXAdAJQAYAHAggCQAVgCAigHIE6g9QAngIAZgUQAfgZgLgcQg/gkgshQQgcgzghhlQgTg8gGgdQgLgyAGgpQAKhJBEhLQAngsBXhRQBDhHAUhVQAWhgg7g2Qg4g1h2APQhsAMhTBBQhSBBhvA0QBNjfgdjJQgSh3g4hnQg6hthZhHQAvgxADhcQABg+gKg1QgCgTgLgLQgJgGgOgDQgwgFgvANQgwAOgkAfQgkAfgUAsQgVAtADA0QAqgBAsADAiStvQA4gJA4gBArstFQAQADAPAHQAnAPArAhQAWARAyAtQCPhdCcgsQA7gRA7gIQgSgsgSggQgRgfgdgXQg2gohNAAQgrAAgeAPQgvAZgdBeQgSgjgagGQgQgEgfgBQgrgBgYAEQglAHgUAVQgOAPgIAZQgFAQACAlQgRgFgRABQglAAgXAUQgUASgJAgQgGAXgBAlQgDA8AXAbQAUAYAtANQAvAMA0gEQguB6gVBuAlujwQAABHgnAzQgoAyg4AAQg4AAgngyQgogzAAhHQAAhIAogyQAngzA4AAQA4AAAoAzQAnAyAABIgAtapwQgUBKAAA6QAAAWAFAOQAEAPARAWQAoAxAzAXQgZCBALBwQALB9A5BqQAUAmAYAhQAwBBBBArIAACZQIKhuIejRIh/iDACYmFQgEAMgHAIACsnGQgFAYgHATAgTmyQgwgegogGQgtgHgmANQgpAOgaAjQgcAmAFAoQACAdATAbQARAZAcARQAmAbBKAVIEeBoQBYhSAih5QAih5ghhzQgVhPgxgUQgcgLgrAJQhGAOg1A2QgzA3gLBGgAhhlTQASASAWAHQAOAGANACQATAEANgC");
	this.shape_81.setTransform(277.3,373.3);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f().s("#000000").ss(2,1,1).p("AjCAXQAAA1gbAlQgaAlgmAAQgmAAgbglQgbglAAg1QAAgzAbgmQAbglAmAAQAmAAAaAlQAbAmAAAzgAF6iVIgEAOIgEAI");
	this.shape_82.setTransform(255.6,347.1);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#CC0000").s().p("AiBCHIg5hPQhEhiAChPQACg2AdgYQAQgLAZgEQAQgCAcABQAnAAAWALQAbAOAPAiQALAZAHAqQANgFANgRQAMgRAUgLQAfgPAxgFQBYgKAfArQANAUgCAcQgCAZgOAXQgNASgWARQgOALgcASIiDBRQhDAtgmA4QgYgqgdgng");
	this.shape_83.setTransform(356.3,307.9);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AhABaQgbgmABg0QgBg0AbglQAbglAlAAQAmAAAaAlQAbAlAAA0QAAA0gbAmQgaAlgmAAQglAAgbglg");
	this.shape_84.setTransform(227,349.4);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AheB6QgogyAAhIQAAhGAogzQAngzA3ABQA4gBAnAzQAoAzAABGQAABIgoAyQgnAzg4gBQg3ABgngzgAhChXQgbAmABAzQgBA1AbAlQAbAlAmAAQAlAAAaglQAbglAAg1QAAgzgbgmQgaglglAAQgmAAgbAlg");
	this.shape_85.setTransform(227.2,349.2);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#9966FF").s().p("AlTEXQgRgWgEgQQgFgNAAgXQAAg5AUhKQAUAYAtANQAvAMA0gEQguB6gVBuQgzgXgogxgAh6hQQgrghgngQQgPgGgQgEQgCgkAFgQQAIgZAOgPQAUgVAlgHQAYgEArAAQAfACAQAEQAaAGARAjQAdheAvgZQAegPArAAQBNAAA2AoQAdAWARAfQASAhASArQg7AJg7AQQicAtiOBcQgygsgWgRg");
	this.shape_86.setTransform(226,303.4);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FF33CC").s().p("Ah7CoQhKgVgmgbQgcgRgRgZQgTgbgCgdQgFgnAcgmQAagjApgOQAmgNAtAHQAoAGAwAeQALhGAzg3QA1g2BGgOQArgJAcALQAxAUAVBPQAhBzgiB4QgiB5hYBSgAgaA4IAIgBIgIABIgBAAIAAAAQgJAAgLgCIgCgBIgCAAQgNgCgOgGQgWgHgSgSQASASAWAHQAOAGANACIACAAIACABQALACAJAAIAAAAIABAAgACLgzIgEAOIgEAIQgEAMgHAIQAHgIAEgMIAEgIIAEgOQAHgTAFgYQgFAYgHATg");
	this.shape_87.setTransform(279.4,337.3);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#8CCCFF").s().p("AlwJ6QhBgrgwhBQgYghgUgmQg4hqgMh+QgKhwAYiAQAVhuAuh6Qg0AEgugMQgugNgTgYQgXgbADg8QABglAGgXQAIggAVgSQAXgUAkAAQARgBASAFQAPADAQAHQAnAPAqAhQAWARAzAtQCOhdCdgsQA6gRA6gIQA4gJA4gBQgCg0AVgtQAUgsAkgfQAlgfAvgOQAvgNAwAFQAPADAJAGQALALABATQALA1gCA+QgDBcgvAxQBaBHA6BtQA3BnASB3QAdDIhNDgIB/CDQofDRoJBugAmeggQgnAxAABIQAABHAnAzQAoAyA4AAQA4AAAngyQAogzAAhHQAAhIgogxQgngzg4AAQg4AAgoAzgAgIiGQgoAOgbAjQgbAmAEAoQADAcASAbQASAZAbARQAmAbBKAVIEeBoQBZhSAih5QAih4ghhzQgWhPgwgUQgdgLgqAJQhHAOg0A2Qg0A3gMBGQgvgegpgGQgPgDgOAAQgcAAgZAJgADrotIgDgBQgfgCgfAAIgBAAIAAAAIgLAAIgLABIALgBIALAAIAAAAIABAAQAfAAAfACIADABg");
	this.shape_88.setTransform(259.1,340.3);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#D9BBFF").s().p("AkoKNQgWgDgMgMQgPgOAAgaQAAgRAHgdQBSlHh7gfQiVglkTgnQg9gIgjgMQg0gRgcghQgwg1ARhRQAQhOA9guQBmhMDDAUQAwBBBBAsIAACYQIKhuIejRIh/iDQBvg1BThBQBShBBtgMQB1gOA4A1QA8A2gXBhQgUBVhDBGQhXBSgmArQhEBMgKBJQgGAoAKAyQAGAdAUA8QAhBkAcA0QArBPA/AkQALAdgeAYQgaAVgnAIIk5A9QgjAHgVABQgfADgZgHQgcgJgTgXQgUgZAFgbQgMgPgWAFQgUAGgMASQgIALgJAYQgKAbgGAKQgTAegqANQgdAKgxADQjVAUiYANIgYABIgOgBg");
	this.shape_89.setTransform(274.6,419.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.startBtn}]}).to({state:[]},10).to({state:[{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.replayBtn}]},10).wait(10));

	// Game Content
	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFCC").s().p("AAAgDIAAAAIAAAHIAAgHg");
	this.shape_90.setTransform(792,502.4);

	this.text = new cjs.Text("Score:", "45px 'Adobe Caslon Pro'", "#9900FF");
	this.text.lineHeight = 79;
	this.text.lineWidth = 150;
	this.text.parent = this;
	this.text.setTransform(12.1,22);

	this.target = new lib.newtarget();
	this.target.name = "target";
	this.target.parent = this;
	this.target.setTransform(232.1,287.6,1,1,0,0,0,85.2,75.4);
	new cjs.ButtonHelper(this.target, 0, 1, 2, false, new lib.newtarget(), 3);

	this.scoreDisplay = new cjs.Text("0", "60px 'Adobe Caslon Pro'", "#9900FF");
	this.scoreDisplay.name = "scoreDisplay";
	this.scoreDisplay.lineHeight = 104;
	this.scoreDisplay.lineWidth = 358;
	this.scoreDisplay.parent = this;
	this.scoreDisplay.setTransform(148.9,12);

	this.countdown_txt = new cjs.Text("15", "50px 'Tw Cen MT Condensed Extra Bold'");
	this.countdown_txt.name = "countdown_txt";
	this.countdown_txt.lineHeight = 56;
	this.countdown_txt.lineWidth = 87;
	this.countdown_txt.parent = this;
	this.countdown_txt.setTransform(480,571.4);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f().s("#000000").ss(3,1,1).p("Axbl2MAi3AAAIAALtMgi3AAAg");
	this.shape_91.setTransform(117.6,45.5);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFCC").s().p("AxaF3IAArtMAi2AAAIAALtg");
	this.shape_92.setTransform(117.6,45.5);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#9900FF").s().p("AEoFkQgVgCggAAIguABIgjACQgGgFgIgMIgQgVIgMgTIgNgWIgWgmIgVgkIgLgTIgQgYIgbgoQgOgVgGgHQgTgZgXgRQgYgQgqgBIgPAAIgSADIAAA5IAAAzIAAA6IABAxIABAbQABAQAHALQAFAMAMAAIA/AAQAFAAACACQABADAAACIAAAXQAAAFgCACQgCACgHAAIgRgBIgogBIhKgBIhHABIglABIgRABQgGAAgBgCIgBgGIAAgYIAAgFQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAIApAAQARABALgIQAKgIABgTIACiRIAAiOIAAhhIAAhkIgBhDQAAgZgJgMQgKgNgTAAIgoAAQgEAAgBgCIgBgFIAAgZIABgFQABgCAEAAIAiACIBaABIBAgBIBAgBIAngBQA9ABAxAQQAvARAcAbQAZAZAOAfQAOAeAAAcQAAA+gUAnQgTAogpAWQgpAXhAANIAAACQASAIALALQALAKAGAJIASAXIAdApIAcAoIAQAYQACAFALAPIAZAkIAdAkQANARAIAGQAPALASADQARADAWAAQAFAAABADIACAEIAAAXQAAAFgCACQgBACgFAAIgZgBgAh7lCQgJABgIAFQgEAEgEAIQgDAIAAANIAAEaQAKACALAAIAYABQBEgBAqgSQAqgTAYgdQAXgcAIgbQAJgbgBgRQAAgjgNgeQgOgfgWgSQgcgXgmgMQgmgKg9gBQgKABgIABg");
	this.shape_93.setTransform(783.4,179.8);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#9900FF").s().p("ADPFlIhAgCIh4AAIjAgBIgwABIglAAIgZACIgSAAQgEAAgCgBQgDgCAAgEIAAgbQAAgBAAAAQABgBAAgBQAAAAABAAQAAgBABAAIAHgBIAoAAQAiABAIgJQAJgJgBgbIAAjuIAAhgIAAhEIgBhFIgBg3IgBgaQgCgXgLgIQgLgJgbABIgkAAQgEAAgBgBQgDgBAAgFIAAgbQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQACgCADAAIAtACQAdABAxAAIAsAAICTAAICVgBIAYgBIAQgBQAEAAACACIACADIAJAdIARA1IAQAzIAJAcIAAAFQAAACgDACIgPAIQgBAAgBAAQAAABgBAAQAAAAgBgBQAAAAgBAAIgDgDIgNgRIgdgkIghglQgPgSgKgGQgQgLgUgHQgUgIgUgBIixgEIAAEkIAWAAIAogBIApgCIAXgCQAVgDAJgJQAKgKAGgWIAFgVIADgcQAAgEACgCQACgCADAAIAZABQAEABABACQACADgBADQgCAKAAAYIgBAvIAAAhIABAlIADAlIACAdQAAADgBACIgFADIgWADQgEAAgBgBQgCgDgBgFIgFgYIgGgXQgEgQgKgKQgKgKgTgDQgXgDgbAAIgygCIgfAAIAAA+IABBAIABBCIAAApQABAnAQARQAQASAYAEQAPADAUACQAUACASAAIAaAAIAhgBIAdgCQAJgBAPgEQAQgFARgGQAQgIAOgLQAHgGARgUIAhgsQARgWAIgNQACgEADgCQADgCAEACIAQAIQAEADAAADQAAADgCAGIg1CTQgCAGgGAEQgFAFgJAAIgXAAg");
	this.shape_94.setTransform(711.6,179.8);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#9900FF").s().p("AgwFnQgEgGgDgKIgZhGIgehVIgfhXIgZhIIgPgqIgLgiIgVhAIgZhKIgWhCQgKgdgGgMQgGgSgKgIQgJgHgPgBIgbAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgBgEIAAgZQAAgEABgCQABgBAEgBIAkACQAcABA6AAQA+AAAjgBIApgCQAGAAACACQACACgBAEIAAAXQAAADgBADQgBACgFAAIgxAAQgVABgKAGQgLAHAAAMIABAPIAEATQACAPAHAaIARA6IASA9IARA0IAQAxIAaBNIAcBRIAXA/IABAAIASgtIAahCIAbhIIAXg7IAMgiIANgiIARg0IATg4IAOgsQAHgSADgOQAEgOABgKQAAgKgHgHQgHgGgTgBIgaAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgBgGIAAgXIABgGQAAAAAAgBQABAAAAAAQABAAABAAQAAgBABAAIAnACQAgABAwAAQA1AAAYgBIAegCQAEABABABQABACAAAEIAAAZQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBACgEAAIgcAAQgYABgQALQgRAKgOASQgHAKgOAbQgNAagPAlIgeBIIgbBAIgRArIgTAwIgkBZIgoBlIgiBUIgQAmQgDAGgDADQgEAEgDgBQgGABgEgHg");
	this.shape_95.setTransform(643.4,180.7);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#9900FF").s().p("Ag7FrQgjgGgogOQgogPgogYQglgWghgqQghgqgWg7QgVg7gBhJQgBgeAHgoQAIgoAUgtQAVguAmguQAsg1AugcQAvgbAtgKQAugKAqABQAfgBAlAGQAlAHAnARQAoARAnAhQAmAfAeArQAgAsASA4QATA3ABBEQAAA3gSA4QgSA3gnA1QgtA+hHAnQhGAmhmACQgYAAgjgGgAgglKQgXABghAMQgiAMglAjQgiAggWApQgWAqgLAtQgLAtAAApQABBhAcBFQAdBEAsAqQArApAtATQAtATAgAAQBBgBAugXQAtgYAdglQAdglAQgrQAPgrAGgnQAGgnAAgcQgBhRgZhAQgahBgogtQgpgsgugYQgugXgqAAIgRgBIgNAAg");
	this.shape_96.setTransform(564.6,179.8);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#9900FF").s().p("ADPFlIhAgCIh4AAIjAgBIgwABIglAAIgZACIgSAAQgEAAgCgBQgDgCAAgEIAAgbQAAgBAAAAQABgBAAgBQAAAAABAAQAAgBABAAIAHgBIAoAAQAiABAIgJQAJgJgBgbIAAjuIAAhgIAAhEIgBhFIgBg3IgBgaQgCgXgLgIQgLgJgbABIgkAAQgEAAgBgBQgDgBAAgFIAAgbQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQACgCADAAIAtACQAdABAxAAIAsAAICTAAICVgBIAYgBIAQgBQAEAAACACIACADIAJAdIARA1IAQAzIAJAcIAAAFQAAACgDACIgPAIQgBAAgBAAQAAABgBAAQAAAAgBgBQAAAAgBAAIgDgDIgNgRIgdgkIghglQgPgSgKgGQgQgLgUgHQgUgIgUgBIixgEIAAEkIAWAAIAogBIApgCIAXgCQAVgDAJgJQAKgKAGgWIAFgVIADgcQAAgEACgCQACgCADAAIAZABQAEABABACQACADgBADQgCAKAAAYIgBAvIAAAhIABAlIADAlIACAdQAAADgBACIgFADIgWADQgEAAgBgBQgCgDgBgFIgFgYIgGgXQgEgQgKgKQgKgKgTgDQgXgDgbAAIgygCIgfAAIAAA+IABBAIABBCIAAApQABAnAQARQAQASAYAEQAPADAUACQAUACASAAIAaAAIAhgBIAdgCQAJgBAPgEQAQgFARgGQAQgIAOgLQAHgGARgUIAhgsQARgWAIgNQACgEADgCQADgCAEACIAQAIQAEADAAADQAAADgCAGIg1CTQgCAGgGAEQgFAFgJAAIgXAAg");
	this.shape_97.setTransform(464.5,179.8);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#9900FF").s().p("AG9FkIgogBIhTgBQhEAAgiACIgqABQgFAAgBgCQgCgCAAgFIAAgYQAAgDACgBQABgCAFAAIBEAAQANABAHgIQAHgIABgVIABgjIABhHIAAhTIAAhHIAAg/IAAhCIAAhSIgBhHQgBgegBgEIgCAAQgDAFgRAiIgmBSIgsBiIglBRIgSAlIgOAgIgeBDIgiBPIgdBDIgNAfQgDAHgFAIQgGAJgGAAQgEAAgEgFQgEgFgDgJIgKgaIgZg8IgghPIgghPIgZg+IgMgbIgTguIgdhGIgghLIgbg9QgNgZgEgFIgCAhIgCBEIgBBPIgBBCIAAAhIAAAbIAAA6IAABFIABBAIABAnQADAqAKAQQAKAQAXgBIAyAAQAFAAABACQAAAAAAABQABABAAAAQAAABAAAAQAAABAAAAIAAAaQAAADgBACQgCACgGAAIgSgBIglgBIhCgBQg/AAgeACIgkABQgGAAgBgBQgCgCAAgGIAAgZIABgDQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAIA1AAQAcgBALgQQAKgRAEgaQAEgWACgoIAFhVIAChZIAChIIAAgkIAAggIAAg7IAAg+IgBgpQAAgLgCgJQgCgIgIgFQgJgEgUAAIg9AAQgEAAgCgCIgBgFIAAgaIABgEQACgCAEAAIARABIAmABIBDABQAjAAAVgBIAdgCQALAAAGADQAFAEAEAKIDdIVQAEgFAOgcIAdhAIAhhKIAbg/QAMgbADgFIAPgfIAdhAIAihLIAchBQAMgbABgHQACgIAHgCQAGgCAIAAIBnAAIA1gCIAWgBQADAAACACIABAFIAAAXQAAAFgCACQgBACgFAAIgsAAQgWAAgGAMQgGAMABARIgBAoIgBBBIgBBIIAAA+IAABFIAAA3IABBIIABBDIABAmQAAAcAIANQAHANATAAIA7AAQAFAAAAACQABAAAAABQAAABAAAAQABABAAAAQAAABAAAAIAAAYQAAAFgCACQgBACgGAAIgRgBg");
	this.shape_98.setTransform(379,179.8);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#9900FF").s().p("AFVFzIgkgBIg/gBQg9AAggACIgwABQgDAAgCgCQgCgCgBgFIAAgXQAAgEADgBQACgCAEAAIAZAAQAVABAHgJQAHgJgEgVIgNgpIgRg7IgUg8IgNgsIj2AAIgOAnIgXA+IgVA9IgMAkIgCAMIgBAKQAAALAJAFQAIAGARAAIAvAAQAFAAADACQADACgBADIAAAXQABAFgDACQgCACgEAAIgogBQgegCgsAAIg6ABIggABIgTABQgDAAgCgCQgCgBAAgFIAAgYQAAgDACgCQADgCAEAAIAiAAQAWAAANgLQAOgLAJgYIAQgnIAehNIAjhaQARgtALgfIAMggIAXg9IAahHIAXg+IANgkIAEgQQACgJgFgJIgFgGIgCgHQAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAQABgDAGgCQAPgDARgJQARgJANgLQAOgKAGgIIAGgGQAEgCAEAAQADAAADAEQACAEACAIIARA3IAbBNIAdBWIAaBPIARA2IAYBKIAeBaIAdBRQAOAjAFAMQANAZASAKQASALATgBIAhAAQAEAAACACQABABAAAAQAAABABAAQAAABAAABQAAAAAAABIAAAZQAAAEgDACQgCABgFAAIgVgBgABSA3IgMgoIgYhHIgahRIgVhEIgLgiIgEgJQgCgEgCgBQgDABgDAEIgFAKIgNAiIgZBEIgeBSIgaBGIgNAnIDcAAIAAAAg");
	this.shape_99.setTransform(293.9,178.3);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#9900FF").s().p("AhbFlQgzgMgwgYQgxgagkgoQgtg0gXhDQgXhCAAhZQAAhGAchCQAehDA3gyQA1gvBFgYQBFgYBZgBQBCACA0ASQA1ASAaAVQAJAGAEgBQAGgBAEgFIAPgSIAHgHQADgCAEAAQAGAAABACQACAEAAAFIADC/IgBAHQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgSACQgDAAgCgCQgCgCAAgEQgHgWgOgfQgOgggZghQgQgSgZgUQgagSgjgMQgkgNgtgBQgzgBgvASQgvARgtAvQgpAsgXA7QgYA7AABEQAABZAYBIQAYBJAvAtQAmAkAsARQAtASAxAAQA6gBAogIQAngKAagQQARgJAGgUQAFgUgBgnIAAhJQABgagKgLQgKgJgVAAIgqAAQgEAAgCgBQAAgBgBAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAgaQAAgEABgBQABgCAFAAIArACQAgABA0AAQA0AAAcgBIAlgCQAGAAABACIABAEIAAAZIgBAGQgCACgEAAIgnAAQgOAAgIAHQgJAIAAAXIAACEQAAAKACAIQACAIAAAFQAAAHgFADQgDAEgIACQg7AfhCARQhBAQhTAAQgsAAg0gLg");
	this.shape_100.setTransform(216.5,179.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_90}]}).to({state:[{t:this.shape_92},{t:this.shape_91},{t:this.countdown_txt},{t:this.scoreDisplay},{t:this.target},{t:this.text,p:{x:12.1,y:22,text:"Score:",font:"45px 'Adobe Caslon Pro'",color:"#9900FF",lineHeight:78.6,lineWidth:150}}]},10).to({state:[{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.text,p:{x:806,y:507.7,text:"J Nones\nComp Art\nMay 2019",font:"30px 'Tw Cen MT Condensed Extra Bold'",color:"#000000",lineHeight:34.5,lineWidth:226}}]},10).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(534.9,400.3,875.6,554.9);
// library properties:
lib.properties = {
	id: 'F4E4B4EE79E64232B3FD75D33E0487F3',
	width: 960,
	height: 640,
	fps: 10,
	color: "#FFCCFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F4E4B4EE79E64232B3FD75D33E0487F3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;