(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AAWjLQAAA6goApQgpApg6AAQg6AAgpgpQgpgpAAg6QAAg6ApgpQApgpA6AAQA6AAApApQAoApAAA6gAECElQAAAVhLAPQhMAPhrAAQhqAAhMgPQhLgPAAgVQAAgVBAAEQBAAEBqABQBqABBXgFQBYgFAAAVg");
	this.shape.setTransform(143.1,75.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#330000").ss(1,1,1).p("AE5tcQDLAkChBiQC8ByAyCUQATA2AAA8IAAADQDDgeDMjYIAAidAS/sBIAAiRIB2AIIAACcAS/sBIB2ATAOTnQIEsigIAAiRAzsqAIhIgnIBmh2IBaA2AocAkQgKgGgKgGQkAiaAAjcQAAgYADgXQAIhDAjg9IlyjaAstmNIm/jzIB4hnAsCoNQA+hvCUhaQC4hwDvgfAEqChQhxATh/AAQjbAAi1g5IjFhWQAAgBgBAAImBJBIC8B2IGLpgQhpgihcg0AjPg7QDTBoDyhoAudJlIhXCCIDEBuIBPh6AOmlbQgyD3jPB8QhJAthTAgQhoAoh3AUIGPKIICgiFIlQo/AK5MpIBBBpIC0hdIhViR");
	this.shape_1.setTransform(133.3,217.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#663300").ss(1,1,1).p("AIAAAQAAAogDAnQgSDriBCtQhBBYhOAyQhkA/h3AAQh+AAhphIQhGgxg8hQQiBitgSjrQgDgnAAgoQAAgeACgfQAOj2CGizQCWjJDTAAQDUAACWDJQCFCzAPD2QACAfAAAeg");
	this.shape_2.setTransform(142.7,68.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ai1FJQhMgPAAgVQAAgVBAAEQBAAEBqABQBqABBYgFQBXgFAAAVQAAAVhMAPQhLAPhrAAQhqAAhLgPgAjYhoQgpgpAAg6QAAg6ApgpQApgpA6AAQA6AAApApQAoApAAA6QAAA6goApQgpApg6AAQg6AAgpgpg");
	this.shape_3.setTransform(143.1,75.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#330000").s().p("AK5MpICgiEIBVCQIi0BdgAv0LnIBXiCIC8B2IhPB5gA00qnIBmh1IBaA1Ih4BngAS/sBIAAiQIB2AHIAACcg");
	this.shape_4.setTransform(133.3,217.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#663300").s().p("AEGNLQB3gTBogoQhoAoh3ATQhxAUh+AAQjcAAi0g6IjGhWQBcA0BqAiImMJgIi8h2IGBpAIABAAIgBAAIgTgNQkBibAAjcQAAgYADgXIm/jzIB4hmIFyDZQA/hvCUhZQC4hvDuggQhGgwg8hRQiBitgSjrQgDgnAAgoQAAgfACgeQAOj2CGizQCWjJDTgBQDUABCWDJQCFCzAPD2QACAeAAAfQAAAogDAnQgSDriBCtQhCBZhNAxQhkBAh3AAQh+AAhphJQBpBJB+AAQB3AABkhAQDLAkChBiQC8BxAzCUQASA3AAA7IAAAEIAAgEQAAg7gSg3IErigIAAiQIB2ATIAACcQjMDZjDAeQgxD2jQB9QhJAuhTAgIFQI/IifCEgAgXKjQBwAAB5g0Qh5A0hwAAQhyAAhpg0QBpA0ByAAgAtREcQAIhCAjg+QgjA+gIBCgAjDm2QAAAUBMAQQBLAPBqAAQBrAABLgPQBMgQAAgUQAAgWhXAFQhYAFhrAAQhpgChAgEIgTAAQgtAAAAASgAiawKQgpApAAA6QAAA6ApApQApApA6AAQA5AAApgpQApgpAAg6QAAg6gpgpQgpgpg5AAQg6AAgpApgAl5MlgAo/LPIDGBWQhqgihcg0g");
	this.shape_5.setTransform(136.9,149.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,268.6,310.8);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0066FF").s().p("AgwBAIAAh8IAsAAIAAAVQAGgOAHgEQAHgGAKAAQALAAAMAHIgPAiQgJgDgEAAQgKAAgFAHQgGALAAAdIAAAqg");
	this.shape.setTransform(604.9,398.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0066FF").s().p("AgmA6QgOgHgKgPQgJgPAAgVQAAgcASgSQAUgSAgAAQAaAAAQAIQAPAIAIAQQAIAPAAAXIAAAGIheAAQABALAEAGQAHAIAKAAQAIAAAGgDQAEgDAFgFIAvAEQgMATgPAIQgPAIgcAAQgYAAgOgHgAAYgKQgCgOgGgGQgGgGgKAAQgKAAgHAJQgFAGAAALIAuAAIAAAAg");
	this.shape_1.setTransform(590.6,398.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0066FF").s().p("AgmA6QgPgHgJgPQgJgPAAgVQAAgcASgSQAUgSAgAAQAaAAAQAIQAPAIAIAQQAIAPAAAXIAAAGIheAAQABALAEAGQAIAIAJAAQAIAAAGgDQAEgDAFgFIAuAEQgLATgPAIQgPAIgcAAQgYAAgOgHgAAXgKQgBgOgGgGQgGgGgKAAQgKAAgHAJQgEAGgBALIAtAAIAAAAg");
	this.shape_2.setTransform(574.6,398.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0066FF").s().p("Ag2BEQgOgTAAgcQABgeAPgRQAOgQAXAAQALAAAIAEQAJAEAHAHIAAg7IAwAAIAACrIgsAAIAAgTQgKAMgIAEQgIAFgNAAQgaABgNgUgAgOAAQgGAGAAARQAAAPAGAHQAFAIAJgBQAIAAAGgHQAHgHgBgQQABgPgHgHQgGgGgIAAQgJAAgFAGg");
	this.shape_3.setTransform(558.2,396.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0066FF").s().p("AASBAIAAhEQAAgLgEgFQgFgFgIAAQgHAAgGAGQgFAHAAAQIAAA8IgwAAIAAh8IAtAAIAAAVQAKgNAKgFQAJgGAPAAQATAAAMAMQALAMAAAZIAABOg");
	this.shape_4.setTransform(542.5,398.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0066FF").s().p("AgXBWIAAh8IAvAAIAAB8gAgXg0IAAghIAvAAIAAAhg");
	this.shape_5.setTransform(530.6,396.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0066FF").s().p("AgmA6QgPgHgIgPQgKgPAAgVQAAgcATgSQASgSAiAAQAZAAAPAIQAQAIAIAQQAIAPAAAXIAAAGIhfAAQABALAGAGQAGAIALAAQAGAAAHgDQAEgDAEgFIAvAEQgKATgPAIQgQAIgcAAQgYAAgOgHgAAXgKQgBgOgGgGQgGgGgKAAQgKAAgHAJQgFAGgBALIAuAAIAAAAg");
	this.shape_6.setTransform(518.6,398.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0066FF").s().p("AgwBAIAAh8IAtAAIAAAVQAFgOAHgEQAGgGALAAQAKAAANAHIgPAiQgIgDgGAAQgIAAgGAHQgGALAAAdIAAAqg");
	this.shape_7.setTransform(506,398.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0066FF").s().p("AgmA6QgOgHgJgPQgKgPAAgVQAAgcATgSQASgSAiAAQAZAAAPAIQAQAIAIAQQAIAPAAAXIAAAGIhfAAQACALAFAGQAGAIALAAQAGAAAHgDQAEgDAEgFIAwAEQgLATgPAIQgQAIgcAAQgYAAgOgHgAAXgKQgBgOgGgGQgGgGgKAAQgKAAgHAJQgFAGgBALIAuAAIAAAAg");
	this.shape_8.setTransform(483.6,398.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0066FF").s().p("AASBWIAAhEQAAgMgEgFQgFgEgIAAQgHAAgGAGQgFAGAAARIAAA8IgwAAIAAirIAwAAIAAA/QAKgKAIgEQAKgEANgBQATAAAMAMQALAMAAAYIAABPg");
	this.shape_9.setTransform(467.6,396.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0066FF").s().p("AgMBSQgIgEgEgJQgEgJAAgVIAAgrIgSAAIAAgjIASAAIAAgXIAvgYIAAAvIAaAAIAAAjIgaAAIAAArQAAAIABADQADADAFAAQAGAAAJgCIAEAhQgSADgPAAQgRABgJgGg");
	this.shape_10.setTransform(454.2,396.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0066FF").s().p("AATBWIgYgyIgSASIAAAgIgxAAIAAirIAxAAIAABYIAjgpIA6AAIgsArIAvBRg");
	this.shape_11.setTransform(433.6,396.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0066FF").s().p("AgcA9QgNgDgJgJQgKgIgFgLQgGgLAAgSQAAgTAHgMQAEgKAJgHQAIgIAJgDQAOgGAUAAQAfAAAQALQAQALAHAVIgtAGQgDgIgFgEQgGgEgJAAQgLAAgHAIQgIAJABAQQgBAPAIAIQAHAIAKAAQAKAAAGgFQAGgFADgJIAuAFQgDAOgJAKQgJALgNAFQgNAGgVAAQgSAAgOgEg");
	this.shape_12.setTransform(417.4,398.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0066FF").s().p("AgXBWIAAh8IAvAAIAAB8gAgXg0IAAghIAvAAIAAAhg");
	this.shape_13.setTransform(405.4,396.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0066FF").s().p("AgXBWIAAirIAvAAIAACrg");
	this.shape_14.setTransform(397.5,396.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0066FF").s().p("AgcA9QgNgDgKgJQgJgIgFgLQgGgLAAgSQAAgTAHgMQAEgKAJgHQAIgIAJgDQAOgGAUAAQAfAAAQALQAQALAHAVIgtAGQgCgIgGgEQgGgEgJAAQgLAAgHAIQgIAJAAAQQAAAPAIAIQAHAIAKAAQAKAAAGgFQAHgFACgJIAuAFQgEAOgIAKQgJALgNAFQgOAGgUAAQgSAAgOgEg");
	this.shape_15.setTransform(386.2,398.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#CC0000").ss(3,1,1).p("AAlAcQAAABAAAAQAFApAIAZQASA0AhgRAAkAZQAAABABACIgBAAQgfgGAlgqQAkgsADgaQADgaAYgBQAXgBASASQATASAAAaQAAAagTASQgSASggANQggAOgegFAgBgfQAWAXgWAWQgYAXgtgMQgtgNgbgWQgbgXADghQADggAYgXQAYgYAXAXQAWAWAYAYQAXAXAWAWgAgBAdQgKAigPAYQgYAkgkAL");
	this.shape_16.setTransform(37.2,145.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#663300").ss(1,1,1).p("ADwwBQDSAqClB6QB1BWA/BmQAnA/ATBEQARBBAABFQAADdixCnQgBAAgBABQgjAggpAeQgwAkg0AcQjeB8klAAQiUAAiCggQgBAAgBAAIjJhKQhGgjhAgvQj+i6AAkJQAAghAEgfQAIhDAag+QA8iQCch0QCRhrCzgtAnhOKIDSgFAnhOKIAAB4IDTAAIgBh9IgHq+AkYDHQhqgbhfgvIAAMNAK1NnIAAB4IizAAIAAhzgAICNsIABsBICwh+AK1gUIAAN7");
	this.shape_17.setTransform(174.6,283.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(3,1,1).p("ADLADQAAALgIAHQgHAHgKAAQgLAAgHgHQgHgHAAgLQAAgKAHgHQAHgHALAAQAKAAAHAHQAIAHAAAKgAiSAAQAAAMgIAIQgIAIgMAAQgLAAgJgIQgIgIAAgMQAAgKAIgJQAJgIALAAQAMAAAIAIQAIAJAAAKg");
	this.shape_18.setTransform(166.7,105.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#663300").ss(3,1,1).p("AEEscQALANALAOQCVDBAAEQQAAERiVC/QgoA0gtAnQh4BmiZAAQiQAAhzhbQg0gpgwg9QiUi/AAkRQAAkQCUjBQANgQANgPQABgBABgBAtrKjIhFggAuNMjIlTiMIAUgUALwJbIEgiMIAzi0AMqLeIE7i6QBvh9ANiM");
	this.shape_19.setTransform(178.9,156);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#FF0000").ss(3,1,1).p("ALclQQgPAFgSAFQgxAMhJAGQgGABgHAAAILkwQgCAAgCAAAMfm6QAAAGABAGQAAAFABAEQAEATAOAOQgJAIgKAIIgBAAQgcAVgkAOAganDQgBgBAAgBQAAgRAFgTQALg7AvhRQCIjnDrhxQDrhyGcgMQGbgNjsCIQjtCJhpCeQhSB5gGBZAIPEWQAAAYgpAQQgpARg6AAQg6AAgpgRQgpgQAAgYQAAgXApgRQAbgLAigDQAPgCAQAAIACAAQACAAADAAQA6AAApAQQApARAAAXgADkk2QgGgBgFgBIAAAAQgXgDgVgDQgBAAgBAAQgngHgigJQgRgEgPgFQgCgBgBAAQgZgJgSgMQgYgRgMgZQgCgEgBgDQgFgLgBgLA0iLmIAAloIFZAAAt8F+IGnAAIAAFoAnVMdIAAExIgBAAIkcAAIiKAAAvJROIlZAAIAAkxAHEkuQh9AChigK");
	this.shape_20.setTransform(131.5,110.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#FFFFFF").ss(3,1,1).p("AB9piIgIAAQgdABgbABQgCAAgBAAQiPALiIgbAEJpyIAegGIADAAIAGAAAEJpyIAEAAQgEABgDAAIgWAEIAAAAIgFAAQgFABgFABQgGABgHABIAHgBIAGgBAEqp4QgPADgOADIABAAIgIABADwptIAZgFADUppIgGAAQgSADgSABIgpADADbpqIgLABIgCAAAEblvIAAAPQgFA5gnApQgrAvg+AAQg9AAgsgvQgmgpgEg5IgBgPQAAgDAAgDIABgOQAGg2AkgnQAsgvA9AAQA+AAArAvQAlAnAGA1IABAOQAAADAAAEgAGVqmIgiAAIgpAQIAAAIIoXAEIh6ABIhUhAQgEgFgDgFQgWgkAYgkIM0ASQgBAPABAOIAVA2QgbAkg6APQAAAAgBAAQgBAAAAABQgUAFgUAFAGBrgIAUAAIAAA6Agal5IgBAPQgEA3gpAoQgpApg4AEIgdAAQg4gEgpgpQgpgogEg3IgBgPQAAgCAAgBIABgOQAFg1AogoQApgoA4gEIAdAAQA4AEApAoQAnAoAGA0IABAOQAAACAAACgABVDTQAAAOgdARQgeAQgtAAQgtAAgjgQQgjgRAAgOQAAgPAeAGQAeAGAtAAQAtAAAjgGQAigGAAAPgAV3i6QAAAagZATQgaATg5ADQg5AEAUgXQAUgWAKgaQAKgaANgSQANgTAVAAQAVAAASASQATATAAAagASSh2QgygBgSgSQgSgTAAgaQAAgbASgTQATgSAPACQAPACAWAZQAXAYAJATQAJASAJATQAIASgwABAThCwIAAkDIBbAAIAAEDIFyAAAThDiIkXAAIAAgyIEXAAIBbAAAU8DiIhbAAAU8DiIAADSIgMAAIhPAAIAAjSAmirTIgCgTQgBgFAAgFIAAgEIgBgDIABAAIARAAIAEgSIgQgSAmUr3IABAAIgLAngAjepwQhAgFgsgSQgZgKgTgOQgtgZAIgRAAlp0IjJAMQgBAAgBAAQgCgJgIAHQAAABgBAAIAAgBIgGgUA1UG0IAAkuIAAg6IAaAAIAmAAIAOAAIAABBIAAEnIGmAAA1UHrIlZAAIAAg3IFZAAIBOAAA0GHrIhOAAAtgHrImmAAIAAExIhOAAIAAkxAjNqKIHWAYAauDiIlyAA");
	this.shape_21.setTransform(171,140.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#3366FF").ss(3,1,1).p("AFyAyIAADSIlyAAAAAkDIFyAAIAAEDAiDkDIApAAAhaEEIhOAAIjJAAIAAjSAlxAAIAAkDIDoAA");
	this.shape_22.setTransform(305,158.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#330000").s().p("ApKBNIAAh2IDSgGIABB8gAGZAqIAAhxICygGIAAB3g");
	this.shape_23.setTransform(185.1,378.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("ACgAVQgHgIAAgKQAAgJAHgIQAHgHALAAQAKAAAHAHQAIAIAAAJQAAAKgIAIQgHAHgKAAQgLAAgHgHgAjCAUQgIgJAAgLQAAgKAIgJQAJgIALAAQAMAAAIAIQAIAJAAAKQAAALgIAJQgIAIgMAAQgLAAgJgIg");
	this.shape_24.setTransform(166.7,105.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF0000").s().p("AnWROIkcAAIiKAAIAAkxIGnAAIAAExgA0iROIAAkxIFZAAIAAExgAt8LmIAAknIABABIAAABIAAAAIAAABQAOAkAVAAIAAAAIAAAAQAHAAAGgDIABAAIAAAAIABgBIgBABIAAAAIgBAAQgGADgHAAIAAAAIAAAAQgVAAgOgkIAAgBIAAAAIAAgBIgBgBIAAhBIGnAAIAAFogA0iLmIAAloIFZAAIAAA6QgYAkgkALQAkgLAYgkIAAEugAt8G/IAAAAgAvJG4gAEgE+QgpgQAAgYQAAgXApgRQAbgLAigDIAfgCIACAAIAFAAQA6AAApAQQApARAAAXQAAAYgpAQQgpARg6AAQg6AAgpgRgACtk+IAsAGIAAAAIALACIABAAQBiAKB9gCQgpADgpAAQhlAAhggTgADZk3IAAgBIAAABIAAgBIAAABIAAAAgAJYk3IAHgBIAGAAIgLABIgCAAIACAAIALgBIgGAAIANgBIAKgCIAEgBIABAAIAWgDIAGgBIABAAIgHABIAHgBIgBAAIAdgGIAHAAQgxAMhJAGIgNABIAkgEgAJlk4IAHgBgADZk3gAK7lGgAK0lGIAogKQgPAFgSAFgAMfl0IABAAIATgQQgbAkg5APQAkgOAcgVgAgQmXQAMAZAYARQgsgZAIgRgAgXmhIgCgTQABALAFALQgFgLgBgLIgBgKIAAgFIAAAAIgBgCIARAAIgJAnIADAHIgHgKgAgWnpQALg7AvhRQCIjnDrhxQDrhyGcgMQGbgNjsCIQjtCJhpCeQhSB5gGBZIs1gSQgFATAAARIAAAAIABACIAAAAIAAAFIABAKIACATQgWgkAXgkgAgZm0IAAAAgAganDIAAAAIAAAAgAganDgAgbnFIAAAAIABACg");
	this.shape_25.setTransform(131.5,110.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#663300").s().p("AoMLIQBeAvBqAbIACAAIgCAAIjIhKQhHgjg/gvQj+i7AAkKQAAggADggQAJhCAZg9QA8iQCdh0QCQhqCzgvQg1gpgug8QiVjBAAkQQAAkRCVjBIAZgeIACgDIAgAKQAjAIAnAHIABAAQCHAbCRgLIACAAIA4gBIAHAAIAFgBIAogCIANgBQBJgHAxgMQASgFAPgFIACgBIAWAbQCVDBAAERQAAEQiVDBQgoA0gtAmQh5BmiXAAQiQAAh0hbQB0BbCQAAQCXAAB5hmQDSAqClB6QB0BWBABnQAnA+ASBDQgShDgng+IEhiNIAyi0IBPAAIBPAAQgNCMhvB9Ik8C5QARBAAABFQAADdixCoIgBABIABgBIAAN8IiyAFIABsBQAzgcAxgkQApgfAjggQgjAggpAfQgxAkgzAcICwh/IiwB/QjfB7kkAAQiUABiDggIAIK+IjSAFgAjVp3QAAAPAjAQQAiAQAuABQAtgBAfgQQAcgQAAgPQAAgOgiAFQgiAHguAAQgtAAgegHIgPgBQgPAAAAAKgAh8ucQghAEgbAKQgpARgBAYQABAXApAQQAoARA7AAQA6AAAogRQApgQgBgXQABgYgpgRQgogQg6AAIgGAAIgCAAIgCAAQgQAAgNACgAgx0rQglAngGA2IgBAOIAAAGIABAQQAEA4AnAqQArAuA9ABQA9gBAsguQAngqAFg4IAAgQIAAgHIgBgNQgGg1glgoQgsgvg9AAQg9AAgrAvgAl20xQgoAngFA1IgCAOIAAAEIACAPQAEA3ApAnQApAqA4ADIAdAAQA3gDApgqQAqgnAEg3IAAgPIAAgFIgBgNQgFg1gognQgpgog3gFIgdAAQg4AFgpAogAkt27QhAgFgsgRQAsARBAAFgAoMLIIDIBKQhqgbhegvgAzggaIAUgUIEcAAIBFAgQgZA9gJBCg");
	this.shape_26.setTransform(178.9,225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("A1UMcIAAkxIBOAAIhOAAIlZAAIAAg3IFZAAIAAkuIAAg6IAaAAIAmAAQAFApAJAZQgJgZgFgpIAOAAIAABCIAAEmIGmAAIAAA3ImmAAIAAExgA0GG0IhOAAgA1UCGQAQgYAKgiQgKAigQAYgAUwG0IhPAAIAAjSIBbAAIAADSgAhjDyQgjgQAAgPQAAgOAeAFQAeAHAtAAQAtAAAjgHQAigFAAAOQAAAPgdAQQgeAQgtABQgtgBgjgQgAU8DiIhbAAIkXAAIAAgyIEXAAIAAkDIBbAAIAAEDIFyAAIAAAygAU8CwIhbAAgA0UBMgAAdj9QgmgqgEg4IgBgQIAAgGIABgOQAGg2AkgnQAsgvA9AAQA+AAArAvQAlAoAGA1IABANIAAAHIAAAQQgFA4gnAqQgrAug+ABQg9gBgsgugAB1lrQgHAIAAAKQAAALAHAHQAIAHAKAAQALAAAHgHQAHgHAAgLQAAgKgHgIQgHgGgLAAQgKAAgIAGgAjGjeQg4gDgpgqQgpgngEg3IgBgPIAAgEIABgOQAFg1AognQApgoA4gFIAdAAQA4AFApAoQAnAnAGA1IABANIAAAFIgBAPQgEA3gpAnQgpAqg4ADgAjslvQgIAIAAALQAAAMAIAIQAIAIAMAAQALAAAIgIQAJgIAAgMQAAgLgJgIQgIgJgLAAQgMAAgIAJgAikpoIDJgMIjJAMIgCAAIAAAAIAAgBQgBgEgDAAIAAAAIAAAAIgFADIAAAAIgBAAIAAAAIgBAAIgGgUIAGAUIgsgGIgBAAQgngHgjgIIgfgKIB6AAIHWAXIgaAFIgEABIgKABIgNACIgGAAIgkAFIgpACIgEABIgIAAIg4ABIgDAAIgoABQhkAAhSgJgAiwpqIAAAAIABAAIAAAAIAFgDIAAAAIAAAAQADAAABAEIAAABIAAAAIgKgCgADvptIAagFInWgXIh6AAIhUhAIgDgHIALgnIgBAAIABAAIgLAnIAKgnIAEgSIgQgSIM0ASQgBAPABAPIABALIACAJQADATAPAPIgUAPIAAg6IgUAAIAUAAIAAA6IAAAAIgiAAIgpAQIAAAIIoXAFIIXgFIAAgIIApgQIAiAAQgcAVglAOIgBAAIgBABIgoAKIgDAAIgeAGIAEAAIgHABIgWAEgAEJpyIAegGIADAAIgdAGgAEJpygAlLqKQgZgJgSgMQgZgRgMgZIBUBAIgEgBgAGVqmgAGVqmgAmbrJgAmlr3QgBgRAGgTIAQASIgEASgAmgsbg");
	this.shape_27.setTransform(171,140.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#3366FF").s().p("AAAEEIAAjSIFyAAIAADSgAioEEIjJAAIAAjSIEYAAIAADSgAAAAAIAAkDIFyAAIAAEDgAlxAAIAAkDIDoAAIAGAAIAqAAIAAEDg");
	this.shape_28.setTransform(305,158.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,612.8,416.1);


(lib.reindeer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3366FF").s().p("AguA9IAAh2IArAAIAAAUQAFgOAHgEQAGgFAKAAQAKAAAMAGIgOAhQgIgEgFAAQgJAAgFAIQgGALAAAbIAAAog");
	this.shape.setTransform(595.2,159.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3366FF").s().p("AglA4QgNgHgJgOQgJgPAAgUQAAgbASgRQASgRAfAAQAZAAAPAIQAOAHAIAPQAIAPAAAWIAAAFIhbAAQACALAFAGQAGAIAKAAQAHAAAFgEQAEgCAEgFIAtAEQgKASgPAIQgOAHgbAAQgXAAgOgGgAAWgJQAAgOgHgFQgFgGgJAAQgKAAgHAJQgEAFgCALIAsAAIAAAAg");
	this.shape_1.setTransform(581.5,159.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#3366FF").s().p("AglA4QgNgHgJgOQgJgPAAgUQAAgbASgRQASgRAfAAQAZAAAPAIQAOAHAIAPQAIAPAAAWIAAAFIhbAAQACALAFAGQAGAIAKAAQAHAAAFgEQAEgCAEgFIAtAEQgKASgPAIQgOAHgbAAQgXAAgOgGgAAWgJQAAgOgHgFQgFgGgJAAQgKAAgHAJQgEAFgCALIAsAAIAAAAg");
	this.shape_2.setTransform(566.2,159.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#3366FF").s().p("Ag0BBQgNgTAAgaQAAgcAPgQQAOgQAWAAQAKAAAIAEQAJADAGAHIAAg4IAvAAIAACjIgrAAIAAgSQgJALgIAFQgIAEgNAAQgYAAgNgSgAgOAAQgFAGAAAQQAAAOAGAIQAFAGAIAAQAIAAAGgGQAGgIAAgPQAAgOgGgHQgGgGgIAAQgIAAgGAGg");
	this.shape_3.setTransform(550.6,157.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#3366FF").s().p("AARA9IAAhAQAAgMgEgEQgFgFgHAAQgHAAgGAGQgEAGAAAQIAAA5IguAAIAAh2IAqAAIAAATQAKgLAJgGQAJgFAOAAQAUAAAKAMQALAKAAAYIAABLg");
	this.shape_4.setTransform(535.6,159.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#3366FF").s().p("AgWBSIAAh2IAtAAIAAB2gAgWgyIAAgfIAtAAIAAAfg");
	this.shape_5.setTransform(524.1,157);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#3366FF").s().p("AglA4QgNgHgJgOQgJgPAAgUQAAgbASgRQASgRAfAAQAZAAAPAIQAOAHAIAPQAIAPAAAWIAAAFIhbAAQACALAFAGQAGAIAKAAQAHAAAFgEQAEgCAEgFIAtAEQgKASgPAIQgOAHgbAAQgXAAgOgGgAAWgJQAAgOgHgFQgFgGgJAAQgKAAgHAJQgEAFgCALIAsAAIAAAAg");
	this.shape_6.setTransform(512.7,159.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#3366FF").s().p("AguA9IAAh2IArAAIAAAUQAFgOAHgEQAGgFAKAAQAKAAAMAGIgOAhQgIgEgFAAQgJAAgFAIQgGALAAAbIAAAog");
	this.shape_7.setTransform(500.5,159.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#3366FF").s().p("AglA4QgNgHgJgOQgJgPAAgUQAAgbASgRQASgRAfAAQAZAAAPAIQAPAHAHAPQAIAPAAAWIAAAFIhaAAQABALAFAGQAGAIAKAAQAGAAAHgEQADgCAFgFIAtAEQgLASgPAIQgOAHgbAAQgXAAgOgGgAAXgJQgBgOgHgFQgFgGgKAAQgJAAgHAJQgEAFgBALIAsAAIAAAAg");
	this.shape_8.setTransform(479.2,159.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#3366FF").s().p("AARBSIAAhBQAAgMgEgEQgEgEgIAAQgHAAgFAFQgFAHgBAQIAAA5IgtAAIAAijIAtAAIAAA8QAKgJAIgFQAJgEANAAQASAAALAMQALALAAAWIAABMg");
	this.shape_9.setTransform(463.9,157);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#3366FF").s().p("AgLBQQgIgFgEgJQgEgJAAgUIAAgpIgRAAIAAghIARAAIAAgWIAtgXIAAAtIAZAAIAAAhIgZAAIAAApQAAAIABACQACAFAGAAQAFAAAJgEIAEAgQgRAEgPgBQgQAAgIgDg");
	this.shape_10.setTransform(451.1,157.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#3366FF").s().p("AASBSIgXgwIgRARIAAAfIgvAAIAAijIAvAAIAABUIAhgnIA4AAIgrApIAuBNg");
	this.shape_11.setTransform(431.4,157);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#3366FF").s().p("AgbA7QgMgEgKgHQgJgIgFgLQgFgLAAgRQAAgSAGgMQAFgJAIgHQAIgHAIgEQAOgFAUAAQAdAAAPAKQAPALAHAUIgrAGQgCgIgGgEQgFgEgJAAQgKAAgHAIQgHAIAAAQQAAAPAHAHQAGAIAKAAQAJAAAGgFQAGgEAEgKIArAFQgEAOgIAKQgIAJgNAGQgNAFgTAAQgSAAgNgDg");
	this.shape_12.setTransform(415.8,159.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#3366FF").s().p("AgWBSIAAh2IAtAAIAAB2gAgWgyIAAgfIAtAAIAAAfg");
	this.shape_13.setTransform(404.3,157);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#3366FF").s().p("AgWBSIAAijIAtAAIAACjg");
	this.shape_14.setTransform(396.6,157);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#3366FF").s().p("AgbA7QgMgEgKgHQgJgIgFgLQgFgLAAgRQAAgSAGgMQAFgJAIgHQAIgHAIgEQAOgFAUAAQAdAAAPAKQAPALAHAUIgrAGQgCgIgGgEQgFgEgJAAQgKAAgHAIQgHAIAAAQQAAAPAHAHQAGAIAKAAQAJAAAGgFQAGgEAEgKIArAFQgEAOgIAKQgIAJgNAGQgNAFgTAAQgSAAgNgDg");
	this.shape_15.setTransform(385.8,159.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#663300").ss(1,1,1).p("AIGu1QAEADADADQBPBBBHBWQCwDWBCEOQAmCfAACxQAAHgkYFUQgxA8g1AxAo8O9Qg1gxgxg8QkYlUAAngQAAiPAZiDQA7kzDEjvQBHhWBjhDQgMgFAJgG");
	this.shape_16.setTransform(195.4,208.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(1,1,1).p("AivAAQAAAcgUAUQgLALgPAFQgKAEgLAAQgcAAgUgUQgUgUAAgcQAAgbAUgUQATgTAcgBQAAAAABAAQAcAAATAUQAUAUAAAbgAE2AAQAAAcgUAUQgTAUgcAAQgcAAgUgUQgCgCgBgBQgRgTAAgaQAAgLAEgLQAFgOALgLQAUgUAcAAQAcAAATAUQAUAUAAAbg");
	this.shape_17.setTransform(193.4,201.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#FFFFFF").ss(1,1,1).p("AOvp1QAAArgfAfQgeAfgsAAQgrAAgfgfQgIgIgGgIQgRgZAAghQAAgsAfgfQAQgQAVgIQALgEAMgBQAGgBAIAAQAsAAAeAeQAfAfAAAsgAtskdIAAgNQgHgRgGgQQgIgXgGgVQgUhUgTghIQLAAIAAABQAcAwAHAjQAMA7AGA8QAAAAAAABIiPAEAp8ILQAAgHAAgGQAAhdAdhCQAdhCAqAAQAqAAAcBCQAeBCAABdQAABdgeBCQgcBCgqAAQgqAAgdhCQgDgIgDgHAjUI4QgEghAAgjQAAhhAchGQAbhEAoAAQAnAAAcBEQAcBGAABhQAABigcBEQgcBFgnAAQgoAAgbhFQgGgPgFgQ");
	this.shape_18.setTransform(232.6,142.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FF0000").ss(1,1,1).p("ANdnsQgygShPhtIghgxIghgwQgggwgLgFQg9gfgsgOQgZgJgTgDQgWgDh8AAQhMAAgxA0QglAngWBFQgfBgAACkQAAA1ApBjAtLiMQgJgdgJgZQgSgzgCgIQgFgTAAjAQAAgPABgOQAIloDqipQA1gnBAgcQCPg/DWgWQCQgPD4AAQFSAACnCiQADACACADQBsBsAgCwQANBIAABTQABApgDAsAszg8QACAFABAGQGpAAGoABIAeAAICOABQgBAEgBAEADOg1QAAADgBADIAIAAACakAQAHASAJAUQAKAYAIAVQAYBHgGAwAszg8QgFgTgFgRAszg8QACgCABgBAhCQ4QAAAug5AgQg5AghRAAQhRAAg5ggQg5ggAAguQAAgtA5ghQA5ggBRAAQBRAAA5AgQA5AhAAAtg");
	this.shape_19.setTransform(226.6,119);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#996633").ss(1,1,1).p("AN0LUQFVg8FaAAQgzhhjRhtIkJAAQLUinDYooQANkekMDJQhOEBkpEBQjKCTAlkBQDskZAnk5QgpkdjbDSIgpClAMdqlQhEFuhXC+QhMAkgnhqQApjphWjYARCjGIhjDTQh0AxgshxQB7jmAYj6AvCMSQiRgJiQAEQkVAHkSA6IBBjkQFmhBCAABQAyAAAPALQgWgSgWgSQgLgIgKgJQm9lukemcQghkQEWCJQCaFtFMDmQA0AkA5AhQB0BQAiivQhziUiQjVQhuilh+jLQBPi8CXBiQADAJADAIQCjGzDsDoQCIB7gVisQg7k8iDmtQBqioBPCoICIGV");
	this.shape_20.setTransform(198.7,105.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("ADDAvIgDgCQgRgTAAgaQAAgLAFgLQAEgOALgLQAUgTAcgBQAcABATATQAVAUgBAbQABAcgVATQgTAVgcgBQgcABgUgVgAkiAvQgTgTgBgcQABgbATgUQATgTAcgBIABAAQAcABATATQAVAUgBAbQABAcgVATQgLANgPAEQgKADgLAAQgcABgUgVg");
	this.shape_21.setTransform(193.4,201.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#663300").s().p("Ao8O6Qg1gygxg8QkYlUAAngQAAiOAZiDQA6k0DFjvQBHhWBjhDINRABIAdAAICPABIgCAIIACgIIABgFIAHAFQBPBBBHBWQCwDWBBEOQAnCfAACxQAAHgkYFUQgyA8g0AygAhXBmQg5AhgBAuQABAtA5AgQA4AgBQABQBRgBA5ggQA6ggAAgtQAAgug6ghQg5gfhRAAQhQAAg4AfgAC3lKQgcBFAABhQAAAkAEAgQgEALAAALQAAAaARATQAFARAGAOQAbBFAoAAQAnAAAchFQAchEAAhiQAAhhgchFQgchFgnAAQgoAAgbBFgAjrAEQAeBDApAAQAqAAAchDQAehBAAhcQAAhdgehCQgchCgqAAQgpAAgeBCQgdBCAABdIAAAMQgbABgTASQgUAVAAAbQAAAdAUATQATAUAcAAQAMAAAKgDIAGANgAINuzIgIAAg");
	this.shape_22.setTransform(195.4,209);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ai8KaQgGgPgFgQIACACQAUAVAcgBQAdABATgVQAUgTAAgcQAAgcgUgUQgTgTgdgBQgcABgUATQgLALgEAOQgEgfAAgkQAAhhAchGQAbhEAoAAQAnAAAcBEQAcBGAABhQAABigcBEQgcBFgnAAQgoAAgbhFgApfKdIgGgPQAOgEAMgNQAUgTAAgcQAAgcgUgUQgTgTgdgBIgBAAIAAgMQAAhdAdhCQAehCApAAQAqAAAcBCQAeBCAABdQAABdgeBCQgcBCgqAAQgpAAgehCgAgakbItSgBIAAgOIgNghIgPgsQgThTgTgiIQLAAIAAABIAQAmQALAYAHAVQAMA7AHA8IAAABIiQAFgAL8orQgIgIgGgHQgRgaAAghQAAgsAfgfQARgQAUgIQALgEALgBIAPgBQAsAAAeAeQAfAfAAAsQAAAsgfAeQgeAfgsAAQgsAAgegfg");
	this.shape_23.setTransform(232.6,142.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF0000").s().p("AmPSGQg5ggAAguQAAgtA5ghQA5ggBRAAQBRAAA5AgQA5AhAAAtQAAAug5AgQg5AghRAAQhRAAg5gggAA/gwICPgFIgBAGgAswgxIgDgLIADgDIAAAOIAAAAgAszg8IgKgkIANAhIgDADIADALQgMgFAJgGgAC8itQAYBHgGAwQgGg7gMg8gAswg/gAtdjCIgUg7QgFgTAAjAIABgdQAIloDqipQA1gnBAgcQCPg/DWgWQCQgPD4AAQFSAACnCiIAFAFQBsBsAgCwQANBIAABTQABApgDAsQgMACgLAEQgygShPhtIghgxIghgwQgggwgLgFQg9gfgsgOQgZgJgTgDQgWgDh8AAQhMAAgxA0QglAngWBFQgfBgAACkQAAA1ApBjIwMAAQATAiAUBTIgSg2g");
	this.shape_24.setTransform(226.6,119);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#996633").s().p("A7JJqQFmhBCAABQAyAAAPALIgsgkIgVgRQm9lukemcQghkQEWCJQCaFtFMDmQA0AkA5AhQB0BQAiivQhziUiQjVQhuilh+jLQBPi8CXBiIAGARQCjGzDsDoQCIB7gVisQg7k8iDmtQBqioBPCoICIGVIgBAdQAADAAFATIAUA7IASA2IAOArIAKAkQgJAGAMAFQhjBDhHBWQjEDvg7EzQiRgJiQAEQkVAHkSA6gAKCDwQhHhWhPhBIgHgGIAAgBQAGgwgYhGQgHgjgbgwIAAgBQgphjAAg1QAAikAfhgQAWhFAlgnQBWDYgpDpQAnBqBMgkQBXi+BEluQAsAOA9AfQALAFAgAwIAhAwQgYD6h7DmQAsBxB0gxIBjjTQAFAIAIAHQAfAfArAAQAsAAAegfQAfgeAAgsQAAgrgfgfQgegfgsAAIgOABQADgsgBgpIApilQDbjSApEdQgnE5jsEZQglEBDKiTQEpkBBOkBQEMjJgNEeQjYIorUCnIEJAAQDRBtAzBhQlaAAlVA8QhCkOiwjWg");
	this.shape_25.setTransform(198.7,105.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,606.2,306.4);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.reindeer = new lib.reindeer();
	this.reindeer.name = "reindeer";
	this.reindeer.parent = this;
	this.reindeer.setTransform(302.4,152.2,1,1,0,0,0,302.4,152.2);
	new cjs.ButtonHelper(this.reindeer, 0, 1, 1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#663300").ss(1,1,1).p("AmhA6QhRgwhKhEAI9g6QhKBEhQAw");
	this.shape.setTransform(195.4,310.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#663300").s().p("AmiA7QhQgxhKhDIR5AAQhKBDhRAxg");
	this.shape_1.setTransform(195.4,310.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.reindeer}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,606.2,318.1);


// stage content:
(lib.AnimatedCardNAyala = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop(); // This will make the main timeline stop on current frame
		
		this.btn_reindeer.addEventListener("click", fl_ClickNextScene.bind(this));
		
		function fl_ClickNextScene()
		{
			// Actions you want the button to do go here
			this.play();
		}
	}
	this.frame_10 = function() {
		this.stop(); // This will make the main timeline stop on current frame
		
		this.btn_reindeer2.addEventListener("click", fl_ClickNextScene.bind(this));
		
		function fl_ClickNextScene()
		{
			// Actions you want the button to do go here
			this.play();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(25));

	// Label
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3,1,1).p("EAq4gXSIAAjNEAoOgZtICqCbICpCbIALAKIADACIgDADIAAGzICqCMEAtsgeZIAADNIAADNIBkiCEAx2gY9IhUBXICoAAEAx2gY9IAAiyEA0ugcXIi4DaEAtsgbMIjch9EA0kgU3IAACgEA0kgU3ICMAAICgCqEA2wgU3ICqAAEAtsgU3IAOAAIgLAMIDkDRIBzBpIEIAAEAtsgUtIAAAFIi5DBIAAAAIjhAAEAthgU3IALAAIAAAKEAtsgN1IAACqEAzGgPxIByBoEAxTgRaIAACpEAt6gU3IGqAAICWjIEAqzgRnIAAAAIkxEuEAqzgRnIAABcEAqzgRnIAAAAEAi6gU3Ih4CgEAi6gU3IhuAAEAoOgU3IiWCWEAi6gU3IFUAAIiMh4EAtsgN1IjIBuEAoOgU3IFTAAEAi6gU3Ih4i0EAwigXmIioCvEAtsgX/IAADIEA71AkBIhPBBIB4AAEA9EAjAIAAAAIAAAAIAAAAICSAAEA+IAmIIBQAAIBQAAEA+IAmIIBOhOEA71AkBIAAjJEA9EAjAIAAhlEA+TAh+IhPBCEA9EAjAIhPBBEA8/AmIIBJAAEAiKAOkIAAh0EAiKAOjIAAABIBpBnIAEAEIAMAMIBHBGIAABeEAiKAOjIhSAAEAlIAO8IBjAAEAmVAN0IhNBIIhFBAIAAATIDCAAIBgAAIBhAAEAmVAN0IAAhTEAkDAOGIA/hCEAkDALmIAACgIhGhKEAj3AQPIAMAAIAAAMIAACUIBPBiEAkDAP8IgQAPIgEAEIAIAAEAlKARhIBHBFIAsAsIAAA/EAiEARzIAAAAIiaB/EAiEARzIAAAAIimAAEAiEARzIAAAAIAABrEAkDATmIAAB5EAkDASvIAAA3IhdBdEAhMAQPICjAAIhrBkEAnFAQPICSBWEAm9ATSIAtArEAoGAMRIhxBjEAkDAOGIAAB2EAolAQPIBhhKEAnFAQPIBEhSEAmRASmICAAAEA3GAkrQhHgpiQA4ICEBOIBJAAICSAAIABABIAIAFICIBeIAABYEA0DAmIIBwAAEA1BAjPIBZA+IAsAeICIBdIADAAIgCABIh4BkIg0AqIhiAAEA5XAjQIAABZIAABaIAAAFIAAAGIAACXIAABMIAABMEA5XAmDIgGAFIAGAAIDoAAIAtA7EAznAiSIBaA9Ih5AAEA2aAkNIABiHEA5XAjQIhWh1EA5XAgdIAACzEA5XAolIg/AAEA2jAoXIh8BnIAABfEA0nAp+IgwAnEA3XAntIgsCtEA9CAowIAAAAICnAAEA7fAnsIBjBEIAAByEA9CAowICgBuEA/YAmIIA8BDEA5XApxIBKBMEA28AmIIhIA7EA5XAkpIBChkEA6mAlCIhPBBEAaVgumIAAhjEAcHgwAIAAAzIgrgwEAcHgwAIBCAAEAe3gvoIgdAcIB+AAEAe3gvoIAAhfEAgRgw8IhaBUEAcHgyVIAACVEAZpgqvIhgBNEAaAgtdIhcgzEAX5gtdICHAAICHAAIAPAAIAMAAIgEAFIgXAVIAACKIg3AAEAV0gtdICFAAIhaBeEAePgsYIBLAAEAePgsYIAzAdIAABSEAddgs1IAyAdEAddgs1IAAB4EAfxgtdIAvAAIBShSEAcHgtlIAPAIIAIAFIA/AjEAcHgtlIAAAIIAAAaIhPBKIhxAAEAcHgq5IA6BHEAcHgq5IAACJEAcigtdIDPAAIBLBDEAeagvMIh4BvEAcHgvNIAABoEAaVgumIByBBEAX5gtdIh9hGEAa4gr5IhPBKIBABvEAXygwFICjBfEgELggeIAAhFEgELggeIAgAgIg/AAEgEsgg+IAhAgEgB9gh6IAAA6IBkg3Ah9/NIAvgyEgB9ggHIAAA6IAAA6IAAACIAAADIAACKIAAAnIhTAoEgB9ghAIAAA5IhJgyAAo/qIgeAQIBFAcAAo/qIAAhlAh7+RIAEAAIgDABIgDACIiPBQIgqAYIh9gyAh7+RIABABIB7B5IAaAZIB6AAAh9+RIACAAAh9+TIACACAh98EIBGAsAh3+RICPAAIBrAAICFAAAlX+RIA6AAIgZAlAkM8+IAABUAkd+RICgAAAAB8XIAABYAh97dIAABkAAb7+IA+A8AAK/aIiBBJEABoggOIhAAkACD+RIBJgwAAY+RIAtA5Ajr/+IBuBrAlX+RIg+hsAm2+RIBfAAAk28mIgyAcAwhjlIAAiPAwhjlICkAAAvMFsICriuAvMFsID9AAAPWgWIAAhEAQKhAIg0AqIgwAlIA/AAAK3gTIABhYANCgdIhBg/AJwhUIBHBBIAbAWIAbAYIgZAdANCg5IAAAcIAAB8IABAAIgBABIAAAIIAACQIg8BAANCiaIAABhIAtgyANCBfIAAABIgFAEIAFAEIBmBbIBKBDIBMgSAM4BfIAKAAAM4BfIAFAFIhhBOIgaAVIgbAWIgUBRALcCyIAMBFALtAbIBLBEAKyBfICGAAAI6BqIgmBGANCD4IAABBIAABIAKnDdIg3AsAHuBfIDEAAIg8hAALCDHIhSgaAOmCwIACATIAIBRAOwCxIBSAAAPyEGIAOANIAoAdAPlEHIAYBFAQVBPIA8geAQLB0IBVA6ALtAbQAIgNgSguALSADIiSgYAN5AkIAAgkANCE5IA1AhAOmAPIhjBQIErAAEg3YgsDIB9hVEg3YgtnIAABkIAADLQAEgBAGAAQAjAAAaAaQACACACADQAbAeAAArQAAAKgBAJICLAAIBuAAIDSAAIBQAAEg2RgofICHhgIAAisEg0Kgp/IBAgtICHhgIAAh+EgxDgsMICHhgEgx6gm+IClg3EgzKgqsIDhAAEg3YgxIIAADhIibibEg/bgm+IhCi+EhAngm+IBMAAIBLAAIBaAAIg3hGEg60grTIAyg1Eg70gsaIh+AAEg4qgm+QgBgJAAgKQAAgrAbgeIAAAAQAXgbAhgDEg4ngm0QgCgFgBgFEg51gqLIBlBxEg82gm+IEMAAEg51gqLIjQA3Eg70gsaIBABHIA/BIEg70gsaIAAidEg9yguoIB+COEg7AglHIhTg2Eg7AglHIAYgRIAAB2Eg8YgkJIBYg+Eg+Ggi6IBuhPIiqAAEgzagi/IAAAAIAAC+Egzagi/IAAAAIChAAEgzagi/IAAAAIBMBVEg0mgkUIBMBVEg2NgmHQgbAegmAAQgGAAgEAAIAABkIAABCIAABDIAACEEg2NgmHIBnBzIAACCEg3YgjDIBBA7Eg1zgm+QgFAfgVAYEg3YglpQghgEgXgaQgRgUgGgZEg6oglYICBhcEguogm+IA3BaEgx6gm+IBpCWEgzogm+IAAB9Eg3YgiAIhzBwEg3YgkFIhfAAEg+Qgm+Ih5BfA7uoEIDXjMEgqwAFsICMAAICOAAIEZAAIExAAQAEgiAZgZIAAAAQAcgbAlgCQAEgBAEAAQAqAAAeAeQAHAHAFAIQAOAUADAYQABAHAAAGQAAAqgeAeQAAAAAAAAQgeAegqAAQgEAAgEAAQgigCgagXQgDgDgCgCQgdgdAAgrQAAgGAAgHEgokAFsIhvjaEgkMgCnIC0CxIk5AAEghYAAKIAAjGAzRhKIAAkBA7ujQIAACZIFTi4A7uAwIiEAAA+mC7IB3B2A7uAwIAADkA1dAwIABAAICSE8IAACPA6BFsIG3AAID+AAIDKCaA6SFAIE1kQImRAAA1cAwICLh6ICwibA7ug3IAABnA7ujQIlRikA7uoEIAAE0EghYAAKICyCxIjXCxIAAEfA7uoEIjCh6A2jK6IBTBSIAAEtA7uM7IClAAA7uM7IAAB8IAABaIAADWA7uQRID2AAEghwALkIDBiqIAADgEghwALkIB7DHEghwALkIlfAAEglmAOoID2jEA7uO3IkHBwEg6GAmnIh+AAEg7UAlKIBOBdIAyA8IAAiCEg3DAlMIBhg1Eg2/AjoIgEBkIgFBlIhkiqEgxMAqCIBCBaEgxMAqCIBiAAEgz/AnBIB0AAEgzkAqCIA2AAIBiAAEg3TAp8IgHAGIAJAAIgIC1IgEBZIgDBSIAAC0Eg3RAp6IgCACIACADIADADIBrCAIApAyIBGBTIAjAqIBGBQEg3RAp6IAAAFIAAADIADAAIDqAAIBSBSEg3IAmxIBvAAEg3IAmxIgJDJEg1GAoAIiLB6Eg1jAs0IApAAIBpAAEg1jAs0IAAAxEg1jAsCIAAAyEg1GAoAIBaAAEgz/AnBIhHA/EgzRAuxIA/AAEg3dAuQIBBBKEgz0AuHIAABrEgyuAqCIBahGEg5UAnjIhtAAEg6eAqCIgrhOEg8AAqCIhWhWEg9hAqCIBhAAIBiAAIgvBHEg5sAsDIAABaEg5sAsDIgYAVIhGA/IAAB8Eg8AAqCIhWBLEg6EAsYIhwAAEg7KAtXIhgBUEg5UAnjICBCZEg6eAqCIDEAAIiSCBEg3gAviIiLBaEg3ZAs3IhcA+Egz/AnBIAAiLEgyiAllIhdBcAfVQPIBAAAIhGiBAeUQPIBBAAIhUhDA6eHBID7D5IEmAAA7uHfIAAFcA+vI6ICFh0AzRhKIFKCiEgmWAFsIAADsA1QMMIDnDlEAfCgr7IBmA6EAgggtdICgAAEAghAM8IBpBnEAhMAQPIhDA2EAgVAQPIA3AA");
	this.shape.setTransform(439.6,346.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#6666FF").ss(1,1,1).p("AHA06QAAAbgTAUQgUATgbAAIAAAAQgcAAgTgTQgUgUAAgbQAAgcAUgTQATgUAcAAIAAAAQAbABAUATQATATAAAcgAGNCcQAAAXgPAQQgBABAAAAQgRARgXAAQgYAAgQgRQgRgQAAgYQAAgXARgRQAQgQAYAAQAXAAARAQQAAABABABQAPAQAAAWgAm/VbQADgBAFAAQAHAAAFAFQAGAFAAAIQAAAHgGAFQgFAGgHAAQgFAAgDgC");
	this.shape_1.setTransform(974.1,249.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#0000CC").ss(1,1,1).p("AMD2OQAAAegUAVQgVAVgeAAQgeAAgVgVQgVgVAAgeQAAgeAVgVQAVgVAeAAQAeAAAVAVQAUAVAAAegAgwKSQAAAcgUATQgUAUgbAAQgcAAgTgUQgUgTAAgcQAAgbAUgUQATgTAcAAQAbAAAUATQAUAUAAAbgApkWIQAAAhgXAXQgXAXghAAQghAAgYgXQgWgXAAghQAAgSAHgPQAFgNAKgLQAYgXAhAAQAhAAAXAXQAWAXABAfQAAABAAACg");
	this.shape_2.setTransform(931.7,293.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFF00").ss(1,1,1).p("AKH1kQAAAjgZAZQgYAZgjAAQgjAAgZgZQgZgZAAgjQAAgjAZgZQAZgYAjAAQAjAAAYAYQAZAZAAAjgAozF+QAAAmgbAbQgbAbgnAAQgPAAgOgEQgUgHgQgQQgbgbAAgmQAAgnAbgbQAbgbAmAAQAcAAAWAPQAJAFAHAHQAbAbAAAngALtVbQAAAngcAcQgaAagmACQgBAAgCAAQgnAAgcgcQgbgcgBgmQAAgBAAAAQAAgoAcgcQAcgbAnAAQACAAABAAQAmABAaAaQAcAbAAAnQAAABAAABg");
	this.shape_3.setTransform(946.6,324.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#CC3366").ss(1,1,1).p("AGulEQAAAtgfAfQgQAQgTAIQgTAIgWAAQgtAAgfggQgggfAAgtQAAgdAOgYQAHgMALgLQAfgfAtAAQAWAAATAIQATAIAQAPQAfAgAAAsgAgYp2QAAAagSASQgSASgaAAQgZAAgSgSQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZgAiTInQAAAGgBAGQgEAzglAkQgpAqg6AAQg7AAgpgqQgjgjgGgvQAAgIAAgJQAAg6ApgqQALgLANgIQAhgWArAAQA6AAApApQAJAJAHAKQAaAjAAAug");
	this.shape_4.setTransform(975.9,405.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#66CCFF").ss(1,1,1).p("ABXAAQAAAkgaAZQgVAWgdADQgFABgGAAQgjAAgagaQgZgZAAgkQAAgjAZgaQAagZAjAAQAGAAAFAAQAdAEAVAVQAaAaAAAjg");
	this.shape_5.setTransform(1011.2,226.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FF6666").ss(1,1,1).p("AHajaQAAAYgLASQgGAJgHAHQgYAYgiAAQgiAAgYgYQgSgRgFgYQgBgIAAgJQAAgiAYgYQAYgYAiAAQAiAAAYAYQAYAYAAAigAlvBGQAFAAAFAAQAcAAAXALQAQAIAOAOQAiAiAAAwIAAAAQAAAwgiAiQghAigwAAQgwAAgigiQghghgBguQAAgBAAgCQAAgwAigiQARgRAWgI");
	this.shape_6.setTransform(901.9,444.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#33CCFF").ss(1,1,1).p("AFsJNQAABAgtAtQgtAthAAAQhAAAgtgtQgtgtAAhAQAAhBAtgtQApgpA6gDQAFgBAFAAQAmAAAgARQAVAKASASQAtAtAABBgAEZojQAABQg5A5Qg5A6hRAAQhQAAg4g6Qg5g5AAhQQAAhQA5g5QAGgHAHgGQA0gtBHAAQBRAAA5A6QAmAmANAwQAGAYAAAbgAhrAvQAAA0glAmQgmAlg1AAQg1AAglglQgmgmAAg0QAAg0AmgmQALgLAMgIQAegSAlAAQA1AAAmAlQARASAKAVQAKAXAAAcg");
	this.shape_7.setTransform(943.7,319);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#006600").ss(1,1,1).p("AIkfeIMPgMMgLCg/MIk5KNIixF0IigFPIiQEtIiBENIiyFyIh4D8IiMEkIhHCTAt2RbIgzBqIiSEyIhZC7IhPCkIhPClIDRgDAmqftIBZgBAt6f0IFvgFAg4foIF7gH");
	this.shape_8.setTransform(966.7,259.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FF0000").ss(1,1,1).p("AJ/6tQBQB4BAgLQA2gJArhkAFcvFQAQgFATAAQAxAAAiAiQAaAaAHAiQACALAAANQAAAxgjAiQgiAjgxAAQgxAAgigjQgjgiAAgxQAAgxAjgjQAVgVAbgIQBLA4BMAhQCMA8CQgUQA4gHA4gTAHN06QBfEDDjhaQAygUA5glAIwCoQgKgHgKgJQgngoAAg4QAAg4AngoQAognA5AAQA5AAAnAnQAoAoAAA4QAAA4goAoQgnAog5AAQgDAAgDAAQBRBEBHAUQA/ASA2gTACdq+QEsDeFGgIQA9gBA9gKAAcmxIAfAKQCSB2CmgUQDRCJDLAeQBIAKBGgCAIwCoIBHAYQgngCgggWgAkNC+IBAAUIC4A6QG5DfFrA1QA0AHAyAEAmZHhQFlCZFcBKQAoAIAoAIQCJAZCHANIDJA1AEtvrQAXAUAYASAmLTyQCuCkDUhlICWAZQBhB0CWhLIDwAnQgJAbgVAVQgkAkgzAAQgzAAgkgkQgkgkAAgzIAAAAQAAgzAkgkQAkgkAzAAQAzAAAkAkQAkAkAAAzQAAAVgGASQBfAcA8AMQBUARASgOAoATeQgHgFgGgHQgmglAAg1QAAg1AmgmQAlglA1AAQA1AAAmAlQAlAmAAA1QAAA1glAlQgXAXgcAJQgTAGgVAAQgsAAghgagAucYWQBRBIB6gWQAPgGASgBIA8ALQDTBcDdAGIBhgBAtOVxIA7AMICYAeQFPCsFhgkIDAAmQDKBWDLACIAjAAAr0S2QBmA9COgVIB1AUApiOEQMrEmJGgBQA3gBA0gCAiVg9QFiDvFjgK");
	this.shape_9.setTransform(934,291.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#663300").ss(1,1,1).p("EAoPgfqIDwAAIAAKVIjwAAgA+5d5QhiA6hrAcQgHACgHACQhgAXhoAAQhoAAhggXQgHgCgGgCQhsgchhg6");
	this.shape_10.setTransform(706.2,664.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6666FF").s().p("AnHV4QgFgFAAgHQAAgIAFgGQAGgEAHAAQAEgBAEACIAFADQAFAGAAAIQAAAHgFAFIgFAEQgEACgEAAQgHgBgGgFgAE5DFQgQgRAAgYQAAgXAQgQQARgRAYAAQAXAAAQARIACABQAPAQAAAWQAAAXgPAQIgCACQgQAQgXAAQgYAAgRgQgAGKz4QgbAAgUgTQgTgUAAgbQAAgbATgUQAUgTAbAAIABAAQAbAAATATQAUAUAAAbQAAAbgUAUQgTATgbAAg");
	this.shape_11.setTransform(972.8,249.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0000CC").s().p("ArsXAQgXgXAAghQABgSAGgPICYAdIAAAEQABAhgYAXQgXAXghAAQghAAgYgXgAr8VnQAGgNAKgLQAYgXAhAAQAhAAAXAXQAWAXABAegAr8VngAiiLBQgUgTABgcQgBgbAUgUQAUgTAbAAQAcAAATATQATAUABAbQgBAcgTATQgTAUgcAAQgbAAgUgUgAKI1bQgUgVAAgeQAAgeAUgVQAWgVAeAAQAdAAAWAVQAUAVABAeQgBAegUAVQgWAVgdAAQgeAAgWgVg");
	this.shape_12.setTransform(931.7,293.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#CC3366").s().p("AmEKKQgjgjgGgvIAAgRQAAg6ApgqQALgLAMgIQAigWArAAQA6AAApApQAJAJAHAKQAaAjAAAuIgBANQgEAyglAkQgpAqg6AAQg7AAgpgqgAitHWIjAgmgAD3j3QggggAAgtQAAgdAOgYIDJA1QAAAtgfAgQgQAPgTAIQgTAIgWAAQgtAAgfgfgADll5QAHgMALgKQAfggAtAAQAWAAATAIQATAIAQAQQAfAfAAAsgADll5gAiBpKQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSg");
	this.shape_13.setTransform(975.9,405.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#66CCFF").s().p("Ag9A9QgZgZAAgkQAAgjAZgZQAagaAjAAIALABQAdADAWAWQAZAZAAAjQAAAkgZAZQgWAWgdADIgLABQgjAAgagag");
	this.shape_14.setTransform(1011.2,226.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF6666").s().p("Am3ELQghghgBguIAAgDQAAgwAigiQARgRAWgIQAQgHARgBIA9ALQAQAIAOAOQAiAiAAAwIAAAAQAAAwgiAiQghAigwAAQgwAAgigigAkyBRgAlvBGIAKAAQAcAAAXALgAFOigQgSgRgFgYICXAZQgFAJgHAHQgYAYgiAAQgiAAgYgYgAE3jJQgBgIAAgJQAAgiAYgYQAYgYAiAAQAiAAAYAYQAYAYAAAiQAAAYgMASgAE3jJg");
	this.shape_15.setTransform(901.9,444.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#33CCFF").s().p("ABlK6QgtgtAAhAQAAhBAtgsQApgqA6gDIAKAAQAmAAAgAPQAVALASATQAtAsAABBQAAA/gtAuQgtAshAABQhAgBgtgsgAEYHCIhQgPIBQAPgAlGCJQglgmAAg0QAAg0AlgmQAMgLANgIIC4A6QAKAXAAAcQAAA0gmAmQglAmg1AAQg1AAgmgmgAktg+QAdgTAlAAQA1AAAlAmQASASAKAVgAktg+gAgymZQg5g5AAhRQAAhRA5g5IANgLIABABIAKAHIAAAAQB4BdCGAAIAAAAIAAAAQAXAAAYgDQAGAYAAAbQAABRg5A5Qg5A4hRAAQhQAAg4g4gADkpTQiGAAh4hdIAAAAIgKgHIgBgBQA0gtBHAAQBRAAA5A4QAmAnANAwQgYADgXAAIAAAAIAAAAg");
	this.shape_16.setTransform(943.7,319);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006600").s().p("AzjdWIACACIACACIABABQA9AzBTAAIAAAAIAAAAQAaAAAcgFQgWAIgRARQgiAjAAAvIAAAEIjRADgAuceiQgOgOgQgIQgXgLgcAAIgKAAQgRACgQAGQgcAFgaAAIAAAAIAAAAQhTAAg9gzIgBgBIgCgCIgCgCIBOilIBai6ICSkyIAzhqQAOAFAPgBQAnAAAbgbQAbgbAAgmQAAgmgbgbQgHgIgJgFIBHiTICMkkIB4j8ICylzICBkNICQksQAYATAWASQgaAIgVAVQgjAjAAAxQAAAxAjAiQAhAjAxAAQAxAAAjgjQAigiAAgxQAAgMgCgMIAIADIAAAAQBmAqBoAAIAAAAIAAAAQAiAAAjgEIABAAQA4gIA4gTQg4ATg4AIIgBAAQgjAEgiAAIAAAAIAAAAQhoAAhmgqIAAAAIgIgDQgHgigZgaQgjgigxAAQgSAAgRAFQgWgSgYgTICglPIAAACQBGC9COAAIABAAIAAAAQAxAAA5gWIACgBQAygUA5glQg5AlgyAUIgCABQg5AWgxAAIAAAAIgBAAQiOAAhGi9IAAgCICxl0IACACIACADIABACIAAAAIACADQBFBjA4ABIACAAIAAAAIAKAAQA2gJArhlQgrBlg2AJIgKAAIAAAAIgCAAQg4gBhFhjIgCgDIAAAAIgBgCIgCgDIgCgCIE5qNMALCA/MIsPAMQAAgmgcgcQgagagmgBIgDAAQgnAAgcAbQgcAdAAAnIAAABIgjAAQjKgBjKhWQgHgKgJgJQgpgpg6AAQgrAAgiAWIgDAAIgBAAQg6AGg6AAIAAAAIAAAAQkWAAkLiDIAAAAIgJgEIgPgIIAPAIIAJAEIAAAAQELCDEWAAIAAAAIAAAAQA6AAA6gGIABAAIADAAQgMAIgLALQgpAqAAA6IAAARIhZABIhhACQjdgGjShdQDSBdDdAGIlvAFQAAgwgigigABhZcQgkAkAAAzIAAAAQAAAzAkAkQAkAkAzAAQAzAAAkgkQAVgVAJgaQBfAbA8AMIADABIAMACIAAAAIAAAAIABAAQAjAGAVAAIAAAAIAAAAQAVAAAIgGIABAAIgBAAQgIAGgVAAIAAAAIAAAAQgVAAgjgGIgBAAIAAAAIAAAAIgMgCIgDgBQg8gMhfgbQAGgTAAgVQAAgzgkgkQgkgkgzAAQgzAAgkAkgAxKamQgKALgGAMQgHAPAAASQAAAiAXAXQAYAXAhAAQAhAAAXgXQAXgXAAgiIAAgDQgBgfgWgWQgXgXghAAQghAAgYAXgAgvbRQAxAAA7geQg7AegxAAIgBAAIAAAAQhOAAg7hHQA7BHBOAAIAAAAIABAAgAxaa9Ig7gMgAk5YnQgYAYAAAhQAAAJABAIQAFAYASASQAYAYAigBQAiABAYgYQAHgIAFgJQAMgSAAgYQAAghgYgYQgYgZgiAAQgiAAgYAZgAnraYQBJAABQglIACgCIgCACQhQAlhJAAIgBAAIAAAAQh4AAhqhjIgBgBIgDgCQAcgJAXgWQAlgmAAg1QAAg1glglQgmgmg1AAQg1AAglAmQgmAlAAA1QAAA1AmAmIAOAMIgBAAIgFABIAAAAQghAEgfAAIAAAAIAAAAQhfAAhKgqIgEgDIgCAAIACAAIAEADQBKAqBfAAIAAAAIAAAAQAfAAAhgEIAAAAIAFgBIABAAQAhAZArAAQAWAAASgGIADACIABABQBqBjB4AAIAAAAIABAAgAHCXpIADAAIABAAIABAAIABAAQA3AAA0gDQg0ADg3AAIgBAAIgBAAIgBAAIgDAAIAAAAIgBAAQo4AAsTkZIgSgGIgNgFIANAFIASAGQMTEZI4AAIABAAIAAAAgAiAQxQgtAtAABAQAABAAtAtQAtAtBAAAQA/AAAtgtQAtgtAAhAQAAhAgtgtQgSgSgWgLQCJAZCHANQgOAYAAAdQAAAtAgAgQAfAfAtAAQAWAAATgIQATgIAQgPQAfggAAgtQAAgsgfgfQgQgQgTgIQgTgIgWAAQgtAAgfAgQgLAKgHAMQiHgNiJgZQgfgQglAAIgLAAQlchJlmiZQFmCZFcBJQg5AEgpApgAltUUQAHAAAFgFQAGgGAAgHQAAgIgGgFQgFgFgHAAQgEAAgEACQAEgCAEAAQAHAAAFAFQAGAFAAAIQAAAHgGAGQgFAFgHAAQgEAAgEgCIAFgDQAFgGAAgHQAAgIgFgFIgFgDQgEgCgEAAQgHAAgGAFQgFAFAAAIQAAAHAFAGQAGAFAHAAQAEAAAEgCQAEACAEAAgAoAO6QgUAUAAAbQAAAbAUAUQATATAcABQAbgBAUgTQATgUAAgbQAAgbgTgUQgUgTgbAAQgcAAgTATgAglMSQgSASAAAZQAAAaASASQASASAYAAQAaAAASgSQASgSAAgaQAAgZgSgSQgSgSgaAAQgYAAgSASgAHINgQA0AIAyADQgygDg0gIQlqg0m6jfQG6DfFqA0gAoUITQgNAHgLALQglAmAAA1QAAA1AlAlQAmAmA1AAQA1AAAlgmQAmglAAg1QAAgcgLgXQgJgWgSgSQglglg1AAQglAAgeATgAIDJhQAbAAAagIIAAAAIAFgCIgFACIAAAAQgaAIgbAAIgBAAIAAAAQgcAAgegIQhGgVhRhEQBRBEBGAVQAeAIAcAAIAAAAIABAAgAoUITIhAgVgAExIAIAFAAQA5AAAngoQAogoAAg4QAAg4gogpQgngng5AAQg4AAgoAnQgoApAAA4QAAA4AoAoQAJAJALAIIgcAAIAAAAIgBAAQlKAAlMjaIAAgBIgFgDIgDgCIAAAAIgLgHIALAHIAAAAIADACIAFADIAAABQFMDaFKAAIABAAIAAAAIAcAAQAfAWAoABgAkLhnIgNAMQg5A5AABPQAABRA5A5QA5A5BQAAQBRAAA5g5QA4g5AAhRQAAgagGgYQgNgwglgmQg5g5hRAAQhHAAg1AtgAI6CqIAdgBIgdABIAAAAIAAAAQg0AAg0gIIgCAAIgDAAIgFgBQjKgejRiIQDRCIDKAeIAFABIADAAIACAAQA0AIA0AAIAAAAIAAAAgAF3ALQgRAQAAAYQAAAXARARQAQARAYAAQAXAAARgRIABgBQAPgRAAgWQAAgWgPgRIgBgBQgRgQgXAAQgYAAgQAQgAkLhnIgfgKgAGxinIAXgBQA9gBA9gKQg9AKg9ABIgXABIAAAAIAAAAQk6gBkgjWQEgDWE6ABIAAAAIAAAAgAGAmEQgaAZAAAkQAAAkAaAZQAZAaAkAAIALgBQAdgDAWgWQAZgZAAgkQAAgkgZgZQgWgWgdgDIgLgBQgkAAgZAagAEusaQgZAYAAAjQAAAkAZAYQAZAZAjAAQAjAAAYgZQAZgYAAgkQAAgjgZgYQgYgZgjAAQgjAAgZAZgAEqxrQgVAWAAAeQAAAdAVAWQAVAUAeABQAegBAVgUQAVgWAAgdQAAgegVgWQgVgUgeAAQgeAAgVAUgAGZ3TQgUAUAAAbQAAAcAUAUQATATAcAAIAAAAQAbAAAUgTQATgUAAgcQAAgbgTgUQgUgTgbAAIAAAAQgcAAgTATgAg3fbQAAgugagjQDKBWDKABIl7AHIABgNgAhReKIAAAAgAkRdkIAAAAgAl1USIAAAAgAAxQUIAAAAgAgeQEIAAAAgACsosIAAAAgAgZqqIAAAAg");
	this.shape_17.setTransform(966.7,259.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("AFAS5QgkgkAAgzIDvAnQgIAagWAWQgjAjgzABQgzgBgkgjgAILSJIjvgnIAAAAQgBg0AlgkQAkgjAzgBQAzABAjAjQAkAkAAA0QABAVgHASgAEcRigApoPNIgOgMQgmglAAg2QAAg1AmglQAmglA0AAQA1AAAmAlQAmAlAAA1QAAA2gmAlQgWAWgcAKIh1gUIB1AUQgTAFgWAAQgrAAghgZgAIPhRIhHgXQgLgHgJgJQgogoAAg5QAAg4AogoQAogoA5AAQA4AAAnAoQApAoAAA4QAAA5gpAoQgnAng4AAIgGAAgAHIhoIBHAXQgogBgfgWgADDwSQgjgjAAgxQAAgwAjgjQAVgVAbgIQBLA4BMAhQACALAAAMQABAxgjAjQgiAjgygBQgwABgjgjgADzzWQARgGASAAQAyABAiAiQAaAaAGAiQhMghhLg4gADzzWIAAAAg");
	this.shape_18.setTransform(944.5,319);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ANoYMQgjgCgagXIgEgFQgegdAAgrIABgNQAEgiAYgZIABAAQAbgbAmgCIAHgBQArABAdAdQAHAHAGAIQAOAUADAYIAAANQAAArgdAdIgBAAQgdAfgrAAIgHgBgAuC08QgggEgXgaQgSgUgGgYIgCgLQgBgJAAgKQAAgqAbgfIAAAAQAXgaAggEIAKAAQAkAAAaAaIAEAEQAbAfAAAqQAAAKgCAJQgEAfgVAYQgbAegnABIgKgBg");
	this.shape_19.setTransform(174.9,239.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#663300").s().p("EgokAfTIgOgEQhrgchhg6INFAAQhiA6hrAcIgOAEQhgAYhogBQhoABhggYgEAoPgVVIAAqUIDwAAIAAKUg");
	this.shape_20.setTransform(706.2,664.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFF00").s().p("AKOW5QgnAAgcgbQgbgcgBgmIAAgCQAAgnAcgcQAcgcAnABIADAAQAmABAaAaQAcAbAAAmIAAACQAAAogcAcQgaAagmABIgDAAgAqtHVQgUgGgQgQQgbgbAAgmQAAgnAbgbQAbgbAmAAQAcAAAWAPQAJAFAHAHQAbAbAAAnQAAAmgbAbQgbAbgnAAQgPAAgOgFgAH30pQgZgYAAgjQAAgjAZgZQAZgZAjAAQAjAAAYAZQAZAZAAAjQAAAjgZAYQgYAZgjAAQgjAAgZgZg");
	this.shape_21.setTransform(946.6,324.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNg");
	this.shape_22.setTransform(424.5,464.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(3,1,1).p("AhmAAQAAAVgPAPQgPAPgWAAQgVAAgPgPQgPgPAAgVQAAgVAPgPQAPgPAVAAQAWAAAPAPQAPAPAAAVgADOgJQAAAJgGAFQgGAHgJAAQgJAAgHgHQgGgFAAgJQAAgJAGgGQAHgGAJAAQAJAAAGAGQAGAGAAAJg");
	this.shape_23.setTransform(438.7,466.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#FFFFFF").ss(3,1,1).p("ACAAAQAAA1glAmQgmAlg1AAQg0AAgmglQglgmAAg1QAAg0AlgmQAmglA0AAQA1AAAmAlQAlAmAAA0g");
	this.shape_24.setTransform(457.8,468.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("Ai+AlQgPgQAAgVQAAgUAPgQQAPgPAVABQAWgBAPAPQAPAQAAAUQAAAVgPAQQgPAPgWgBQgVABgPgPgACpAFQgGgFAAgJQAAgIAGgHQAHgGAJAAQAJAAAGAGQAGAHAAAIQAAAJgGAFQgGAHgJAAQgJAAgHgHg");
	this.shape_25.setTransform(438.7,466.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhaBbQglgmAAg1QAAg0AlglQAmgmA0AAQA1AAAlAmQAmAlAAA0QAAA1gmAmQglAlg1AAQg0AAgmglgAgUgyQgHAHAAAJQAAAJAHAGQAGAHAJgBQAIABAGgHQAGgGABgJQgBgJgGgHQgGgFgIAAQgJAAgGAFg");
	this.shape_26.setTransform(457.8,468.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_22}]},10).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]},10).to({state:[]},10).wait(5));

	// reindeer
	this.btn_reindeer = new lib.Symbol3();
	this.btn_reindeer.name = "btn_reindeer";
	this.btn_reindeer.parent = this;
	this.btn_reindeer.setTransform(573.5,697.9,1,1,0,0,0,302.4,158);
	new cjs.ButtonHelper(this.btn_reindeer, 0, 1, 1);

	this.btn_reindeer2 = new lib.Symbol1();
	this.btn_reindeer2.name = "btn_reindeer2";
	this.btn_reindeer2.parent = this;
	this.btn_reindeer2.setTransform(633.4,538.8,1,1,0,0,0,304.9,206.6);
	new cjs.ButtonHelper(this.btn_reindeer2, 0, 1, 1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FFFFFF").ss(1,1,1).p("AGuikQBVgzBFASQAhAIAdAYIAAAAQAsAjAkBFAsQoIIAAhiIAAhMIAAhUAlgqiQAAAAgBAAQgag7gZgiQgOgTgNgMQgBgBAAAAQgPgNgPgFQgUgGgTAJQgLAFgLALQgNAMgMATQgUAggUAzIAABLAsQteQAyg8AvgrApMoWIAABIIAABuIAABfAsQiLIAAhUIAAheIAAhSApmwBQB6hXBlAeQAvAOAqAoQAAAAAAAAQA/A7A0B1AiKrVIAAAAQATA6ARBDAkyopQgKgfgLgbQgBgEgCgFAjLgBQBKgtA9AQQAcAHAaAVIAAAAQAlAdAgA8AgQDyQgHgQgGgOIgCgEAi7DVIAAgnIAYgqQAHgKAIgHQAHgFAHgDIAXgBQAJACAJAHIABAAQAIAGAIAKQAPASARAeABUCZQAMAeAKAiAkyEDIAAgzIAAgnIAAgsAi7D7IAAAmIAAA4IAAAyAkyBSQAegeAdgXAi7G4IAAAoIAAA5IAAAyAkyKIIAAghIAAgwIAAg9AkyHHIAAgrIAAgxIAAgqAkyNeIAAg6IAAgrIAAg+Ai7J/IAAAiIAAA7IAAA8ApMipIAABNIAABuIAABiAsQDpIAAhAIAAhcIAAh3ApMDXIAABDIAABxIAAB2AsQKHIAAhvIAAhUIAAh3ApMJgIAABuIAABUIAACJIAACBIAAAXIjEAAIAAiPAi7NKIAAA4IAAAsIAABGIAABDIAAAMAkyRDIAAhKAkyPKIAAhBAsQNYIAAh9AL4ANIAAABQANAiAMAnAHABSIAAgtIAcgvQAIgMAJgHQAIgHAIgDQANgFANAEQAKACALAIQAAAAABABQAJAHAJALQASAUASAjAKEBzQgIgSgHgQIgCgFAE4hDQAjgjAhgaAE4CHIAAg7IAAgtIAAgwAHAB+IAAArIAABBIAAA5AE4FpIAAgyIAAg4IAAgxAHAFXIAAAuIAABCIAAA5AE4JGIAAgmIAAg3IAAhHAHAI8IAAAnIAABDIAABGAE4M8IAAhCIAAgyIAAhHAHAMlIAABBIAAAxIAABSIAABMAE4O4IAAhKAE4RDIAAhV");
	this.shape_27.setTransform(131.7,608.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#000000").ss(1,1,1).p("EBAbgiiQF4kGEziVQCjhPCQgvAHmrOQIXm3Jok5QD4h/EGhpQEth6E/heQCAgmCEgiQBqgbBsgZAHmrOQHoC0GKCjQB4AyBvAwQAOAGAOAGQAFACAFACQAQAHAQAHQEIB1DWBrQA0AaAyAaEA1BAeXQnbAkoVDlEA6ZAeXQIlAiIKFFEgiMAq8QnklRrChMIAAANIiHAAIn1AAIh2AAIkbAAQofAciZEeAExsQQBcAhBZAhEhPYgq7UAp0ALfAeRAOL");
	this.shape_28.setTransform(514.4,482.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#660066").ss(1,1,1).p("Amw2EQAAAbgUATQgTATgbAAQgbAAgTgTQgTgTAAgbQAAgbATgUQAFgFAGgEQAQgKATAAQAPAAAMAGQAKAFAJAIQAUAUAAAbgAmdPWQAAASgMANQgNAMgSAAQgSAAgMgMQgNgNAAgSQAAgSANgNQAMgMASAAQASAAANAMQAMANAAASgAnOVUQAAAggXAXQgWAWghAAQggAAgXgWQgXgXAAggQAAghAXgXQAXgXAgAAQAhAAAWAXQAXAXAAAhgAJrWQQAAAWgQARQgQAQgXAAQgXAAgQgQQgQgRAAgWQAAgYAQgPQAQgQAXAAQAXAAAQAQQAQAPAAAYg");
	this.shape_29.setTransform(951.2,386);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#33CC00").ss(1,1,1).p("AkuzMQAAAggXAXQgXAXghAAQggAAgXgXQgXgXAAggQAAghAXgXQAXgXAgAAQAhAAAXAXQAXAXAAAhgAlWkaQAAAWgQAQQgHAHgJAEQgKAFgNAAQgDAAgEAAQgSgCgNgOQgQgQAAgWQAAgXAQgQQAQgQAWAAQAXAAAQAQQAQAQAAAXgAGNAcQhQAFACACQAOAPAAAUQAAAVgOAOQgOAOgVAAQgUAAgPgOQgNgOgBgUQAAAAAAgBQAAgUAOgPQABgBACgBQAOgMASAAQARAACfADABjTAQAAAmgbAbQgbAbgmAAQglAAgbgbQgbgbAAgmQAAgEAAgEQADghAYgYQAbgbAlAAQAmAAAbAbQAYAYACAhQABAEAAAEg");
	this.shape_30.setTransform(948.1,444.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#CC6699").ss(1,1,1).p("AkDwWQAEAAAEAAQAnAAAcAcQAcAcAAAoQAAAngcAcQgcAcgnAAQgoAAgcgcQgcgcAAgnQAAgoAcgcQAOgOAQgHAh/PtQAAABAAAAQgBARgMAMQgMAMgRAAQgSAAgMgMQgMgMAAgRQAAAAAAgBQAAgBAAAAQAAgRAMgMQAMgMASAAQARAAAMAMQAMAMABARQAAABAAAAgAFcJiQAAAWgJATQgHAOgLALQgEAEgEADQgBABgCABQgYATggAAQgdAAgXgQQgCgBgCgCQgFgEgFgFQgcgbAAgnQAAgnAcgcQAbgbAnAAQAnAAAcAbQALALAHAOQAJATAAAXg");
	this.shape_31.setTransform(961.1,443.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#3366CC").ss(1,1,1).p("ABor1QAAAcgUAUQgUAUgdAAQgdAAgTgUQgUgUAAgcQAAgdAUgUQATgUAdAAQAdAAAUAUQAUAUAAAdgAkWAAQAAAWgQAPQgPAQgWAAQgWAAgQgQQgPgPAAgWQAAgVAPgQQAQgPAWAAQAWAAAPAPQAQAQAAAVgAkaLkQAAAPgLAKQgKALgPAAQgOAAgLgLQgKgKAAgPQAAgIADgGIAAgBIAAABIAAgBQAEgGADgEQALgKAOAAQAPAAAKAKQAEAEADAFQAAABABABQADAGAAAIgAGBLnQAAAjgZAYQgYAZgjAAQgjAAgZgZQgYgYAAgjQAAgIABgHQAAgCABgBQAEgYASgSQAZgYAjAAQAjAAAYAYQATATAFAYQAAABAAABQABAHAAAIg");
	this.shape_32.setTransform(953.9,471.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#FF6666").ss(1,1,1).p("AHajaQAAAYgLASQgGAJgHAHQgYAYgiAAQgiAAgYgYQgSgRgEgYQgCgIAAgJQAAgiAYgYQAYgYAiAAQAiAAAYAYQAYAYAAAigAlvBGQAFAAAFAAQAcAAAXALQAQAIAOAOQAiAiAAAwQAAAwgiAiQghAigwAAQgSAAgQgFQgbgIgVgVQghghgBgtQAAgCAAgCQAAgwAigiQARgRAWgI");
	this.shape_33.setTransform(768.2,548.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#33CCFF").ss(1,1,1).p("AEZojQAABQg5A6Qg5A5hRAAQgIAAgIgBQhGgFgygzQg5g6AAhQQAAhQA5g5QAGgHAHgGQAugnA9gFQAIgBAIAAQBRAAA5A6QAmAlANAxQAGAYAAAbgAFsJNQAABAgtAtQgtAthAAAQhAAAgtgtQgUgUgLgYQgOgeAAgjQAAgkAOgeQALgYAUgTQAqgqA5gDQAFAAAFAAQAnAAAfAQQAVALASASQAtAtAABAgAhrAvQAAA1glAlQgVAUgYAJQgVAJgZAAQg1AAglgmQgmglAAg1QAAg0AmgmQALgLAMgIQAegSAlAAQAZAAAVAIQAYAJAVAUQARASAKAWQAKAWAAAcg");
	this.shape_34.setTransform(810,422.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#CC3366").ss(1,1,1).p("AgYp2QAAAagSASQgSASgaAAQgZAAgSgSQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZgAGulDQAAAogbAfQgCACgCACQgQAQgTAIQgTAIgWAAQgtAAgfggQgggfAAgsQAAgeAOgYQAHgMALgLQAfgfAtAAQAWAAATAIQATAIAQAPQACADACACQAbAeAAAqgAiTInQAAAGgBAGQgEAzglAlQgbAbgjAJQgSAFgTAAQg7AAgpgpQgjgjgFgwQgBgJAAgIQAAg7ApgpQALgLANgIQAhgWArAAQATAAASAEQAjAKAbAbQAJAJAHAKQAaAjAAAug");
	this.shape_35.setTransform(842.2,509.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#66CCFF").ss(1,1,1).p("ABXAAQAAAkgZAZQgGAGgGAEQgRANgWACQgFABgGAAQgjAAgZgaQgagZAAgkQAAgjAagZQAZgaAjAAQAGAAAFABQAWACARANQAGAEAGAGQAZAZAAAjg");
	this.shape_36.setTransform(877.6,330.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#FFFF00").ss(1,1,1).p("AIs/qIArh2IAzBqIBuAAIhHBGIAABTIg6gtIgCgCIgGgFIhxBGIA6hRIhphOgALw2jQAAAagSATQgTATgaAAQgbAAgSgTQgTgTAAgaQAAgaATgTQASgTAbAAQAaAAATATQASATAAAagAHmq9QAAAjgZAYQgYAZgjAAQgjAAgZgZQgYgYAAgjQAAgjAYgZQAZgYAjAAQAjAAAYAYQAZAZAAAjgAN7B4QAAAYgQAQQgHAHgIAEQgMAGgNAAQgHAAgGgBQgQgEgMgMQgQgQAAgYQAAgXAQgSQARgQAYAAQAXAAARAQQAQASAAAXgEAJNAgCQAAAcgOAWQgGAIgJAJQgLALgOAHQgRAJgWABQgBAAgBAAQgoAAgcgcQgbgbAAgnQAAgBAAAAQAAgFAAgDQACgjAZgZQAcgbAoAAQABAAABAAQAWAAARAJQAOAHALALQAJAIAGAKQALATACAXQAAACABAEQAAAAAAACgAOOW3QAAAQgLAMQgMALgQAAQgQAAgLgLQgMgMAAgQQAAgQAMgLQALgMAQAAQAQAAAMAMQALALAAAQgArUQlQAAAmgbAbQgbAbgnAAQgPAAgNgEQgVgHgQgQQgbgbAAgmQAAgnAbgbQAbgbAmAAQAcAAAXAPQAIAFAHAHQAbAbAAAng");
	this.shape_37.setTransform(829,360.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#FF0000").ss(1,1,1).p("EBLqgeSQAFAAAEgBEAo5gSeIAfAKQA1AqA3AZQBiAsBrgNQDRCJDKAeQAUADATACQAUABATACQAPABDpgcQASgCATgCQFZCrCrjqEAmHgMqQAdATAcASQCCBQCCAwQDFBHDFgFQgLgIgJgJQgogoAAg4QAAg5AogoQAognA4AAQA5AAAnAnQAoAoAAA5QAAA4goAoQgnAog5AAQgCAAgDAAQBRBEBGAUQAUAGATACQAUACATgCQAKgBDKgfQAOgCAQgCQB0AsB3ABQA8ABA8gKQAAAAABAAQAXAYAAAhQAAAhgXAXQgYAYghAAQghAAgXgYQgYgXAAghQAAgbAQgVQAEgEAEgFQAXgXAhAAQAhAAAXAXQCrgdCwhyEAycgmaQBQB4BAgLQAVgDASgQQAVgSBaA5QAUANAWAEEA4qgkNQA1gQA/g4EA4kgd4QAkgIAngYQBJgsBUhjEA4kgd4QAEgFAFgFQAXgXAgAAQAGAAAFABQAaADASATQAXAXAAAgQAAAhgXAWQgWAXghAAQggAAgXgXQgXgWAAghQAAgZAOgUgEAvrggnQBeEDDjhaQATgHAUgKQATgJB7AgQAgAIAjgIEAwQgZZQCMA8CQgTQAUgDATgEQAUgEDKACQDKACCOibEAt5gayQARgFASAAQAxAAAjAiQAZAaAHAiQACALAAANQAAAxgiAiQgjAjgxAAQgxAAgigjQgjgiAAgxQAAgxAjgjQAVgVAbgIQBLA4BMAhEAq6gWrQAFAEAFADQEoDXFAgIQAUAAATgBQAUgCBMAEQA8AEFUhQQAOgGAQgBQBSgTBigYEAtKgbYQAYAUAXASEBCEAB/QAAAlgaAZQgaAagkAAQglAAgagaQgZgZAAglQAAgkAZgaQAagaAlAAQAkAAAaAaQAaAaAAAkgEAkPgIuIBAAUIC5A7QBgAwBcAoQFNCSEbApQAUADATACQAUACHWAXQFHAQBKghQAhgOgRgYQAZgBB5gFIA/gDEAyVgIsQgogCgfgVgEAiDgELQCfBFCeA0QCCAsCCAgQBBARBBANQAoAIAoAIQCIAYCHANIDJA1EAyRAKuQgJAagVAVQgkAkgzAAQgzAAgkgkQgkgkAAgzIAAAAQAAgzAkgkQAkgkAzAAQAzAAAkAkQAkAkAAAzQAAAVgGATQBfAbA8AMQAHACBfABQAlADDyABIAFAAQAIAAAIABIAAAAQABgBACAAQgCAAgBAAIAAAAQgIAAgIAAEAiRAIFQCLCDCkgmQApgJArgVICXAZQAMAPANALQBaBRCDhCIDwAoAbPKEIA6AMICYAeQEKCIEVAGQBJACBKgHIC/AmQCQA9CQASQA6AIA7AAIAjAAEA7BALcQAdgCAfAAQBFABBOAAQApAAArAAQB+ABCVAAQAPAAAQAAQBIAAA+ABQAOAAANAAQFBABAaAAIAAAAQgaABlBgBQgNAAgOAAQgbAAgdAAQg4AAg1AAQh6ByiZhzQgrAAgpAAQhPAAhDAAQgggBgdAAgAe6CYQD7BaELA+QCAAdCEAXQHmBUIbgHQAYgFAUADQHBBLB1hbQh6AEiiAEQiiAFh4ADQlkALAKgBAaAMpQBRBIB6gVQAFgCAEgBQAMgEAMAAIA9AKQDSBcDdAHIBhgCEAgdAHyQgIgGgGgHQgmglAAg1QAAg1AmgmQAlglA1AAQA1AAAmAlQAlAmAAA1QAAA1glAlQgXAXgcAJQgSAGgWAAQgrAAghgZgAcoHKQAVAMAXAJQBYAjBxgQIB0ATEBKaAGUIASAyQitgjhIgGQgEAAgFgBQgLAAgIAAQgxABg7ACQgEAAgEAAQACgBACgCIBzgCIAQACID+AqEBLmAOoQAAAFAAADQgDAhgYAYQgbAbgmAAQgmAAgbgbQgYgYgDghQAAgDAAgFQAAgmAbgbQAbgbAmAAQAmAAAbAbQAbAbAAAmgEg5TATAQAAgBABAAEg3VAVFIAdinIA9AgEhJoAFjQgjAZglAiICXCaIANANEhJoAFjQAAgBABAAEhMRAJZIDDBeIAphSIjshfgEhMRAL5IDDBUIAAhLIjDhVEhJOAOWIjDg7IAAB5IDDAvEhMRASEIDDA2IAAhXIjDg9EhGJAEqIAAAAEhJoAFjICYDQIgmACIgjADEhFIAMAIgDgIQgKgbgLgXQgBgCgBgDEhEvAFfIhTEiQgGgWgOgHQgRgJgKgWEhFiALBICmiyQAZA5AYBGEhGyAJEIApkaIBZA1EhFIAMAIAAAAEhBSANkIjTAAQgHgWgHgUIDMgvQABAHACAHQAJAlAJAmgEhCLAKPIi9BxEhBeAXXIAYiSIA2AcEhAPAVhIgzCVQgDgLgIgEQgLgEgGgMEhAgAY0QgHgOgGgMQAAgBgBgCIBkhbQAQAdAOAkIhyA7Eg+JAZsIiAAAQgFgLgEgLIB8gYQABADABAEQAFASAGAVgEhDNAViQgVANgXASIBcBPEhDNAViQAAAAABAAEhC9AaFIh2geIAAA+IB2AYEhCIAXQIgVAAIAIAHEhEzAY0IB2ArIAAgmIh2gsEhCkAXoIiPgxIAAAqIB2AxEhDNAViIBcBsEhEzAcAIB2AcIAAgtIh2ggEhC9AdEIh2gZIAAAzIB2AgEhC9AhAIh2ghIAAgzIB2AZEhEzAhdIB2AgIAAAxIh2gmEhEzAfLIB2AYIAAgzIh2gUEhJOAUHIjDgvIAABiIDDA8EhJOAbvIjDg+IAAhkIDDAxEhMRAYNIDDAuIAAhjIjDgnEhJOAgyIjDhGIAABUIDDBGEhMRAcoIDDA9IAABfIjDhIEhJOAkPIjDhSIAABbIDDB4EhC9AlZIh2grIAAAwIB2A9EhC9AjmIh2gkIAAArIB2AlEg2OAWwQgHgQgHgNQgBgCAAgBIByhqQASAhAQAqEgzhAXwIiSAAQgFgMgFgNICNgbQABADACAFQAGAWAGAWgEg5TATAIBqB7IgbABIgYACIAJAIEg16AS+Ig6CsQgEgNgJgFQgMgFgHgNEg5TATAQgYAOgaAVIBpBbEg7IAWwICHAyIAAgsIiHgzEg4lAVZIijg4IAAAxICHA4Eg5BAYNIiHgiIAABHICHAcEg7IAabICHAgIAAg0IiHgkEg5BAbpIiHgcIAAA5ICHAlEg7IAeEICHAcIAAg7IiHgYEg7IAgsICHAkIAAA5IiHgrEg5BAgKIiHglIAAg6ICHAcEg0JAVyIiCBDEg5BAjKIiHgqIAAAyICHApEg5BAlNIiHgxIAAA3ICHBH");
	this.shape_38.setTransform(541.4,470.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#0000CC").ss(1,1,1).p("AMD2OQAAAegVAVQgUAVgeAAQgeAAgVgVQgVgVAAgeQAAgeAVgVQAVgVAeAAQAeAAAUAVQAVAVAAAegAgxKSQAAAcgTATQAAABgBAAQgTATgbAAQgcAAgTgUQgUgTAAgcQAAgbAUgUQATgTAcAAQAbAAATASQABABAAAAQATAUAAAbgApkWIQAAAhgXAXQgWAXggAAQgBAAgBAAQghAAgYgXQgWgXAAghQAAgSAGgPQAGgNAKgLQAYgXAhAAQABAAABAAQAgABAWAWQAWAXABAfQAAABAAACg");
	this.shape_39.setTransform(798,397.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#6666FF").ss(1,1,1).p("AHA06QAAAbgUAUQgDADgEADQgRANgWAAIgBAAQgbAAgUgTQgTgUAAgbQAAgcATgTQAUgUAbAAIABAAQAWAAARANQAEADADAEQAUATAAAcgAGNCcQAAAXgPAQQgBABgBAAQgQARgYAAQgXAAgRgRQgQgQAAgYQAAgXAQgRQARgQAXAAQAYAAAQAQQABACABAAQAPAQAAAWgAm/VbQADgBAEAAQAIAAAFAFQAFAFAAAIQAAAHgFAFQgFAGgIAAQgEAAgDgC");
	this.shape_40.setTransform(840.5,353);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#006600").ss(1,1,1).p("EAZogk8IgijGIgkBKAXSfJIjrqDIiFltIiOmGIiHlxIiMl/Ih9lVIhukuIjrqEIgBgEIgBACIkTJBIiyFzIhQCoIhQCnIiQEsIiBENIiyF0Ih5D8IiLEjIhHCUEgGbAnvIBwgBEADBAnmIABAAIIEgBEgEEAntIBvgCIB1gCAzZZjIgzBqIiSExIhaC7IhPClIhPClIDSgDEgMOAn1IBagBEgTdAn8IFvgFAYiXWIBGgBAXkf7IBmEYEAZKAkTIBNDSIh5AAEAN9AnlIHpAA");
	this.shape_41.setTransform(868.6,311.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("#FFFFFF").ss(3,1,1).p("EAzIgBrIAAhzEAzIgBrIAAAAIBpBnIgEAEIAIAAIAMALIAACUIBOBiEA1BgCIIhGhLEA2GgBTIBjAAEA3TgCaIhNBHIhFBBIAAASIAAALIBHBGIAABeEA3TgCaIAAhUEA1BgCIIA+hDEA1BgEpIAAChIAAB2IgQAOIAEAEIAMAAIDBAAICTBVEA3PACXIAsArIAAA/EA2IABRIBHBGIB/AAEA0tAAAIhrBjIAABrEAyJAAAICkAAEA1BADWIheBeEA1BADWIAAB5EA1BACfIAAA3EA5jAAAIBhAAEA37ADCIAsAsEA4CAAAIBhAAIBhhKEA4CAAAIBFhSEA5DgD+IhwBkEAhIgRPIg0AqIAAhEAeAypIAABgIAAAdIhBhAAb1wjIAAhYAeAxJIAsgyAauxjIBHBAIAbAYIiSgZAeBuvIgBABIAAAIIAACPIg8BAAeAuvIABAAIErAAAeAuvIAAABIgFADIAFAFIBlBbIAIBQAd2uvIAKAAAd2uvIAFAEIhiBPIgZAUIgbAWIgVBRAcQwLIAaAYIgZAcAcZtcIAMBEAcqvzIBMBEAbvuvICHAAAZ3ulIglBGAeArVIAABHAeArVIA1AgAblsyIg3AsAYsuvIDDAAIg8hBAcAtIIhTgZAeAsXIAABCAfuteIBSAAAfjtfIACAUIBLBDIAOAMIAnAeAfkv/IA/AAEAgjgMHIAYBEEAhSgO/IA8geEAhIgObIBVA7EAgwgMIIBMgSAeAwsIAAB9Afkv/IhjBQAe2vrIAAgkEAgUgQlIgwAmAcqvzQAJgNgSgwEAvSAAAIBAAAIBBAAIhHiBEAwSAAAIhUhCEAzCABjIiaB/EAzIgBrIhSAAEAzCABjIimAAEAxTAAAIA2AAIhCA2EAxegDTIBqBoAIfn4IAAC4IAABbIAAA+IhQAAAIfjlIDMhuAFEi9Ii8AAAFEi9IAAh3ADYkoIBsBrIBsBqIiCBoIAACsAAwAVIBVAAIAACNAgkAVIBUAAIhCiBACiFrICUh1IjTAAACFAVICpAAIC5AAAJPBIIAAAAQgSASgZAAQgDAAgCAAQgVgBgPgOQgCgCgBgBQgSgSAAgZQAAgEABgEQACgUAPgOIAAAAQAQgQAXgCQACAAADAAQAZAAASASQAEAEADAFQAJALACAOQAAAEAAAEQAAAZgSASICYCVICxAAAGrCQIBQhFAIfF0IifBDAIfF0IAAA2ICUAAAIfEqIAABKAIfEqIBjAAAIfBaIAADQAGrCQIAACGAIflAIjLhiAE2D2IB1hmAE2D2IBKB3AIfinIAACIAGwhTIBIBGAPPlNIAAhVAPPlNIBjAAAMRinIBUhJIAAiaANljwIDHBhANljwIBqhdAQCAVIB6BcANpAVIAABWAMZEOICLCJANpAVICZAAICZAAAMRinIBYC8AQCAVIBohnAJWgEIC7ijIjyAAAJhAVIEIAAALnDdIAyAxIAAC0AIfn4Ih1hJAIfn4ICCh6AzJKEIgeAcIB/AAAzJKEIAAhfAxwIwIhZBUAyPMPIAvAAICgAAAy+NxIBmA6AyPMPIBKBDAxgMPIBShSA16KfIgrgwA16JsIBDAAA16JsIAAAzIAABoIAAAIIAAAaIhPBKIhwAAA4BMPIhbgzA1rMPIAIAFIA/AkIAzAcIBKAAA1eMPIgFAFIgXAVIAACKIg2AAA1rMPIANAAIDPAAA16MHIAPAIA16MPIAPAAA3rLGIAAhjA3rLGIBxBBA4BMPICHAAA16OzIA7BHA4XO9IhhBNA4XO9IA/BvA16OzIAAD3AzxNUIAzAdIAABSA0kM4IAAB3A3JNzIhOBKAznKgIh3BvA16FzIAAD5AIfGqIAACAEgrggC/ICHhgEgrggC/IAAh+Egx1gEaIAABkIB9hVEgumgAyIA/gtIDhAAEgumgAyIAAisEgx1gH7IAADhIibibEgwtAAuQACABACADQAbAeAAArQAAAKgCAJQgEAfgVAYQgbAegnAAQgFAAgFAAIAABkIhfAAEgx1AAUQAFgBAFAAQAkAAAaAbICHhgEgysAAyIAAAAQAXgbAggDEgzEACZQgBgGgBgFQgBgJAAgKQAAgrAbgeEgx1ADjQgggEgXgaQgSgUgGgYEgx1AFHIAABCIBBA7Egt2AGNIAAABIBLBUEgvCAE5IBMBUICgAAEgvCAE5IAACBEgwQACOICLAAIAAB9EgwpADFIBnB0EgpFACOIBQAAEgsXACOIClg3EgsXACOIDSAAIA3BaEgsXACOIBpCWEguFACOIBuAAEgx1gC2IAADKEgtngBfICHhgEg1RgCGIAyg1Eg1RgCGIBABIIjRA3Eg2QgDNIA/BHEg2QgDNIh/AAEg4PgFbIB/COIAAidEg7DACOIBLAAIhBi9Eg3TACOIg3hGEg4tACOIBaAAIENAAEg4jAGSIBvhPIirAAEg1FAD0IAAB2Eg1cAEFIAXgRICBhbEg20AFDIBYg+IhUg2Eg54ACOIBLAAIh4BfA6HMPIhaBeA8MMPICFAAIh9hGEgx1AHMIAACEEg0RgA+IBlBwEgx1AGJIAABDIhzBwEgt2AGOIAAC9A6HMPICGAAA6PJnICkBf");
	this.shape_42.setTransform(490.9,153.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#663300").ss(3,1,1).p("AiromIAAgEACsovIAARfIlXAAIAAxR");
	this.shape_43.setTransform(870.8,621);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#663300").ss(1,1,1).p("Ah3ADIAAgFIBfAAAANgCIBnAAIAEAAIAAAC");
	this.shape_44.setTransform(842,566.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#660066").s().p("AINW3QgQgRAAgWQAAgYAQgQQAQgQAXAAQAXAAAQAQQAQAQAAAYQAAAWgQARQgQAQgXAAQgXAAgQgQgApTWKQgXgWAAggQAAghAXgXQAXgWAggBQAhABAWAWQAXAXAAAhQAAAggXAWQgWAYghAAQggAAgXgYgAnmP1QgNgNAAgSQAAgSANgNQAMgMASAAQASAAANAMQAMANAAASQAAASgMANQgNAMgSAAQgSAAgMgMgAog1WQgTgTAAgbQAAgbATgUQAFgFAGgEQAQgKATAAQAPABAMAFQAKAFAJAIQAUAUAAAbQAAAbgUATQgTATgbABQgbgBgTgTg");
	this.shape_45.setTransform(951.2,386);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#33CC00").s().p("AjVUBQgbgbAAgmIAAgIQADghAYgYQAbgbAmAAQAmAAAbAbQAYAYADAhIAAAIQAAAmgbAbQgbAbgmAAQgmAAgbgbgAHLTxQgYgYgDghIAAgIQAAgmAbgbQAbgbAmAAQAmAAAbAbQAbAbAAAmIgBAIQgCAhgYAYQgbAbgmAAQgmAAgbgbgABeBpQgOgOAAgUQAWgJAAgOQAAgHgGgIICSgFQhRAFACACQAPAPAAAUQAAAVgPAOQgOAOgUAAQgVAAgOgOgABQBGQAAgUAOgPIACgCQAGAIAAAHQAAAOgWAJIAAgBgACBAVICwADIg/AEIiSAFQAOgMATAAgAovjkIAegFQgLAFgMAAIgHAAgAovjkQgSgCgOgOQgQgQAAgWQAAgXAQgQQAQgQAXAAQAWAAAQAQQAQAQAAAXQAAAWgQAQQgHAHgIAEIgeAFIAAAAgAoRjpIAAAAgApQyVQgXgXAAggQAAghAXgXQAXgXAhAAQAgAAAXAXQAXAXAAAhQAAAggXAXQgXAXggAAQghAAgXgXg");
	this.shape_46.setTransform(963.6,444.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#CC6699").s().p("AjIQKQgLgLAAgRIBTAAQAAARgMALQgMANgSAAQgRAAgNgNgAjTPuIAAgBIAAgBQAAgRALgMQANgMARAAQASAAAMAMQAMAMAAARIhTAAIBTAAIAAABIAAABIhTAAgAjTPuIAAAAgAiAPsIAAAAgADKKwIBsgDQgYASggABQgdgBgXgPgADKKwIgEgDIBzgCIgDACIhsADIAAAAgAE2KtIAAAAgADGKtIgLgJQgbgbAAgoQAAgnAbgbQAcgbAnAAQAnAAAbAbQAMALAHAOQAJATAAAWQAAAXgJATQgHAOgMALIgHAHIhzACIAAAAgAE5KrIAAAAgAk/tzQgcgcAAgnQAAgoAcgcQAOgOAQgHQAOgGAQgBIAHAAQAoAAAcAcQAcAcAAAoQAAAngcAcQgcAcgoAAQgnAAgcgcg");
	this.shape_47.setTransform(961.1,443.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#3366CC").s().p("ADyMiQgZgYAAgjIABgPIBtAAIA5AAIABAPQAAAjgYAYQgZAZgjAAQgjAAgYgZgAlWL9QgLgKAAgPQAAgIADgGIABAAIAAgBQADgGAEgEQAKgKAOAAQAPAAAKAKIAHAIQgfAAgeACIA+ABQADAGAAAIQAAAPgLAKQgKALgPAAQgOAAgKgLgAldLWIACgBIgCAAIACAAIgCABgAD6LVIgfAAQAEgYATgSQAYgYAjAAQAjAAAZAYQASATAEAYIiFgBgAlwAlQgQgPAAgWQAAgVAQgQQAPgPAWAAQAWAAAPAPQAQAQAAAVQAAAWgQAPQgPAQgWAAQgWAAgPgQgAgNrFQgTgUgBgcQABgdATgUQAUgUAcAAQAdAAATAUQAVAUgBAdQABAcgVAUQgTAUgdAAQgcAAgUgUg");
	this.shape_48.setTransform(953.9,471.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FF6666").s().p("AmHEoQgbgIgVgVQghghgBgtIAAgEQAAgwAigiQARgRAWgIIAJgDQALgEANgBIAKAAQAcAAAXALQAQAIAOAOQAiAiAAAwQAAAwgiAiQghAigwAAQgSAAgQgFgAkyBRIg9gLgAFOigQgSgRgEgYQgCgIAAgJQAAgiAYgYQAYgYAiAAQAiAAAYAYQAYAYAAAiQAAAYgLASQgGAJgHAHQgYAYgiAAQgiAAgYgYgAHPiwIiXgZg");
	this.shape_49.setTransform(768.2,548.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#33CCFF").s().p("ABlK6QgUgUgLgYQgOgeAAgjQAAgkAOgeQALgYAUgTQApgqA6gDIAKAAQAnAAAfAPQAVALASATQAtAsAABBQAABAgtAtQgtAshAABQhAgBgtgsgAEYHCIhQgPIBQAPgAlGCJQglgmAAg0QAAg0AlgmQAMgLANgIIC4A7QAKAWAAAcQAAA0gmAmQgUAUgYAJQgVAIgZABQg1AAgmgmgAktg+QAdgSAlgBQAZAAAVAJQAYAJAUAUQATASAJAWgAktg+gABGlhQhGgFgygzQg5g5AAhRQAAhRA5g5IANgLQA0AqA3AYIACABIABABIABAAQBLAhBPAAIAAAAIAAAAQAWAAAWgDIADAAQAGAYAAAbQAABRg5A5Qg5A4hRAAIgQAAgADkpTQhPAAhLghIgBAAIgBgBIgCgBQg3gYg0gqQAugoA9gFIAQAAQBRAAA5A4QAmAnANAwIgDAAQgWADgWAAIAAAAIAAAAgAglq4IAAAAg");
	this.shape_50.setTransform(810,422.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#CC3366").s().p("AmEKKQgjgjgFgvIgBgRQAAg6ApgqQALgLANgIQAhgWArAAQATAAASAEQAjAKAbAbQAJAJAHAKQAaAjAAAuIgBANQgEAyglAkQgbAcgjAKQgSAEgTAAQg7AAgpgqgAitHWIi/gmgAD3j3QggggAAgtQAAgdAOgYIDJA1QAAApgbAfIgEAFQgQAPgTAIQgTAIgWAAQgtAAgfgfgADll5QAHgMALgKQAfggAtAAQAWAAATAIQATAIAQAQIAEAEQAbAeAAApgADll5gAiBpKQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSg");
	this.shape_51.setTransform(842.2,509.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#66CCFF").s().p("Ag9A9QgZgZAAgkQAAgjAZgZQAagaAjAAIALABQAVACASANIAMAKQAZAZAAAjQAAAkgZAZIgMAKQgSANgVACIgLABQgjAAgagag");
	this.shape_52.setTransform(877.6,330.8);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFF00").s().p("EAHtAhgQgnAAgcgbQgbgcAAgmIAAgCIAAgHQACgjAZgZQAcgcAnABIAEAAQAVAAARAJQAOAHAMALQAHAIAGAKQAMATACAXIAAAFIAAACQAAAcgOAWQgGAKgHAIQgMALgOAHQgRAJgVAAIgEAAgANLXSQgLgLAAgQQAAgQALgMQAMgLAQAAQAQAAALALQAMAMAAAQQAAAQgMALQgLAMgQAAQgQAAgMgMgAtNR8QgVgGgQgQQgbgbAAgmQAAgnAbgbQAbgbAnAAQAbAAAXAPQAIAFAHAHQAbAbAAAnQAAAmgbAbQgbAbgmAAQgQAAgNgFgAM2CwQgQgEgMgMQgRgRABgXQgBgXARgRQARgRAXAAQAYAAARARQARARAAAXQAAAXgRARQgHAHgJAEQgLAGgOAAIgMgBgAM2CwIAlgFIglAFgAFWqCQgZgYABgjQgBgjAZgZQAZgZAjAAQAjAAAZAZQAZAZAAAjQAAAjgZAYQgZAZgjAAQgjAAgZgZgAKD12QgSgTAAgaQAAgbASgSQATgTAaAAQAbAAASATQATASAAAbQAAAagTATQgSASgbAAQgaAAgTgSgAI4+cIhphOIBdAAIArh2IAzBqIBuAAIhHBGIAABSIg6gsIgBgEIgCACIgFgFIhyBGg");
	this.shape_53.setTransform(829,360.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#0000CC").s().p("AqzXXQghAAgYgXQgXgXAAghQABgSAGgPICYAeIAAADQABAhgYAXQgWAXggAAIgCAAgAr8VnQAGgNAKgLQAYgXAhAAIACAAQAgABAWAWQAXAXAAAfgAr8VngAiiLBQgUgTABgcQgBgbAUgUQAUgTAbAAQAbAAATASIABABQATAUABAbQgBAcgTATIgBABQgTATgbAAQgbAAgUgUgAKI1bQgUgVAAgeQAAgeAUgVQAWgVAeAAQAdAAAWAVQAUAVABAeQgBAegUAVQgWAVgdAAQgeAAgWgVg");
	this.shape_54.setTransform(798,397.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#6666FF").s().p("AnHV4QgFgFAAgHQAAgIAFgGQAGgEAHAAIAIABIAFADQAFAGAAAIQAAAHgFAFIgFAEIgIACQgHgBgGgFgAE5DFQgQgRAAgYQAAgXAQgQQARgRAYAAQAXAAAQARIACABQAPAQAAAWQAAAXgPAQIgCACQgQAQgXAAQgYAAgRgQgAGKz4QgbAAgUgTQgTgUAAgbQAAgbATgUQAUgTAbAAIABAAQAWAAARAMIAHAHQAUAUAAAbQAAAbgUAUIgHAHQgRAMgWAAg");
	this.shape_55.setTransform(839.2,353);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#006600").s().p("EgZHAleIADACIAAAAIADADQA9AyBTAAIAAAAIAAAAQAYAAAZgDIABgBIAAAAIAEAAQgXAIgRARQgiAiAAAwIAAAEIjRADgEgUAAmqQgNgOgRgIQDTBcDdAHIlwAFQABgwgjgigEgUeAmUQgXgLgcAAIgKAAQgMABgMAEIgIADIgEAAIAAAAIgBABQgZADgYAAIAAAAIAAAAQhTAAg9gyIgDgDIAAAAIgDgCIBPilIBai7ICSkxIAzhqQANAEAQAAQAmAAAbgbQAbgbAAgmQAAgngbgbQgHgHgIgFIBGiUICMkjIB4j8ICzl0ICAkNICQksIBRinIBQioICylzIESpBIACgCIABAEIgDgCIADACIDrKEIBuEuIB9FVICMF/ICGFxICPGGICFFtIDrKDIASAyIBmEYIlagBIgcAAIAcAAIFaABIAAAAIlaAAIgcAAIAcAAIFaAAIBNDSIh5AAIAAgIQAAgmgbgbQgbgbgmAAQgmAAgbAbQgbAbAAAmIAAAIInpAAQgCghgYgYQgcgbglAAQgnAAgbAbQgYAYgCAhIoEABIgCAAIAAgGQgCgXgMgTQgGgKgHgIQgMgLgOgHQgRgJgVAAIgEAAQgnAAgcAbQgZAZgCAjIAAAIIAAABIgjAAQg6AAg7gIQiQgSiQg9QCQA9CQASQA7AIA6AAIh1ACIhvACQghgKgRAAQgGAAgBADQAAAFAIABIAKACIhwABIAAgMQAAgugagjQgHgKgJgJQgbgcgjgJQgSgEgTAAQgqAAgiAWQg7AGg7AAIAAAAIAAAAIgbgBIgCAAQkVgGkKiIQEKCIEVAGIACAAIAbABIAAAAIAAAAQA7AAA7gGQgNAIgLALQgpApAAA7IABARIhaABIhgACQjdgHjThcgEAQtAkiQAAAjAZAZQAYAYAkAAQAiAAAZgYQAZgZgBgjIgBgPIAAgBIAAABIg4AAIhtAAIAAgCIAfAAICGABQgFgZgSgSQgZgZgiAAQgkAAgYAZQgSASgFAYIAAACIgDADQg7A1hDABIAAAAIgBAAQhAgBhIgyIgBgBIgDgDIgDgCIgCgBIACABIADACIADADIABABQBIAyBAABIABAAIAAAAQBDgBA7g1IADgDIgCAPgEAHzAkgQAAAOAKALQAKAKAPAAQAPAAAKgKQALgLAAgOQAAgIgDgGICSAAIiSAAIgCgDICUABIAAABIAAABQAAARALALQANANARAAQASAAAMgNQAMgLAAgRIAAgBIAAgBQAAgRgMgMQgMgMgSAAQgRAAgNAMQgLAMAAARIiUgBIgGgIQgKgLgPAAQgPAAgKALQgEADgDAHIAAAAIgQAAIAQAAQgEAHABAIgEgEBAhkQglAkABAzIAAAAQgBAzAlAkQAkAkAzAAQAyAAAkgkQAWgVAJgaQBdAbA9AMQAGABBfABQAlADDyACIAFAAIgFAAQjygCglgDQhfgBgGgBQg9gMhdgbQAFgTAAgVQABgzglgkQgkgkgyAAQgzAAgkAkgEgWuAiuQgKAKgGANQgGAPgBASQAAAhAXAXQAYAYAhAAIACAAQAggBAWgXQAYgXgBghIAAgDQAAgfgXgWQgWgXggAAIgCAAQghAAgYAXgEAQvAkRIkTgBIETABgEgGTAjZQAxAAA5gcIABgBIADgBIgDABIgBABQg5AcgxAAIAAAAIAAAAQg8AAgwgpIgCgCIgCgCQgNgLgMgPQALgSAAgYQAAgigYgYQgYgYgiAAQgiAAgYAYQgYAYAAAiQAAAJACAIQgrAVgpAJQglAJgjAAIgBAAIAAAAQh3gBhphgIgCgCIgDgDQAbgJAXgXQAmglAAg1QAAg1gmgmQgmglg1AAQg0AAgmAlQgmAmAAA1QAAA1AmAlIAOANIgBAAIgDAAQgiAFgfAAIAAAAIAAAAQhGAAg7gXIgBAAIgBgBIgBAAQgXgJgUgNQAUANAXAJIABAAIABABIABAAQA7AXBGAAIAAAAIAAAAQAfAAAigFIADAAIABAAQAhAZArAAQAWAAATgGIADADIACACQBpBgB3ABIAAAAIABAAQAjAAAlgJQApgJArgVQAFAYARARQAYAYAiAAQAiAAAYgYQAIgHAFgJQAMAPANALIACACIACACQAwApA8AAIAAAAIAAAAgEgW+AjFIg6gMgEAVHAhRQgQAQAAAXQAAAXAQAQQAQAQAXAAQAXAAAQgQQAQgQAAgXQAAgXgQgQQgQgQgXAAQgXAAgQAQgEADmAgEQgWAXAAAhQAAAgAWAXQAXAXAgAAQAhAAAWgXQAXgXABggQgBghgXgXQgWgWghAAQggAAgXAWgEAN7AgGQChAABAgwIABgBIABAAIAAAAIABgBIAIAAQAXAPAdAAQAgAAAYgSIADgDIAHgGQAMgMAHgNQAJgTAAgXQAAgXgJgTQgHgNgMgLQgbgcgnAAQgnAAgcAcQgbAbAAAnQAAAnAbAcIALAJIgEADIkcAIIkaAIIgDAAIgPgBIAAAAIAAAAIgTABIgHABIgHAAIhMABIAAAAIgBAAQniAAm4hKIgSgEQiEgWiAgeQkLg9j6haQD6BaELA9QCAAeCEAWIASAEQG4BKHiAAIABAAIAAAAIBMgBIAHAAIAHgBIATgBIAAAAIAAAAIAPABIADAAIgwACIgNAAIkcAIIAAAAQgBAAAAAAIAAAAIABAAIgBAAIAAAAQAAAAABAAIAAAAIEcgIIANAAIAwgCQDKAiCHAAIABAAIAAAAgAXkf7Ij+gqgATmfRIAKABQBHAFCtAkQitgkhHgFIgKgBIgLAAIgDAAIgBAAIAAAAIgCAAIgCAAIACAAIACAAIAAAAIABAAIADAAIALAAgATmfRIgQgDgAG/eCQgLALAAAQQAAAQALAMQAMALAQAAQAQAAALgLQAMgMAAgQQAAgQgMgLQgLgMgQAAQgQAAgMAMgAnkY5QgUAUgLAXQgOAeAAAkQAAAjAOAeQALAYAUAUQAtAtBAAAQBAAAAtgtQAtgtAAhAQAAhAgtgtQgSgSgVgLQCIAZCIANQiIgNiIgZQgfgQgnAAIgKAAQhBgNhBgRQiBggiDgsQidg0ighFQCgBFCdA0QCDAsCBAgQBBARBBANQg6ADgpAqgArRccQAHAAAGgGQAFgFAAgHQAAgIgFgFQgGgFgHAAQgEAAgDABIgIgBQgIAAgGAFQgEAFAAAIQAAAHAEAFQAGAGAIAAIAIgCIAEgEQAGgFAAgHQAAgIgGgFIgEgEQADgBAEAAQAHAAAGAFQAFAFAAAIQAAAHgFAFQgGAGgHAAQgEAAgDgCQADACAEAAgAMlZ2QgZAaAAAkQAAAlAZAZQAbAaAkAAQAlAAAZgaQAagZAAglQAAgkgagaQgagagkAAQgkAAgbAagAFTagQgMAMAAASQAAASAMANQAMAMATAAQASAAAMgMQAMgNAAgSQAAgSgMgMQgMgNgSAAQgTAAgMANgAgQYrQgLALgGAMQgOAYgBAdQABAtAfAfQAfAgAsAAQAWAAAUgIQASgIAQgQIAEgEQAbgfAAgpQAAgpgbgeIgEgFQgQgPgSgIQgUgIgWAAQgsAAgfAfgAHjYWQgPAPAAAWQAAAWAPAQQAQAPAVAAQAXAAAPgPQAPgQAAgWQAAgWgPgPQgPgQgXAAQgVAAgQAQgAtkXCQgUATABAcQgBAbAUAUQAUATAbAAQAbAAATgSIABgBQATgUABgbQgBgcgTgTIgBgBQgTgTgbAAQgbAAgUAUgAQXVPIgDACQgOAOAAAVIAAABQAAAUAOANQAOAPAVAAQAUAAAOgPQAPgOAAgUQAAgVgPgOQgCgCBRgGIA/gDIiwgDQgTAAgNAMgAMvWLQCjAAAzgWIABAAIgBAAQgzAWijAAIgBAAIAAAAQhOAAhpgFIgCAAQnWgXgUgCIgmgFQkbgplNiSQhcgohggwQBgAwBcAoQFNCSEbApIAmAFQAUACHWAXIACAAQBpAFBOAAIAAAAIABAAgAmJUaQgSASAAAZQAAAaASASQASASAaAAQAZAAASgSQASgSAAgaQAAgZgSgSQgSgSgZAAQgaAAgSASgAt3QaQgNAIgMALQglAmAAA1QAAA1AlAlQAmAmA1AAQAZAAAVgJQAYgJAUgUQAmglAAg1QAAgcgKgXQgJgWgTgSQgUgUgYgJQgVgIgZAAQglAAgdASgAKAShQAAAhAXAXQAYAYAhAAQAhAAAXgYQAXgXAAghQAAghgXgYIgBgBQCrgcCwhyQiwByirAcQgXgWggAAQghAAgYAXIgIAJQh3gBh0gsQB0AsB3ABQgPAVAAAbgACdRpIAOgBIAHAAIDUggIAHABQANAAAKgFQAIgEAHgHQAQgQABgXQgBgWgQgQQgPgQgXAAQgWAAgRAQQgPAQAAAWQAAAXAPAQQAOANASACIjUAgIgHAAIgOABIgBAAIAAAAIgRgBQgTgCgTgGQhHgUhQhEIAGAAQA3AAAngoQApgoAAg4QAAg5gpgoQgngng3AAQg5AAgoAnQgoAoAAA5QAAA4AoAoQAKAJAKAIIgbAAIAAAAIgBAAQi0AAi0hAIgGgCQiCgwiChRIg5gkIA5AkQCCBRCCAwIAGACQC0BAC0AAIABAAIAAAAIAbAAQAfAVAoACQBQBEBHAUQATAGATACIARABIAAAAIABAAgAt3QaIhBgUgANHMVQgUAUAAAcQAAAdAUAUQAUAUAcAAQAdAAAUgUQAUgUAAgdQAAgcgUgUQgUgUgdAAQgcAAgUAUgAoDFzQg9AFgvAoIgNAMQg5A5AABQQAABRA5A5QAzAzBGAFIAQABQBRAAA5g5QA5g5AAhRQAAgbgGgYQgNgwgmgmQg5g5hRAAIgQAAgALULaQCZAABiiBIAAAAIADgDIABgDIgBADIgDADIAAAAQhiCBiZAAIAAAAIAAAAQhvAAiLhDIgFgDIgGgDQAJgEAHgHQARgQAAgYQAAgXgRgRQgRgRgYAAQgXAAgRARQgRARABAXQgBAYARAQQAMANAQADIgLABIgOACIgBAAIgEABIgLABIgBAAIgDAAIgDABQi2AVgRAAIAAAAIAAAAIgBAAIgngDIgmgFQjKgejRiJQDRCJDKAeIAmAFIAnADIABAAIAAAAIAAAAQARAAC2gVIADgBIADAAIABAAIALgBIAEgBIABAAIAOgCIALgBIAMABQAOAAALgGIAGADIAFADQCLBDBvAAIAAAAIAAAAgAATITQgQAQAAAYQAAAXAQARQAQAQAYAAQAXAAARgQIACgCQAOgQAAgWQAAgXgOgQIgCgBQgRgRgXAAQgYAAgQARgAKZENQgQABgOAGQgQAHgOAOQgcAcAAAnQAAAoAcAcQAcAcAnAAQAoAAAcgcQAcgcAAgoQAAgngcgcQgcgcgoAAIgHAAIC0grIi0ArIAAAAgApvGgIgegKgAI9EiIABAAIApgJIAKgDIAKgCIgKACIgKADIgpAJIgBAAQkPA+g9AAIAAAAIgFAAIgCAAQgzgDgZAAIgDAAIAAAAIgOABIgCAAIgmABIgEAAIgTABIAAAAIgBAAQkrgBkWjEIgNgJIgCgCIgKgHIAKAHIACACIANAJQEWDEErABIABAAIAAAAIATgBIAEAAIAmgBIACAAIAOgBIAAAAIADAAQAZAAAzADIACAAIAFAAIAAAAQA9AAEPg+gAAcCCQgaAaABAkQgBAkAaAZQAZAaAlAAIALgBQAVgCARgNIAMgKQAagZgBgkQABgkgagaIgMgJQgRgNgVgDIgLAAQglAAgZAZgAFlApQgWAXAAAgQAAAhAWAXQAYAXAgAAQAgAAAYgXQAWgXAAghQAAgggWgXQgYgXggAAQggAAgYAXgAl+hgQgjAjAAAxQAAAwAjAiQAjAjAwAAQAyAAAigjQAjgigBgwQAAgNgCgLQgGgigagaQgigigyAAQgSAAgRAFQgXgSgYgUQAYAUAXASQgbAIgVAVgAAfAIQAfAAAggDIAHgBIAmgGIABAAQAPgDBkAAIAAAAIAAAAIAdAAIAFAAIBIABIAFAAIAAAAIABAAQC9AACIiLIABgCIABAAIACgCIACgCIAHgIIgHAIIgCACIgCACIgBAAIgBACQiICLi9AAIgBAAIAAAAIgFAAIhIgBIgFAAIgdAAIAAAAIAAAAQhkAAgPADIgBAAIgmAGIgHABQggADgfAAIAAAAIAAAAQhpAAhmgqIgDgBIAAAAIgEgBIAEABIAAAAIADABQBmAqBpAAIAAAAIAAAAgAg1kTQgZAZABAjQgBAjAZAZQAZAZAiAAQAjAAAZgZQAZgZAAgjQAAgjgZgZQgZgYgjAAQgiAAgZAYgAFPkWQgBAhAXAWQAXAXAgAAQAhAAAXgXQAWgWAAghQAAgggWgXQgTgTgZgDQBIgsBUhjQhUBjhIAsIgMgBQggAAgXAXIgJAKIgEABIgBAAQgOADgOAAIAAAAIgBAAQgPAAgOgEIgEAAIgCgBIgCAAIgBgBIgJgCIgDgBIgJgCIgBAAIgZgGIgDgBIgBAAIgCgBIgCAAIgDgBIgEgBIgKgCIgMgCIAAAAIgEgBIAAAAIgagDIgBAAIgCAAIgFAAIAAAAQgJAAgFABIgBABQgTAKgTAHIgCABQg5AWgwAAIgBAAIAAAAQiLAAhGi0IgEgMIAEAMQBGC0CLAAIAAAAIABAAQAwAAA5gWIACgBQATgHATgKIABgBQAFgBAJAAIAAAAIAFAAIACAAIABAAIAaADIAAAAIAEABIAAAAIAMACIAKACIAEABIADABIACAAIACABIABAAIADABIAZAGIABAAIAJACIADABIAJACIABABIACAAIACABIAEAAQAOAEAPAAIABAAIAAAAQAOAAAOgDIABAAIAEgBQgOAUABAZgAg5pjQgUAVAAAeQAAAeAUAVQAWAVAeAAQAcAAAWgVQAUgVABgeQgBgegUgVQgWgVgcAAQgeAAgWAVgAEkrTQgGADgFAGQgTATAAAbQAAAbATATQAUAUAaAAQAcAAASgUQAUgTAAgbQAAgbgUgTQgIgJgLgFQA1gQA/g4Qg/A4g1AQQgMgFgPAAQgTAAgQAKgAD6rkQAUANAWAEQgWgEgUgNIgCgBQhBgpgcgCIgCAAIAAAAQgJAAgFAFQgSAQgUADIgLABIAAAAIgBAAQg6gBhFhmIAAgBIgBgBIgBgCIAAAAIgBgCIgBgBIABABIABACIAAAAIABACIABABIAAABQBFBmA6ABIABAAIAAAAIALgBQAUgDASgQQAFgFAJAAIAAAAIACAAQAcACBBApIACABIAAAAgAA1vLQgTAUgBAbQABAcATATQATAUAcAAIABAAQAVAAARgNIAIgHQAUgTgBgcQABgbgUgUIgIgGQgRgNgVAAIgBAAQgcAAgTATgAD3vqQgSATAAAaQAAAbASASQATATAaAAQAbAAASgTQATgSAAgbQAAgagTgTQgSgSgbAAQgaAAgTASgEgUeAmUIAAAAgEgJ0AlsIAAAAgEAI3AkSIg+gBQAegCAeAAIACADIAAAAgEAH2AkRIAAAAIAAAAgEAH2AkRIAAAAIAAAAgEAH2AkRIAAAAgEAHmAkRIAQAAIAAAAIgQAAgEAH2AkRIAAAAgEAHmAkRIAAAAgEAI1AkPIAAAAgEgIcAiSIAAAAgEgKzAh5IAAAAgEAN6AgGQiHAAjKgiIEagIIEcgIIgBABIAAAAIgBAAIgBABQhAAwihAAIAAAAIgBAAgAIpfkIAAAAgAIpfkIAAAAgARffUIAAAAgARjfRIAEADIgIAAIAEgDgARjfRIAAAAgAkxYcIAAAAgAmBYMIAAAAgAYileIAAqtIAA2tIAkhKIAiDGMAAAA8RIhGABgAYileIAJAAIgJAAgAGGRIIAAAAg");
	this.shape_56.setTransform(868.6,311.6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("EgVzAsWIAAhVICIBHIAAAOgEgfeAsWIAAhKIB3A9IAAANgEgm8AsWIAAiPIDDB3IAAAYgEgfeAqcIAAhAIB3AkIAABHgEgVzAqKIAAhKICIAqIAABSgEgm8AorIAAh9IDDBHIAACJgEgfeAowIAAg5IB3AlIAAA5gEgVzAoPIAAhDICIAsIAABAgEgfeAnLIAAg9IB3AhIAAA8gEgVzAmbIAAhHICIAlIAABGgEgm8AlaIAAhwIDDBJIAABtgEgfeAlbIAAghIB3AYIAAAigEgVzAkZIAAgnICIAcIAAAngEgfeAkKIAAg9IB3AfIAAAygEgm8AiXIAAh3IDDA+IAAB2gEgVzAi8IAAhHICIAkIAAA6gEgfeAiaIAAgsIB3AdIAAAogEgfeAg+IAAgqIB3AYIAAAxgEgVzAg8IAAgzICIAhIAAAugA1zfSIAAgxICIAcIAAA5gA/efVIAAgyIB3ArIAAAmgEgm8Ae8IAAhBIDDAvIAABDgA7JemIByg6QAMAeAKAiIh7AYIgNgegA/ed7IAAgrIB3AxIAAAmgA74dWQAIADAEAMIAyiWQAlAfAhA8IhkBcQgRgegPgSgA1zdaIAAg7ICIAyIAAArgA/eclQAegfAcgWIBcBPIAWgBQgIACgGAGIgIgHIAIAHQgIAGgHAKgA8JdGQAIAGAJAKQgKgFgHgLgEgm8AcfIAAh3IDDA9IAABhgAw2ckICChEQANAjAMAnIiNAcIgOgigA8cc8IhchrIABgBQBKgsA8AQQAdAHAZAUIg2gbIgYCRQgKgHgJgCgA1zbyIAAgxICIA3IAAAtgAxsbHQAKAEADANIA6isQAsAkAjBFIhyBpQgSgjgSgUgA1zaPQAjgkAggaIBpBbIAJAIQgJAIgIALgAx+a0QAJAIAJALQgMgGgGgNgAzHasIAYgBQgHADgIAGgAyUapIhqh7IABAAQBUg0BGATQAgAIAeAXIg+gfIgcCnQgLgIgKgDgEgm8AZHIAAhUIDDA2IAABMgEgm8AWUIAAhSIDDAvIAABggEgm8ATKIAAhiIDDBTIAABJgA/zRvIAAAAIC9hyQATA6ARBDIjMAuIgVg5gEgm8AQbIAAhUIDDBeIAABMgA/zRvIgDgJIADAJgA/zRvgEghAAPSQANAIAGAWIBTkiQA/A7A0B1IimCyQgag7gZgjgEgm8AN0QAyg8AvgsICXCaIANAOIgNgOIAjgCQgLAFgLALQgNAMgMATgEghbAO0QANAMAOASQgSgJgJgVgEgh7AOhIiYjQIABAAQB6hXBkAeQAvAOAqAoIhZg2IAAAAIAAAAIgoEbQgQgNgPgFgEgUZgoSQgggEgYgaQgRgTgGgZIgCgKQgCgKAAgKQAAgqAbgfIAAAAQAYgaAggEIAKAAQAkgBAZAbIAFAEQAbAeAAArQgBAKgBAKQgFAegUAYQgbAegnAAIgKAAgEAl7gqaQgVgCgQgOIgCgCQgSgTAAgZIAAgIQADgUAPgPIAAAAQAQgQAXgCIAFAAQAZAAASASQAEAEADAFQAIAMADAOIAAAIQAAAagSARIAAABQgSARgZABIgFAAg");
	this.shape_57.setTransform(302.5,433.8);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FF0000").s().p("Eg/sAhdIAAgwIB3ArIAABCgEg2BAhSIAAg3ICIAxIAABNgEhHKAgYIAAhcIDDBSIAACBgEg/sAftIAAgsIB3AlIAAArgEg2BAfRIAAgyICIAqIAAAygEg/sAeIIAAgsIB3AgIAAAxgEg2BAddIAAgyICIAkIAAA5gEhHKAc/IAAhUIDDBGIAABUgEg/sAcfIAAgzIB3AZIAAA6gEg2BAblIAAg7ICIAcIAABEgEg/sAbKIAAgvIB3AUIAAAzgEhHKAZ7IAAhUIDDA9IAABggEg2BAaDIAAg2ICIAXIAAA7gEg/sAZdIAAgyIB3AYIAAA6gEg2BAYGIAAg6ICIAcIAABCgEg/sAX/IAAgwIB3AfIAAAugEhHKAWwIAAhjIDDAwIAABygEg/sAWlIAAg/IB3AeIAAA5gEg2BAWaIAAg3ICIAjIAAA1gEg7CAVrIgIgWIB7gYIACAHIALAngEg/sAU0IAAgoIB3AsIAAAngEg2BAUyIAAhIICIAjIAABBgEhHKAUMIAAhcIDDAnIAABkgEg7ZAUzIgMgaIgBgCIBkhcQAPAdAOAlIhyA6gEg/sAThIAAgrICPAxIgYAqgEg8GATnQgJgKgIgGIAAgBIAYiRIA2AbIABAAIgyCWQgEgMgIgDgEgwsATwIgKgZICNgcIADAIIAMAtgEg2BASwIAAgtICIAyIAAAtgEg+yASAQAXgRAVgNIBcBrIgWACIgWABgEgxHASvIgNgdIgCgDIByhqQATAiAPAqIAAAAIiCBDgEg2BARRIAAgxICkA4IgcAxgEhHKAQ5IAAhiIDDAvIAABwgEgx6ARYQgJgMgJgHIgBAAIAcioIA+AgIAAAAIg6CsQgDgNgKgEgEg0+APiQAagUAYgPIBqB7QgOgDgNAFIgYABgEhHKAODIAAheIDDA9IAABYgEhHKALTIAAh5IDDA7IAABtgEg/eAJkIgOgrIDMgvIAEAPIARBLgEhHKAH4IAAhMIDDBVIAABLgEA0NAHcQglgkABgyIDwAnQgJAagWAVQgkAkgyAAQgzAAgkgkgEhAEAH3IgUgxIgCgFIgBgBICmiyQAaA5AXBHIAAAAIi9BygEhHKAFYIAAhTIDsBfQgVAggUAygEA3ZAGtIjwgnIAAgBQgBgzAlgkQAkgkAzAAQAyAAAkAkQAlAkgBAzQAAAVgFATgEAzpAGGgEhBOAFjQgOgTgNgMIgBgBIAokaIBZA2IABAAIhTEiQgGgXgNgHgEhFpACdQAlgiAjgZICYDQQgTgGgTAJIgjACgEAlkADxIB1ATIh1gTIgOgMQgmgmAAg1QAAg1AmglQAmgmA0AAQA1AAAmAmQAmAlAAA1QAAA1gmAmQgXAWgbAJQgTAGgWAAQgrAAghgZgEBE0gBCQgZgaAAgkQAAglAZgaQAbgZAkAAQAlAAAZAZQAaAaAAAlQAAAkgaAaQgaAagkAAQgkAAgbgagEBCmgJbQgXgYAAghQAAgbAPgVIAIAAIABAAIAAAAQA3AAA4gJIABABQAXAXAAAhQAAAhgXAYQgXAXghAAQghAAgYgXgEBCmgLEIgIAAIAIgIQAYgYAhAAQAgAAAXAXQg4AJg3AAIAAAAIgBAAgEA3cgMtIhHgXIBHAXQgogBgfgWQgKgHgKgKQgognAAg5QAAg4AogoQAogoA5AAQA4AAAnAoQApAoAAA4QAAA5gpAnQgnAog4AAIgGAAgEAyQgbuQgjgjAAgxQAAgxAjgiQAVgWAbgIQBLA5BMAgQACAMAAAMQABAxgjAjQgiAigyAAQgwAAgjgigEA1XgdaIAAAAgEAzAgezQARgFASAAQAyAAAiAjQAaAZAGAiQhMgghLg5gEA90ggUQgXgXABggQgBgaAOgUQAkgHAogYQgoAYgkAHIAJgKQAXgWAgAAIAMABQAZADATASQAWAXAAAhQAAAggWAXQgXAXghAAQggAAgXgXg");
	this.shape_58.setTransform(508.7,496.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#663300").s().p("Ag1IwIAAxRIgNACQgXgBgdACQgQgBgWgGIBnAAIAAgFIB0gCIAkAAQAAAnAbAbQAcAcAnAAIAEAAQAVAAARgKQAOgGAMgMQAHgIAGgJQAOgWAAgcIAAgCIACAAIAARfgAgxoiIAAgDIgEAAIAEAAgAiimgIgCAAIAHAAgAkNnSIAAAAIAAAAgAj6oKIAMAAIAAAAgAjgoKIgBgBIACABgAkMofIgJABIgMgBIAAgGIBfAAQAMACANAFg");
	this.shape_59.setTransform(859,621);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#0033CC").s().p("AhbDgQgag0gEhRIBPgKQADAmAIAUQAMAhAXAAQASAAAKgRQAJgRAAgVQAAgVgJgRQgJgQghgPQg2gYgXgoQgYgoAAg/QAAgpAMglQAMglAYgVQAYgVApAAQA0AAAbAmQAbAmAFBUIhOAJQgDgkgKgRQgKgQgRAAQgOAAgIAMQgHAMAAASQAAANAGAKQAGAKAWAKQA1AXAYAYQAXAYALAiQALAkAAAsQAAAzgPArQgOAsgaAXQgZAWgnAAQhEAAgag1g");
	this.shape_60.setTransform(423.6,142.8);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#0033CC").s().p("AA8EMIgOhZIhdAAIgNBZIhVAAIBloXIBZAAIBlIXgAAcBAIgcjAIgdDAIA5AAg");
	this.shape_61.setTransform(395.7,142.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#0033CC").s().p("ABTEMIAAmYIg0GYIg9AAIg0mYIAAGYIhEAAIAAoXIBtAAIApFFIAqlFIBtAAIAAIXg");
	this.shape_62.setTransform(363.4,142.8);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#0033CC").s().p("AgoEMIAAmTIhVAAIAAiEID7AAIAACEIhVAAIAAGTg");
	this.shape_63.setTransform(332.1,142.8);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#0033CC").s().p("AhbDgQgag0gEhRIBPgKQADAmAIAUQAMAhAXAAQASAAAKgRQAJgRAAgVQAAgVgJgRQgJgQghgPQg2gYgXgoQgYgoAAg/QAAgpAMglQAMglAYgVQAYgVApAAQA0AAAbAmQAbAmAFBUIhOAJQgDgkgKgRQgKgQgRAAQgOAAgIAMQgHAMAAASQAAANAGAKQAGAKAWAKQA1AXAYAYQAXAYALAiQALAkAAAsQAAAzgPArQgOAsgaAXQgZAWgnAAQhEAAgag1g");
	this.shape_64.setTransform(305.1,142.8);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#0033CC").s().p("AgpEMIAAoXIBTAAIAAIXg");
	this.shape_65.setTransform(284.3,142.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#0033CC").s().p("AAmEMIgrikQgJgggGgJQgJgNgMAAIgHAAIAADaIhTAAIAAoXICJAAQAmAAAVANQAUAOANAjQAMAkAAAzQAAAsgKAhQgJAggRATQgKANgSAIQAOAKAHAKIANAcIAMAhIAoCcgAgwgyIAjAAIAVgHQAJgDAEgOQAGgNAAgSQAAgagIgOQgJgOgWAAIgkAAg");
	this.shape_66.setTransform(264,142.8);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#0033CC").s().p("AAtEMIAAjZIhaAAIAADZIhSAAIAAoXIBSAAIAAC8IBaAAIAAi8IBTAAIAAIXg");
	this.shape_67.setTransform(232.4,142.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#0033CC").s().p("Ag9D8QgcgagUhAQgVhAAAhiQABiFAjhIQAjhHBAAAQAzAAAdApQAdApAOBVIhJAgQgEgYgEgMQgHgTgKgKQgKgKgNAAQgbAAgPAtQgLAiAABIQAABYAOAhQANAhAXAAQAYAAANgbQAMgbAFgyIBJArQgHA9gRApQgPApgYAVQgXAVgkAAQgqAAgcgZg");
	this.shape_68.setTransform(202.5,142.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#0033CC").s().p("AgoEMIAAjhIhpk2IBcAAIA1C1IA2i1IBcAAIhoE2IAADhg");
	this.shape_69.setTransform(160.8,142.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#0033CC").s().p("AAmEMIgrikQgJgggGgJQgJgNgMAAIgHAAIAADaIhTAAIAAoXICJAAQAnAAAUANQAUAOAMAjQANAkAAAzQAAAsgJAhQgKAggQATQgLANgSAIQAOAKAHAKIANAcIAMAhIAoCcgAgwgyIAjAAIAVgHQAJgDAFgOQAFgNAAgSQAAgagIgOQgJgOgWAAIgkAAg");
	this.shape_70.setTransform(134.7,142.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#0033CC").s().p("AAmEMIgrikQgJgggGgJQgJgNgLAAIgHAAIAADaIhUAAIAAoXICJAAQAmAAAVANQAUAOAMAjQANAkAAAzQAAAsgKAhQgJAggQATQgLANgTAIQAPAKAHAKIANAcIAMAhIAoCcgAgvgyIAiAAIAVgHQAIgDAGgOQAFgNAAgSQAAgagJgOQgHgOgWAAIgkAAg");
	this.shape_71.setTransform(105.6,142.8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#0033CC").s().p("AhwEMIAAoXIDdAAIAABzIiKAAIAABVICAAAIAABsIiAAAIAABpICOAAIAAB6g");
	this.shape_72.setTransform(76.5,142.8);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#0033CC").s().p("ABTEMIAAmYIg0GYIg9AAIg0mYIAAGYIhEAAIAAoXIBtAAIApFFIAqlFIBtAAIAAIXg");
	this.shape_73.setTransform(44.8,142.8);

	this.reindeer = new lib.Symbol2();
	this.reindeer.name = "reindeer";
	this.reindeer.parent = this;
	this.reindeer.setTransform(424,564.8,1,1,0,0,0,133.2,154.4);
	new cjs.ButtonHelper(this.reindeer, 0, 1, 1);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f().s("#3300CC").ss(3,1,1).p("AhyE7Im4AAIAAk7AoqiGIAAi0IG4AAAIrAAIAAE7IorAAAAAk6IIrAAIAAC0");
	this.shape_74.setTransform(863.7,711.7);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f().s("#FF0000").ss(3,1,1).p("AmmAAIAAlnIFZAAAhNFoIlZAAIAAkxAGnA3IAAExIgBAAIkcAAIiKAAAAAlnIGnAAIAAFn");
	this.shape_75.setTransform(693.2,715.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f().s("#FFFFFF").ss(3,1,1).p("AvkAAIAAktIAAg6IAaAAIAmAAIAOAAIAABBIAAEmIGmAAAvkA3IlZAAIAAg3IFZAAIBOAAAuWA3IAAExIhOAAIAAkxAuWA3IhOAAAKfgmIm4AAIAAiHIG4AAIAAi0IBzAAIAAC0IIsAAAnwA3ImmAAAKfitIBzAAAMSgmIhzAAAMSgmIAAE6IhzAAIAAk6AU+gmIosAA");
	this.shape_76.setTransform(785.1,715.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f().s("#CC0000").ss(3,1,1).p("AgBgfQAWAXgWAWQgYAXgtgMQgtgNgbgWQgbgXADghQADggAYgXQAYgYAXAXQAWAWAYAYQAXAXAWAWgAgBAdQgKAigPAYQgYAkgkALAAlAcIgBAAQgfgGAlgqQAkgsADgaQADgaAYgBQAXgBASASQATASAAAaQAAAagTASQgSASggANQggAOgegFgAAkAZQAAABABACQAAABAAAAQAFApAIAZQASA0AhgR");
	this.shape_77.setTransform(688.1,676.6);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f().s("#663300").ss(3,1,1).p("AI1udIAAgFAuMOoIAHgGApbOoIgOgGAONunIAAOrAI1AEIAAud");
	this.shape_78.setTransform(797.1,658.6);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f().s("#006600").ss(1,1,1).p("AC9+mIgeA+AEG+NIgCgEIgBACACV9TIi/GSIiyF0IigFPIiQEtIiBENIiyFyIh5D8IiLEkIhHCTAXSVuIjrqEIiFlsIiOmFIiHlyIiMl/Ih9lWIhukuIi7oBAmbeUIBwgCADBeKIABAAIIEAAAkEeRIBvgCIB1gBAzZQHIgzBqIiSEyIhaC7IhPCkIhPClIDSgDAsOeaIBagCAzdehIFvgGAYiN6IBGgBAXkWfIBmEYAZKa3IBNDTIh5AAAN9eKIHpAA");
	this.shape_79.setTransform(868.6,371.9);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f().s("#FFFF00").ss(1,1,1).p("AKP9TIgGgEIhoBAIgJAGIATgbIAog3IgKgHIg1gnIgIgGIgigaIBdAAIAqh1IAzBpIBuAAIhHBHIAABSIgkgcIgVgRALw3cQAAAagSATQgTASgaAAQgbAAgSgSQgTgTAAgaQAAgbATgSQASgTAbAAQAaAAATATQASASAAAbgAHmr2QAAAjgZAYQgYAZgjAAQgjAAgZgZQgYgYAAgjQAAgjAYgZQAZgZAjAAQAjAAAYAZQAZAZAAAjgAN7A/QAAAXgQARQgHAHgIAEQgMAGgNAAQgHAAgGgBQgQgEgMgMQgQgRAAgXQAAgYAQgRQARgQAYAAQAXAAARAQQAQARAAAYgAJNfIQAAAcgOAWQgGAJgJAIQgLAMgOAHQgRAJgWAAQgBAAgBAAQgoAAgcgcQgbgbAAgnQAAAAAAgBQAAgEAAgEQACgiAZgZQAcgcAoAAQABAAABAAQAWABARAJQAOAGALAMQAJAIAGAJQALATACAXQAAADABADQAAABAAABgAOOV+QAAAQgLALQgMAMgQAAQgQAAgLgMQgMgLAAgQQAAgQAMgMQALgLAQAAQAQAAAMALQALAMAAAQgArUPrQAAAngbAbQgbAbgnAAQgPAAgNgFQgVgGgQgQQgbgbAAgnQAAgmAbgbQAbgbAmAAQAcAAAXAOQAIAGAHAHQAbAbAAAmg");
	this.shape_80.setTransform(829,365.9);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f().s("#FF0000").ss(1,1,1).p("AYhzHQAFAAAEAAAqPnSIAfAJQA1ArA3AYQBiAsBrgMQDRCIDJAeQAUADATACQAUACATABQAPABDpgbQASgDATgCQFZCrCrjpAtBhfQAdATAcASQCCBQCCAvQDFBIDFgGQgLgHgJgKQgognAAg5QAAg3AogoQAogoA4AAQA4AAAnAoQAoAoAAA3QAAA5goAnQgnAog4AAQgCAAgDAAQBQBEBGAVQAUAFATADQAUABATgCQAKgBDKgeQAOgCAQgDQB0AsB3ABQA8ABA8gKQAAAAABABQAXAXAAAhQAAAhgXAYQgYAXghAAQghAAgXgXQgYgYAAghQAAgbAQgVQAEgEAEgEQAXgYAhAAQAhAAAXAXQCrgcCwhyAgs7PQBPB4BAgKQAVgEASgQQAVgSBaA5QAUANAWAEAFh5BQA1gQA/g5AFbysQAEgGAFgFQAXgWAgAAQAGAAAFABQAaADASASQAXAXAAAhQAAAggXAXQgWAXghAAQggAAgXgXQgXgXAAggQAAgaAOgTgAjd1bQBeECDihZQATgIAUgKQATgJB7AgQAgAIAjgHQAkgIAngYQBJgtBUhjAi4uOQCMA8CPgTQAUgCATgEQAUgFDKACQDKACCOiaAlPvnQARgFASAAQAxAAAjAjQAZAZAHAiAlPvnQBLA5BMAgQACAMAAAMQAAAxgiAjQgjAigxAAQgxAAgigiQgjgjAAgxQAAgxAjgiQAVgWAbgIgAoOrfQAFADAFAEQEoDXE/gIQAUgBATgBQAUgBBMAEQA8ADFUhPQAOgGAQgBQBSgUBigYAl+wMQAYAUAXARAO7NLQAAAkgaAaQgaAagkAAQglAAgagaQgZgaAAgkQAAglAZgaQAagZAlAAQAkAAAaAZQAaAaAAAlgAu5CcIBAAVIC5A6QBgAxBcAoQFNCREaApQAUADATADQAUACHWAWQFHAQBKghQAhgOgRgYQAZgBB5gEIA/gEAh6CHIBHAXQgogBgfgWgAxFHAQCfBECeA1QCCArCCAhQBBAQBBAOQAoAIAoAHQCIAaCHANIDIA1AknVSIAAgBQAAgzAkgkQAkgkAzAAQAzAAAkAkQAkAkAAAzQAAAVgGATQgJAagVAVQgkAkgzAAQgzAAgkgkQgkgkAAgyIDwAnQBeAcA8AMQAHABBfABQAlADDyACIAFAAAw3TQQCLCECkgmQApgKArgUICXAZQAMAOANAMQBaBQCDhBA35VQIA6AMICYAeQEKCHEVAHQBJACBKgIIC/AmQCQA9CQATQA6AHA7ABIAigBAH4WoQAdgDAfABQBFAABOAAQApAAArABQB+AACVABQAPgBAQABQBIAAA+AAQAOAAANAAQFBABAaAAIAAABQgaAAlBAAQgNAAgOAAQgbAAgdAAQg4gBg1ABQh6BxiZhyQgrAAgpAAQhPgBhDAAQggAAgdAAQgCAAgBAAIAAAAQgIgBgIABQAIAAAIAAIAAAAQABAAACAAgA0ONjQD7BbELA9QCAAdCEAXQHmBUIagHQAYgEAUADQHBBKB1haQh6ADiiAFQiiAEh4AEQlkAKAKgBA5IX0QBRBIB6gVQAFgCAEgBQAMgEAMAAIA9ALQDSBcDdAGIBhgBAyrS9QgIgGgGgGQgmgmAAg1QAAg1AmglQAlgmA1AAQA1AAAmAmQAlAlAAA1QAAA1glAmQgXAWgcAJQgSAGgWAAQgrAAghgZIB0ATA2gSVQAVAMAXAJQBYAkBxgRAXRRgIASAxQitgjhIgGQgEAAgFAAID+ApAReRrQACgCACgCIBzgCIAQADQgLgBgIAAQgxACg7ABQgEAAgEABgAYdZ0QAAAEAAAEQgDAhgYAYQgbAbgmAAQgmAAgbgbQgYgYgDghQAAgEAAgEQAAgmAbgbQAbgbAmAAQAmAAAbAbQAbAbAAAmg");
	this.shape_81.setTransform(868.7,398.9);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f().s("#FFFFFF").ss(1,1,1).p("AB4AAQAAAygkAjQgjAjgxAAQgwAAgkgjQgjgjAAgyQAAgwAjgkQAkgjAwAAQAxAAAjAjQAkAkAAAwg");
	this.shape_82.setTransform(444,467.9);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#3300CC").s().p("AAAE7IAAk7IIrAAIAAE7gAoqE7IAAk7IG4AAIAAE7gAAAiGIAAi0IIrAAIAAC0gAoqiGIAAi0IG4AAIAAC0g");
	this.shape_83.setTransform(863.7,711.7);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FF0000").s().p("EgLRAlKIkdAAIiJAAIAAkxIGmAAIAAExgEgYeAlKIAAkxIFaAAIAAExgAx3fiIAAkmIAAhCIGmAAIAAFogAxTbjQAGAAAHgEIABAAIAAAAIABAAIgBAAIAAAAIgBAAQgHAEgGAAIAAAAIgBAAQgUgBgNgiIAAAAIgBgBIAAAAIAAgCIgBgBIABABIAAACIAAAAIABABIAAAAQANAiAUABIABAAIAAAAgA4efiIAAloIFaAAIAAA6QgYAkgkALQAkgLAYgkIAAEugAzEa0gAFgEtQgkglAAgyIDwAnIjwgnIAAgBQAAgzAkgkQAkgjAzgBQAzABAkAjQAkAkAAAzQAAAWgGASQgJAagVAWQgkAjgzABQgzgBgkgjgAE8DWgApIBCIB1ATIh1gTIgNgNQgmgmAAg0QAAg1AmglQAlglA1AAQA1AAAmAlQAlAlAAA1QAAA0glAmQgXAWgcAKQgTAFgVAAQgrAAgigYgAWIjyQgagZABglQgBglAagaQAagZAlAAQAkAAAZAZQAaAaAAAlQAAAlgaAZQgZAagkAAQglAAgagagAT6sLQgYgYAAghQAAgbAQgVIAIABIAAAAIABAAQA3gBA4gJIAAABQAYAXAAAhQAAAhgYAYQgXAYghgBQghABgXgYgAT6tzIgIgBIAIgIQAXgYAhAAQAgAAAYAXQg4AJg3ABIgBAAIAAAAgAIvvdIhGgWQgLgIgKgJQgngoAAg5QAAg4AngoQAogoA5AAQA4AAAoAoQAoAoAAA4QAAA5goAoQgoAng4AAIgGAAgAHpvzIBGAWQgngBgfgVgADk+eQgjgjAAgxQAAgwAjgjQAVgWAbgHQBLA4BMAhQACALAAAMQAAAxgjAjQgiAjgxgBQgxABgigjgEAGrggJIAAAAgEAEUghiQARgGASAAQAxABAiAiQAaAZAHAjQhMghhLg4gEAPIgjEQgXgWAAghQAAgaAOgTQAkgIAngYQAZADATATQAXAWAAAhQAAAhgXAWQgWAXghAAQghAAgWgXgEAPIgkyQAWgXAhAAIALABQgnAYgkAIIAJgKgEAQKglIIAAAAg");
	this.shape_84.setTransform(807.6,513.7);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#33CCFF").s().p("ABlK6QgUgUgLgYQgOgeAAgjQAAgkAOgeQALgYAUgTQApgqA6gDIAKAAQAnAAAfAPQAVALASATQAtAsAABBQAABAgtAtQgtAshAABQhAgBgtgsgAEYHCIhQgPIBQAPgAlGCJQglgmAAg0QAAg0AlgmQAMgLANgIIC4A7QAKAWAAAcQAAA0gmAmQgUAUgYAJQgVAIgZABQg1AAgmgmgAktg+QAdgSAlgBQAZAAAVAJQAYAJAUAUQATASAJAWgAktg+gABGlhQhGgFgygzQg5g5AAhRQAAhRA5g5IANgLQAugoA9gFIAQAAQBRAAA5A4QAmAnANAwQAGAYAAAbQAABRg5A5Qg5A4hRAAIgQAAgADkpTQAWAAAWgDIADAAIgDAAQgWADgWAAIAAAAIAAAAQhPAAhLghIgBAAIgBgBIgCgBQg3gYg0gqQA0AqA3AYIACABIABABIABAAQBLAhBPAAIAAAAIAAAAg");
	this.shape_85.setTransform(810,422.9);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFF00").s().p("EAHtAgnQgnAAgcgcQgbgbAAgnIAAgBIAAgIQACgiAZgZQAcgcAnAAIAEAAQAVABARAJQAOAGAMAMQAHAIAGAJQAMATACAXIAAAGIAAACQAAAcgOAWQgGAJgHAIQgMAMgOAHQgRAJgVAAIgEAAgANLWZQgLgLAAgQQAAgQALgMQAMgLAQAAQAQAAALALQAMAMAAAQQAAAQgMALQgLAMgQAAQgQAAgMgMgAtNRDQgVgGgQgQQgbgbAAgnQAAgmAbgbQAbgbAnAAQAbAAAXAOQAIAGAHAHQAbAbAAAmQAAAngbAbQgbAbgmAAQgQAAgNgFgAM2B2QgQgDgMgMQgRgRABgXQgBgYARgRQARgQAXAAQAYAAARAQQARARAAAYQAAAXgRARQgHAHgJAEQgLAGgOAAIgMgCgAM2B2IAlgEIglAEgAFWq7QgZgYABgjQgBgjAZgZQAZgZAjAAQAjAAAZAZQAZAZAAAjQAAAjgZAYQgZAZgjAAQgjAAgZgZgAKD2vQgSgTAAgaQAAgbASgSQATgTAaAAQAbAAASATQATASAAAbQAAAagTATQgSASgbAAQgaAAgTgSgAIr8sIAog3IgKgHIg1goIgIgFIAIAFIgXAOIAPgTIgigaIBcAAIArh1IA0BpIBtAAIhHBHIAABSIgkgdIgVgQIgCgEIgBACIgGgEIhoBAIgJAGg");
	this.shape_86.setTransform(829,365.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#006600").s().p("A5HclIADADIAAAAIADADQA9AyBTAAIAAAAIAAAAQAYAAAZgEIABAAIAAAAIAEAAQgXAHgRASQgiAiAAAwIAAADIjRADgA0AdyQgNgOgRgIQDTBcDdAGIlwAGQABgwgjgigA0edcQgXgLgcAAIgKAAQgMABgMADIgIAEIgEAAIAAAAIgBAAQgZAEgYAAIAAAAIAAAAQhTAAg9gyIgDgDIAAAAIgDgDIBPikIBai7ICSkyIAzhqQANAFAQAAQAmAAAbgbQAbgbAAgmQAAgngbgbQgHgHgIgFIBGiUICMkkIB4j8ICzlyICAkNICQktIChlPICylzIC/mTIBohAIAGAFIABgDIACAFIAVAQIC7IBIBuEtIB9FWICMGAICGFwICPGGICFFtIDrKDIASAyIBmEYIlagCIgcAAIAcAAIFaACIAAAAIlaAAIgcAAIAcAAIFaAAIBNDSIh5AAIAAgIQAAgmgbgbQgbgbgmAAQgmAAgbAbQgbAbAAAmIAAAIInpAAQgCghgYgYQgcgbglAAQgnAAgbAbQgYAYgCAhIoEAAIgCAAIAAgFQgCgXgMgTQgGgKgHgIQgMgLgOgHQgRgJgVAAIgEAAQgngBgcAcQgZAZgCAjIAAAHIAAACIgjAAQg6gBg7gHQiQgTiQg8QCQA8CQATQA7AHA6ABIh1ACIhvABQghgKgRABQgGgBgBAEQAAAFAIABIAKABIhwACIAAgMQAAgvgagiQgHgLgJgIQgbgcgjgJQgSgEgTgBQgqAAgiAXQg7AFg7AAIAAAAIAAAAIgbAAIgCAAQkVgGkKiIQEKCIEVAGIACAAIAbAAIAAAAIAAAAQA7AAA7gFQgNAHgLAMQgpApAAA7IABARIhaABIhgABQjdgGjThcgAQtbqQAAAjAZAYQAYAZAkAAQAiAAAZgZQAZgYgBgjIgBgPIAAgCIAAACIg4AAIhtAAIAAgCIAfAAICGAAQgFgYgSgSQgZgZgiAAQgkAAgYAZQgSASgFAYIAAACIgDACQg7A2hDAAIAAAAIgBAAQhAAAhIgyIgBgBIgDgDIgDgCIgCgBIACABIADACIADADIABABQBIAyBAAAIABAAIAAAAQBDAAA7g2IADgCIgCAPgAHzbnQAAAPAKAKQAKALAPAAQAPAAAKgLQALgKAAgPQAAgHgDgHICSABIiSgBIgCgCICUAAIAAACIAAABQAAAQALAMQANAMARAAQASAAAMgMQAMgLAAgRIAAgBIAAgBQAAgRgMgNQgMgMgSABQgRgBgNAMQgLANAAAQIiUAAIgGgJQgKgKgPAAQgPAAgKAKQgEAEgDAHIAAAAIgQAAIAQAAQgEAHABAHgAkBbaQAkAjAzABQAygBAkgjQAWgWAJgaQAFgSAAgWQABgzglgkQgkgjgygBQgzABgkAjQglAkABAzIAAABIgDABIgBABQg5AbgxAAIAAAAIAAAAQg8AAgwgoIgCgCIgCgCQgNgLgMgPQALgSAAgYQAAgigYgYQgYgYgiAAQgiAAgYAYQgYAYAAAiQAAAJACAIQgrAUgpAKQglAIgjAAIgBAAIAAAAQh3AAhphhIgCgBIgDgDQAbgKAXgWQAmgmAAg1QAAg1gmglQgmglg1AAQg0AAgmAlQgmAlAAA1QAAA1AmAmIAOANIgBAAIgDAAQgiAFgfAAIAAAAIAAAAQhGAAg7gXIgBgBIgBAAIgBgBQgXgJgUgMQAUAMAXAJIABABIABAAIABABQA7AXBGAAIAAAAIAAAAQAfAAAigFIADAAIABAAQAhAYArAAQAWAAATgFIADADIACABQBpBhB3AAIAAAAIABAAQAjAAAlgIQApgKArgUQAFAXARASQAYAYAiAAQAiAAAYgYQAIgHAFgJQAMAPANALIACACIACACQAwAoA8AAIAAAAIAAAAQAxAAA5gbIABgBIADgBQgBAyAlAlgA2uZ2QgKAKgGANQgGAPgBASQAAAhAXAXQAYAXAhABIACAAQAggBAWgXQAYgXgBghIAAgDQAAgfgXgWQgWgXggAAIgCAAQghAAgYAXgAQvbZIkTgBIETABgABlbSQAGABBfABQAlADDyACIAFAAIgFAAQjygCglgDQhfgBgGgBQg9gMhdgcQBdAcA9AMgA2+aNIg6gMgAVHYYQgQAQAAAYQAAAWAQARQAQAQAXAAQAXAAAQgQQAQgRAAgWQAAgYgQgQQgQgQgXAAQgXAAgQAQgADmXMQgWAXAAAhQAAAgAWAWQAXAYAgAAQAhAAAWgYQAXgWABggQgBghgXgXQgWgWghgBQggABgXAWgAN7XNQChAABAgvIABgBIABAAIAAgBIABAAIAIgBQAXAQAdAAQAgAAAYgTIADgCIAHgGQAMgMAHgNQAJgTAAgXQAAgXgJgTQgHgNgMgMQgbgbgnAAQgnAAgcAbQgbAcAAAnQAAAnAbAcIALAIIAEADIgIABIAEgEIgEAEIkcAIIkaAIIgwABIgNABIkcAIIAAAAQgBAAAAAAIAAAAIABgBIgBABIAAAAQAAAAABAAIAAAAIEcgIIANgBIAwgBIEagIIEcgIIgBAAIAAABIgBAAIgBABQhAAvihAAIAAAAIgBAAQiHAAjKghQDKAhCHAAIABAAIAAAAgAXkXDQitgkhHgGIgKAAIAKAAQBHAGCtAkIj+gqgAGqWuIBMgBIAHAAIAHgBIATgBIAAAAIAAAAIAPABIADAAIgDAAIgPgBIAAAAIAAAAIgTABIgHABIgHAAIhMABIAAAAIgBAAQniAAm4hLIgSgDQiEgWiAgeQkLg9j6hbQD6BbELA9QCAAeCEAWIASADQG4BLHiAAIABAAIAAAAgATmWZIgQgDIAQADIgLgBIgDAAIgBAAIAAAAIgCAAIgCAAIACAAIACAAIAAAAIABAAIADAAIALABgAG/VJQgLAMAAAQQAAAQALALQAMAMAQAAQAQAAALgMQAMgLAAgQQAAgQgMgMQgLgLgQAAQgQAAgMALgAnkQBQgUATgLAYQgOAeAAAkQAAAjAOAeQALAYAUAUQAtAsBAABQBAgBAtgsQAtgtAAhAQAAhBgtgsQgSgTgVgLQCIAaCIANQiIgNiIgaQgfgPgnAAIgKAAQhBgOhBgQQiBghiDgrQidg1ighEQCgBECdA1QCDArCBAhQBBAQBBAOQg6ADgpAqgArRTkQAHgBAGgFQAFgFAAgHQAAgIgFgGQgGgEgHAAQgEgBgDACIgIgBQgIAAgGAEQgEAGAAAIQAAAHAEAFQAGAFAIABIAIgCIAEgEQAGgFAAgHQAAgIgGgGIgEgDQADgCAEABQAHAAAGAEQAFAGAAAIQAAAHgFAFQgGAFgHABQgEgBgDgBQADABAEABgAMlQ9QgZAaAAAlQAAAlAZAZQAbAaAkAAQAlAAAZgaQAagZAAglQAAglgagaQgagZgkAAQgkAAgbAZgAFTRnQgMANAAASQAAASAMANQAMAMATAAQASAAAMgMQAMgNAAgSQAAgSgMgNQgMgMgSAAQgTAAgMAMgAgQPzQgLAKgGANQgOAYgBAdQABAsAfAgQAfAgAsAAQAWgBAUgHQASgJAQgPIAEgEQAbgfAAgpQAAgpgbgeIgEgFQgQgPgSgIQgUgIgWAAQgsgBgfAggAHjPeQgPAPAAAWQAAAWAPAPQAQAQAVAAQAXAAAPgQQAPgPAAgWQAAgWgPgPQgPgQgXAAQgVAAgQAQgAtkOJQgUAUABAcQgBAbAUAUQAUATAbAAQAbAAATgTIABAAQATgUABgbQgBgcgTgUIgBgBQgTgSgbAAQgbAAgUATgAQXMWIgDADQgOAOAAAVIAAABQAAATAOAOQAOAOAVAAQAUAAAOgOQAPgOAAgUQAAgVgPgOQgCgDBRgFIA/gDIiwgEQgTABgNALgAMvNTQCjAAAzgWIABAAIgBAAQgzAWijAAIgBAAIAAAAQhOAAhpgFIgCAAQnWgXgUgCIgmgGQkbgplNiRQhcgohggwQBgAwBcAoQFNCREbApIAmAGQAUACHWAXIACAAQBpAFBOAAIAAAAIABAAgAmJLiQgSARAAAaQAAAaASARQASATAagBQAZABASgTQASgRAAgaQAAgagSgRQgSgTgZABQgagBgSATgAt3HiQgNAIgMALQglAmAAA1QAAA0AlAmQAmAmA1AAQAZgBAVgIQAYgJAUgUQAmgmAAg0QAAgcgKgXQgJgWgTgSQgUgUgYgJQgVgJgZAAQglABgdASgAKAJoQAAAhAXAYQAYAYAhgBQAhABAXgYQAXgYAAghQAAghgXgXIgBgBQCrgcCwhyQiwByirAcQgXgXggAAQghAAgYAYIgIAJQh3gCh0grQB0ArB3ACQgPAUAAAbgACdIxIAOgBIAHAAIDUggIAHABQANgBAKgEQAIgEAHgHQAQgQABgXQgBgXgQgQQgPgQgXAAQgWAAgRAQQgPAQAAAXQAAAXAPAQQAOANASACIjUAgIgHAAIgOABIgBAAIAAAAIgRgBQgTgDgTgFQhHgVhQhEIAGAAQA3AAAngnQApgoAAg5QAAg4gpgoQgngog3AAQg5AAgoAoQgoAoAAA4QAAA5AoAoQAKAJAKAIIgbAAIAAAAIgBAAQi0AAi0hBIgGgCQiCgviChRIg5glIA5AlQCCBRCCAvIAGACQC0BBC0AAIABAAIAAAAIAbAAQAfAVAoABQBQBEBHAVQATAFATADIARABIAAAAIABAAgAt3HiIhBgVgANHDcQgUAVAAAcQAAAdAUATQAUAVAcgBQAdABAUgVQAUgTAAgdQAAgcgUgVQgUgTgdgBQgcABgUATgAp8iMQg5A5AABRQAABQA5A5QAzAzBGAFIAQAAQBRAAA5g4QA5g5AAhQQAAgbgGgYQDRCHDKAeIAmAGIAnACIABABIAAAAIAAAAQARAAC2gWIADAAIADAAIABAAIALgCIAEAAIABAAIAOgCIALgBIAMABQAOAAALgGIAGADIAFADQCLBCBvAAIAAAAIAAAAQCZAABiiAIAAAAIADgDIABgDIgBADIgDADIAAAAQhiCAiZAAIAAAAIAAAAQhvAAiLhCIgFgDIgGgDQAJgEAHgHQARgRAAgXQAAgXgRgQQgRgRgYAAQgXAAgRARQgRAQABAXQgBAXARARQAMAMAQAEIgLABIgOACIgBAAIgEAAIgLACIgBAAIgDAAIgDAAQi2AWgRAAIAAAAIAAAAIgBgBIgngCIgmgGQjKgejRiHQgNgwgmgnQg5g4hRAAIgQAAQg9AFgvAoIgegKIAeAKIgNALgAATgkQgQAQAAAWQAAAYAQARQAQAQAYAAQAXAAARgQIACgCQAOgQAAgXQAAgVgOgQIgCgBQgRgRgXAAQgYAAgQARgAKZkqQgQABgOAGQgQAHgOAOQgcAcAAAnQAAAoAcAcQAcAcAnAAQAoAAAcgcQAcgcAAgoQAAgngcgcQgcgcgoAAIgHAAIC0grIi0ArIAAAAgAI9kVIABAAIApgKIAKgCIAKgCIgKACIgKACIgpAKIgBAAQkPA+g9AAIAAAAIgFAAIgCAAQgzgDgZAAIgDAAIAAAAIgOAAIgCABIgmABIgEAAIgTAAIAAAAIgBAAQkrAAkWjEIgNgJIgCgCIgKgHIAKAHIACACIANAJQEWDEErAAIABAAIAAAAIATAAIAEAAIAmgBIACgBIAOAAIAAAAIADAAQAZAAAzADIACAAIAFAAIAAAAQA9AAEPg+gAAcm1QgaAZABAlQgBAjAaAaQAZAaAlAAIALgBQAVgDARgMIAMgKQAagagBgjQABglgagZIgMgKQgRgNgVgCIgLgBQglAAgZAagAFloPQgWAXAAAhQAAAgAWAYQAYAWAgAAQAgAAAYgWQAWgYAAggQAAghgWgXQgYgWggAAQggAAgYAWgAl+qYQgjAjAAAwQAAAxAjAjQAjAjAwgBQAyABAigjQAjgjgBgxQAAgMgCgLIAEABIAAAAIADABQBmArBpAAIAAAAIAAAAQAfAAAggEIAHgBIAmgGIABAAQAPgDBkAAIAAAAIAAAAIAdAAIAFAAIBIAAIAFABIAAAAIABAAQC9gBCIiKIABgCIABgBIACgBIACgCIAHgIIgHAIIgCACIgCABIgBABIgBACQiICKi9ABIgBAAIAAAAIgFgBIhIAAIgFAAIgdAAIAAAAIAAAAQhkAAgPADIgBAAIgmAGIgHABQggAEgfAAIAAAAIAAAAQhpAAhmgrIgDgBIAAAAIgEgBQgGgjgagZQgigigygBQgSAAgRAGQgXgSgYgUQAYAUAXASQgbAHgVAWgAg1tLQgZAZABAjQgBAjAZAYQAZAZAiAAQAjAAAZgZQAZgYAAgjQAAgjgZgZQgZgZgjAAQgiAAgZAZgAFPtOQgBAhAXAWQAXAXAgAAQAhAAAXgXQAWgWAAghQAAghgWgWQgTgTgZgDQBIgtBUhjQhUBjhIAtIgMgBQggAAgXAXIgJAKIgEABIgBAAQgOADgOAAIAAAAIgBAAQgPAAgOgEIgEgBIgCAAIgCgBIgBAAIgJgCIgDgBIgJgCIgBgBIgZgGIgDAAIgBAAIgCgBIgCgBIgDAAIgEgBIgKgCIgMgCIAAAAIgEgBIAAAAIgagDIgBAAIgCAAIgFgBIAAAAQgJAAgFACIgBAAQgTALgTAHIgCABQg5AWgwAAIgBAAIAAAAQiLAAhGi1IgEgLIAEALQBGC1CLAAIAAAAIABAAQAwAAA5gWIACgBQATgHATgLIABAAQAFgCAJAAIAAAAIAFABIACAAIABAAIAaADIAAAAIAEABIAAAAIAMACIAKACIAEABIADAAIACABIACABIABAAIADAAIAZAGIABABIAJACIADABIAJACIABAAIACABIACAAIAEABQAOAEAPAAIABAAIAAAAQAOAAAOgDIABAAIAEgBQgOATABAagAg5ybQgUAVAAAeQAAAeAUAVQAWAVAeAAQAcAAAWgVQAUgVABgeQgBgegUgVQgWgVgcAAQgeAAgWAVgAEZ0DQgTAUAAAbQAAAbATATQAUATAaABQAcgBASgTQAUgTAAgbQAAgbgUgUQgIgIgLgFQA1gQA/g4Qg/A4g1AQQgMgFgPgBQgTAAgQAKQgWgEgUgNIgCAAQhBgpgcgCIgCAAIAAAAQgJAAgFAFQgSAPgUAEIgLABIAAAAIgBAAQg6gBhFhmIAAgBIgBgBIgBgCIAAAAIgBgCIgBgBIABABIABACIAAAAIABACIABABIAAABQBFBmA6ABIABAAIAAAAIALgBQAUgEASgPQAFgFAJAAIAAAAIACAAQAcACBBApIACAAQAUANAWAEQgGAEgFAFgAA14DQgTAUgBAbQABAbATAUQATATAcAAIABAAQAVAAARgMIAIgHQAUgUgBgbQABgbgUgUIgIgGQgRgNgVAAIgBAAQgcAAgTATgAD34iQgSASAAAbQAAAaASATQATASAaAAQAbAAASgSQATgTAAgaQAAgbgTgSQgSgTgbAAQgaAAgTATgA0edcIAAAAgAp0c0IAAAAgAI3bZIg+AAQAegCAeAAIACACIAAAAgAH2bZIAAAAIAAAAgAH2bZIAAAAIAAAAgAH2bZIAAAAgAHmbZIAQAAIAAAAIgQAAgAH2bZgAI1bXIAAAAgAocZaIAAAAgAqzZBIAAAAgARfWcIAAAAgARnWbIAAAAgAkxPjIAAAAgAmBPUIAAAAgAYiuWIAAw0IBGAAMAAAAtmIhGABgAYiuWIAJAAIgJAAgAGGIQIAAAAgAk2g1IAAAAgApviXgAC9+DIAKAIIgoA2g");
	this.shape_87.setTransform(868.6,368.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("ABiXGIAAkxIlYAAIAAg3IFYAAIAAkuIAAg6IAZAAIAnAAIANAAIAABCQgIgagFgoQAFAoAIAaIAAEmIGnAAIAAA3ImnAAIhNAAIBNAAIAAExgACvReIhNAAgABiMwQAPgYAKgiQgKAigPAYgAbmVyIAAk7IBzAAIAAE7gAdZQ3IhzAAIm4AAIAAiHIG4AAIAAi0IBzAAIAAC0IIrAAIAACHgAdZOwIhzAAgACvM4IAAAAgEglggT4QgjgjAAgyQAAgyAjgjQAjgjAyAAQAxAAAjAjQAkAjAAAyQAAAygkAjQgjAjgxAAQgyAAgjgjg");
	this.shape_88.setTransform(675.6,603.7);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#663300").s().p("AuMOoIAHgGIEcAAIAOAGgAI1ADIAAucIgNACQgXgBgdACQgQgBgWgGIBnAAIAAgFIB1gCIAjAAQABAnAbAbQAcAcAnAAIADAAQAWAAARgKQAOgGALgMQAIgIAGgJQAOgWAAgcIAAgCIACAAIAAOqgAI5uaIAAgDIgEAAIAEAAgAHHsYIgCAAIAIAAgAFctKIABAAIgBAAgAFwuCIAMAAIAAAAgAGJuCIAAgBIACABgAFeuXIgJABIgMgBIAAgGIBfAAQAMACAMAFg");
	this.shape_89.setTransform(797.1,658.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_reindeer}]}).to({state:[{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.btn_reindeer2}]},10).to({state:[{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_45},{t:this.shape_84},{t:this.shape_55},{t:this.shape_54},{t:this.shape_52},{t:this.shape_47},{t:this.shape_46},{t:this.shape_48},{t:this.shape_51},{t:this.shape_49},{t:this.shape_83},{t:this.shape_44},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_34},{t:this.shape_29},{t:this.shape_40},{t:this.shape_39},{t:this.shape_36},{t:this.shape_31},{t:this.shape_30},{t:this.shape_32},{t:this.shape_35},{t:this.shape_33},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.reindeer},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60}]},9).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(536.6,406.8,1076.3,845.5);
// library properties:
lib.properties = {
	id: 'CEC8E2DA79329A4FBE2F22C3489C5FA1',
	width: 1024,
	height: 768,
	fps: 10,
	color: "#66CCFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CEC8E2DA79329A4FBE2F22C3489C5FA1'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;