(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.halfEyes = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AAFAAQAAACgCABQAAACgDAAQgBAAgCgCQgBgBAAgCQAAgDABAAQACgBABAAQADAAAAABQACAAAAADg");
	this.shape.setTransform(25.525,4.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(3,1,1).p("AB7ANQgZkCA9ghQA8ghBPASQAIADAIABIADACQArAOAkBeQAIBYACBNQAAAQAAAPQADDcghAcQgkAeg6ARIhyAAQgJglgIg5QgThvgJheIBiACIABAAIAJARQAJASALALQAjAcAlhAQACgDACgFIhHgCIAjAAIAHAAIATAAIBZACAgWACQgDgRgDgYQgOgYgLgXQgzhYgqg3QgOgSgNgOQgNgPgNgIQglgggiAFIgfBRQgXA4gRA1QgLAlgNAiQgFATgFATQhADrBKAhQBRAkBfAUQBbgqArhKQAAgCACgCQAqhNgLhxIiBgEIhigFIh+gFAj5gHIAFAMQAKASALAKQAFAEAHAEIACAAIAAABIAMAAQAYgFAWgnAEAAPIgiAA");
	this.shape_1.setTransform(-0.0036,0.0102);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ACoCjQgJglgIg6QgThtgJhfIBiACIABAAIAJARQAJATALAKQAjAdAlhAIAEgIIhHgDIAjAAIAHAAIATAAIBZADQADDbghAcQgkAeg6ARgAltBqQhKggBAjsIB+AGIAFAMQAKATALAKQAFAEAHADIACAAIAAACIAMAAQAYgFAWgpICBAFQALBxgqBNIgCAEQgrBKhbAqQhfgVhRgkg");
	this.shape_2.setTransform(-0.0036,14.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("ADVAeQgMgLgIgSIgJgQIAiAAIBHACIgFAIQgZAsgZAAQgLAAgKgJgADUALIABAEIAEABQAAAAABAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBgBQgBAAAAAAIgEACQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAAgADVAPIgBgEQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAIAEgCQAAAAABAAQABABAAAAQAAAAABAAQAAAAAAABQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAQgBAAAAAAIgEgBgADeALIAAAAgAj4ALIAAgBIgBAAQgIgEgFgEQgKgJgKgSIgGgNIBjAFQgXAngYAFgAj9gWIAAACIAAADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQgBAAAAAAIgEABg");
	this.shape_3.setTransform(3.825,3.1141);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC99").s().p("AEuCiIgTAAIgHAAIgjAAIghAAIgCAAIhhgCQgakCA9ghQA9ggBOASIARAEIACABQArAOAkBfQAIBWACBOIAAAggAimCQIhigEIh+gGIAKglQANgiALgmQASgzAWg4IAghRQAhgGAmAhQAMAIANAPQAOANAOASQAqA4AyBXIAaAuIAFAqg");
	this.shape_4.setTransform(1.45,-14.7398);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.halfEyes, new cjs.Rectangle(-42.1,-32.7,84.2,65.5), null);


// stage content:
(lib.MPHFinalDMacias = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		this.Face1_btn.addEventListener("click", ClickFace1.bind(this));
		
		function ClickFace1() {
			this.eyes1.x = 100;
			this.eyes1.y = 100;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Body Parts
	this.eyes1 = new lib.halfEyes();
	this.eyes1.name = "eyes1";
	this.eyes1.setTransform(660.85,351.35);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAvBaIgTABQACgeAAgeQAAgUgCgHQgDgGgGgEQgHgFgKABQgJAAgIAEQgJAGgDAEQgCAFAAARIAAAVQAAAeABADQACACAIABIALABIAAAHIgfgBIgfABIAAgHIAHgBIAJgBQACgCABgEQABgHAAgXIAAhRQAAghgCgDQgBgDgJAAIgIAAIAAgHQASgCAMgEIAKgDQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIgBAFIAAAWIgBAaIAAAhIAQgPQAGgFAFgCQAFgBAHgBQAOABAKAFQAKAFAEAIQADAIAAAUIAAAkIABAUQAAABAAAAQAAABAAABQAAAAABABQAAAAABABQABABAGAAIAJABIAAAHIgXgBg");
	this.shape.setTransform(447.725,395.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgFBLQgHgCgCgGQgDgFAAgLIAAgXIAAgtIgTABIAAgGIATgJIgBglQAPgGAFgEIADACIgCAtIAYAAIAKAAIgCAMIgEAAIgYAAIgEAAIAAAwQAAASABAFQABAGAEACQAEAEAFAAIAHgCIAHgEIADAEIgLAOIgIACIgHABQgJAAgFgEg");
	this.shape_1.setTransform(436.4,397.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgjA3QgHgEgEgIQgEgHAAgQIABgTIAAgTQAAgUgBgCQgBgDgHAAIgLAAIAAgGQARgCAOgFIAKgEQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABIgBAMIgBAvQAAAWABAHQACAFAGAFQAGAEAIAAQALAAAJgIQAKgHADgHQABgFAAgUQAAgkgBgDQgBgDgKAAIgKAAIAAgGIAWgEIASgGIACgBQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAALIgCBIQAAASACADQADAEAIAAIAIAAIAAAHIgagBIgQABIABgWIgHAHQgIAKgJADQgIAFgNAAQgLAAgIgGg");
	this.shape_2.setTransform(424.525,399.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgrAsQgPgRgBgbQAAgRAIgNQAIgOAOgIQAOgHARAAQAaAAAQAPQAPAPAAAaQAAAdgUASQgTAQgYAAQgYAAgPgQgAgTguQgIAFgEAIQgFALAAANQAAAZALARQAKASASAAQAPAAAJgLQAJgLAAgXQAAgRgFgOQgGgNgIgHQgJgGgKAAQgKAAgHAFg");
	this.shape_3.setTransform(410.25,399.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABlA7IgTAAIgSAAQABgWAAgfQABgYgCgIQgDgIgGgFQgGgEgKAAQgKAAgIAFQgHAHgCAIQgCAEABAmIAAAZQAAABAAABQAAABABAAQAAABAAAAQABABAAAAQACACAIAAIAJABIAAAHIggAAIgeAAIAAgHIAIAAQAHAAACgCQACgCABgIIABgpQAAgTgDgHQgCgIgHgEQgGgEgIAAQgKAAgHAFQgJAGgCAHQgCAFAAAXIAAAmQABAHACABQABACAJAAIAIABIAAAHIgcAAIgiAAIAAgHIAKAAQAHABACgFQACgEgBgqIAAgjQgBgFgBgCQgCgCgIABIgIAAIAAgHQASgDANgEIAJgDQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIgBAFIAAAPIARgOQAEgEAEgCQAGgBAHgBQAOAAAIAGQAHAEAHANIAQgOQAEgEAGgCQAIgCAHgBQALAAAJAGQAJAEAEAJQAFAIgBAOIAAAvQAAAQACADQACADAHAAIAJAAIAAAHg");
	this.shape_4.setTransform(392.6,399.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_5.setTransform(662.725,36.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgFBLQgHgDgCgFQgDgFAAgKIABgYIAAgtIgUABIAAgGIAUgJIgBglIATgKIADACIgCAtIAYAAIAKAAIgBANIgGAAIgXAAIgEAAIAAAuQAAATABAGQACAEADAEQAEADAGAAIAGgCIAHgEIAEAEIgMAOIgIACIgHABQgJAAgFgEg");
	this.shape_6.setTransform(653.5,34.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgvA0QgHgHgBgOQABgMAFgJQAGgJALgEQALgEAngHQAAgQgHgHQgIgKgPAAQgGAAgFACIgJAEIgHARIgHgCIAAgIIAAgJIAOgHQAJgGAHgBQAGgCAIAAQAQAAAKAHQALAIACALQABAJABAiQgBAhACADQABAEAFAAIAKAAIAAAIIgUgBIgSABIAAgLIAAgLIgYATIgHAEIgKABQgPAAgJgIgAgYAGQgKAGABAOQgBAJAGAFQAFAGAJAAQAJAAAHgGQAIgFAIgKIAAgaIAAgGQghAHgJAGg");
	this.shape_7.setTransform(643.15,36.375);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAvBaIgTABQACgfAAgdQAAgUgCgHQgDgGgGgEQgHgEgKAAQgJAAgIAEQgJAFgDAGQgCAEAAARIAAAVQAAAeABADQACACAIABIALACIAAAGIgfgBIgfABIAAgGIAHgCIAJgCQACgBABgEQABgGAAgYIAAhRQAAghgCgEQgBgCgJAAIgIAAIAAgIQASgCAMgDIAKgDQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIgBAFIAAAWIgBAaIAAAhIAQgPQAGgFAFgCQAFgCAHAAQAOABAKAFQAKAFAEAIQADAIAAAVIAAAkIABATQAAABAAAAQAAABAAABQAAAAABABQAAAAABAAQABACAGAAIAJACIAAAGIgXgBg");
	this.shape_8.setTransform(629.625,33);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(2,1,1).p("AD0AtQgHgUAJgJQAEgEAHgCIBvAJIIMAqIg2BXQgoBegpDeQgoDfBQCPIi+grIgBAAQgNg0gEgeQgGgjAGglIAGgeIgJADIgCAAIgBACQgDAAgDABQgDACgDAAQgRADgKgDQgSgDgDgCQgDgBgCgCIgfgQIgSgUIgEAjQgGApgDAjQgGBuAaAFAFzNTQgwhzg9jBQg/jAAMhJICdkDAHVI3IgRgTIgIgdIAAgWIAMgBQAQgGALgCQAlgGAPAJQAEAFADAEQACADACADQAAACAAABIgEgJIAXgKIAHgDQATAAALABQAYADAFAGQAGALAQARIABARQACAVgPANQgEAGgXALIgTAKAi2n3IA2hhIhihxArqtiIiRAbAFhNjIB7hKQATgRAXgJIACgBIACABIBUAU");
	this.shape_9.setTransform(494.05,530.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#000000").ss(1,1,1).p("AYiuHQAAAOgFAKQgGALgHAAQgIAAgFgLQgHgKAAgOQAAgPAHgKQAFgLAIAAQAHAAAGALQAFAKAAAPgAV8uLQAAAOgFAKQgFALgJAAQgHAAgFgLQgGgKAAgOQAAgQAGgKQAFgKAHAAQAJAAAFAKQAFAKAAAQgArNu5IgEAXQgDAdABAZQAEBSAvAZQAwAaD6gYQB+gOB1gRICuAAQB1ARB+AOQD6AYAvgaQAugZAGhSQABgZgDgdIgEgXALpukQgPgKgqgHQgcgEgfAAQg9AAhFAQAhiqcIB9gFADGI/IglABIgeACIhPAEQgUgZgMgdQgVg6AkgYIA5gBIAJAYIAAAMIAGAQIAiAAIAGgSIgBghIAZADIAUALIAWAoIABAtgApdukQgPgKgqgHQgagEgdAAQg3AAg9AMAxJsqQgWAKgWAPAxJsqQgCAGgIADQgWAKgMAGQgCABgDACIgEACQAFgCAEgDAywuvQA8AYAVAhQAhA4gLAUAvUqdIAAhdQgXhMg0AOQgWAFgUAJAvUqdQhsBwg/ARQg9ASgpAHIg+gYQhKggg4ghQixhpBKhOQBMhPCeg1QArgOAqgKApUmhQgZgTgagVQgxgmg2gnQiuh+g4gJAB1NWQgBAAgCAAAggOqIgSAQ");
	this.shape_10.setTransform(534.4592,521.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(1,1,1).p("ALGg0QAAACAAADQgBABgFAAQgBAAgCgBQgCgDAAgCQAAgBACgCQACgDABAAQAFAAABADQAAACAAABgAoaAwQAAAEgCABQAAACgBAAIgBgCQAAgBAAgEQAAgDAAgDIABgBQABAAAAABQACADAAADgArCAzQAAACgBACQAAAEgBAAIgCgEQAAgCAAgCQAAgDAAgDIACgDQABAAAAADQABADAAADg");
	this.shape_11.setTransform(743.45,424.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(3,1,1).p("AQy+0IgcAKIgagYQANgFAOgOQAbgYADgkIAQiwIAeh9IBOjEQA5iVCVgGQBygKBogRQCKgYCIAzQBPBNA7B9IADFxIAUCNIA2AYIgJAxIgigYAf1+0IglgPIgDh2IgYiDIg2hfIj3gQIkNAPIhUAOIgtAWIglAbIguBJIhBCvIgZAoIgbAJAf1+0IgQDkIAyAAIAAjUAf1+0IAiAQAAFwYQgkkdg5gUQghgNBdgQQBdgQCAgDQCVgBBoALQBpALgeAOQggANAbDsQAGAxAHApQAEAjAFAeIAeCJIAAAoID6AAIBhAjIAxBJIADAsIgDBPIizAoInvAAIjsgiIi6AAIjRgRIh4hEIgCgoIA3hqIDFgWIDzAhQgEgngDgoIgUjGIAAgDIIMAVARm/lIg0AxIgICKIgcBaIBMAAgAI4s5IofgWAMsG5Qgsgcg2gXQhogygqATQAHhCAXg5QAyhuBcBOQBXBNAEA/QABA/gUAigAXwF4QgKgBgLABQgqgBguAFQhyAKgdAlQgbg9gHg9QgKh4BzAXQB1AVAhA2QAdAxACAjQAAAEAAAFgADXVeQgIg5gKiKQgNiiAGhEQAAgIACgGQACghAKAAQAKAAAugJQA0gKAjgEQB4gLA+A4IABACQAFAEACAFQAGAGAEAIQACAGADAIQAKAegEAvQAAAbgGAfQgHApgPAwQgBAHgDAIQgbBSghA+QghA8gqAmQgqAng+ASQg/g0gJhLgAkEXJQgghTgXhiQgxjPAmhcQAOgeAbgWQAKgIAMgGQA3ghBkgFQBvgFAtArQAHAGAGAIQAOAXADAfIAKBFQAJBTABBHQAEDmhQAdQhOAehugOQgjgEgigIIgOgCIgCgBEgI+gvLIAAYOEguKAKyMAAAgh5MAlMAAKIAATsMA3JAAAAj+XNIABAAIACABIgDgBIgCgBIACAAgAkEXJIAAACQACABACAAAnNWpIAjAAQApADAmAGQAuAJApAOEgc8AiYQgBAEgCADQgbAtgoAfQgKAIgLAFQgQANgfAIQhXAXjAgCQhqgBhDgUQhDgWgagpQgIgNgEgQIgCAAIgBAAQhYAGg2gYEglmAjMQhGgeg7ABQgHAAgFACQAAACAAAXIACA0QADBJAHBBQADAdACAZIAMAAIB6AAIDzAAICZAAIBOjTEgn1AixIACAZEgkoAoEQAxgRAugMQEHhJALBJQAIA1AHBGQACAdADAgQAAAHABAHQAAAIACAHQADAmACAcIAuAAQAbAhgJAaQgIAbguATIARBlEgnNAo/QAEAWAEAWQAEAOAEAPIAAADQAFASAGAQQACAIADAHQAZBBAhAMQBKAaDXgdQBtgNAbAFIAvAAEgnNAo/IBQgeQARgGAQgGQAagJAagIIC/hGEgniAm+QAGAtAGAmQADAYAGAWEgniAm+IAVCBEgl9AohIBVgdEgeRAtnQhfAnkAADAj5XPQAzAUAjAi");
	this.shape_12.setTransform(666.475,312.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#996633").s().p("AHSCKIAQjjIAjARIAADSgAoECKIAdhaIAIiJIAbgJIAZgnIgNETg");
	this.shape_13.setTransform(821.925,123.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#336600").s().p("AH4GCIgjgQIgkgQIgDh1IgYiDIg2hfIj3gPIkMANIhUAOIgtAWIglAbIguBJIhBCwIg0AxIgdAJIgZgXQANgFAOgOQAbgYADgkIAQiwIAeh8IBNjFQA6iUCUgHQBzgJBngSQCKgXCHAyQBQBOA6B9IAEFwIAUCNIA2AXIgJAygAnsFygAm4FBIgZAnIgbAKg");
	this.shape_14.setTransform(823.2,77.7519);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#660033").s().p("AhcAPQgWg5AlgYIA5gCIAJAYIAAAMIAGAQIAhAAIAGgRIgBghIAZADIAUAKIAWAoIABAsIgQAeQgMgBgSAAIgHADIgeABQgPgJgkAGQgLACgQAGQgUgagMgcg");
	this.shape_15.setTransform(545.7781,572.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#990033").s().p("AtvfwQgwhyg9jBQg/jBAMhJICdkCIIMApIg1BXQgpBegoDeQgoDfBPCQIi+gsIgBAAQgMg0gFgeQgGgiAGgmIAGgdIAUgLQAWgLAEgFQAPgOgBgVIgCgQQgQgSgGgKQgFgHgXgCIAQgfIgCgtIgWgnIgTgLIgagDIACAhIgGARIgjAAIgGgQIAAgMIgIgYIg5ACQgmAYAXA6QAMAcATAaIgMACIAAAVIAIAdIASAUIgFAiQgGAqgDAiQgGBuAaAFIh7BLgAHz83IgVjGIAAgCIIMAUIAKBBIAeCJg");
	this.shape_16.setTransform(619.129,412);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("A2QPIQgigNgYhBIgGgPIgLghIAAgDIgIgeIgIgrIBQgeIBVgeQAxgQAugMQEHhKALBKQAIA0AHBHIAGA9IABANQAAAJABAGIAGBDIgwAAQgbgGhsAOQhyAPhKAAQhDAAgigMgAyGJ9IjzAAIh6AAIgMAAIgGg2QgGhBgDhKIgDgzIAAgaQAEAQAIAOQAaApBEAVQBCAVBqABQDBABBWgXQAggIAQgMQALgGAJgIIhNDUgAM7lkQgjgEghgHIgOgDIgDAAIgBgBIgCAAIAAgCIgBAAIgFAAIAAgCQgghTgXhjQgxjPAnhbQANgfAbgVQAKgIAMgGQA4ghBjgFQBwgFAtArQAHAGAGAIQAOAXADAfIAKBFQAKBSABBIQADDlhQAeQg1AUhEAAQggAAgkgFgAQYq4QgHAKAAAQQAAAOAHAKQAFALAGAAQAJAAAFgLQAGgKAAgOQAAgQgGgKQgFgKgJAAQgGAAgFAKgAS6njQgIg5gLiKQgMiiAGhDQAAgIABgGQADghAKAAQAJAAAvgJQA0gKAjgEQB4gMA9A5IABABQAGAEACAGQAFAGAEAIIAGANQAKAfgEAuQAAAbgGAgQgHApgQAvQgBAIgDAIQgbBRghA+QghA9gpAmQgqAng+ARQhAg0gIhLgAS+qzQgHAKAAAPQAAAOAHAKQAEALAIAAQAIAAAFgLQAGgKAAgOQAAgPgGgKQgFgLgIAAQgIAAgEALgAQeqhIAAgFIAAgFIABgDQABAAAAAAQAAAAAAABQAAAAABABQAAAAAAABIABAFIgBAFQAAABAAAAQgBABAAABQAAAAAAAAQAAAAgBAAgATFqjIAAgGIAAgFIABgBQABAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAIABAFQAAAEgBACQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAgBAAg");
	this.shape_17.setTransform(567.0321,497.7548);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC0000").s().p("ALIMdQADgjAGgpIAEgjIASAUIAfAQIAFADQADACASADQAKADARgDIAGgCIAGgBIABgCIACAAIAJgDIgJADIgCAAIgBACIgGABIgGACQgRADgKgDQgSgDgDgCIgFgDIgfgQIgSgUIgSgTIgHgdIAAgWIAMgBQAQgGALgCQAlgGAPAJIhPAFIBPgFIAHAJIAXgKIAHgDQASAAAMABIglACIAlgCQAYADAEAGQAGALARARIABARQACAVgPANQgFAGgWALIgTAKIgGAeQgGAlAGAjQAEAeAMA0IhUgUIgBgBIgCABQgXAJgUARQgZgFAGhugAMhJ0IAAgDIgDgGgAomGwIAMAAIB6AAIDzAAIi/BGIg0ARIghAMIhQAegAqPn6QhKghg4ggQixhqBKhOQBMhPCeg1QArgNAqgLIAdAAQA8AYAVAhQAhA5gLAUQgWAKgWAPIgFACIgEADIAJgFQAWgPAWgKQAUgJAWgFQA0gOAXBLIAABdQhsBwg/ASQg9ARgpAIgAp7rQICRgbgAm/sBQgWAKgMAHQAMgHAWgKQAIgCACgGQgCAGgIACg");
	this.shape_18.setTransform(468.466,518.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("Ak0UXQgHgKAAgOQAAgPAHgKQAFgLAIAAQAHAAAGALQAFAKAAAPQAAAOgFAKQgGALgHAAQgIAAgFgLgAksTrIAAAFIAAAGIABACQAAAAAAgBQABAAAAAAQAAAAAAgBQAAAAAAAAQACgCAAgEIgCgFQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAgAnaUTQgGgKAAgOQAAgQAGgKQAFgKAHAAQAJAAAFAKQAFAKAAAQQAAAOgFAKQgFALgJAAQgHAAgFgLgAnUTuIAAAFIAAAFIACADQAAAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIABgFIgBgFQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAAAAAgAOvSQQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIACgEIADgCQAFAAABACIAAAEIAAAEIgGABIgDgBgAC6HeQhogxgqATQAHhDAXg5QAyhtBcBOQBXBNAEA/QABA/gUAhQgsgcg2gXgALCGKQgKh4BzAXQB1AVAhA2QAdAxACAjIAAAIQgKgBgLABQgqgBguAGQhyAJgdAmQgbg9gHg9gAjtmqIjsghIi7AAIjRgRIh4hFIgCgnIA3hqIDFgWID0AhIgHhPIIeAWIAAAnID6AAIBhAjIAxBJIADAsIgDBQIizAngAoKu/Qglkdg5gVQghgMBdgQQBegQCAgDQCVgCBoALQBoALgdAPQggAMAbDsIAMBag");
	this.shape_19.setTransform(719.275,303.191);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.eyes1}]}).wait(1));

	// Character
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_20.setTransform(575.075,360.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AglAsQgPgPAAgbQAAgUAJgPQAFgKAQgIQAPgIANAAQAWAAAMAMQANANAAAXIAAAHIgQADIgkABIgdAAQAAAXAMAMQAMAMARAAQAJAAAIgCQAJgDAIgGIACACIgEAKQgKAGgLADQgKADgMAAQgXAAgQgQgAgUgpQgIAKAAAVIApABIARgBIAAgGQAAgLgEgKQgDgGgGgEQgHgEgJAAQgNAAgIAKg");
	this.shape_21.setTransform(563.725,360.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AAABWIgeABIAAgIIALgBQAGAAACgCIABgMIABgqIgBgdQAAgEgCgBQgCgCgGAAIgKAAIAAgHIAWgEIASgGIACABIgBAVIgBAzQAAAQACALQAAAFACACQACACAHAAIAIABIAAAIIgfgBgAgJg+QgEgDAAgHQAAgFAEgEQAEgFAFABQAFgBAEAFQAEAEAAAFQAAAHgEADQgEAFgFAAQgFAAgEgFg");
	this.shape_22.setTransform(554.125,357.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgMA7IggABIAAgIIALgBQAHAAABgCQACgCABgKIABgoQgBgegCgFQgBgEgJABIgKAAIAAgHIAVgEQAKgCAGgDIAEgBIACABIAAACIAAAZIAJgMQAHgJAFgEQAHgCAGAAQAHgBAEACQAAAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAABQgCALAAARIgGAAQgDgGgEgCQgDgDgGAAQgHAAgGAFQgGAFgCAIQgBAJAAAZIABAcQAAAFABABQAFACAJAAIAIAAIAAAIIgjgBg");
	this.shape_23.setTransform(545.45,359.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgsAsQgPgRAAgbQAAgRAIgNQAIgOAOgIQAOgHARAAQAaAAAQAPQAQAPAAAaQgBAdgUASQgTAQgXAAQgZAAgQgQgAgTguQgIAFgEAIQgFALAAANQAAAZAKARQALASASAAQAPAAAJgLQAJgLAAgXQAAgRgFgOQgFgNgJgHQgJgGgKAAQgKAAgHAFg");
	this.shape_24.setTransform(533.75,360.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_25.setTransform(521.625,360.075);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_26.setTransform(511.025,360.075);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AglAsQgPgPAAgbQAAgUAJgPQAFgKAQgIQAPgIANAAQAWAAAMAMQANANAAAXIAAAHIgQADIgkABIgdAAQAAAXAMAMQAMAMARAAQAJAAAIgCQAJgDAIgGIACACIgEAKQgKAGgLADQgKADgMAAQgXAAgQgQgAgUgpQgIAKAAAVIApABIARgBIAAgGQAAgLgEgKQgDgGgGgEQgHgEgJAAQgNAAgIAKg");
	this.shape_27.setTransform(499.675,360.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgVA1QgNgHgGgNQgHgNAAgRQAAgPAFgMQAFgLAKgHQAJgHAOgGQAJgEANAAQAJAAAHABQAHACAHAEQgDAQAAAQIgIAAIAAgGQAAgIgCgDQgCgEgIgDQgIgDgKAAQgPAAgJAKQgJAKAAAUQAAAZANAPQAMAOASAAQAHAAAHgBIAOgGIADADIgFAIQgIAFgJACQgIACgKAAQgRAAgMgHg");
	this.shape_28.setTransform(487.975,360.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgVA1QgNgHgGgNQgHgNAAgRQAAgPAFgMQAFgLAKgHQAJgHAOgGQAJgEANAAQAJAAAHABQAHACAHAEQgDAQAAAQIgIAAIAAgGQAAgIgCgDQgCgEgIgDQgIgDgKAAQgPAAgJAKQgJAKAAAUQAAAZANAPQAMAOASAAQAHAAAHgBIAOgGIADADIgFAIQgIAFgJACQgIACgKAAQgRAAgMgHg");
	this.shape_29.setTransform(476.875,360.075);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgvA0QgHgHgBgOQABgMAFgJQAGgJALgEQALgEAngHQAAgQgHgHQgIgKgPAAQgGAAgFACIgJAEIgHARIgHgCIAAgIIAAgJIAOgHQAJgGAHgBQAGgCAIAAQAQAAAKAHQAKAIADALQABAJABAiQgBAhACADQABAEAFAAIAKAAIAAAIIgUgBIgSABIAAgLIAAgLIgYATIgHAEIgKABQgPAAgJgIgAgYAGQgKAGABAOQgBAJAGAFQAFAGAJAAQAJAAAHgGQAIgFAIgKIAAgaIAAgGQghAHgJAGg");
	this.shape_30.setTransform(465.4,360.075);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_31.setTransform(691.575,504.325);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AglAsQgPgPAAgbQAAgUAJgPQAFgKAQgIQAPgIANAAQAWAAAMAMQANANAAAXIAAAHIgQADIgkABIgdAAQAAAXAMAMQAMAMARAAQAJAAAIgCQAJgDAIgGIACACIgEAKQgKAGgLADQgKADgMAAQgXAAgQgQgAgUgpQgIAKAAAVIApABIARgBIAAgGQAAgLgEgKQgDgGgGgEQgHgEgJAAQgNAAgIAKg");
	this.shape_32.setTransform(680.225,504.325);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_33.setTransform(668.975,504.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_34.setTransform(658.375,504.325);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AguA0QgIgHAAgOQAAgMAFgJQAGgJALgEQALgEAngHQgBgQgGgHQgIgKgPAAQgFAAgGACQgFABgEADIgHARIgGgCIAAgIIAAgJIANgHQAJgGAHgBQAGgCAIAAQAQAAALAHQAJAIADALQABAJAAAiQABAhABADQABAEAFAAIAJAAIAAAIIgTgBIgSABIAAgLIAAgLIgYATIgHAEIgKABQgPAAgIgIgAgZAGQgJAGAAAOQABAJAFAFQAFAGAIAAQAKAAAHgGQAIgFAIgKIAAgaIAAgGQghAHgKAGg");
	this.shape_35.setTransform(646.95,504.325);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAFBbIgiABIAAgIIAKAAQAHgBABgDQACgFAAgmIAAg+IAAgYIgBgQQAAgFgBgBQgCgDgGAAIgKAAIAAgHQAZgCAOgIIACACQgCAkAAAdIAAA+QAAAlACAFQABACAHABIAKABIAAAIIgZgBg");
	this.shape_36.setTransform(636.875,500.95);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgyBTQgNgLAAgQQAAgJAHgLQANgGAIgGQgKgDgCgDQgEgCAAgFQAAgFAEgFQABgCAGgEIAMgJQgPgDgGgHQgJgJAAgOQAAgMAHgLQAGgKAMgGQAQgHAPAAQAIAAAHACQAHADAHAGIALAAIAZgBIABACIgHALIgWAAQADAIgBAFQAAALgGAKQgHAKgMAGQgMAHgNAAIgGgBQgIAGgCADQgDADAAACQABAFAFACQAEADAPAAIAPAAIAVgBQALAAAFADQAFADAEAIQADAIAAAJQAAAOgJANQgHAMgQAIQgRAHgTAAQgZAAgOgLgAgcAcQgKAHgDAEQgDAGAAAKQAAANAKAJQAKAJARAAQANAAAKgFQALgFAFgJQAFgJAAgJQAAgIgDgGQgEgGgFgCQgEgBgKAAIgbAAQgJAAgDACgAgdhNQgHAIAAANQgBARAJAJQAHAJAMAAQALAAAHgIQAIgHAAgOQgBgQgHgJQgJgJgKAAQgMAAgHAHg");
	this.shape_37.setTransform(626.8,507.625);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_38.setTransform(751.525,305.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AAfA7IgSguIgOgmIgbA8IgKAYIgNAAIgWhLIgIgZQgCgEgDgCQgDgCgEAAIgGAAIAAgHIAdAAIAeAAIAAAHIgGAAQgIAAgDABQAAABgBAAQAAABAAAAQgBABAAAAQAAABAAABQAAAGAVBEIAag4IANgiIAGAAIALAdIAaA/IASgxQAGgPABgHIABgFQAAgDgDgCQgDgBgFAAIgIAAIAAgHIAdAAIAUAAIAAAHIgFAAQgEAAgFAEQgDAEgSApQgOAhgHAag");
	this.shape_39.setTransform(735.6,305.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgsAsQgPgRABgbQAAgRAHgNQAIgOAOgIQAOgHARAAQAaAAAPAPQAQAPABAaQAAAdgVASQgSAQgYAAQgZAAgQgQgAgUguQgHAFgEAIQgFALAAANQAAAZAKARQALASATAAQAOAAAJgLQAJgLAAgXQAAgRgFgOQgFgNgKgHQgIgGgKAAQgJAAgJAFg");
	this.shape_40.setTransform(718.55,305.375);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgMA6IggABIAAgHIALgBQAHAAACgCQACgCAAgKIAAgpQAAgdgCgFQgCgEgHABIgLAAIAAgIIAVgDQAJgCAIgEIACAAIACAAIABADIgBAZIAKgMQAHgJAFgEQAGgDAHAAQAGABAFABQAAAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAACQgCAJgBASIgFAAQgDgGgEgCQgEgDgFAAQgHAAgGAEQgGAFgCAKQgBAIAAAZIABAdQAAADACABQAEADAJAAIAHAAIAAAHIgigBg");
	this.shape_41.setTransform(706.7,305.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgQBaQgIgCgIgGIgKAJIgDgCQACgTAAgUIAAhNIgBglQgBgIgBgCQgCgCgFAAIgLAAIAAgGIAWgEIARgFIABgBQADAAAAAFIgBAGIgBAKIAAAsIAAAZIAPgPQAFgEAGgDQAIgDAJAAQAUAAANAOQAMANAAAWQAAAMgEAMQgFALgGAHQgDAEgNAKIgRALQgIAEgJAAQgJAAgHgDgAgJgFQgJAFgEAIQgBADAAALIAAAcQAAANABACQACAEAJAGQAJAFAJAAQARAAAKgOQAKgPAAgUQAAgVgJgKQgKgMgQAAQgJAAgJAHg");
	this.shape_42.setTransform(694.65,302.125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgwB1IgJABIAIgSIBSjIIAGgRIAMABIAHAAIgHAQIhVDLIgFAPg");
	this.shape_43.setTransform(679.525,304.625);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgoA3QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIABgGIABgTIAAgGIAHAAIAAAIQAAAKACACQADAEAJAEQAKADAJAAQAMAAAIgGQAIgHAAgKQAAgHgFgFQgEgEgOgDQgXgFgIgDQgHgDgEgGQgEgGAAgJQAAgQAMgKQALgKAVAAQARAAARAGIgCAcIgHAAQAAgLgCgDQgDgEgIgEQgHgEgHAAQgLAAgHAGQgHAGAAAIQAAAIAGAEQAFAFAXAEQARAEAGADQAFADAEAFQADAHAAAIQAAAQgOAMQgOAMgWAAQgPAAgTgFg");
	this.shape_44.setTransform(667.525,305.375);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AglAsQgPgPAAgbQAAgUAJgPQAFgKAQgIQAPgIANAAQAWAAAMAMQANANAAAXIAAAHIgQADIgkABIgdAAQAAAXAMAMQAMAMARAAQAJAAAIgCQAJgDAIgGIACACIgEAKQgKAGgLADQgKADgMAAQgXAAgQgQgAgUgpQgIAKAAAVIApABIARgBIAAgGQAAgLgEgKQgDgGgGgEQgHgEgJAAQgNAAgIAKg");
	this.shape_45.setTransform(656.175,305.375);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("Ag1BbIgHgDIAFgTIADAAQADAFAEABQADACADAAQAIAAAGgHQAGgIANghIgVg1IgLgcIgJgVQgFgLgIAAIgFAAIAAgHIAWAAIAjAAIAAAHIgJAAQgEAAgCABQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIACAIQAMAiAQAmQAQgjAMggIADgMQAAgEgIgBIgJgBIAAgHIAaAAIAVAAIAAAHIgEAAIgGABQgDABgCADQgEAHgSApIgaA8IgUAvQgFAIgIAEQgHAEgJAAIgHgBg");
	this.shape_46.setTransform(643.075,308.85);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AglAsQgPgPAAgbQAAgUAJgPQAFgKAQgIQAPgIANAAQAWAAAMAMQANANAAAXIAAAHIgQADIgkABIgdAAQAAAXAMAMQAMAMARAAQAJAAAIgCQAJgDAIgGIACACIgEAKQgKAGgLADQgKADgMAAQgXAAgQgQgAgUgpQgIAKAAAVIApABIARgBIAAgGQAAgLgEgKQgDgGgGgEQgHgEgJAAQgNAAgIAKg");
	this.shape_47.setTransform(630.275,305.375);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f().s("#000000").ss(4,1,1).p("AlrrWIA6BFQA+BKCmBkQClBlD8i2IAiAAQD8C2CnhlQCmhkA+hKIA6hFIhEg5ImxDbIj8hqIh7A6Qh6BChSg9gAl/DrIE1m5IhUgrIkjGaQAPAMAOANQAWAXAPAaQAcAyAAA/QAABehBBDQhEBDheAAQgpAAhBghIj6DxIiMgjIE2kYAsKHDQghhBAAgmQAAhfBChDQBEhDBfAAQBKAAA7AqIBCBKAsKHDIBaBcIg5giQgMgSgLgWQgFgIgFgKg");
	this.shape_48.setTransform(487.5,285.5);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f().s("#663300").ss(4,1,1).p("AB6gnQALhgBChJQBNhUBvAAQBuAABPBUQBNBVAAB4QAAB2hNBVQhPBUhuAAQhvAAhNhUQhLhRgDhvAh3AJQgCB1hMBSQhPBVhuAAQhuAAhOhVQhOhUAAh4QAAh3BOhUQBOhUBuAAQBuAABPBUQA/BFALBb");
	this.shape_49.setTransform(848.625,544.45);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f().s("#663300").ss(3,1,1).p("Ah6gYID1AAAB6AXQh6gTh2AU");
	this.shape_50.setTransform(848.55,542.95);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#666666").ss(3,1,1).p("AKIAAQAABHhNAyQhMAxhrAAQhsAAhMgxQhHgvgEg/IADgrQAAgCABgBQAJgbAVgWQAEgFAFgFQANgOATgLQBMgyBsAAQBrAABMAyQBNAyAABFgAjMB5QgWAOgYAKQg9AZhNAAQhRAAg/gdQgVgIgSgMQhMgyAAhHQAAhFBMgyQBMgyBrAAQBsAABMAyQATALAOAOQAWAVAKAXQAEAIACAKIAFArQgFA/hHAvg");
	this.shape_51.setTransform(694.125,548.15);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f().s("#FFCC33").ss(3,1,1).p("AgJBQIgBifAALhPIAACf");
	this.shape_52.setTransform(672.325,125.65);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f().s("#FFFFFF").ss(3,1,1).p("AxDpHIAFBmICTgCIAVAAIBIAAIBvgBIAAiSIgzgIQgegDg1gCIgxAAQgMAAgLAAQhrADgzAKgAQxGNQAAAEAAADQAAANgOALQgPAIgWAAQgRAAgNgFAO0EGQADAAABAAQAcgCBHArQBHAqggBBQgMAWgTAbQgMAOgSAUQgQAWgFBAQgBAfABAaQgXAFgbABQgjADgRgCQgIgBgEgDQgJgEgDAAQgCgfgGghQgRhIgOgGQgrgkgJgsQgRhZBsgsIAYgJQAQgIAVgBAM3FoQACgFAEgEQACgCADgDQAOgPAVAAQAMAAAJAFQAJADAGAHQAOAPAAAVQAAAUgOAPQgOAOgTABQgBAAgCAAQgVAAgOgPQgPgPAAgUQAAgFAAgDQAAgBABgCAPdGpQgTgFgGgQIgDgYQAEgUAFgLIABAAQAngQAjATQAPAVgDASQgDAWgVAJQgTAHgZgEgANoGwQgJACgKAAQgVAAgPgLQgJgGgEgHQgDgFAAgHQAAgPAQgKQgEgDgCgFQAGgEAGgBANyJ7QgCAAAAABQAAADAXAEQgVgEAAgEgAOKKDIgDAAAMzF2QAAgBgCAAQACgCABAAQACgGABgFAMrFtQgRgRAlAAAMkGaQgKgJAAgKQAAgPARgL");
	this.shape_53.setTransform(765.3853,182.0339);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f().s("#000000").ss(1,1,1).p("EAsKgBlQgNA0gVAuQgrBggrgKQgtgJhagdIhSgXIgVhSQgQhOAqgIQApgGCVAaQBLALBDAOgEAhyAAkQgMgzgUgwQgqhiguAJQgsAMhbAdIhRAVIgWBUQgPBNArAGQAoAGCVgXQBLgMBCgMgEgnhAANIgCAOEgreACaIgrgB");
	this.shape_54.setTransform(561.8125,435.387);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f().s("#000000").ss(3,1,1).p("EA+YgYyQgDgLgGgWQAAgDAAgBQgJgigOg6IgXh8QhZifhpgmQhWgfhdAuQg3Aag3A0QgKAKgKALIg5BpQgUAjgRAlQgPAkgKAjQgKAlgIAXQgGAXgDALQgFAWhxAjQhwAkgzgNQg0gMgXgSQgtgfgiAiQgcAfAAA0QAAAlBsC9QA2BfA1BXIBkgZQCBgcCIgPQAPgBAPgCQEfgcD6AlQA0AIAxAJQAhAFAfAIIBsAcQAzhWA2hcQBqi9AAglQAAg0gcgfQgigigrAfQgXASg0AMQg0ANhxgkQhkgfgMgWQgEgBgCgDQAAgCgBgEgEAUPgjQQgJi6AFi+QAGl7DHg9QDGg+DnAYQDoAXBaA4QA8AxANAxQAXBBAjCoQAlCkgSEMgEAejgm6IgvAQIACAbIABBBIACAAIAqALEAd0gmqIAAAbIACAAIAOAJIAWAQIAOgeIgFgmIgfA0IgLATIAAAlEAdTglZIAkALIACAXIAAgXEA5lgY1QADAAACAAEA4ngXfIAJgMAcxbxIA3AAIEKAAIBIAAIgCArIhKAAQiFgkh9AkIg7AAgAv54QIACAGQABACABADQBFC2BMBjQATAYASASQACADACACQBbBYBcgvQB3g9BxkjQACgEABgFQASgtASg0IAghiIgYgFIjVGRQgWAfg7AnIhnACQiWiZg8igIgRgkIgag6IgfhCIgdABIAOAzQAFAQAFAQQALAgAKAfIAKAbQAAAAAAABQACADABADgAv84XIADAHA81NMQAHAEAGAFQAvAkAvAWQAcAOAbAJQAFACAFABQDIA9CnjFQAaiLARiSQACgNABgOQAdkHgghNQgHgSgKgIQg3gsg3AAQgcAAgQAKIgXGFIhSnVIgWgGQgdgGgXgCQhKgFgCA0QgDA1AdDSQAPBpAPBeIium3QgDgKgVACQgVADgTAOQgKAHgHAIQgfAlAaA9QACAGADAHQAcBIAfCKQASBLALA9IgWCVIk1g5ASar5IAAOwIAAOxMA1SAAKEgSxAp2MAAAgnsMAlLAAtEg5HAL9QkjD7j5kLQgkiWgZifQgzk+A1gwQA1gwA2gCQAcgBARAIIAqGFIA7nYIAWgIQAcgIAXgDQBKgIAFA0QAFA0gTDTQgJBpgLBgICYm/QADgKAVACQAWABATANQA3AjgbBNQgbBJgbCYQgOBMgIA9IA7B3gEg2BAJpQhaoJgdj5QiPzhHmAzIB/AAQANAAAMABQCTAFCQAWQA6AJA2AKQAIACAIABQEoA3CyBPQA/AcAwAfQDTCIgjFAQgSCfgVBqQgDAPgDAOQgKAtgLAhQgJAegKAVQiVHTAEGQQABBEAFBCQADAfADAfQAAADABACQAHBDAMBAIBZIRQgTAuhoApQjPBQmkgbQiGgJiLgSQhugOh6gUIg9gLQhsgThkgRQgCgBgDAAQjKgjimgdQgEAAgDgBQhmgRhZgPQh8gUhagOIgBAAQhagOg3gHQgpgFgMAAQgGgBAAABQiCh0CIg/QAQgIAUgHQAIgDAJgCQBlgeBZgXIAHCPQgDCNgwgGA81NMIkRgFA9jKwIjwgyA8gLFIgVCHEg5HAJNIDGAcEg1iAMgIgQhgQgBgJgCgJQAAgBgBgCIgLhCEhCzARhQB+ghCUgiIA1gLIAUBFQAWBSAOBDQAoDMg3ABEg3LAPdIANBXQAOBpAGBWQAUEHg4ABEg3LAPdQAiACArAOQAVAHAOAHIARgxQgLhegNhMIjlgjEg9sAQTQEYg6CJAEASaRoIAAfG");
	this.shape_55.setTransform(491.1608,367.2151);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFF00").s().p("Ah2DnIgEgFQgSgSgTgYQhMhjhFi1IgCgFIgCgGIgDgHIgKgbIgVg/IgKggIgOgzIAdgBIAfBCIAaA6IARAkQA8CfCWCZIBmgCQA7gnAWgfIDVmQIAYAFIggBiQgSA0gSAtIgDAJQhxEih3A9QggARgfAAQg7AAg8g6g");
	this.shape_56.setTransform(420.275,222.7038);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#272727").s().p("AmbDMQhOhUAAh4QAAh3BOhUQBPhUBtAAQBvAABOBUQA+BFAMBbID2AAIDMAAIgEBBIhxAAQgsgMgtgGQh6gSh3ATQgCB1hLBSQhOBUhvAAQhtAAhPhUg");
	this.shape_57.setTransform(832.275,544.875);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#663300").s().p("AqXMpIghAAQj9C3ilhmQinhkg+hKIg6hFIFqB3QBUA9B5hBIB7g6ID8BpIGyjaIBCA4Ig4BFQg/BKimBkQg8AkhGAAQh/AAiih1gAEim5QAGl6DHg+QDGg+DnAYQDoAYBaA3QA8AxANAxQAXBBAjCoQAlClgSELIxOANQgJi7AFi+gAKBkjIAIAwIAFBlICTgBIAVAAIBIAAIBvgCIAAiSIgzgHQgegEg1gBIgxAAIgXAAQhrADgzAJg");
	this.shape_58.setTransform(591.2836,148.0789);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("EAN9AkgIABgOIANAAIABAOgEApGAabQgDgiAAgvIABg0IAPAAIABA0QAAAvgDAiQgCAggEAAQgDAAgCgggAcswZQgIgBgEgCQgJgFgDAAQgDgfgFghQgRhIgOgGQgsgkgIgsQgRhZBsgsIAYgJQAQgIAVgBIAEAAIAFAAQAcgCBHArQBHAqghBBQgMAWgSAbIgeAiQgQAWgFBAQgCAfACAaQgXAFgcABIggACIgTgBgAdc0nQgBAGADAEIAAAGQAAAGABAGQAAAEAEADQACAIAJAGQAKAGAKADQANAGAQgBQAWAAAQgIQAOgLAAgNIAAgHIAAgIQAAgPgQgKIgCAAQgCgHgLgHQgOgJgXAAQgTAAgPAJIgBAAQgRAKABANgAbN0vQgSALAAAPQAAAKALAJQAEAHAJAHQAPAKAVAAQAKAAAJgBQATgCANgOQAPgPAAgUQAAgVgPgPQgGgHgIgDQgJgFgMABQgVAAgOAOIgEACQgZAAAAAIQAAAEAGAFgEgpTgQeIAAgFIAEAFgAbH04QAAgIAZAAIgBADQgFAFgBAEQgGABgGAEQgGgFAAgEgAbg1AIAAAAgEgChgjjIgIgwQAzgKBrgDIAWAAIAwAAQA2ACAeAEIAzAHIAACSIhvABIhIAAIAAigIAACgIgVAAIgBigIABCgIiTACgEABlgiYIAAgXIAqALIgqgLIAAgkIAKgTIAWAPIAPgeIgFglIggA0IgOgKIgCAAIAAgbIAAAbIACAAIAOAKIgKATIAAAkIgCAAIgChBIACBBIgkgLIAkALgEABfgkLIACAbIgCgbIAwgPIgwAPgEgAKgiAgEABjgivIACAAIAAAXgEABjgivgEACFgjXIgWgPIAgg0IAFAlIgPAegEABvgjmg");
	this.shape_59.setTransform(672.4,351.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFCC99").s().p("ACdXVQiGgJiKgSQhugOh6gUIg9gLIjQgkQAqgBgBiQQAAgzgFhEQgGhWgOhpIgNhXIANBXQAOBpAGBWQAFBEAAAzQABCQgqABIgFgBIlxhAQAggBABhEQAAgygRhWQgOhDgWhSIgUhFQEYg6CJAEQAiACArAOQAVAHAOAHIARgxQgLhegNhMIgQhgIgDgSIgBgDIgLhCQhaoIgdj6QiPzhHmAzIB/AAIAZAAQCSAGCQAWIBwATIAQADQEoA3CyBPQA/AcAwAfQDTCIgjFAQgSCfgVBqIgGAdQgKAtgLAhQgJAegKAVQiVHTAEGQIE0A5IAXiVQgLg9gShLQgfiKgchIIgFgNQgag8AfglQAHgIAKgHQATgOAVgDQAVgCADAKICuG2QgPhegPhpQgdjRADg1QACg1BKAFQAXACAdAHIAWAGIBSHUIAXmEQAQgKAcAAQA3AAA3AsQAKAIAHARQAgBNgdEHIgDAbQgRCSgaCLQinDFjIg9IgKgDQgbgJgcgOQgvgWgvgkIgNgJIAUiHIgUCHIkSgGQAIBDAMBBIBZIRQgTAuhoApQibA8kTAAQhcAAhpgHgAMeK0IAAgEIArABIgrgBIgGg/QgFhBgBhEIDwAyIjwgyQABBEAFBBIAGA/IAAAEgAREIzIACgOgAvkUnIi/ggIjWgiIAAAAIAEAAIAAAAIAAAAQAqgBAEh5IABgMIAAgBIgHiPIAHCPIAAABIgBAMQgEB5gqABIAAAAIAAAAIgEAAIAAAAIgBAAIiRgVQgpgFgMAAQgGgBAAABQiCh0CIg/QAQgIAUgHIARgFQBlgeBZgXQB+ghCUgiIA1gLIAUBFQAWBSAOBDQARBWAAAyQgBBEggABIgGgBgAz9JbQgkiWgZifQgzk9A1gwQA1gwA2gCQAcgBARAIIAqGEIA7nYIAWgIQAcgIAXgDQBKgIAFA0QAFA1gTDSQgJBpgLBgICYm/QADgKAVACQAWABATANQA3AkgbBNQgbBIgbCYQgOBMgIA9IA7B3IAACwQiNB5iDAAQiMAAiAiJgAMeKwgArhJrIAAiwIDGAcIALBCIABADIADASIAQBggArhG7g");
	this.shape_60.setTransform(199.3877,381.8371);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("EAg3AexQhKhRgEhvQAtAGAsAMIBxAAIAEhCIjNAAQAMhgBBhJQBNhUBvAAQBuAABPBUQBOBVAAB4QAAB3hOBVQhPBUhuAAQhvAAhNhUgAIzeGQhGgugFhAIBJAAIADgrIhJAAIACgEQAIgaAWgXIAJgKQAMgNATgMQBNgxBrAAQBrAABMAxQBNAyAABGQAABHhNAyQhMAyhrAAQhrAAhNgygAitebQgVgJgSgMQhMgyABhHQgBhGBMgyQBMgxBsAAQBqAABMAxQATAMAOANQAWAWAKAWIAHATIg3AAIA3AAIAEArIgEgrIEJAAIgDArQiFgjh9AjIg7AAIAAgrIAAArIA7AAQgEBAhIAuQgWAPgYAKQg9AZhLAAQhSAAg/gdgAHocYIADgrIBJAAIgDArgADmcYgAbOL5QgtgJhagdIhSgXIgVhTQgQhOArgIQAogGCVAaQBLALBEAOQgOA0gVAuQgmBYgoAAIgIgBgANkLzQgqgGAOhOIAWhUIBSgVQBagdAsgMQAugJAqBiQAUAwAMA0QhCAMhLAMQh4ASgxAAIgUgBgEgrhgBHIE3kXIgLgSIBbBbIg6giQgMgSgKgVQAKAVAMASIA6AiIhbhbQghhBAAgnQAAhfBChDQBEhDBfAAQBKAAA7ArQAPALANANQAXAXAQAaQgQgagXgXQgNgNgPgLIEjmcIBUArIk0G6IhDhJIBDBJQAcAyAAA/QAABehDBDQhEBEhdAAQgpAAhAgiIj7DxgATvzFQhsi+AAglQAAgzAcggQAigiAsAgQAYARA0AMQAzANBwgjQBxgkAFgWIAJgiIASg7QAKgkAPgjQAQglAVgkIA5hpIAUgUQA3g0A2gbQBeguBVAfQBpAnBaCeIAXB8IAXBcIAAAFIAJAgIABAGQACADAEACQALAWBlAfQBwAjA0gNQA0gMAYgRQArggAiAiQAcAgAAAzQAAAlhqC+Qg2BcgzBVIhsgcQgfgHghgGQgxgJg0gHQj6glkfAcIgeADQiIAPiBAcIhlAZQg0hXg2hfgAeuy/QAEACAIABQARADAigDQAcgCAXgEQgCgbACgfQAFhAAQgWIAegiQASgaAMgXQAhhBhHgpQhHgrgcABIgFAAIgEAAQgVACgQAHIgYAJQhsAsARBZQAIAtAsAjQAOAGAQBJQAGAgADAfQgBAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQAAADAXAEQgVgFAAgEQADAAAJAFgAe3y7IADgBgAe3y7IAAAAgAegzCQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAQAAAEAVAFQgXgEAAgDgAeV2OQgVAAgOgPQgQgPABgVIAAgHIABgDIADgMQABgEAFgFIAFgEQAOgPAVAAQAMAAAJAEQAIADAGAIQAPAOAAAVQAAAVgPAPQgNANgTACIgDAAgAeh3jIAJgMgEAgNgWWQgUgEgGgRIgCgXQAEgVAFgKIABAAQAmgRAkAUQAPAUgDASQgDAWgVAJQgMAFgOAAQgJAAgJgCg");
	this.shape_61.setTransform(658.2,367.576);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]}).wait(1));

	// Frame
	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f().s("#000000").ss(2,1,1).p("EhJbgwbMCS3AAAMAAABg3MiS3AAAg");
	this.shape_62.setTransform(480,320);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#F0FFFF").s().p("EhJbAwcMAAAhg3MCS3AAAMAAABg3g");
	this.shape_63.setTransform(480,320);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_63},{t:this.shape_62}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(489,328.5,474.5,352);
// library properties:
lib.properties = {
	id: 'EA2F94B9C7C4D14D9FC9A7C1DE351D47',
	width: 960,
	height: 640,
	fps: 24,
	color: "#000099",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA2F94B9C7C4D14D9FC9A7C1DE351D47'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;