(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.timbs = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AERh4QgEgGgYgEQgKgBgLgBQgXgCgeAAQggAAgZACQgIABgIABQgeAFAAAHQAAAHAeAFQAGABAHABQAaADAiAAQAhAAAZgDQACAAACAAQADAEASAEQAFAAAFABQAKACAMABQACAAADABQAEAAAEAAQAUACAXAAQAtAAAhgGQAggFAAgHQAAgHgggFQghgFgtAAQgYAAgUABQgEAAgDABQgJAAgJACQgEAAgFABQggAFAAAHQAAABABACQAGgBAGgBQAegFAAgHQAAgBgCgBgAEchMQABgGAAgHQAAgCABgBQAEgPgkALQgJACgNAFIgPAAIgIAAAEchMIAHgEAERggQAfgGgKgTQANgKgZAJQABgHABgLADkgtIAOgLQABABABABQAEAFAEAEQgDAAgCACIgZAHIgIACIAHgFIAHgGIAPgIIABgBIAogWAERggIgWgBIgdgBIgIAAADgAZIAGgHIAegiIANgQAEag6QgMAEgSAJQAXAVAHgigAE9geQgOAXgegZAE9gVQAUAchEgFIglATIgIAEAFuAyIgKACQgHgagkAIQAYgKgFgOAFxA2IgNgCQgRAQgbgGIg4ANIgKACIAIgGIAogfIAAAAIgBAAIg9gNIgIgCAFEB1IgHAAAFdB3IgJAAADyBzIgOAAADwCCIgLAAAEfB1IgPAAAEYCGIgKAAAFECHIgOAAAFdCHIgJAAAEmAoQALgDAIgDACTByIgMgFACUBkIgFAAACsBrIgLAAAB1BsIgHgGAB5BdIgGAAACvB9IgMgFABjBhIgJgFABpBXIgHAAADUBuIgTAAADKB/IgLAAAkdhcQgCAAgDABQgEAAgEAAQgUACgXAAQgtAAghgGQgggFAAgHQAAgHAggFQAhgFAtAAQAYAAAUABQAEAAADABQAJAAAJACQAEAAAFABQAgAFAAAHQAAABgBACQgGgBgGgBQgegFAAgHQAAgBACgBQAEgGAYgEQAKgBALgBQAXgCAeAAQAgAAAZACQAIABAIABQAeAFAAAHQAAAHgeAFQgGABgHABQgaADgiAAQghAAgZgDQgCAAgCAAQgDAEgSAEQAJACANAFIAPAAIAIAAAjjgtIgPgIIgBgBQgEAFgEAEQADAAACACIAZAHIAIACIgHgFIgHgGIgOgLQgBABgBABIgogWQgBgGAAgHQAAgCgBgBQgEgPAkALQgFAAgFABQgKACgMABAkbhMIgHgEAkQggQgfgGAKgTQgNgKAZAJQgBgHgBgLAjfAZIgGgHIgegiIgNgQIAWgBIAdgBIAIAAAkZg6QAMAEASAJQgXAVgHgigAk8geQAOAXAegZAk8gVQgUAcBEgFIAlATIAIAEAhiBhIAJgFAiTBkIAFAAAiSByIAMgFAiuB9IAMgFAirBrIALAAAh4BdIAGAAAh0BsIAHgGAjJB/IALAAAhoBXIAHAAAklAoIABAAIA9gNIAIgCAljA0QARAQAbgGIA4ANIAKACIgIgGIgogfIAAAAQgLgDgIgDQgYgKAFgOAkeB1IAPAAAjxBzIAOAAAjvCCIALAAAltAyIAKACQAHgaAkAIAlwA2IANgCAlcB3IAJAAAlDB1IAHAAAlcCHIAJAAAlDCHIAOAAAkXCGIAKAAAjTBuIATAA");
	this.shape.setTransform(0,-0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("ADbkqQAsANAjgIQAEgBADgBQgBAQgBAOQgCAhgCAcQgvASghgSIADAdQAAASACARQACAOADAOQACAHABAHQAFARAFAQQABACAAABQACAFACAFQACAFACAGQAEAIAFAIQAEAKAFAKQALASANASQABAAAAAAQAJALAJALQATAWAXAUQiRAQh/gwIAFgiQANgxAGgwIAFgtIADgbIADgaIAMhnIAEghgACBkNIAwAFIAABjIg8gBADHhkQAAAEADADQACADAEAAQAEAAADgDQACgCAAgDQABgBAAgBQAAgEgDgDQgDgCgEAAQgEAAgCACQgDADAAAEgAF6AyIgGAAQgCgCgBgCQgCgDgBgCQgbgqgWgmQgOgagMgXIAAgMIAAgfIAAg+AErjMQgBArAAAeQAAASABAOQAAADAAADIBPCPICCAwQBBB3g1A7QgHgLgigDImQglQgPAGgBgZIAAgNIATiCADLgrQAAAEADADQADADAEAAQAEAAADgDQACgDAAgDIAAgBQAAgBAAgBQAAgCgBgBQgBgBAAgBQgDgCgEAAQgEAAgDACQgDADAAAEgADbjMIAAheAIIEUIAAAJIgBAAQiLgJhigIQgDgBgCAAQgNgBgMgBQgKgBgKgBAHtEoIAAgIAIIEUIgBAJIgBASIkOgWIgRgBIABgRAHMElIAAgFAGdEhIAAgFADWAQQAAAEADADQACADAEAAQAEAAADgDQACgCAAgDQABgBAAgBQAAgCgBgCQgBgBgBgCQgDgCgEAAQgEAAgCACQgDADAAAEgADtBFQAAAEADADQADADAEAAQAEAAADgDQACgDAAgEQAAgBAAgCQgBgCgBgCQgDgCgEAAQgEAAgDACQgDADAAAEgACGEMIAAgEACYEGIAAAOIgtgDIAAgLACYEGIAAgLQAXAGA5AGABPEPIgSgBIAAgQIACgwABPEPIABgJACYEGIhbgIABrERIgcgCAF1EeIAAgFAEyEYIAAgFAFTEcIAAgGAETEWIACgLAD4EZIAEgQAiAkNIgEghIhWAEQgwAPgmgMQAEAzACAoQAvASAhgSIgDAdQAAASgCARQgCAOgDAOQgCAHgBAHQgFARgFAQQgBACAAABQgCAFgCAFQgCAFgCAGQgEAIgFAIQgEAKgFAKQgLASgNASQgBAAAAAAQgJALgJALQgTAWgXAUQCRAQB/gwIgFgiQgNgxgGgwIgFgtIgDgbIgDgaIgMhnIgwAFIAABjIA8gBAkqjMQABArAAAeQAAASgBAOQAAADAAADIhPCPIAGAAQACgCABgCQACgDABgCQAbgqAWgmQAOgaAMgXIAAgMIAAgfIAAg+AjGhkQAAAEgDADQgCADgEAAQgEAAgDgDQgCgCAAgDQgBgBAAgBQAAgEADgDQADgCAEAAQAEAAACACQADADAAAEgAjKgrQAAAEgDADQgDADgEAAQgEAAgDgDQgCgDAAgDIAAgBQAAgBAAgBQAAgCABgBQABgBAAgBQADgCAEAAQAEAAADACQADADAAAEgAjajMIAAheAoHEUQAHgLAigDIGQglQAPAGABgZIAAgNIgTiCAjVAQQAAAEgDADQgCADgEAAQgEAAgDgDQgCgCAAgDQgBgBAAgBQAAgCABgCQABgBABgCQADgCAEAAQAEAAACACQADADAAAEgAjsBFQAAAEgDADQgDADgEAAQgEAAgDgDQgCgDAAgEQAAgBAAgCQABgCABgCQADgCAEAAQAEAAADACQADADAAAEgAj7EJQAKgBAKgBAkSEWIgCgLQANgBAMgBAoGEdQCLgJBigIQADgBACAAAj3EZIARgBIgBgRAj3EZIgEgQAlSEcIAAgGAl0EeIAAgFAkxEYIAAgFAhOEPIASgBIAAgQIgCgwAhOEPIgBgJAhqERIAAgLAiXEGIAAAOIAtgDIAcgCAiFEMIAAgEAiXEGIAAgLQgXAGg5AGAiXEGIBbgIAoHEUIAAAJIABAAIABASIEOgWAnsEoIAAgIAoHEUIABAJAmcEhIAAgFAnLElIAAgFAl5AyIiCAwQhBB3A1A7");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#996666").s().p("AD4AbIAEgRIgEARIgRgCIABgRQg5gGgXgEIAAAKIhbgIIACgvQABAZAPgGIGQAjQAiADAHAMIgBAJQiLgKhigIIgFAAIAFAAQBiAICLAKIgBARgAHtApIAAgHgAHMAmIAAgFgAGdAiIAAgEgAF1AfIAAgFgAFTAeIAAgHgAEyAZIAAgEgAETAXIACgKIgZgDIAZADgAD8AKIgUgCIAUACgAoGAfQCLgKBigIIAFAAIgFAAQhiAIiLAKIgBgJQAHgMAigDIGQgjQAPAGABgZIACAvIhbAIIAAgKQgXAEg5AGIABARIgRACIgEgRIAUgCIgUACIgZADIACAKIgCgKIAZgDIAEARIkOAVgAnsApIAAgHgAnLAmIAAgFgAmcAiIAAgEgAl0AfIAAgFgAlSAeIAAgHgAkxAZIAAgEgAIHAfIABgJIAAAJgAIHAfIAAAAgAoHAfIAAgJIABAJgAIIAWgABrASIAAgLIAAALIgcgBIABgJIgBAJIgSgCIAAgPIBbAIIAAANgACGAOIAAgEgAiXAIIBbgIIAAAPIgSACIgBgJIABAJIgcABIAAgLIAAALIgtADgAiFAOIAAgEgAhOARgACYAIg");
	this.shape_2.setTransform(0,25.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ADwBbQgDgCAAgEQAAgEADgDQADgCAEAAQAEAAADACIgIAGIAKgCIAAADQAAAEgCACQgDAEgEAAQgEAAgDgEgAj9BbQgCgCAAgEIAAgDIAKACIgIgGQADgCAEAAQAEAAADACQADADAAAEQAAAEgDACQgDAEgEAAQgEAAgDgEgAD2BUgAD+BOIACAEIgKACgAj/BSIACgEIAIAGgAj/BSgAD+BOIAAAAgAj9BOgADZAnQgDgDAAgEQAAgEADgDQACgDAEABQAEgBADADIgGAHIAGgHIACADIgIAEIAIgEIABAEIgBACQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQgDADgEAAQgEAAgCgDgADoAiIgIgCgAjlAnQgBgBAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAIgCIgIACIgBgCIABgEIAIAEIgGgHQADgDAEABQAEgBACADQADADAAAEQAAAEgDADQgCADgEAAQgEAAgDgDgAjnAcIACgDIAGAHgAjnAcgADmAZIAAAAgAjlAZgADOgUQgDgDAAgEQAAgEADgDQADgCAEgBQAEABADACIABACIABADIgIACIAHgFIgHAFIAIAAQAAAEgCADQgDACgEAAQgEAAgDgCgAjbgUQgCgDAAgEIAIAAIgIAAIAAAAIAAgCIABgDIABgCQADgCAEgBQAEABADACQADADAAAEQAAAEgDADQgDACgEAAQgEAAgDgCgAjVgbIgHgFIAHAFIgIgCIAIACgADegbgADWgbIAIgCIAAACIAAAAgADWgbgAjVgbgADegdIAAAAgADKhNQgDgDAAgEQAAgEADgDQACgDAEABQAEgBADADQADADAAAEIgBACIgIAAIAIAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBABQgDADgEAAQgEAAgCgDgAjWhNQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIgBgCQAAgEADgDQADgDAEABQAEgBACADQADADAAAEQAAAEgDADQgCADgEAAQgEAAgDgDgAjQhSIgIAAgADZhSg");
	this.shape_3.setTransform(0,-1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AB1AzIAMhmIAwAFIAABigAiwguIAwgFIAMBmIg8ABg");
	this.shape_4.setTransform(0,-21.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#996600").s().p("AHfETImQgkQgPAFgBgZIAAgNIATiCIACABIACAAIACABIAAAAQBdAiBnAAIAAAAIAAAAQAgAAAhgDIACAAIADgBQgXgTgTgXIANACIAAAAIAAAAQARAAANgKIABgCIANADIgNgDIAKgCIgKACIAAgBQgGgSgWAAIAAAAIAAAAIgNABIgBAAIAAAAIAAAAIAAAAIgBAAQAUgHAAgLIgBgFIABAFQAAALgUAHIABAAIAAAAIAAAAIAAAAIABAAIANgBIAAAAIAAAAQAWAAAGASIAAABIgBACQgNAKgRAAIAAAAIAAAAIgNgCIgSgWIAAAAIgBAAQgNgSgLgTIACAAIACAAIAOABIAAAAIAAAAQAuAAgPgXIgBgBIABABQAPAXguAAIAAAAIAAAAIgOgBIgCAAIgCAAIgJgSIANgQQAPAMALABIABAAIAAAAQALAAAGgMQgGAMgLAAIAAAAIgBAAQgLgBgPgMIgWgBIgEgKIAFgDIgIgIIAogWIgCASIABAAIAAAAIABgBIAAAAIABAAIAAAAIAHgDIAAAAIABAAIAAAAQAJgCgGAFIAAAAIgCACQACAEABAEQAAAMgYAFQAYgFAAgMQgBgEgCgEIACgCIAAAAQAGgFgJACIAAAAIgBAAIAAAAIgHADIAAAAIgBAAIAAAAIgBABIAAAAIgBAAIACgSIAHgEIgHAEIgoAWIgCgDIgKggIAWgHIABgBIABAAIAAAAIABAAIABgBIAAAAIACAAIAMgDIAFAAIAAAAQAKAAgBAIIAAABIgWgDIgKgBIAKABIAWADIgBADIgBANIABgNIABgDIAFAAIAAAMIAaAxQAWAlAbArIADAFIADAEIAGAAIgGAAIgDgEIgDgFQgbgrgWglIgagxIAAgMIAIABIgIgBIAAgeIAHgBIgHABIAAg/IAAA/IgSABQgEgFgYgEIgVgCQgCgRAAgSIgDgdIAAheQAsAOAjgJIAHgCIgCAeIgEA9QgYAJgUAAQgUAAgQgJQAQAJAUAAQAUAAAYgJIgBBJIABAgIAAAGIBPCPICCAwQBBB4g1A6QgHgLgigDgAFdCMIgJAAgAFECLIgOAAgAEYCKIgKAAgADwCGIgLAAgADKCDIgLAAgACvCBIgMgFgAFdB8IgJAAgAFEB6IgHAAgAEfB6IgPAAgADyB3IgOAAgACTB2IgMgEgADUByIgTAAgAB1BxIgHgGgACsBvIgLAAgACUBoIgFAAgABjBlIgJgEgAB5BhIgGAAgABpBbIgHAAgAEmAsIATgGIgTAGgAEMggQAJgBAEgRIABgCIAAgBIAAABIgBACQgEARgJABIgBAAIAAAAQgGgBgHgGIgCgCIAegMIgeAMIACACQAHAGAGABIAAAAIABAAgAn7BvICCgwIAGAAIADgEIADgFQAbgrAWglIAagxIAAgMIAFAAIABADIABANIgBgNIgBgDIAWgDIAKgBIgKABIgWADIAAAAQgCgJALAAIAAAAIAFAAIAMADIACAAIAAAAIABABIABAAIACABIAWAHIgKAgIgCADIABABIgEAKIgFgDIAIgIIgogWIgHgEIAHAEIACASIgBAAIAAAAIgBgBIAAAAIgBAAIAAAAIgHgDIAAAAIgBAAIAAAAQgJgCAGAFIAAAAIACACQgCAEgBAEQAAAMAYAFQgYgFAAgMQABgEACgEIgCgCIAAAAQgGgFAJACIAAAAIABAAIAAAAIAHADIAAAAIABAAIAAAAIABABIAAAAIABAAIgCgSIAoAWIgIAIIAFADIgEAKIgWABQgPANgMAAIAAAAIAAAAQgLAAgGgMQAGAMALAAIAAAAIAAAAQAMAAAPgNIANAQIgJASIgCAAIgCAAIgOABIAAAAIAAAAQgvAAARgYQgRAYAvAAIAAAAIAAAAIAOgBIACAAIACAAQgLATgNASIgBAAIAAAAIgSAWIgNACIAAAAIAAAAQgSAAgMgLIgBgBIAAAAQAFgTAXAAIAAAAIAAAAIANABIAAAAIABAAIABAAQgUgHAAgLIABgFIgBAFQAAALAUAHIgBAAIgBAAIAAAAIgNgBIAAAAIAAAAQgXAAgFATIAAAAIgKgCIAKACIgNADIANgDIABABQAMALASAAIAAAAIAAAAIANgCQgTAXgXATIADABIACAAQAhADAgAAIAAAAIAAAAQBqAABggkQhgAkhqAAIAAAAIAAAAQggAAghgDIgCAAIgDgBQAXgTATgXIA4AOIg4gOIASgWIAoAfIgogfIABAAIA9gMIg9AMQANgSALgTIAlATIglgTIAJgSIAeAiIgegiIAJgRIAdgBIgdABIAEgKIAZAGIgZgGIAEgKIAPAIIAHAFIgHgFIgOgMIAKggIAPAAQAAAAAAABQAAAAAAABQABAAAAABQAAABABAAQADADAEAAQAEAAACgDQADgDAAgEQAAgDgDgDQgCgDgEAAQgEAAgDADQgDADAAADIABADIgPAAIADgPQAZADAhgBQAiAAAagCQgaACgiAAQghABgZgDIAFgcQAXgCAeAAQAgAAAZACQgZgCggAAQgeAAgXACQACgRAAgSIADgdIAAheIAABeQgRAJgUAAQgUAAgXgJIgGhbQAmAMAwgPIBWgDIAEAhIgwAEIAABjIA8gBIADAaIADAcIAFAsQAGAxANAwIAFAiIATCCIAAANQgBAZgPgFImQAkQgiADgHALQg1g6BBh4gAlTCMIgJAAgAk1CLIgOAAgAkNCKIgKAAgAjkCGIgLAAgAi+CDIgLAAgAiuCBIAMgFgAlTB8IgJAAgAkPB6IgPAAgAk8B6IgHAAgAjjB3IgOAAgAiSB2IAMgEgAjAByIgTAAgAh0BxIAHgGgAigBvIgLAAgAiOBoIgFAAgAhiBlIAJgEgAhyBhIgGAAgAj9BLIgCAFIAAACQAAAFACACQADADAEAAQAEAAADgDQADgCAAgFQAAgDgDgEQgDgCgEAAQgEAAgDACgAhhBbIgHAAgAklAsQgLgCgIgEQAIAEALACgAjlAXIgCADIgBADIABADQAAAAAAABQAAAAAAABQAAAAABABQAAABABAAQADADAEAAQAEAAACgDQADgDAAgEQAAgDgDgDQgCgDgEAAQgEAAgDADgAjbgkIgBABIgBADIAAADIAAAAQAAADACADQADADAEAAQAEAAADgDQADgCAAgEQAAgFgDgCQgDgDgEAAQgEAAgDADgAkKggQAGgBAHgGIACgCIgegMIAeAMIgCACQgHAGgGABIAAAAIAAAAQgKgBgFgUQAFAUAKABIAAAAIAAAAgAEcBwQhnAAhdgiIAAAAIgCgBIgCAAIgCgBIAFgiQANgwAGgxIAFgsIADgcIADgaIA8ABIAAhjIgwgEIAEghIBWADIAABeIADAdQAAASACARQgXgCgeAAQggAAgZACQAZgCAgAAQAeAAAXACIAFAcQgZADghgBQgiAAgagCQAaACAiAAQAhABAZgDIADAPIgPAAIABgDQAAgDgDgDQgDgDgEAAQgEAAgCADQgDADAAADQAAAEADADQACADAEAAQAEAAADgDQABAAAAgBQABgBAAAAQAAgBAAAAQAAgBAAAAIAPAAIAKAgIgOAMIAPgIIAEAKIgZAGIAZgGIAEAKIgdgBIAdABIAJARIgeAiIAegiIAJASIglATIAlgTQALATANASIg9gMIABgDIgBgDIgCgDQgDgDgEAAQgEAAgCADQgDADAAADQAAAEADADQACADAEAAQAEAAADgDQABAAAAgBQAAgBABAAQAAgBAAAAQAAgBAAAAIA9AMIABAAIgoAfIAogfIASAWIg4AOIA4gOQATAXAXATIgDABIgCAAQghADggAAIAAAAIAAAAgADwBLQgDAEAAADQAAAFADACQADADAEAAQAEAAADgDQACgCAAgFIAAgCIgCgFQgDgCgEAAQgEAAgDACgADOgkQgDACAAAFQAAAEADACQADADAEAAQAEAAADgDQACgDAAgDIAAAAIAAgDIgBgDIAHgFIgHAFIgBgBQgDgDgEAAQgEAAgDADgAE4BCIAAAAgAl5A/IBPiPIAAgGIAIgBIAAAMIgaAxQgWAlgbArIgDAFIgDAEgAljA4gAEmAsIAAAAgAEmAsIgBAAIABAAIAAAAIAAAAgAklAsgAklAsIABAAIgBAAgAElAsgADoAggAENAHIAAAAgAEEgLIAAAAgAEEgLIgJgRIAWABIgNAQIAAAAgAkDgLgAkQgbIAWgBIgJARgAD7gcgAD3gmIgEgKIABgBIAIAIIgFADIAAAAgAj2gmIAAAAgADyg0IABAEIgPAIgAjygwIABgEIAOAMgADzgwIAAAAgADzgwIgBgEIACADIgBABIAAAAgAjygwgAjzgxIACgDIgBAEgADyg0IAAAAgADohUIgDgPIAEAAIgEAAIgFgcIAVACQAYAEAEAFIgJABQggAGAAAHIABADIAMgCQAegFAAgHQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBQABABAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAAHgeAFIgMACIgBgDQAAgHAggGIAJgBIASgBIAAAeIgFAAIAAgBQABgIgKAAIAAAAIgFAAIgMADIgCAAIAAAAIgBABIgBAAIAAAAIgBAAIgBABQgSgFgDgDQADADASAFIgWAHIAAAAgADZhUgAjnhUgAjnhUIgWgHQASgFADgDQgDADgSAFIgCgBIgBAAIgBgBIAAAAIgCAAIgMgDIgFAAIAAAAQgLAAACAJIAAAAIgFAAIAAgeIASABIgSgBIAAg/IAAA/IgHgBIAHABIAAAeIgIABIABggIgBhJQAXAJAUAAQAUAAARgJIgDAdQAAASgCARIgVACQgYAEgEAFQgBABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAAHAeAFIAMACIABgDQAAgHgggGIgJgBQAEgFAYgEIAVgCIgFAcIgEAAIAEAAIgDAPgAEjhXIAAAAgAD+hbIAAAAgAj9hbIAAAAgADlhjIAAAAgAj0hlQgegFAAgHQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIAJABQAgAGAAAHIgBADIgMgCgADgh/IAAAAgAjfh/IAAAAgAkqi/IAAAAg");
	this.shape_5.setTransform(0,-1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,-31.2,110.8,62.6);


(lib.sneakers = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("ACrjTIgMgKIAEgXAB9jpIAAgVACMidIAAgMACrijIgRgbIgPgYACrijIAFgbACfjdIgbgXACVilIAFgZIAFgfACJjEIgGgPADLhUIgIgIIgLgNIAFgUAC4hpIgVgVIgOgPACehiIAFgcIAIglACXhvIgIgYAC+gdIALgXACZg9IAAgOACggZIAAgJAC+gdIgagZACuhHIAKgiAC7iJIgQgaAH9BkQgNgOgNgKQgQgLgXgJQgqgMguAhQgTAkAOA7ICnAQQAIgngRgxgAHhDnQAAAEADAAIAGgEQABgCABgBAH0DlQgCgBgDAAQgBAAgCAAQgFgBgGAAQAAADAAABAAWDkIAAggIHwAYQgNAWgeAHQgFAAgFABIgngBIiFgFQgbgBgbgCQhtgHhsgGgAHqDnIgJAAAHRD/QgEgBgTgEIgJAEAEhAKIgNAFIgYAIIgogRAD8AXIgiAMADoAvIgRAAAEwA6IgOAAAEFA0IgKAAAC5AnIgLAAACqAXIAAgOIAUgmADQAqIgMAAADNgQIgPgNAh8jpIAAgVAiqjTIAMgKIgEgXAiqijIARgbIAPgYAiqijIgFgbAiLidIAAgMAiIjEIAGgPAiUilIgFgZIgFgfIAbgXAiWhvIAIgYAi3hpIAVgVIAOgPAidhiIgFgcIgIglAjKhUIAIgIIALgNIgFgUAiYg9IAAgOAifgZIAAgJAi9gdIgLgXAi9gdIAagZAithHIgKgiAi6iJIAQgaAipAXIAAgOIgUgmAi4AnIALAAAj7AXIAiAMAj7AXIAogRAkgAKIANAFIAYAIAkvA6IAOAAAjnAvIARAAAkEA0IAKAAAn8BkQANgOANgKQAQgLAXgJQAqgMAuAhQATAkgOA7IinAQQgIgnARgxgAgVDkIAAggInwAYQANAWAeAHQAFAAAFABIAngBICFgFQAbgBAbgCQBtgHBsgGgAjPAqIAMAAAnQD/QAEgBATgEIAJAEAnzDlQACgBADAAQABAAACAAQAFgBAGAAQAAADAAABQAAAEgDAAIgGgEQgBgCgBgBAnpDnIAJAAAjMgQIAPgN");
	this.shape.setTransform(0,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AG8BQQg8gZhtgQQgegGghgEQgDAAgDAAQgBgMgBgLQgBgQgDgSQgCgVgEgUQgCgQgDgQQgBgGgBgGQgFgagGgbQgDgLgCgKQgEgRgEgQQgHgbgHgaQgsAihUgiIAADfIAAAMQABAeAKAUQAKAYAPAAQAPAAALgYQAKgWAAgiQAAgigKgYQgLgXgPAAQgPAAgKAXQgKAWgBAeAHaEQQAUgFAXgYQACgDACgFAIJCtQgDgTgFgYQgJgQgVgOAIJDjQAGgOgGgcAHRESQgEAAgFAAIgPAAIgPgBAEpD7Ij8gQAAVgmIAAEBAm7BQQA8gZBsgQQAegGAigEQACAAADAAQABgMABgLQACgQACgSQADgVADgUQADgQADgQQABgGABgGQAFgaAGgbQACgLADgKQADgRAFgQQAGgbAIgaQArAiBUgiIAADfIAAAMQgBAegJAUQgLAYgPAAQgPAAgKgYQgLgWAAgiQAAgiALgYQAKgXAPAAQAPAAALAXQAJAWABAeAkpD7ID9gQAnaEQQgTgFgYgYQgCgDgBgFQgJgeARhLQAJgQAVgOAnQESQAEAAAEAAIAPAAIAQgBAgVgmIAAEB");
	this.shape_1.setTransform(0,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AFfCZQgPg7AUgkQAtghArAMQAXAJAQALQANAKAMAOQASAxgIAngAn8BRQANgOANgKQAQgLAXgJQArgMAtAhQAUAkgPA7IinAQQgIgnARgxgAAggdQgKgWAAgdIAAgMQAAgfAKgWQAKgXAQAAQAOAAALAXQALAYAAAiQAAAigLAYQgLAYgOAAQgQAAgKgYgAhSgdQgLgYAAgiQAAgiALgYQALgXAOAAQAQAAAKAXQAJAWABAfIAAAMQgBAdgJAWQgKAYgQAAQgOAAgLgYg");
	this.shape_2.setTransform(0,4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AG5ESIgPgBIAnABIgJAAgAnQESIAngBIgQABIgPAAIgIAAgAGqERIiFgFIg2gDIjagNIAAghIAAkBQABAeAKAUQAKAYAPAAQAPAAALgYQAKgWAAgiQAAgigKgYQgLgXgPAAQgPAAgKAXQgKAWgBAeIAAjfQBUAiAsgiIAOA1IAIAhIAFAVIALA1IACAMIAFAgIAGApIAEAiIACAXIAGAAQAhAEAeAGQBtAQA8AZQgrgMgtAgQgUAkAPA8ICnAPQAIgmgSgxQgMgPgNgJQAVAOAJAQQAFAYADATIAAAMQAGAcgGAOIAAAIIgEAIInwgYIHwAYQgXAYgUAFIgJACgAHjECIAHgDIACgDIADAAIAFAAIgFAAIgDAAIgLgBIgBAEQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAgAEpD7Ij8gQgAEvBRIgNAAgAEEBLIgKAAgADoBGIgRAAgADQBCIgNAAgAC4A/IgKAAgADZA6IAjgMgAD8AuIAXgHIgXAHIgogRgACqAgIAAAOIAAgOIATgmIALgWIgLAWIgagZIAaAZgADMAGIgPgMgACggCIAAgIgACZglIAAgPgACugwIAJghIgUgVIAHglIgHAlIgPgQIAPAQIgFAbIAFgbIAUAVgAC3hRIALAMIgLgMIAGgUIgGAUgACWhXIgIgZgACqiLIARAaIgRgaIAGgbIgGAbIgRgbIAGgfIgbgXIAbAXIgGAfIgPgYIAPAYIgEAZIAEgZIARAbgACMiGIAAgMgACJisIgHgPgACfjFIAMAKIgMgKIAEgXIgEAXgAB9jSIAAgVgAnaEQQgTgFgYgYIHwgYIAAAhIjZANIg2ADIiFAFIgnABIgKgCgAnjECQABAAABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIAAgEIgLABIgDAAIgFAAIAFAAIADAAIACADgAkpD7ID9gQgAmpERgAIFDzQgNAWgeAHQAUgFAXgYgAoFDzQAYAYATAFQgegHgNgWgAHgD/IAKAAIgHADQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBgAnpD/IAJAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAgAHqD/gAHgD/IABgEIALABIgCADgAnpD/IgCgDIALgBIAAAEgAnpD/gAHsD8IAAAAgAnrD8IAAAAgAIFDzgAoFDzIAAAAgAoIDrQgJgeARhLQAJgQAVgOQgNAJgNAPQgRAxAIAmICngPQAOg8gTgkQgugggqAMQA8gZBsgQQAegGAigEIAFAAIACgXIAEgiIAGgpIAGggIACgMIALg1IAFgVIAIghIAOg1QArAiBUgiIAADfQgBgegJgWQgLgXgPAAQgPAAgKAXQgLAYAAAiQAAAiALAWQAKAYAPAAQAPAAALgYQAJgUABgeIAAEBInwAYIgDgIgAkhBRIgOAAgAj6BLIgKAAgAjWBGIgRAAgAjDBCIgMAAgAitA/IgLAAgAj7AuIAiAMIgigMIAogRIgoARIgYgHgAipAuIAAgOIgUgmIAagZIgaAZIgLgWIALAWIAUAmgAjMAGIAPgMgAifgCIAAgIgAiYglIAAgPgAitgwIgKghgAjChFIALgMIgFgUIAFAUgAidhLIgFgbgAi3hRIAVgVIAOgQIgOAQIgIglIARgbIAFAZIgFgZIAPgYIgPAYIgFgfIAbgXIgbAXIAFAfIgRAbIgFgbIAFAbIgQAaIAQgaIAIAlgAiWhXIAIgZgAiLiGIAAgMgAiIisIAGgPgAiqi7IAMgKIgEgXIAEAXgAh8jSIAAgVgAgVDbgACZimgAiZimg");
	this.shape_3.setTransform(0,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.4,-28.6,106.8,57.3);


(lib.redmouth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AjQAHQg8hUAaguQAxgbA4gNQBqgaCDAaQA/AMBGAYQArAuhEBYQA5A3gHA5QgJAEgIAEQgCAAgBABQjtBlkDhrQgBg5Azg6IGgAA");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AkCB6QgBg5Azg6IGgAAImgAAQg8hUAaguQAxgbA4gNQBqgaCDAaQA/AMBGAYQArAuhEBYQA5A3gHA5IgRAIIgDABQhzAxh5AAQh/AAiFg3g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.9,-18.7,53.8,37.5);


(lib.rednose = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ABzAAQAAAHgBAHQAAAIgCAHQgGAjgXAbQgBACgBABQgKALgLAIQgIAGgKAFQgTAIgXAAQghAAgagTQgLgIgKgLQghgmgBg1QAAgBAAgCQAAg2AignQAhgmAvAAQAwAAAhAmQAeAiADAvQABAHAAAFg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("Ag6BxQgMgIgKgLQgggmgBg1IAAgDQAAg2AhgnQAhgmAvAAQAwAAAhAmQAdAiAEAvIAAAMIAAAOIgCAPQgGAjgXAbIgCADQgKALgLAIQgJAGgJAFQgTAIgXAAQggAAgagTg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.4,-14.2,24.9,28.5);


(lib.nose = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ah5hCQBDiqBBAUQAcAJAbArQAmA7AkB3QBWDYiTgnQgyA4g9g4QggAMgZADQhCAHgNg2QgQhDA/ieg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AgfC/QghAMgZADQhCAHgMg2QgRhDA/ieQBDiqBBAUQAcAJAcArQAlA7AkB3QBWDYiTgnQgZAcgcAAQgbAAgegcg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.1,-22.8,36.3,45.8);


(lib.mouth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AEJAGIAABFQhBAZhIAKQhlAPh0gPQhUgKhbgZIAAhEgAkIAHIAAh8QEIBJEJhJIAAB7");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhZBuQhTgKhcgZIAAhEIAAh8QEIBJEJhJIAAB7IoRABIIRgBIAABFQhBAZhIAKQgzAIg2AAQg2AAg6gIg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.4,-12.7,54.9,25.5);


(lib.moustache = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4.1,1,1).p("Ai+hQIBWAAIBlAAIBGAAIBfAAIAxAAIAcAAIBlChIhxAAIhCAAIhqAAIhFAAIhxAAIhuAAIhmAAICLiVg");
	this.shape.setTransform(0,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#666666").ss(2.1,1,1).p("ADahdIACAPIAPChIAAAJABNhaIgBAMIgMChIAAAKACshaIgCAMIAAChIAAALAh3BdIAAgKIAXihIACgNAgGBeIAAgLIALihIABgLAjqBeIAGgLIAkiVIAFgV");
	this.shape_1.setTransform(-0.8,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ADjBRIhCAAIhqAAIhFAAIALihIgLChIhxAAIAXihIgXChIhuAAIAliVIglCVIhmAAICLiVIAKgMIBWAAIBlAAIBGAAIgMChIAMihIBfAAIgBChIABihIAxAAIAQChIgQihIAcAAIBlChgABDhQg");
	this.shape_2.setTransform(0,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.9,-10.4,72,20.8);


(lib.hat = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(5,1,1).p("AkYgEIIxAJ");
	this.shape.setTransform(0.8,12);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(3.4,1,1).p("AEhgLQAkgMBjAKQBjAJAAAGQAAAHiZAFQiZAFjZAAQjYAAiZgFQgLgBgKAAQiEgFAAgGQAAgGCEgEQAKgBALAAQAugCAzgB");
	this.shape_1.setTransform(0,30.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(5,1,1).p("AkYk/IIxAAIAAHEIAACrIAAAQIoxAAIAAgQIAAi1g");
	this.shape_2.setTransform(0.8,-0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AlxFCIgVAAQiEgFAAgHQAAgGCEgEIAVgBIBhgDIAAi1IAAm6IIxAAIAAHEIoxgKIIxAKIAACrIAAAQIoxAAIAAgQIAAAQIIxAAIAAgQQAjgLBkAJQBjAJAAAHQAAAIiZAEQiaAGjYAAQjXAAiagGgAEhB9g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.9,-35.2,107.9,69.7);


(lib.glasses = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AFdAKQAAAbgTATQgTAUgbAAQgbAAgUgUQgTgTAAgbQAAgaATgTQAUgTAbAAQAbAAATATQATATAAAagAFXgBQAAALgNAIQgNAIgSAAQgSAAgNgIQgMgIAAgLQAAgLAMgIQANgIASAAQASAAANAIQAHAEADAGQACAFABAEgABnAAIAAigIFcAAIAAFBIlcAAgAjegKQACAFABAEQABAFAAAGQAAAbgUATQgTAUgbAAQgbAAgTgUQgTgTAAgbQAAgaATgTQATgTAbAAQAbAAATATQAMALAEAOgAjbgBQAAALgNAIQgNAIgSAAQgSAAgNgIQgMgIAAgLQAAgLAMgIQANgIASAAQASAAANAIQAHAEADAGAhmAAIAAChIlcAAIAAlBIFcAAIAACgIDNAA");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABnChIAAihIAAigIFcAAIAAFBgADtgjQgTATAAAaQAAAbATATQAUAUAbAAQAbAAATgUQATgTAAgbQAAgagTgTQgTgTgbAAQgbAAgUATgAnCChIAAlBIFcAAIAACgIAAChgAlKgjQgTATAAAaQAAAbATATQATAUAbAAQAbAAATgUQAUgTAAgbIgBgLIgDgJQgEgOgMgLQgTgTgbAAQgbAAgTATgAEMASQgMgIAAgLQAAgLAMgIQANgIASAAQASAAANAIQAHAEADAGIADAJQAAALgNAIQgNAIgSAAQgSAAgNgIgAkmASQgMgIAAgLQAAgLAMgIQANgIASAAQASAAANAIQAHAEADAGIADAJQAAALgNAIQgNAIgSAAQgSAAgNgIgAjbgBIAAAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ADuAuQgTgTAAgbQAAgaATgUQATgSAbAAQAbAAATASQAUAUAAAaQAAAbgUATQgTATgbAAQgbAAgTgTgAENgeQgNAHAAAMQAAALANAHQANAJASAAQASAAAMgJQANgHAAgLIgCgJQgDgGgIgEQgMgJgSABQgSgBgNAJgAlKAuQgTgTAAgbQAAgaATgUQAUgSAbAAQAbAAATASQALAMAFAOQgDgGgIgEQgMgJgSABQgSgBgNAJQgNAHAAAMQAAALANAHQANAJASAAQASAAAMgJQANgHAAgLIABALQAAAbgTATQgTATgbAAQgbAAgUgTg");
	this.shape_2.setTransform(0,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46,-17.1,92.2,34.3);


(lib.gauntlet = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#6600CC").ss(7,1,1).p("ALYGiIjrtpArXHIIDqto");
	this.shape.setTransform(-13,-31.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AMxgyQgDgKAGgJQAFgKALgDQALgDAJAGQAKAFACAKQADALgFAKQgGAJgKADQgLADgJgFQgKgGgDgLgAMaBgQAoBRBRA2QALAFAJAEQAzARgKg0IiPjNIBLBCQAPANAMAIQAgATAPgTQAfgbg9hDQgJgJgIgJQhChHg0gxQg6g3gegzQgWgrgSg2IhbAYIhbAXIgIBwIgGBkQglAtACBMQBEB4ArhqQABgBABAAIgOgyIAMAzQAGBwA1CCQACAFACAFQAGAOAHAPQBEA2AQhRIg0jCQAdBhA/BVQADAFAEAFQAFAGAFAGQAUAYAfgHQAcgLADgSQAAgDAAgCIhKjFIgahEAHhATQgCgJAFgIQAFgIAJgDQAJgCAJAFQAIAFADAIQACAJgFAJQgFAIgJADQgJACgJgEQgIgGgDgJgAJMAfQgDgKAFgKQAGgIAKgDQAKgCAJAEQAKAGADAKQACAKgFAJQgFAJgLADQgKADgJgGQgJgFgDgKgAKgAUQgCgKAGgKQAFgJAKgDQALgDAKAGQAKAGADAJQADALgGAKQgGAJgLADQgKADgKgFQgKgGgDgLgAL2gMQgDgKAGgKQAFgJAKgDQAKgCAJAFQAKAFACAKQADAKgGAKQgFAIgKACQgKADgJgFQgKgEgCgKgALZj7IjmA+AKVAvIAQA7Ar9gaIgXhfAt6gEIgyAIQgkg2gOhDQgQhGCVhkIAvAWQDNBpgjB2QgfAxgyhjQAIAogUAJQAUgRgmAfIgOADIg4AKIgYhRAs1gQIhFAMIgUhJ");
	this.shape_1.setTransform(0,42.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AgMAWQgJgFgDgKQgCgJAFgKQAFgJAKgDQAKgCAJAFQAJAFADAKQACAJgFAKQgFAJgLACIgGABQgGAAgGgDg");
	this.shape_2.setTransform(78.3,40.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000FF").s().p("AgMAYQgKgGgDgLQgDgJAGgKQAFgKALgDQAKgDAKAGQAKAGACAKQADAKgGAKQgFAJgLADIgHABQgGAAgGgDg");
	this.shape_3.setTransform(69.9,43.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#660099").s().p("AgMAWQgJgGgDgKQgDgJAFgJQAGgJAKgDQAJgCAJAFQAKAFADAKQACAJgFAKQgFAJgLACIgGABQgGAAgGgDg");
	this.shape_4.setTransform(61.3,45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00FF00").s().p("AgLAVQgIgGgDgJQgCgIAFgIQAFgJAJgDQAIgCAJAFQAIAFADAJQACAIgFAJQgFAIgJADIgGABQgFAAgGgDg");
	this.shape_5.setTransform(50.4,43.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF9933").s().p("AgMAXQgKgFgDgLQgCgKAGgJQAFgKALgDQAJgDAKAGQAJAFADALQADAKgGAJQgFAKgLADIgHABQgGAAgGgEg");
	this.shape_6.setTransform(84.3,36.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFF00").s().p("AhPFHIgNgdIgEgKQg1iCgGhwIACgBIgOgyIAMAzIgMgzIAOAyIgCABQgrBqhEh4QgChMAlgtIAGhkIAIhwIBbgXIBbgYQASA2AVArQAeAzA6A3QA0AxBCBHIARASQA9BDgfAbQgPATgggTQgMgIgPgNIhLhCICPDNQAKA0gzgRIgUgJQhRg2gohRIBKDFIAAAFQgDASgcALQgfAHgUgYIgKgMIgHgKQg+hVgdhhIgQg7IAQA7IAzDCQgJAxgcAAQgTAAgbgWgABFBgIgahEgAh2AAQgKADgGAIQgFAKADAKQADAKAJAFQAJAGAKgDQALgDAFgJQAFgJgCgKQgDgKgKgGQgGgCgGAAIgHAAgAghgMQgKADgFAJQgGAKACAKQADALAKAGQAKAFAKgDQALgDAGgJQAFgKgDgLQgCgJgKgGQgGgEgIAAIgHABgAjigJQgJADgFAIQgFAIACAJQADAJAIAGQAJAEAJgCQAJgDAFgIQAFgJgCgJQgDgIgIgFQgGgEgGAAIgGABgAAzgsQgKADgFAJQgGAKADAKQACAKAKAEQAJAFAKgDQAKgCAFgIQAGgKgDgKQgCgKgKgFQgGgEgGAAIgHABgABvhSQgLADgFAKQgGAJADAKQADALAKAGQAJAFALgDQAKgDAGgJQAFgKgDgLQgCgKgKgFQgGgEgHAAIgHABgAjhi9IDlg+g");
	this.shape_7.setTransform(72.5,42.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#9900FF").s().p("AiwAYQgPhFCVhkIAuAWQDNBpgkB1QgeAygzhkQAJAogUAJQATgRgmAfIgNADIgXhfIAXBfIg3AKIgYhRIAYBRIhFAMIgVhJIAVBJIgyAJQgkg3gPhDg");
	this.shape_8.setTransform(-81.4,28.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100.2,-80.9,200.5,159.3);


(lib.eyebrows = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(9,1,1).p("AGJA0QgFgHgFgHQgCgDgBgCQgdglgfgYQhlhNh9BNAmIBDQAEgGAFgGQAFgIAFgHQABgBABgBQABgBABgBQAhgoAkgWQBUgzBlAzQAMAGAMAI");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.8,-11.2,87.6,22.5);


(lib.ears = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("AGaAJQAABkAoA6QAoA7A9AAQA+AAAug7QAvg6AAhkQAAhjgrhHQgrhGg+AAQg9AAgsBGQgrBHAABjgAmZAQQAAAdgDAaQgFAggJAbQgJAYgOAUQgTAcgZAPQgaAPgfAAQggAAgbgPQgbgPgWgcQgvg6AAhkQAAhkArhGQArhHA+AAQA9AAAsBHQAQAaAKAdQAJAdAFAgQADAaAAAcg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(4,1,1).p("AICA5QgyA2AOAUQAOATAvgBQABAAAAAAIABAAQAxgCAhgtQAigsAAg9QAAg/gigsQgegpgqgDQgFAAgEAAQgvAAAiBPQAjBOgyA2gAoBBAQAyA2gOAUQgOATgvgCQgBAAAAAAIgBAAQgxgCghgsQgigsAAg/QAAg9AigtQAegoAqgDQAFgBAEAAQAvAAgiBPQgjBPAyA2g");
	this.shape_1.setTransform(0,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC00FF").s().p("AoaCbIgBAAIgBAAQgxgCghgsQgigsAAg/QAAg9AigtQAegoAqgDIAJgBQAvAAgiBPQgjBPAyA2QAyA2gOAUQgNARgpAAIgHAAgAHeCDQgOgUAyg2QAyg2gjhOQgihPAvAAIAJAAQAqADAeApQAiAsAAA/QAAA9giAsQghAtgxACIgBAAIgBAAIgHAAQgpAAgNgSg");
	this.shape_2.setTransform(0,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF00FF").s().p("AphDZQgbgPgWgcQgvg7AAhkQAAhiArhHQArhGA+gBQA9ABAsBGQAQAaAKAdQAJAdAFAgQADAaAAAbQAAAegDAaQgFAggJAbQgJAYgOAUQgTAcgZAPQgaAPgfAAQggAAgbgPgAomiLQgqADgeApQgiAsAAA+QAAA+AiAsQAhAtAxACIABAAIABAAQAvABAOgTQAOgUgyg2Qgyg2AjhOQAihPgvAAIgJAAgAHCCnQgog6AAhkQAAhjArhGQAshHA9AAQA+AAArBHQArBGAABjQAABkgvA6QguA7g+AAQg9AAgog7gAIRhDQAjBOgyA3QgyA2AOATQAOAUAvgCIABAAIABAAQAxgCAhgsQAigsAAg/QAAg9gigtQgegpgqgDIgJAAQgvAAAiBPg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.1,-24.7,144.3,49.4);


(lib.Cigar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("AADABIgDACQABgCgBgDQgFABgCAFQAFABACgCAAAgCIgKACAADABIAIgBIgCgDQgCgCgEADg");
	this.shape.setTransform(22.3,23.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#666666").ss(1,1,1).p("AgbDYQgjg6BHhCQAXgUAMgVQAcgzgcg8QgBgDgCgDAgtBBQgjg7BHhAQBMhEgrhZ");
	this.shape_1.setTransform(29.2,-2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("AEkC+IgRAJIgGgKIhpi2Ig4hhIARgJIA6BkIBrC5ACpgmQAAgPABgFQADADgEgHIAAAEgACNgVIgSABIhMADIlShJIAAhsIHMAAIAACIACpgfIAAgHAkOh2IEoAA");
	this.shape_2.setTransform(-5.7,4.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(1,1,1).p("AARgmQgBgEAAgDQAAgBgBgBQAAgBgBAAIgCAAIgBABQgBACgEAFQABgDABgEQAAgCAAgDIgCAFIgFAIIAAgBQgFAEgCAEQgBABAAABQgCADgBACQgEgFgBgDQgBgBAAgCQgBgDAAgBQAAgCACgCQgBAEAAAEQgBADAAAFQgBAEAAAGQAAAAABABQgBgBAAAAQgBgBgBgBQgBgCgBAAQAAAAgBABQgBABgCAAQgEgBgBgDQgBgDADgCQADgDADAAIAAAAQACAAABACQACAAABACQABABABADQABACAAADQABACAAADQAAABAAACQgBALAAAKQAEgKADgEQAAADABACQAAABAAABQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAgJABgHQAAgBAAAAQgCgDgBgDIgFAIIgKAPIgHAMAAdhAQgBAIAAAIQAAAAAAABQgBADgBACQgBADgBAEQgBAFgBAGAAcgqQAAgDAAgCAAcgmQAAgCAAgDQAAAAAAABQgBAAgBAAQgFACgEACQgGACgFAEQgBgCgBgBQAAgBgBgBIgDAIIAAAEIAAACIgBADIAAABQAAABAAACIgBACQgBgCAAgDQABgCABgDQABAAAAgBQACgGACgEQABgDABgCQgCACgBABQgBgBgBgBIgGAMQgBgCAAgDQgDgIgDgHIAAAAQgBgCgCgDQAAADAAACQAAACAAABQABgBACgCIAAAAQAEgCAGgBAAhg0QABADAAACQAAAEAAAFQAAAAAAABQgBACgCABQAAABgBAAQgBABgBACQgBAAgBABQAAABgBAAQgCABgBADQACgGADgDQAAgBABgBQAAgCAAgBQABgEACgDQgBACABAGQAAACAAAAQAAABAAAAAgDgTQgBABAAABIgBABQAAADACAHQAAADABADQAAAAAAAAQAEgGAAgVQACARgGARIAAgHAAJgIIAAgBQACgNgFgKQgEAEgCAFQgCACgBACQgBgEgBgEIgDAFQgCgBAAgCQgCADgCADQgCAEgDAEQgBAAAAABIAAgKIAAgDQABACABADIAAAAQgBAEAAADQgBABAAACIAAgCQgBACgCADQgNAUgRAdQgEAGABACQADAEAHgCQAJgCAFgFQADgEAEgGQABgDABgCQACgFACgGQACgGADgFAAfglQABgBACAAQABAAABgBQAAAFAAAFQgCAIgFAHQgBgIAAgIQAAgCAAgBQAAgBAAgBQgBgEABgDAAbghQAAAAABAAQABgCACgCAAageQAAABgBABQgBADgBADQABgCABgDIABAAAAagdQAAAAAAgBQABgCAAgBAAXgQQABgEABgFQAAgBABgBQAAAAAAgBQAAAAAAgBQABgDABgBAAiglQABAEABAEAAWgYQAAAAAAAAIAAAAQgDACgBACQgBABAAAAQgDAHADABQAAgFABgEQAAgJgBgJAAVgWQgCAHAAAFQABgDADgJQAAABAAACQAAABAAACQAAAEAAAFQAAAAAAABQgCAIgCAGQgCACgBABIAAABQgBgEAAgDQgDgDgBgCQgBACgBACQgGALAAAMQAAAEABAFIgBAAQgCgEgBgDQACgBABgBQAHgDAFgFQABAAABgBIAAAAQAEgDAAgCQAAgDgCgCQgBgBgBgBIAAAAQgBgBgBAAQAAgEAAgCQABgLAFgKgAAWgYQgBABAAABAAJgIQACgCACgCQgCAHgCAGQgBABAAABQgEAKgEAMQgBACgBADQACgBAAAAQAAgCAAgCQAAgDAAgCQgBgFABgEQACgLAHgIgAARAGQABgGAAgDQABgGAAgBQAAACAAACQACgEACgGAAPATQAAgCABgBIAAgBQAAgCAAgCQABgCAAgDAgDgGQgBADgBADQgBABAAACQAAAFAAAGQAAAEgBAEQgBAEgCAEQAFgEAEgGQAAAAABAAQAJgSAAgKAgGADQgCAJAAAGQAAADABABQAAACABAAQAAgGAAgEQAAgGAAgFgAAEAkQAAABAAABQAAgBgBgBQgCABgBACQABABADABQABgBABgBQACgDACgDQAAgBABAAQgCAAAAACQgDAAgCACgAAKAhQgBAAAAABAALAgIAAgBQACgFACgHAgKAeQAAABgBACQAFgCAEgBQgEAJgFAKQAAABABAAQABABABAAQAFACAFgEIAKgDQgBgBgBgBQgCAAgCgBIACAAQgBgBgBgCIADABQABABACABQAAAAABABQAAAAABABIABgBIADgBIADgBQABAAAAAAIACAAQgBgBAAAAQgIgEgHADIABABIANABQAAgBABAAQABgBAAgCQABACAAACIABAAQgBAAAAAAIAAAAIAAABIABAAIgBgBAAIArIAEAAIAGAAIAGAAQgCABgCAAQACAAACAAQAEAAAEgBQgBgBAAgBQgFgGgEgCQgDgCgDAAQAEAAACACQABABAAABQABABAAACQABgCgCgCQgBAAAAgBQgCAAgBAAQgFgBgEABAAKAsQgBgBgBAAQADAAACABQABAAABAAQACAAADAAQgDABgCAAQADACAEADQAAABgBABQgFgCgEgEIABgBQgBAAgCgBgAAEApQACABACABAgIAzQAHgDAFgHAAQAfQAAAAgBAAIgDAAIAAAAQAAAAgBAAAAZArQgBAAAAABIAAAAQAAADgCADQADABAEACQABABABAAIACABIAEACIALAGIADABQAAgBACgBQABgCADAAQAAADgBABIgDgCIgHgFAAOAtQAAAAgBAAAAOAtIABAAAAZAqIAAAAIgBAAgAAYArIABAAAgBgQQgBADgBAHAAhA3QADAAADAAQADgBABAAQgCAAgDAAQgFgBgEAAQgXgBgWACQALAEANAAQAQgCAJgBgAgMBAIANABAgUgXIAAgHIAAgJAgOAKQAAgGABgCQABgFAHgMAgOAKIAAAAAgOANQAAgBAAgCAgOAhQABACAAADQAAAHACAEQgBACgBACQACgBADgBAgZAlQABAAABAAQAEgBAEgCQAAAAABgBQACgBACgCAgPAiQAAgDAAgDQAAgJABgGQgBAKABAKAgcAlQABAAACAAAgTA1QADgIABgLAgQA2QgCAAgCAAQABgBAAAAQACAAABABgAgMBAQgBAAgCAAQgDAAgDgCQgBgCACgGQAAAHAIADg");
	this.shape_3.setTransform(1.3,-5.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AENC8IAMgBIgMABIhpi1Ig4hhIARgJIA6BjIg6hjIgRAJIA4BhIgXgcQgcgfAEAQIACAGIAEAKIhMADIlShJIAAhsIHMAAIAACIIAAADIgUgTIAUAuIAOAgIBrC6IACADIgIACIAAgEIAAgBIADgBIAAAAIAAAAIACABIABAAIAAAAIAAAAIgBAAIgCgBIAAAAIAAAAIgDABIAAABIAAAEIAIgCIgRAKgAEUDCIACgBIACgBIAEgBIgEABIABgEIAAgBQgHABgBAGIAAAAIABAAIAAAAIAAAAIACAAgAAvgRIA8gTIADgBIgBgBIAFgBIgGAAIgGgMIgBgBIgNgXQADgDAAgDQAAgCgCgDQADgFACgJQgCAJgDAFIgBgBIABgLIgBALIgBAAIgCgCIABgHIgBAHIACACIABAAIgBAFIgBABIgBgIIABAIIABgBIACgEQACADAAACQAAADgDADIgCgDIAAAAIABgEIgBAEIAAAAIgGgMIABgDIAEAEIgEgEIgBADIgBAAIAAgCIAAACIgBgBIABgBIAHgEIADgCIAFgCIAQgJIAAggIgGAAIAAgEIAAAEIgGAAIAAgBIACgQIgCAQIAAABIgMAAIgBgBIgDAAIAAABIgEAAIABgEIgDAEIgSAAQADgCAGgBQgGABgDACIgBAAIgCgEIAAAEIgIAAIAAAPIgBAAQgDABgDACQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABIABABQABADADAAIACABIACgBIAAAQIgfAyQgCAFAAACIAAAAIABACQAAAAABAAQAAABABAAQAAAAABAAQABABAAAAIABAAIAAAAIADgBIABAAQAIgDAFgEQAEgEADgGIADAAgAB3geIgMgGgAAah2IkoAAgAESDCIAAAAIgBAAIAAAAQABgGAHgBIAAABIgBAEIgCABIgCABIgCAAIAAAAgAEYDAIAAAAgAEcC/gAATgmQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAAAIgBgCIAAAAQAAgCACgFIAfgyIAAAHIgHALIAHgLIAAAeIgDAGIgDAAIADAAQgDAGgEAEQgFAEgIADIgBAAIgDABIAAAAIgBAAgABtgmIgBgBIAGAAIgFABgABsgnIAAAAgAAsg4IADgGIAAAGIgDAAgABXhSIAAAAgABYhXIABABIgCAEIABgFgAAvhjgAArhzQgDAAgBgDIgBgBQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQADgCADgBIABAAIAAALIgCABIgCgBgAAvhzgABSiNIAAgBIADAAIABABgABOiNIgCAAIADgEIgBAEgAA3iNIAAgEIACAEg");
	this.shape_4.setTransform(-5.7,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.9,-25,71.9,50);


(lib.rectbevelbluecopyface2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgYAlIAAgKIAKgJIAKgJIAMgNQAEgFgBgHQABgFgEgEQgEgDgFAAQgFAAgFACQgFACgGADIAAAAIAAgKIAJgEIAMgBQAKAAAGAFQAHAGgBAJIgBAHIgCAHIgFAGIgGAGIgKAKIgLAIIAnAAIAAAJg");
	this.shape.setTransform(13,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_1.setTransform(3.3,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgFAbQgFgBgEgFQgDgDgCgFQgCgGAAgGQAAgNAHgHQAIgIALAAIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEAAQgHgBgEAGQgFAFAAAKQAAAJAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIAAQgFAAgFgBg");
	this.shape_2.setTransform(-2.2,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOIgKAAg");
	this.shape_3.setTransform(-8.1,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgWAkIAAhHIAtAAIAAAIIgjAAIAAAVIAeAAIAAAHIgeAAIAAAjg");
	this.shape_4.setTransform(-12.8,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7F2F6").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_5.setTransform(11.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7F2F6").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_6.setTransform(6.2,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7F2F6").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFAAIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_7.setTransform(1.3,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7F2F6").s().p("AAOAcIAAgeIgBgHIgBgFIgEgEIgGgBQgDAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAGIAJgFQAEgCAFAAQAJAAAEAGQAFAFAAAJIAAAjg");
	this.shape_8.setTransform(-3.9,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7F2F6").s().p("AgXAkIAAhHIAvAAIAAAIIglAAIAAAUIAlAAIAAAIIglAAIAAAbIAlAAIAAAIg");
	this.shape_9.setTransform(-10,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},2).to({state:[]},1).wait(1));

	// outline inner
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#E8E8E8").ss(1,1,1).p("AFtBfIrZAAIAAi9ILZAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_10).to({_off:true},3).wait(1));

	// bevel inner
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#B7DBEA","#ECF5F9"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#298CB6","#66ADCB"],[0,1],-0.8,-5.7,14.8,7.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11}]}).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[]},1).wait(1));

	// outline outer
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFF00").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14}]}).to({state:[{t:this.shape_15}]},1).to({state:[]},2).wait(1));

	// bevel outer
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#BDDEEC","#E7F1F5"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#5CACCD","#BADEE7"],[0,1],9,9,-8,-8.9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16}]}).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.5,-13.5,81,27);


(lib.rectbevelbluecopy2reset = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFAAIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape.setTransform(11.9,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_1.setTransform(6.9,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgMAbIgIgDIAAgKIAAAAQAEADAGACQAFACAFAAQAFAAADgCQAEgCAAgEQAAgEgCgBIgHgDIgEgBIgGgBQgHgCgDgDQgDgEAAgFQAAgDABgDIAEgGIAHgDQAFgCAEAAIAKACIAIACIAAAKIAAAAIgJgEIgKgCQgEAAgDACQgEACAAAEQAAADACACQACACAFABIAFABIAFABQAGABAEADQADAEAAAGQAAAHgGAFQgGAFgKAAQgGAAgFgCg");
	this.shape_2.setTransform(1.4,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_3.setTransform(-4.2,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AARAkIgXgdIgOAAIAAAdIgJAAIAAhHIAUAAIAKAAIAIADQAEADACAEQACAEAAAFQAAAIgEAGQgEAEgGACIAbAggAgUAAIAKAAIAIAAQACgBADgDIADgEIABgHQAAgDgBgDIgDgEIgFgCIgGAAIgMAAg");
	this.shape_4.setTransform(-9.9,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7F2F6").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_5.setTransform(11.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7F2F6").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_6.setTransform(6.2,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7F2F6").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFAAIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_7.setTransform(1.3,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7F2F6").s().p("AAOAcIAAgeIgBgHIgBgFIgEgEIgGgBQgDAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAGIAJgFQAEgCAFAAQAJAAAEAGQAFAFAAAJIAAAjg");
	this.shape_8.setTransform(-3.9,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7F2F6").s().p("AgXAkIAAhHIAvAAIAAAIIglAAIAAAUIAlAAIAAAIIglAAIAAAbIAlAAIAAAIg");
	this.shape_9.setTransform(-10,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},2).to({state:[]},1).wait(1));

	// outline inner
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#E8E8E8").ss(1,1,1).p("AFtBfIrZAAIAAi9ILZAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_10).to({_off:true},3).wait(1));

	// bevel inner
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#B7DBEA","#ECF5F9"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#298CB6","#66ADCB"],[0,1],-0.8,-5.7,14.8,7.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11}]}).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[]},1).wait(1));

	// outline outer
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFF00").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14}]}).to({state:[{t:this.shape_15}]},1).to({state:[]},2).wait(1));

	// bevel outer
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#BDDEEC","#E7F1F5"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#5CACCD","#BADEE7"],[0,1],9,9,-8,-8.9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16}]}).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.5,-13.5,81,27);


(lib.rectbevelblue = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgTAlIAAgIIAPAAIAAgvIgPAAIAAgHIAHgBIAFgBIAEgEQABgCAAgCIAHAAIAABAIAPAAIAAAIg");
	this.shape.setTransform(13.1,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_1.setTransform(3.3,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgFAbQgFgBgEgFQgDgDgCgFQgCgGAAgGQAAgNAHgHQAIgIALAAIAJABIAIADIAAAKIAAAAQgFgDgEgBQgFgCgEAAQgHgBgEAGQgFAFAAAKQAAAJAFAGQAEAFAHAAIAGgBIAFgCIAEgCIADgCIAAAAIAAAKIgJAEIgIAAQgFAAgFgBg");
	this.shape_2.setTransform(-2.2,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgRAYQgFgFAAgIQAAgGADgEQACgCAFgDIAMgDIAOgBIAAgBQAAgDgBgCIgDgEIgFgBIgFgBIgIABIgJADIAAAAIAAgJIAHgCIAKgBIAJABQAFABADADQADACACADQABAEAAAFIAAAkIgJAAIAAgGIgDADIgEACIgGACIgGABQgHAAgFgFgAAEAAIgIABQgEABgCACQgDADAAAEQAAAEADADQADACAGAAQAEAAAEgCIAHgEIAAgOIgKAAg");
	this.shape_3.setTransform(-8.1,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgWAkIAAhHIAtAAIAAAIIgjAAIAAAVIAeAAIAAAHIgeAAIAAAjg");
	this.shape_4.setTransform(-12.8,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7F2F6").s().p("AgQAbIAAg1IAJAAIAAAIQAFgFAEgBQAEgCAEAAIAEAAIADAAIAAAKIAAAAIgFgBIgEAAQgEAAgEACIgHAFIAAAlg");
	this.shape_5.setTransform(11.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7F2F6").s().p("AgQAVQgIgHAAgOQAAgMAIgIQAHgIALAAQALAAAGAHQAGAGAAAMIAAAEIgnAAQAAAFABAEIAEAGQADACADABQADACAEAAQAGAAAFgDQAGgCACgCIABAAIAAAKIgKADQgEACgGAAQgMAAgIgIgAgJgQQgFAEAAAHIAeAAQAAgHgEgEQgDgEgIAAQgGAAgEAEg");
	this.shape_6.setTransform(6.2,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7F2F6").s().p("AgGAfQgEgEAAgKIAAgcIgGAAIAAgIIAGAAIAAgQIAJAAIAAAQIASAAIAAAIIgSAAIAAAXIAAAHIABAFIADADIAFAAIAFAAIAEgBIAAAAIAAAIIgGABIgFAAQgHAAgFgEg");
	this.shape_7.setTransform(1.3,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7F2F6").s().p("AAOAcIAAgeIgBgHIgBgFIgEgEIgGgBQgDAAgEACIgIAGIAAAnIgJAAIAAg2IAJAAIAAAGIAJgFQAEgCAFAAQAJAAAEAGQAFAFAAAJIAAAjg");
	this.shape_8.setTransform(-3.9,0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7F2F6").s().p("AgXAkIAAhHIAvAAIAAAIIglAAIAAAUIAlAAIAAAIIglAAIAAAbIAlAAIAAAIg");
	this.shape_9.setTransform(-10,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},2).to({state:[]},1).wait(1));

	// outline inner
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#E8E8E8").ss(1,1,1).p("AFtBfIrZAAIAAi9ILZAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_10).to({_off:true},3).wait(1));

	// bevel inner
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#B7DBEA","#ECF5F9"],[0,1],8.3,6.8,-7.3,-6.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#298CB6","#66ADCB"],[0,1],-0.8,-5.7,14.8,7.7).s().p("AlnBaIAAizILPAAIAACzg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11}]}).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[]},1).wait(1));

	// outline outer
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#000000").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFF00").ss(1,1,1).p("AGLB9IsVAAIAAj5IMVAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14}]}).to({state:[{t:this.shape_15}]},1).to({state:[]},2).wait(1));

	// bevel outer
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#8DC7DF","#DCEBF2"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#BDDEEC","#E7F1F5"],[0,1],-9,-8.9,8,9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#5CACCD","#BADEE7"],[0,1],9,9,-8,-8.9).s().p("AmFB4IAAjvIMLAAIAADvg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16}]}).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.5,-13.5,81,27);


(lib.brownhair = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AAnk/QCYgLgUDDQG5BviCFXQgggPiJggQgDgBgDgBQgHgBgHgCQjUgtjJATQiYAPiQA2QhHAbgYgqIAAhkQARj5EZisQBAgiA0gWAAYDDQACikCRimAF7gqQACDRhEBpAmgE2QgOljFNjtQBRghA3gEAjeDVQAoj+DdkW");
	this.shape.setTransform(0,1.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(4,1,1).p("AgDAAQADAAAEAB");
	this.shape_1.setTransform(29.8,-33.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("An/EnIAAhkQARj5EZisQBAgiA0gWQk/DjAAFQIAAAdQgbALgVAAQggAAgPgagAE5EQQBChlAAjHIAAgOIAAAOQAADHhCBlIgGgCIgOgDQjUgtjJATQiYAPiQA2IAAgdQAAlQE/jjQBRghA3gEQCYgLgUDDQG5BviCFXQgggPiJgggAjeDVQAoj+DdkWQjdEWgoD+gAAYDDQACikCRimQiRCmgCCkgAhhkaIAAAAg");
	this.shape_2.setTransform(0,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AgEAAIAJAAIgCABIgHgBg");
	this.shape_3.setTransform(29.9,-33.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-35.4,104.4,69.8);


(lib.browneyes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("ADqAGQAAALgJAIQgIAJgLAAQgMAAgIgJQgIgIAAgLQAAgLAIgIQAIgIAMAAQALAAAIAIQAJAIAAALgAioAAQAAAMgJAKQgKAJgNAAQgOAAgJgJQgKgKAAgMQAAgOAKgJQAJgKAOAAQANAAAKAKQAJAJAAAOg");
	this.shape.setTransform(-0.4,11.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(2,1,1).p("AETAAQAAAsgUAfQgUAfgdAAQgcAAgUgfQgUgfAAgsQAAgrAUgfQAUgfAcAAQAdAAAUAfQAUAfAAArgAiJAAQAAAsgUAfQgUAfgcAAQgdAAgUgfQgUgfAAgsQAAgrAUgfQAUgfAdAAQAcAAAUAfQAUAfAAArg");
	this.shape_1.setTransform(0.7,4.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("ABTBFQAGBLAJAtQAIAtA/AHQA/AGAsglQAtglAFh1QAFh0gVhaQgVhZg4gEQg5gEgxB5QgyB4AGBLgAhFBEQgJBTgQAtQgQAtgxADQgyACglgSQgPgHgNgKQgtglgFh2QgBgggBgdQgChMAYhIQAYhIA6gGQA5gHA0BwQA0BwgIBSg");

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#663300").s().p("ACeBLQgUgfAAgsQAAgrAUgfQAUgfAcAAQAdAAAUAfQAUAfAAArQAAAsgUAfQgUAfgdAAQgcAAgUgfgACuA1QgIAJAAALQAAAMAIAIQAJAIALAAQAMAAAIgIQAIgIAAgMQAAgLgIgJQgIgIgMAAQgLAAgJAIgAj+BLQgUgfAAgsQAAgrAUgfQAUgfAdAAQAcAAAUAfQAUAfAAArQAAAsgUAfQgUAfgcAAQgdAAgUgfgAjrArQgJAKAAANQAAAOAJAJQAKAKANAAQAOAAAJgKQAKgJAAgOQAAgNgKgKQgJgJgOAAQgNAAgKAJg");
	this.shape_3.setTransform(0.7,4.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Aj2DkQgPgHgNgKQgtglgFh2IgCg9QgChMAYhIQAYhIA6gGQA5gHA0BwQA0BwgIBSQgJBTgQAtQgQAtgxADIgMAAQgqAAghgQgAj2gZQgUAeAAAsQAAAsAUAfQAUAfAcAAQAdAAAUgfQAUgfAAgsQAAgsgUgeQgUgfgdAAQgcAAgUAfgACpDxQg/gHgIgtQgJgtgGhLQgGhLAyh4QAxh5A5AEQA4AEAVBZQAVBagFB0QgFB1gtAlQgmAggzAAIgSgBgAClgZQgUAeAAAsQAAAsAUAfQAUAfAdAAQAcAAAUgfQAUgfAAgsQAAgsgUgeQgUgfgcAAQgdAAgUAfgAC2COQgIgIAAgMQAAgLAIgJQAIgIAMAAQALAAAIAIQAJAJAAALQAAAMgJAIQgIAIgLAAQgMAAgIgIgAjjCKQgKgJAAgOQAAgNAKgKQAJgJAOAAQANAAAKAJQAJAKAAANQAAAOgJAJQgKAKgNAAQgOAAgJgKg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33.7,-25.4,67.4,50.8);


(lib.blondehair = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(1,1,1).p("AHfERQgkkTkPi8AIjCzQgdirkdjhAnnBTQAWjJC6iIAoiFHQBwlACKi9Ag3kTQCCgVAtBGAg0k4QBbgzCQCA");
	this.shape.setTransform(-0.2,-0.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#333333").ss(2,1,1).p("AI+DhQgIBTgPAmQgZBCgvhCQgdgpgkhaQiDlBjzhVQjxhWjQGaQhVCogpAtQgeAggIggQgIggAQhiQAzlIBQhVQBRhVDOhKQDNhKEQCsQEQCsgcE3g");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("AHfFaQgdgpgkhaQiDlBjzhVQjxhWjQGaQhVCogpAtQgeAggIggQgIggAQhiQAzlIBQhVQBRhVDOhKQDNhKEQCsQEQCsgcE3QgIBTgPAmQgMAhgSAAQgSAAgYghgAokE+QBwk/CKi+QiKC+hwE/gAHdEIQgkkTkQi8QEQC8AkETgAIgCpQgdiqkcjhQEcDhAdCqgAnpBKQAWjJC6iJQi6CJgWDJgAB2jrQgjg2hVAAIAAAAIAAAAQgZAAgcAEIAAAAIgCAAIACAAIAAAAQAcgEAZAAIAAAAIAAAAQBVAAAjA2IAAAAgAC1j1IgBgBIgCgBIAAAAIgBgBQhkhYhLAAIAAAAIgBAAQgcAAgZANIgCABIACgBQAZgNAcAAIABAAIAAAAQBLAABkBYIABABIAAAAIACABIABABIAAAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.6,-38.9,117.3,77.8);


(lib.blacksunglasses = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("ABoABQAAgBAAAAQAAhLA2g1QA2g1BMAAQBMAAA2A1QA1A1AABLQAABLg1A2Qg2A1hMAAQhMAAg2g1Qg2g2AAhKgAhmABQgBBLg1A1Qg2A1hMAAQhMAAg2g1Qg2g2AAhLQAAhLA2g1QA2g1BMAAQBMAAA2A1QA2A1AABLQAAABAAAAIDOAA");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("ACeCBQg2g2AAhKIAAgBQAAhKA2g2QA2g1BMAAQBMAAA2A1QA1A2AABKQAABLg1A2Qg2A1hMAAQhMAAg2g1gAmgCBQg2g2AAhLQAAhKA2g2QA2g1BMAAQBMAAA2A1QA2A2AABKIAAABQgBBLg1A1Qg2A1hMAAQhMAAg2g1g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.1,-19.2,96.3,38.4);


(lib.Blackeyes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("ADiAAQAAAYgKARQgJARgNAAQgOAAgJgRQgJgRAAgYQAAgXAJgRQAJgQAOAAQANAAAJAQQAKARAAAXgAiYAAQAAAVgLAQQgKAQgPAAQgPAAgLgQQgLgQAAgVQAAgXALgQQALgPAPAAQAPAAAKAPQALAQAAAXg");
	this.shape.setTransform(-196.2,20.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AgxAAQAACJgrBgQgMAbgNAUQgHALgIAIQgcAfgiAAQgsAAgigyQgNgUgMgbQgqhgAAiJQAAiIAqhgQAfhFAngUQAHgEAHgCQAJgCAKAAQAKAAAJACQAHACAHAEQAnAUAeBFQAEAIADAIQAkBcAAB8gAFUAAQAACJgqBgQgMAbgNAUQgiAygsAAQgrAAgigyQgNgUgMgbQgrhgAAiJQAAh8AkhcQADgIAEgIQAjhSAxgNQAJgCAJAAQAKAAAJACQAwANAkBSQADAIAEAIQAjBcAAB8gAEVAaQAHA7gSAyQgEAIgDAHQgMAXgQAIQgHADgIAAQgegDghg4QgDgFgDgGQgVgqAAg7QAAg6AVgqQAVgqAeAAQAdAAAVAqQAFAKAEAKQAMAkAIA5gAhzAZQAGA6gTA5QgCAFgCAFQgCAFgDAFQgKAQgNAGQgMADgegMQgHgDgGgEQgSgOgEgbQgDgFgCgGQgVgqAAg7QAAg6AVgqQAVgqAdAAQAeAAAVAqQAEAKAEAKQABACAAABQAMAjAFA2g");
	this.shape_1.setTransform(-193.9,14.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ADRCdQgfgDghg4IgFgLQgVgqAAg6QAAg7AVgqQAVgqAdAAQAeAAAVAqIAIAUQANAkAHA6QAIA6gTAyIgGAPQgNAXgPAIQgGADgHAAIgCAAgACMgEQgJAQAAAYQAAAYAJAQQAKARANAAQAOAAAJgRQAJgQAAgYQAAgYgJgQQgJgRgOAAQgNAAgKARgAjRCSQgIgDgFgEQgHgJgHgNIgIgTIgGgLQgVgqAAg6QAAg7AVgqQAVgqAeAAQAdAAAVAqIAJAUIABADQALAjAGA3QAFA5gTA5IgDAKIgFAKQgLAQgMAGIgFABQgMAAgZgKgAj1gDQgKAPAAAWQAAAXAKAPQALAQAPAAQAPAAALgQQALgPAAgXQAAgWgLgPQgLgQgPAAQgPAAgLAQg");
	this.shape_2.setTransform(-193.2,16.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AB2EYQgNgUgMgbQgrhhAAiIQAAh8AkhbIAHgRQAjhSAxgNQAJgCAJAAQAKAAAJACQAwANAkBSIAHARQAjBbAAB8QAACIgqBhQgMAbgNAUQgiAygsAAQgrAAgigygACThXQgVAqAAA6QAAA7AVAqIAGALIAIATQAVAqAeAAQAKAAAJgFQAQgIAMgXIADgGQAVgqAGg4QAFg3gRgaIgUggIgJgUQgVgqgdAAQgeAAgVAqgAkQEYQgNgUgMgbQgqhhAAiIQAAiIAqhgQAfhFAngUIAOgGQAJgCAKAAQAKAAAJACIAOAGQAnAUAeBFIAHARQAkBbAAB8QAACIgrBhQgMAbgNAUQgHALgIAIQgcAfgiAAQgsAAgigygAjXClQARAVAUAAQAKAAAIgEQANgGAKgQIAFgHIAFgJQAVgqAAg7QAAg6gVgqIgFgJIgBgBIgIgUQgVgqgeAAQgdAAgVAqQgVAqAAA6QAAA7AVAqIAFALQAEAbASANIAAAAgAjtB9IAJATQAGAMAHAJQgSgNgEgbgACUBnQgJgRAAgXQAAgZAJgRQAJgQAOAAQANAAAJAQQAKARAAAZQAAAXgKARQgJARgNAAQgOAAgJgRgAjtBjQgLgPAAgXQAAgXALgQQALgPAPAAQAPAAAKAPQALAQAAAXQAAAXgLAPQgKAQgPAAQgPAAgLgQg");
	this.shape_3.setTransform(-193.9,14.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Blackeyes, new cjs.Rectangle(-228.9,-19.8,70,68), null);


(lib.arms = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(7,1,1).p("AMQHdIj5vKAsPHuIEYut");
	this.shape.setTransform(-1.2,-15.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("ALBB9QgCgbAHgqQhkBJBJiEIAghWQAQgOAIgRQACgEABgDQAIgPAkAAQABAAgQgYQAZAYAKABIAAAAQAfAUAXAXQAJAJAHAKQAWAdALAiQATA7gQBNQgCgBgBAAQgUgKgNgZQgIgRgFgXQAEAqgFAnANfAsQgCgMgBgNQgBgIgBgIANgB9QgBAHgBAHQgBACAAACQgBABAAACIgUAAQgBgBgBgCQgFgJgEgJAM7B9QgRgmgFgwIgUBWAL3B9QgFgQABgaQAAgTAAgTQgEAvgJAhAMTB9IgGAWQgGAAgEgEQgHgFgDgNALXCnQgMgGgFgSQgCgIgBgKALoB9QgCAKgDAIQgFAOgGAKAqvB9QAMgZgOgkQAuASAMgTQAJgQgOgoIhDhOQgJgbgJgSQgCgDgCgEQgGgLgZgHQgQgFgXgDQgzAigeArQgBABgCACQgCADgCAEQgWAigJAoQgKA0ANA9ArkB9QACgOAAgTQgBgOAAgPQAAgFAAgFQABAFAAAFQAEAnAPAXAstB9QAPgjAFgsIAUBPAsDB9IAIAgQABAAABAAQADgBAEgBQAGgDAFgJQADgHACgLArNB9QAHALAJAHQAAABAAAAQABAAAAgBQAJgIAGgKAtaA1QAFgUACgXAuEB9QAMgIAJgMQACgCABgCQAMgTAGgdQgCAlAEAjAuNB9QABACAAACQAFgCAFgCAtWB9QABAJABAJQABAHACAGIAWAAQAEgGADgHQAFgJAEgJ");
	this.shape_1.setTransform(0,48.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ALXCnQgMgGgFgSIgDgSIgCAAQgCgbAHgqQhkBJBJiEIAghWQAQgOAIgRIADgHQAIgPAkAAIgPgYQAZAYAKABIAAAAQAfAUAXAXIAQATQAWAdALAiQATA7gQBNIgDgBQgUgKgNgZQgIgRgFgXQAEAqgFAnIACAAIgCAOIgBAEIgBADIgUAAIgCgDIgJgSIgCAAQgRgmgFgwIgUBWIACAAIgGAWQgGAAgEgEQgHgFgDgNIgCAAQgFgQABgaIAAgmQgEAvgJAhIACAAIgFASQgFAOgGAKgANcATIADAZIgDgZIgCgQIACAQgAr7CdIgIggIgCAAIgUhPQgFAsgPAjIACAAIgJASIgHANIgWAAIgDgNIgCgSIgCAAQgEgjACglQAFgUACgXQgCAXgFAUQgGAdgMATIgDAEQgJAMgMAIIACAAIgKAEIgBgEIgCAAQgNg9AKg0QAJgoAWgiIAEgHIADgDQAegrAzgiQAXADAQAFQAZAHAGALIAEAHQAJASAJAbIBDBOQAOAogJAQQgMATgugSQAOAkgMAZIACAAQgGAKgJAIIgBABIAAgBQgJgHgHgLIgCAAQgPgXgEgnIgBgKIAAAKIABAdQAAATgCAOIACAAQgCALgDAHQgFAJgGADIgHACIgCAAg");
	this.shape_2.setTransform(0,48.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.9,-68.8,185.9,135.1);


// stage content:
(lib.MPHFinalCSilva = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.face1_btn.addEventListener("click", fl_ClickFace1.bind(this));
		
		function fl_ClickFace1()
		{
			this.hat.x = 240;
			this.hat.y = 135;
			this.timbs.x = 240;
			this.timbs.y = 500;	
			this.blacksunglasses.x = 240;
			this.blacksunglasses.y = 240;	
			this.rednose.x = 244;
			this.rednose.y = 267;	
			this.Cigar.x = 252;
			this.Cigar.y = 300; 
			this.ears.x = 235;
			this.ears.y = 242; 
			this.arms.x = 235;
			this.arms.y = 332;
		}
		this.btn_reset.addEventListener("click", fl_Clickreset.bind(this));
		
		function fl_Clickreset()
		{
			this.hat.x = 688;
			this.hat.y = 348;
			this.timbs.x = 514;
			this.timbs.y = 530;	
			this.blacksunglasses.x = 500;
			this.blacksunglasses.y = 108;	
			this.rednose.x = 610;
			this.rednose.y = 167;	
			this.Cigar.x = 702;
			this.Cigar.y = 156; 
			this.ears.x = 604;
			this.ears.y = 30; 
			this.arms.x = 473;
			this.arms.y = 245; 
			this.redmouth.x = 692;
			this.redmouth.y = 206; 	
			this.browneyes.x = 688;
			this.browneyes.y = 262; 	
			this.brownhair.x = 688;
			this.brownhair.y = 514;
			this.nose.x = 613;
			this.nose.y = 228;
			this.gauntlet.x = 474;
			this.gauntlet.y = 397;
			this.sneakers.x = 379;
			this.sneakers.y = 537;
			this.eyebrows.x = 472;
			this.eyebrows.y = 22;
			this.blondehair.x = 686;
			this.blondehair.y = 429;
			this.glasses.x = 494;
			this.glasses.y = 57;
			this.nose.x = 613;
			this.nose.y = 228;
			this.moustache.x = 602;
			this.moustache.y = 116;
			this.mouth.x = 688;
			this.mouth.y = 105;
		}
		this.face2_btn.addEventListener("click", f1_ClickFace2.bind(this));
		
		function f1_ClickFace2()
		{
			this.redmouth.x = 241;
			this.redmouth.y = 288; 	
			this.browneyes.x = 243;
			this.browneyes.y = 230; 	
			this.brownhair.x = 237;
			this.brownhair.y = 156;
		}
		
		this.timbs.addEventListener("pressmove", dragMe.bind(this));
		this.redmouth.addEventListener("pressmove", dragMe.bind(this));
		this.rednose.addEventListener("pressmove", dragMe.bind(this));
		this.hat.addEventListener("pressmove", dragMe.bind(this));
		this.ears.addEventListener("pressmove", dragMe.bind(this));
		this.Cigar.addEventListener("pressmove", dragMe.bind(this));
		this.brownhair.addEventListener("pressmove", dragMe.bind(this));
		this.browneyes.addEventListener("pressmove", dragMe.bind(this));
		this.blacksunglasses.addEventListener("pressmove", dragMe.bind(this));
		this.arms.addEventListener("pressmove", dragMe.bind(this));
		this.gauntlet.addEventListener("pressmove", dragMe.bind(this));
		this.sneakers.addEventListener("pressmove", dragMe.bind(this));
		this.blackeyes.addEventListener("pressmove", dragMe.bind(this));
		this.glasses.addEventListener("pressmove", dragMe.bind(this));
		this.eyebrows.addEventListener("pressmove", dragMe.bind(this));
		this.moustache.addEventListener("pressmove", dragMe.bind(this));
		this.mouth.addEventListener("pressmove", dragMe.bind(this));
		this.nose.addEventListener("pressmove", dragMe.bind(this));
		this.blondehair.addEventListener("pressmove", dragMe.bind(this));
		
		function dragMe(evt) {
			evt.currentTarget.x = evt.stageX;
			evt.currentTarget.y = evt.stageY;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Body Parts
	this.gauntlet = new lib.gauntlet();
	this.gauntlet.name = "gauntlet";
	this.gauntlet.parent = this;
	this.gauntlet.setTransform(474,395.5,1,1,0,0,0,0,-1.5);
	new cjs.ButtonHelper(this.gauntlet, 0, 1, 1);

	this.hat = new lib.hat();
	this.hat.name = "hat";
	this.hat.parent = this;
	this.hat.setTransform(688,347.6,1,1,0,0,0,0,-0.4);
	new cjs.ButtonHelper(this.hat, 0, 1, 1);

	this.nose = new lib.nose();
	this.nose.name = "nose";
	this.nose.parent = this;
	this.nose.setTransform(613,228);
	new cjs.ButtonHelper(this.nose, 0, 1, 1);

	this.mouth = new lib.mouth();
	this.mouth.name = "mouth";
	this.mouth.parent = this;
	this.mouth.setTransform(688,105);
	new cjs.ButtonHelper(this.mouth, 0, 1, 1);

	this.moustache = new lib.moustache();
	this.moustache.name = "moustache";
	this.moustache.parent = this;
	this.moustache.setTransform(602,116);
	new cjs.ButtonHelper(this.moustache, 0, 1, 1);

	this.eyebrows = new lib.eyebrows();
	this.eyebrows.name = "eyebrows";
	this.eyebrows.parent = this;
	this.eyebrows.setTransform(472,22);
	new cjs.ButtonHelper(this.eyebrows, 0, 1, 1);

	this.glasses = new lib.glasses();
	this.glasses.name = "glasses";
	this.glasses.parent = this;
	this.glasses.setTransform(494,57);
	new cjs.ButtonHelper(this.glasses, 0, 1, 1);

	this.sneakers = new lib.sneakers();
	this.sneakers.name = "sneakers";
	this.sneakers.parent = this;
	this.sneakers.setTransform(379,537);
	new cjs.ButtonHelper(this.sneakers, 0, 1, 1);

	this.browneyes = new lib.browneyes();
	this.browneyes.name = "browneyes";
	this.browneyes.parent = this;
	this.browneyes.setTransform(688,262);
	new cjs.ButtonHelper(this.browneyes, 0, 1, 1);

	this.redmouth = new lib.redmouth();
	this.redmouth.name = "redmouth";
	this.redmouth.parent = this;
	this.redmouth.setTransform(692,206);
	new cjs.ButtonHelper(this.redmouth, 0, 1, 1);

	this.arms = new lib.arms();
	this.arms.name = "arms";
	this.arms.parent = this;
	this.arms.setTransform(473,243.5,1,1,0,0,0,0,-1.5);
	new cjs.ButtonHelper(this.arms, 0, 1, 1);

	this.Cigar = new lib.Cigar();
	this.Cigar.name = "Cigar";
	this.Cigar.parent = this;
	this.Cigar.setTransform(702,156);
	new cjs.ButtonHelper(this.Cigar, 0, 1, 1);

	this.rednose = new lib.rednose();
	this.rednose.name = "rednose";
	this.rednose.parent = this;
	this.rednose.setTransform(610,167);
	new cjs.ButtonHelper(this.rednose, 0, 1, 1);

	this.blacksunglasses = new lib.blacksunglasses();
	this.blacksunglasses.name = "blacksunglasses";
	this.blacksunglasses.parent = this;
	this.blacksunglasses.setTransform(500,108);
	new cjs.ButtonHelper(this.blacksunglasses, 0, 1, 1);

	this.timbs = new lib.timbs();
	this.timbs.name = "timbs";
	this.timbs.parent = this;
	this.timbs.setTransform(513.1,530);
	new cjs.ButtonHelper(this.timbs, 0, 1, 1);

	this.blackeyes = new lib.Blackeyes();
	this.blackeyes.name = "blackeyes";
	this.blackeyes.parent = this;
	this.blackeyes.setTransform(589.2,59.4);
	new cjs.ButtonHelper(this.blackeyes, 0, 1, 1);

	this.ears = new lib.ears();
	this.ears.name = "ears";
	this.ears.parent = this;
	this.ears.setTransform(674,53);
	new cjs.ButtonHelper(this.ears, 0, 1, 1);

	this.blondehair = new lib.blondehair();
	this.blondehair.name = "blondehair";
	this.blondehair.parent = this;
	this.blondehair.setTransform(686,429);
	new cjs.ButtonHelper(this.blondehair, 0, 1, 1);

	this.brownhair = new lib.brownhair();
	this.brownhair.name = "brownhair";
	this.brownhair.parent = this;
	this.brownhair.setTransform(688,513.2,1,1,0,0,0,0,-0.8);
	new cjs.ButtonHelper(this.brownhair, 0, 1, 1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AABAAQAAAAgBAAQAAAAAAAA");
	this.shape.setTransform(546.7,310.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAAIABAAIgBAAIAAAAg");
	this.shape_1.setTransform(546.7,310.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.brownhair},{t:this.blondehair},{t:this.ears},{t:this.blackeyes},{t:this.timbs},{t:this.blacksunglasses},{t:this.rednose},{t:this.Cigar},{t:this.arms},{t:this.redmouth},{t:this.browneyes},{t:this.sneakers},{t:this.glasses},{t:this.eyebrows},{t:this.moustache},{t:this.mouth},{t:this.nose},{t:this.hat},{t:this.gauntlet}]}).wait(1));

	// Character
	this.face2_btn = new lib.rectbevelbluecopyface2();
	this.face2_btn.name = "face2_btn";
	this.face2_btn.parent = this;
	this.face2_btn.setTransform(58.3,249.7);
	new cjs.ButtonHelper(this.face2_btn, 0, 1, 2, false, new lib.rectbevelbluecopyface2(), 3);

	this.btn_reset = new lib.rectbevelbluecopy2reset();
	this.btn_reset.name = "btn_reset";
	this.btn_reset.parent = this;
	this.btn_reset.setTransform(59.3,287.3);
	new cjs.ButtonHelper(this.btn_reset, 0, 1, 2, false, new lib.rectbevelbluecopy2reset(), 3);

	this.face1_btn = new lib.rectbevelblue();
	this.face1_btn.name = "face1_btn";
	this.face1_btn.parent = this;
	this.face1_btn.setTransform(58.3,212);
	new cjs.ButtonHelper(this.face1_btn, 0, 1, 2, false, new lib.rectbevelblue(), 3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgUAkQgHgHAAgMQAAgIAEgGQAEgEAIgCQgHgDgDgEQgDgFAAgGQAAgJAHgHQAHgGAKAAQALAAAHAHQAHAGAAAJQAAAGgDAFQgEAEgGADQAIACAEAFQAEAGAAAIQAAALgIAHQgHAIgNAAQgMAAgIgIgAgMAFQgFAFAAAHQAAAFADAEQACAEAEADQAEACAEAAQAIAAAFgFQAEgFAAgHQAAgIgFgFQgFgFgHAAQgHAAgFAFgAgJgeQgEADAAAGQAAAGAEAEQAEAEAFAAQAGAAAEgEQAEgEAAgGQAAgFgEgEQgEgEgGAAQgFAAgEAEg");
	this.shape_2.setTransform(84.1,554.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAFArIAAhCQgDADgGAEIgLAGIAAgKQAJgFAGgGQAGgFADgGIAHAAIAABVg");
	this.shape_3.setTransform(77,554);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgTAjQgIgLAAgYQAAgOADgKQAEgJAGgFQAFgFAJAAQAHAAAFADQAGADADAFQADAFACAIQACAHAAAMQAAAPgDAJQgDAKgHAFQgFAFgKAAQgLAAgIgJgAgLgcQgFAIAAAUQAAAVAFAHQAFAHAGAAQAIAAAEgHQAFgHAAgVQAAgUgFgHQgEgHgIAAQgGAAgFAGg");
	this.shape_4.setTransform(70.8,554.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgcArQAAgEACgEQACgFAFgFQAEgHAKgHQANgLAFgGQAEgHABgFQAAgHgFgEQgFgEgGgBQgIABgEAEQgEAFAAAHIgLgBQABgLAHgHQAIgGALAAQAMAAAHAGQAIAHAAALQgBAFgCAEQgCAFgFAFQgEAFgMALIgLAKIgFAGIAqAAIAAAKg");
	this.shape_5.setTransform(64,554);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgWAqIgBgKIAGABIAGgBIADgDIADgIIABgDIgXg9IALAAIANAkIADANIAFgNIANgkIAKAAIgXA+IgFAOQgDAGgEACQgDADgGAAIgGgCg");
	this.shape_6.setTransform(54.5,556.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgWAbQgGgEABgJQAAgEACgEQACgDADgDIAHgDIAKgBQALgBAHgDIAAgCQgBgHgDgDQgEgDgHAAQgHAAgDACQgEADgCAHIgKgBQACgHADgEQADgEAGgDQAGgBAHAAQAIgBAFACQAFACACADQADADABAEIABAKIAAANIAAASQAAAEACAEIgKAAIgCgIQgHAFgFADQgEABgHABQgKAAgFgGgAgBAEQgHAAgDACQgCABgCACQgBADgBACQABAFADADQADACAGAAQAFAAAFgCQAEgDADgFQACgEAAgGIAAgEIgQAEg");
	this.shape_7.setTransform(48.1,555.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAeArIAAhHIgZBHIgKAAIgYhIIAABIIgLAAIAAhVIARAAIAUA8IAEAMIAEgNIAVg7IAPAAIAABVg");
	this.shape_8.setTransform(39.8,554);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgBApIgEgFQgBgDAAgJIAAgjIgIAAIAAgIIAIAAIAAgQIAJgHIAAAXIALAAIAAAIIgLAAIAAAjIABAFIABADIAEABIAFgBIABAKIgIABQgFAAgDgCg");
	this.shape_9.setTransform(83.8,538.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgQAgIAAg9IAKAAIAAAJQADgHADgCQACgCAEAAQAFAAAGAEIgEAJQgEgCgEAAQgDAAgCACQgCACgCAEQgBAFAAAHIAAAgg");
	this.shape_10.setTransform(80.6,539.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAcArIgLgaIgiAAIgKAaIgMAAIAhhVIALAAIAjBVgAgFgQIgKAXIAcAAIgIgWIgFgSQgCAJgDAIg");
	this.shape_11.setTransform(74.1,538.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgaAsIAAhVIAJAAIAAAIQAEgFAEgCQAFgDAEAAQAIAAAHAEQAFAEAEAIQADAHAAAJQAAAKgDAGQgEAIgGAEQgHAEgHAAQgFAAgEgCQgEgCgDgEIAAAfgAgLgcQgGAGAAAMQAAALAGAGQAEAFAHAAQAGAAAFgFQAFgGAAgMQAAgMgFgGQgEgGgHAAQgGAAgFAHg");
	this.shape_12.setTransform(63.6,541);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAfAgIAAgmIgBgKIgDgEQgDgCgEAAQgGAAgEAFQgFAEAAAKIAAAjIgJAAIAAgoQAAgHgCgDQgDgEgGAAQgFAAgEADQgDACgCAEQgBAFgBAIIAAAgIgKAAIAAg9IAJAAIAAAIQADgEAFgDQAFgDAGAAQAHAAAEADQAEADACAFQAHgLAMAAQAJAAAFAFQAFAFAAALIAAAqg");
	this.shape_13.setTransform(55.1,539.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgUAYQgIgJAAgPQAAgQAJgJQAIgHALAAQANAAAIAJQAIAIAAAPQAAALgEAHQgDAHgHAEQgHADgIAAQgMABgIgJgAgMgRQgFAGAAALQAAAMAFAGQAFAGAHgBQAIABAFgGQAFgGAAgMQAAgLgFgGQgFgGgIAAQgHAAgFAGg");
	this.shape_14.setTransform(46.8,539.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgTAnQgJgGgFgLQgEgLAAgLQAAgNAFgKQAFgKAJgFQAKgGAKABQAOgBAIAHQAJAHADALIgKAEQgEgKgFgFQgGgDgJAAQgIgBgHAFQgHAFgDAIQgDAIAAAIQABAKADAJQADAIAHAEQAHADAGAAQAKABAHgGQAGgFACgLIAMADQgDAOgKAHQgJAIgOgBQgNABgIgGg");
	this.shape_15.setTransform(39.2,538.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgWAbQgGgFAAgHQABgFACgEQACgDADgDIAHgCIAKgCQAMgCAFgCIAAgCQAAgHgCgCQgEgEgIAAQgGAAgFADQgDADgBAGIgLgBQABgHAEgEQADgEAGgCQAGgCAHAAQAIAAAFABQAFACACADQADADABAEIAAAKIAAANIABATQABADACAEIgLAAIgDgHQgGAFgFACQgEACgGAAQgLAAgFgGgAgCAEQgGAAgDACQgDABgBACQgBACAAAEQgBADAEAEQADACAGAAQAFAAAFgCQAEgDADgFQACgEgBgGIAAgEIgQAEg");
	this.shape_16.setTransform(69.4,524.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgEAfIgYg9IAMAAIANAkIADAMIAEgMIAOgkIALAAIgYA9g");
	this.shape_17.setTransform(63.1,524.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgEArIAAhVIAJAAIAABVg");
	this.shape_18.setTransform(58.7,523.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgEArIAAg9IAJAAIAAA9gAgEgeIAAgMIAJAAIAAAMg");
	this.shape_19.setTransform(56.1,523.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgQApQgIgEgFgGQgEgHAAgIIAKgBQABAGADAEQADAEAGADQAFACAHABQAGAAAFgCQAFgDADgDQACgEAAgEQAAgDgCgEQgDgDgFgBIgOgFQgMgDgFgBQgGgDgDgFQgDgFAAgFQAAgHAEgGQADgFAHgEQAHgDAJAAQAJAAAHADQAHAEAEAGQAEAFAAAJIgKAAQgBgIgFgEQgFgEgKgBQgKAAgEAFQgFADAAAGQAAAEADADQAEADAMADQAOADAFADQAIACADAGQAEAFAAAGQAAAIgEAFQgEAHgHADQgIADgJABQgKgBgIgDg");
	this.shape_20.setTransform(50.8,523.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgTAnQgJgGgFgLQgEgKAAgMQAAgNAFgKQAFgKAJgFQAKgFAKgBQAOABAIAGQAJAHADAMIgKACQgEgJgFgEQgGgFgJAAQgIABgHAEQgHAFgDAIQgDAIAAAIQABAKADAIQADAJAHADQAHAFAGAAQAKgBAHgFQAGgGACgKIAMADQgDAOgKAHQgJAHgOABQgNgBgIgFg");
	this.shape_21.setTransform(39.2,523.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#424242").s().p("AgyC8IgggqIAAguIATgEQAIgBADgKQADgIAAgOIAAhFIg4hsQgGgLgGgGQgFgGgHgCIgQgCIAAgtID7AAIAoAwIAAAlIgRADQgJABgJAFQgKAFgIANIghA7IAAB6IAhAqIAAAngAiIiVIANACQAIABAFAJIANAXIA5BsIAABHQAAASgEAKQgEAKgJACIgQADIAAAdIB4AAIAAgdIgQgDQgJgCgEgKQgEgKAAgSIAAhcIA4hlIAHgNQAEgEAFgCIARgCIAAgcIhjAAIAAAcIAPACQAHACACAGQABAHgGAJIgdA4Ighg5QgEgKACgFQACgGAIgCIAQgCIAAgcIh5AAgAgUAoQgDgVgHgUQAHgIADgFQADgGABgFQgHgFgHABQgGAAgEAEIgvhaQgIgQgIgMQgIgMgJgCIgIgBIAAgLIBoAAIAAALIgOACQgKACgDAIQgEAJAHAOIAkBBQACAEAEAAQACAAACgEIAkhCQAGgNgDgHQgDgKgLgBIgLgCIAAgMIBSAAIAAALIgKACQgHACgFAFQgFAHgGAKIg7BrQgDgDgEgBQgFABgDADQABAFAFAGQADAGAGAHQgFAUgEAVQgEAVgCAVIgHgqgAgOgaIgGgTQgCgKAAgIQgNgNgNgSQgNgRgLgSIAJAZIAIAaQAEAMABAHQAKAJAJAHQAHAIAIAJIACAAIAAAAg");
	this.shape_22.setTransform(272.7,39.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#424242").s().p("AgyCrQgegSgRgnQgSgogBhBIAAh1QAAgRgEgHQgFgHgHAAIgQgDIAAguICKAAIAJALIAAgLIBxAAIAlAxIAAAnIgQADQgHAAgFAJQgFAJAAAUIAACOQAAAlgOAYQgOAXgXALQgXALgdAAQgiAAgdgSgAiLiXIAQADQAHACAFAKQAEAKAAASIAAB1QgBAsAJAcQAJAdAVAOQAWAOAnAAQAZAAASgKQASgLAJgaQAJgaAAgvIAAh+QAAgPADgMQADgLAKgCIAQgDIAAgcIhgAAIAAAcIAPADQAKACAEALQAEAMgBAPIAACHQAAAfgGARQgFASgKAGQgKAHgMAAQgUAAgKgLQgKgLgEgYQgDgYAAgmIAAhqQAAgSAEgKQAFgLAHgBIAQgDIAAgcIh4AAgAAMhlQgKACgDAKQgFAJABASIAABaQAAAZACANQADAMAEAEQAFAEAGgBQAGAAAFgPQAEgPAAgdIAAh/gAhWAcIgJgfQAFgGAEgGQAFgHABgFQgGgDgFAAQgFAAgCADIAAhRQAAgTgDgKQgDgLgFgEQgEgFgFgBIgNgCIAAgLIBoAAIAAALIgNACQgFABgEAFQgFAEgDALQgDAKAAATIAABRQgBgDgGAAQgFAAgGADIAGALQAEAHAGAGQgGALgDAUQgDATACAfIgOgygAhWhXQgEAPgFAJQAFAGAEAIQAEAIACANIACAAQACgNAEgIQAEgIAGgGQgGgJgEgPQgEgQgDgcQgCAcgFAQgAA3geQgEAAgDADIAAhRQAAgVgFgMQgFgNgQgEIgGgCIAAgLIBPAAIAAALIgIACQgQAEgFAMQgFANABAVIAABRQgDgDgEAAg");
	this.shape_23.setTransform(244.2,39.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#424242").s().p("AhGCnQghgWgUgoQgUgogBgzIAAhSQABgjAOgcQAPgbAZgQQAYgPAfAAQANAAALACQAKABAIAEIAMAHQAFACADAAQACABABgFIABgKIAuAAIAqAvIAACNIAZAbIAAA4IgSAAQgGgBgEAEQgFAFAAAIIAABYIgdAAIgHgIQgEgCgFgBIgKACIgMAEQgKAEgLACQgLACgKAAQgngBgigXgAhXilQgXARgNAZQgMAaAAAdIAABSQAAAXAGAXQAGAWANASQAMASAUALQAUAKAcAAQAMABALgCQAKgBAGgCIALgGQAFgBAEAAQAEgBADADIAEAHIAbAAIAAhQQAAgLADgHQADgHAJgBIARAAIAAgkIhmAAIAAAkIAHAAQAIAAAFAHQAFAGAAAOQAAAUgGALQgHALgKAEQgKAEgLAAQgQgBgKgLQgKgMgFgPQgEgPAAgPIAAiEQAAgOACgNQADgMAIgJQAIgIAPAAQAOABALALQAJALAHASQAGARADAVQAEAVAAASIAzAAIAAiUIgiAAQAAAFgCAGQgBAEgFABQgFAAgHgDIgMgFQgIgFgKgCQgKgDgLAAQghAAgXAQgAgJhuQgJAAgCAKQgCAKAAARIAACKQAAALAFAHQAFAHAJABQAJgBAEgIQAEgKAAgOQAAgKgGgDQgFgFgGAAIgJAAIAAg2IAlAAIgLgNQgBgigEgSQgDgTgFgGQgEgGgFAAIgBAAgAhrAjIgKgkIAJgNIAGgLQgHgDgGgBQgGABgFADIAAgkQAAgeALgZQAMgaAVgPQAWgPAdgBQALABAJADQAKACAGADQAHAFAHACQAIADAIAAQAGAAAEgFQAEgFAAgGIAQAAIAACDIghAAQgCgggHgaQgHgbgOgRQgNgQgUgBQgTABgKAJQgKAJgDAPQgDAPAAAQIAABEQgLgHgNAHIAGALIAJANQgEAOgCAVQgCAVgBAZIgNgtgAhrheIgKAhQAFAGAEAHQAEAJACANIACAAQACgNAEgJQAEgHAFgGQgHgPAAgQQgBgQADgVQgKASgHARg");
	this.shape_24.setTransform(216,39.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#424242").s().p("AhdC8IgggqIAAguIAUgEQAHgBADgKQADgIAAgOIAAipQAAgRgFgHQgEgHgIgBIgQgDIAAgtIDUAAIAnAzIAAB2Ig1AAIghgsIAAgSQAAgIgDgEQgCgEgGgBQgGABgDAFQgDAFAAAHIABAMIAsA7IAAAVIAZAAIAnA0IAAB6gAh0iVIAQACQAIACAEALQAEAKAAASIAACrQAAASgDAKQgEALgJABIgQADIAAAdIDEAAIAAhyIggAAIAAAZQAAAPgDANQgEANgJAHQgKAIgRAAQgSAAgHgJQgIgKABgPIAAhRIAwAAIAAgkIgwAAIAAhBQgBgQAIgKQAHgIASgBQASAAAMAPQANAPAAAcIAAAUIAgAAIAAhsIjEAAgAARBJQAAAGACAFQABAEAEABQAFAAAFgLQAFgJABgWIAAgIIgXAAgAg+AdQgEgTgGgLQAGgGAEgHIAGgLQgFgDgFgBQgFABgEADIAAhRQAAgTgDgKQgDgLgEgEQgFgFgEgBIgNgCIAAgLICyAAIAABcIgOAAIAAgMQAAgagIgPQgJgOgMgGQgMgFgLAAQgQABgJAFQgJAHgEAKQgEAKABAKIAABKIAxAAIAAANQgJgDgIgBQgJABgIADQgIgDgIgBQgJABgJADIAHALQAEAHAFAGQgFALgEATQgFATgCAgQgDgggEgTgAg+hVQgEAQgGAIQAGAGAEAHQAEAJACANIABAAQACgNAFgJQADgHAGgGQgGgIgEgQQgEgQgCgcQgDAcgEAQg");
	this.shape_25.setTransform(178,39.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#424242").s().p("AhkC8IgggqIAAguIAUgEQAHgBADgKQADgIAAgOIAAipQAAgRgFgHQgEgHgIgBIgQgDIAAgtICKAAIAlAwIAAAoIgQACQgHABgFAJQgFAJAAAUIAAB8QAAAKAGAEQAGAEAGgBQAIAAAFgJQAGgHAAgOIAAgcIAwAAIAmAyIAABwgAh7iVIAQACQAIACAEALQAEAKAAASIAACrQAAASgDAKQgEAKgJACIgQADIAAAdIDSAAIAAhnIgfAAIAAAcQAAARgLAJQgLAJgaAAQgRAAgJgFQgKgFgDgLQgEgKABgNIAAifQAAgSAEgKQAEgLAIgCIAQgCIAAgcIh5AAgAhFAdQgEgTgGgLQAGgGAEgHIAGgLQgFgDgFgBQgFABgEADIAAhRQAAgTgDgKQgDgLgEgEQgFgFgEgBIgNgCIAAgLIBnAAIAAALIgNACQgEABgFAFQgEAEgDALQgDAKAAATIAABRQgEgDgFgBQgFABgFADIAHALQAEAHAFAGQgFALgEATQgFATgCAgQgDgggEgTgAhFhVQgEAQgGAIQAGAGAEAHQAEAJACANIABAAQACgNAFgJQAEgHAFgGQgFgIgEgQQgFgQgCgcQgDAcgEAQg");
	this.shape_26.setTransform(151.5,39.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#424242").s().p("AAYC8IgLgMIAAAMIiLAAIgggqIAAguIAUgEQAHgBADgKQADgIAAgOIAAipQAAgRgFgHQgEgHgIgBIgQgDIAAgtIEUAAIAlAwIAAAoIgUACQgKABgLAHQgLAFgMAPIgpA0IBRB7IAcAdIAAA0gAAABMIAEALQACAFAAAEQAAAEgCADQgCACgCACIgLABIAAAdIB/AAIAAgdIgSgDQgKgBgJgMQgKgLgJgQIg8hkIA9hQIATgWQAHgJAFgBIARgCIAAgcIh4AAIAAAcIALABIAJAEQADABABACIgCAFIgCAEIg+BRIgDADIgEACIAAg8QAAgSAEgKQAEgLAIgCIAQgCIAAgcIh5AAIAAAcIAQACQAIACAEALQAEAKAAASIAACrQAAASgDAKQgEAKgJACIgQADIAAAdIB5AAIAAgdIgQgDQgJgCgEgKQgDgKAAgSIAAgZIAVgcgAAEAoQgNgSgOgMQgCgKgFgHQgFgKgIgIQgDgDgFgBQgGABgGADQgGgDgGgBQgGABgHADIAHALQAEAHAFAGQgFALgEATQgFAUgCAfQgDgfgEgUQgEgTgGgLQAGgGAEgHIAGgLQgFgDgFgBQgFABgEADIAAhRQAAgTgDgKQgDgLgEgEQgFgFgEgBIgNgCIAAgLIBnAAIAAALIgNACQgEABgFAFQgEAEgDALQgDAKAAATIAABHQAIAAAFgDQAGgCAEgHIA/hSIADgFQACgEAAgFQAAgGgEgDQgEgEgHgBIgJgBIAAgLIBmAAIAAALIgNACQgGACgJAKIgUAZIhIBeQgEgDgFgBQgFABgHADIAWAMQAKAGAJADQAEAQAIAUIAWAwIgegogAAChYQgPASgPAJIgHARIgIASIACAAIAVgRIAVgSQABgHAGgLIANgZIAOgZQgRAXgQASgAhfhVQgEAQgGAIQAGAGAEAHQAEAJACANIABAAQACgNAFgJQADgHAGgGQgGgIgEgQQgEgQgCgcQgDAcgEAQg");
	this.shape_27.setTransform(122.2,39.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#424242").s().p("AAGC+QgjAAgggWQgggWgTgnQgUgogBg1IAAhSQABgiAPgcQAPgbAYgQQAZgQAegBQAMAAALADQAJACAJAEIANAGIAIACQABAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBIABgLIAuAAIAqAwIAACfIhEAAIgmgpQgBgqgHgXQgGgXgIAAQgIABgDAKQgDAKAAAQIAACKQAAALAEAIQADAHAGAAQAKAAAGgRQAGgRABghIBDAAIAqAvQgGAxgTAaQgTAagbAJQgaAKgcAAIgDgBgAg/irQgTAKgOARQgNAQgHAUQgIAUAAAUIAABSQAAAXAGAWQAGAXANASQANARAVALQAVALAdAAQAjAAAXgQQAWgPAKgYQALgZgBgbIgzAAQAAApgNARQgNASgVgBQgWgBgLgSQgKgTAAgeIAAiEQgBgPADgMQADgNAIgIQAIgIAPAAQAOABAKALQAKALAHASQAGARAEAVQADAUAAATIAzAAIAAiUIgiAAQAAAJgCAEQgCADgEAAQgEAAgHgDIgNgGQgJgEgKgDQgJgCgLAAQgYAAgTAKgAhjAbQgFgTgCgSQAFgGAEgHIAGgLQgHgDgGAAQgHAAgEADIAAgcQAAgcAMgZQAMgZAWgQQAVgQAcgBQALABAJACIAQAGIAQAHQAIADAHAAQAGAAADgEQAEgEAAgIIAQAAIAACDIghAAQgCgggHgbQgIgagNgRQgNgQgUgBQgTABgKAJQgKAJgDAPQgEAOABARIAAA7QgFgDgGAAQgHAAgGADIAGALIAJANQgFALgEAUQgDATADAfQgLgZgFgTgAhgheQgHASgDAOQAFAGAEAHQAFAGABAGIACAAQABgGAEgGQAEgHAGgGQgFgOgBgQQgBgRACgUQgKARgHASg");
	this.shape_28.setTransform(92.4,39.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#424242").s().p("Ag3C8IgggqIAAguIAUgEQAHgBADgKQADgIAAgOIAAipQAAgRgFgHQgEgHgIgBIgQgDIAAgtICKAAIAlAwIAAAoIgQACQgHABgFAJQgFAJAAAUIAACkIAhAqIAAAngAhOiVIAQACQAIACAEALQAEAKAAASIAACrQAAASgDAKQgEAKgJACIgQADIAAAdIB4AAIAAgdIgQgDQgJgCgEgKQgDgKAAgSIAAirQAAgSAEgKQAEgLAIgCIAQgCIAAgcIh4AAgAgYAdQgEgTgGgLQAGgGAEgHIAGgLQgFgDgFgBQgFABgEADIAAhRQAAgTgDgKQgDgLgEgEQgFgFgEgBIgNgCIAAgLIBmAAIAAALIgNACQgEABgFAFQgEAEgDALQgDAKAAATIAABRQgDgDgFgBQgFABgFADIAHALQAEAHAFAGQgFALgEATQgFATgCAgQgDgggEgTgAgYhVQgEAQgGAIQAGAGAEAHQAEAJACANIABAAQACgNAFgJQAEgHAFgGQgFgIgEgQQgFgQgCgcQgDAcgEAQg");
	this.shape_29.setTransform(69.4,39.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#424242").s().p("AhxC8IgggqIAAguIAUgEQAHgBADgKQADgIAAgOIAAipQAAgRgFgHQgEgHgIgBIgQgDIAAgtICaAAQAeAAAZAMQAZAOASAUQASAVAKAYQAKAZABAWQgBAjgPAWQgOAXgZAKQgYALgeAAIgnAAIAAA2IAgAqIAAAngAiIiVIAQACQAIACAEALQAEAKAAASIAACrQAAASgDAKQgEAKgJACIgQADIAAAdIB5AAIAAgdIgQgDQgJgBgEgLQgEgKABgSIAAhBIAvAAQAcAAAWgIQAXgKANgSQANgTAAgeQAAgwgYgXQgYgWgvABIiMAAgAhSAdQgEgTgGgLQAGgGAEgHIAFgLQgKgHgIAHIAAhRQAAgTgDgKQgDgLgEgEQgFgFgEgBIgNgCIAAgLICDAAQAaAAATAIQAUAHAKAUQALASAAAgQAAAUgHAOQgIAQgLAIQgFgDgEAAQgFABgJADQgHgDgHgBQgHABgHADQgIgDgGgBQgIABgHADQgHgDgIgBQgIABgIADQgHgDgHgBQgHABgHADIAGALQAEAHAGAGQgGALgEATQgEATgDAgQgCgggEgTgAA+hVQgDARgIAHQACAIgDAJQgCAIgIAKIACAAIATgRIASgSQAAgNgEgQQgFgQgJgXQAFAbgEARgAhThVQgEAQgFAIQAFAGAEAHQAEAJACANIACAAQACgNAEgJQAEgHAFgGQgFgIgEgQQgFgQgCgcQgDAcgEAQgAgviGQgJAIAAAWIAABBIA8AAQAUAAALgOQAMgPAAgVQAAgagNgOQgMgNgTAAIgZAAIgCgBQgOAAgJAJgAgvgwIAAg4QAAgSAGgGQAHgGALAAIAbAAQANAAAKALQALAKAAAYQAAASgLALQgKAMgNAAgAABhPQgDAEAAAHIAAAOIAGAAQAJgBAGgGQAHgIAAgGQAAgEgCgCQgCgCgEAAIgJAAQgFAAgDAEg");
	this.shape_30.setTransform(47.6,39.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(1,1,1).p("AAqzEQAAAJgDAHQgDAGgEAAQgFAAgDgGQgDgHAAgJQAAgKADgGQADgFAFAAQAEAAADAFQADAGAAAKgAEMwsQAAALgEAIQgEAJgGAAQgGAAgEgJQgEgIAAgLQAAgMAEgJQAEgIAGAAQAGAAAEAIQAEAJAAAMgACIrEQAAAMgEAHQgEAIgFAAQgGAAgEgIQgDgHAAgMQAAgKADgJQAEgIAGAAQAFAAAEAIQAEAJAAAKgAEio/QAAAJgEAHQgDAHgFAAQgEAAgEgHQgDgHAAgJQAAgKADgHQAEgHAEAAQAFAAADAHQAEAHAAAKgAGfloQAAAIgCAGQgDAFgEAAQgEAAgCgFQgDgGAAgIQAAgHADgGQACgFAEAAQAEAAADAFQACAGAAAHgAgHvrQAAAJgEAGQgCAHgFAAQgEAAgDgHQgEgGAAgJQAAgJAEgGQADgHAEAAQAFAAACAHQAEAGAAAJgAgin7QAAAKgEAGQgDAHgFAAQgEAAgEgHQgDgGAAgKQAAgKADgHQAEgHAEAAQAFAAADAHQAEAHAAAKgAjOopQAAAGgCAFQgDAEgDAAQgDAAgCgEQgCgFAAgGQAAgHACgEQACgEADAAQADAAADAEQACAEAAAHgAkcBXQAAAKgEAIQgEAHgFAAQgFAAgEgHQgEgIAAgKQAAgLAEgIQAEgIAFAAQAFAAAEAIQAEAIAAALgAhYHUQAAALgEAIQgEAIgGAAQgFAAgEgIQgEgIAAgLQAAgLAEgIQAEgIAFAAQAGAAAEAIQAEAIAAALgAkbJFQAAAHgCAGQgDAFgEAAQgDAAgDgFQgDgGAAgHQAAgIADgGQADgFADAAQAEAAADAFQACAGAAAIgAGgEtQAAAMgEAIQgEAJgGAAQgFAAgEgJQgEgIAAgMQAAgLAEgJQAEgIAFAAQAGAAAEAIQAEAJAAALgAC+GZQAAALgEAIQgEAIgGAAQgFAAgEgIQgEgIAAgLQAAgMAEgIQAEgIAFAAQAGAAAEAIQAEAIAAAMgABeKmQAAAMgEAJQgEAJgGAAQgGAAgEgJQgFgJAAgMQAAgMAFgIQAEgJAGAAQAGAAAEAJQAEAIAAAMgAFwLgQAAAIgDAGQgDAFgEAAQgEAAgDgFQgCgGAAgIQAAgJACgFQADgFAEAAQAEAAADAFQADAFAAAJgAHgE4QgQIlgLDwQgLDwiNChQiNCik9iMQk+iMgavAQgZu/BBoZQBCoaHJAXQHKAWgMKYQgMKYgQIlgADASWQAAALgEAIQgEAIgGAAQgFAAgEgIQgEgIAAgLQAAgMAEgIQAEgIAFAAQAGAAAEAIQAEAIAAAMgAhUSTQAAAIgDAGQgDAGgEAAQgEAAgDgGQgDgGAAgIQAAgIADgGQADgGAEAAQAEAAADAGQADAGAAAIg");
	this.shape_31.setTransform(236.5,312.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#33CC33").s().p("AidX0Qk+iMgavAQgZu/BBoZQBCoaHJAXQHKAWgMKYQgMKYgQIlQgQIlgLDwQgLDwiNChQhMBXh+AAQhsAAiUhBgACpSCQgEAIAAAMQAAALAEAIQAEAIAFAAQAGAAAEgIQAEgIAAgLQAAgMgEgIQgEgIgGAAQgFAAgEAIgAhlSFQgDAGAAAIQAAAIADAGQADAGAEAAQAEAAADgGQADgGAAgIQAAgIgDgGQgDgGgEAAQgEAAgDAGgAFfLSQgCAFAAAJQAAAIACAGQADAFAEAAQAEAAADgFQADgGAAgIQAAgJgDgFQgDgFgEAAQgEAAgDAFgABGKSQgFAIAAAMQAAAMAFAJQAEAJAGAAQAGAAAEgJQAEgJAAgMQAAgMgEgIQgEgJgGAAQgGAAgEAJgAkqI3QgDAGAAAIQAAAHADAGQADAFADAAQAEAAADgFQACgGAAgHQAAgIgCgGQgDgFgEAAQgDAAgDAFgAhvHBQgEAIAAALQAAALAEAIQAEAIAFAAQAGAAAEgIQAEgIAAgLQAAgLgEgIQgEgIgGAAQgFAAgEAIgACnGFQgEAIAAAMQAAALAEAIQAEAIAFAAQAGAAAEgIQAEgIAAgLQAAgMgEgIQgEgIgGAAQgFAAgEAIgAGJEZQgEAJAAALQAAAMAEAIQAEAJAFAAQAGAAAEgJQAEgIAAgMQAAgLgEgJQgEgIgGAAQgFAAgEAIgAkyBEQgEAIAAALQAAAKAEAIQAEAHAFAAQAFAAAEgHQAEgIAAgKQAAgLgEgIQgEgIgFAAQgFAAgEAIgAGQl1QgDAGAAAHQAAAIADAGQACAFAEAAQAEAAADgFQACgGAAgIQAAgHgCgGQgDgFgEAAQgEAAgCAFgAg2oMQgDAHAAAKQAAAKADAGQAEAHAEAAQAFAAADgHQAEgGAAgKQAAgKgEgHQgDgHgFAAQgEAAgEAHgAjbo0QgCAEAAAHQAAAGACAFQACAEADAAQADAAADgEQACgFAAgGQAAgHgCgEQgDgEgDAAQgDAAgCAEgAEOpQQgDAHAAAKQAAAJADAHQAEAHAEAAQAFAAADgHQAEgHAAgJQAAgKgEgHQgDgHgFAAQgEAAgEAHgABxrXQgDAJAAAKQAAAMADAHQAEAIAGAAQAFAAAEgIQAEgHAAgMQAAgKgEgJQgEgIgFAAQgGAAgEAIgAgZv6QgEAGAAAJQAAAJAEAGQADAHAEAAQAFAAACgHQAEgGAAgJQAAgJgEgGQgCgHgFAAQgEAAgDAHgAD0xBQgEAJAAAMQAAALAEAIQAEAJAGAAQAGAAAEgJQAEgIAAgLQAAgMgEgJQgEgIgGAAQgGAAgEAIgAAYzUQgDAGAAAKQAAAJADAHQADAGAFAAQAEAAADgGQADgHAAgJQAAgKgDgGQgDgFgEAAQgFAAgDAFg");
	this.shape_32.setTransform(236.5,312.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#663300").s().p("AB0S9QgDgIgBgLQABgMADgIQAEgHAGAAQAGAAADAHQAEAIAAAMQAAALgEAIQgDAJgGAAQgGAAgEgJgAiaS1QgDgGAAgHQAAgJADgGQAEgGADAAQAFAAACAGQADAGAAAJQAAAHgDAGQgCAHgFAAQgDAAgEgHgAErMCQgDgFAAgJQAAgIADgFQACgGAFAAQAEAAACAGQADAFAAAIQAAAJgDAFQgCAFgEAAQgFAAgCgFgAARLPQgEgIAAgNQAAgMAEgIQAEgJAHAAQAFAAAFAJQADAIAAAMQAAANgDAIQgFAJgFAAQgHAAgEgJgAleJmQgEgFAAgIQAAgIAEgFQACgFADAAQAFAAACAFQADAFgBAIQABAIgDAFQgCAFgFAAQgDAAgCgFgAikH7QgDgHAAgMQAAgLADgIQAFgIAEAAQAHAAADAIQAEAIAAALQAAAMgEAHQgDAIgHAAQgEAAgFgIgAByHAQgDgIAAgLQAAgLADgJQAEgHAFAAQAGAAAEAHQAEAJAAALQAAALgEAIQgEAJgGAAQgFAAgEgJgAFUFVQgEgHAAgMQAAgMAEgJQAEgHAFAAQAGAAAFAHQAEAJAAAMQAAAMgEAHQgFAJgGAAQgFAAgEgJgAlmB9QgFgIAAgKQAAgKAFgIQADgIAGAAQAEAAAFAIQADAIAAAKQAAAKgDAIQgFAIgEAAQgGAAgDgIgAFblGQgDgFABgIQgBgIADgFQADgGAEAAQADAAADAGQACAFABAIQgBAIgCAFQgDAGgDAAQgEAAgDgGgAhrnWQgDgHAAgJQAAgLADgHQAEgGAFAAQAEAAADAGQAEAHAAALQAAAJgEAHQgDAHgEAAQgFAAgEgHgAkQoKQgCgFAAgFQAAgHACgEQACgEAEAAQADAAACAEQACAEAAAHQAAAFgCAFQgCAEgDAAQgEAAgCgEgADaoaQgDgHgBgKQABgJADgHQADgHAFAAQAEAAAEAHQADAHAAAJQAAAKgDAHQgEAHgEAAQgFAAgDgHgAA8qcQgDgIAAgLQAAgLADgIQAEgIAGAAQAFAAAEAIQAEAIAAALQAAALgEAIQgEAIgFAAQgGAAgEgIgAhOvHQgEgGAAgKQAAgJAEgGQADgGAFAAQAEAAACAGQAEAGAAAJQAAAKgEAGQgCAGgEAAQgFAAgDgGgADAwEQgEgIgBgMQABgMAEgIQAEgIAFAAQAGAAAEAIQAFAIAAAMQAAAMgFAIQgEAIgGAAQgFAAgEgIgAgcygQgDgHAAgIQAAgKADgGQADgGAFAAQAEAAADAGQADAGAAAKQAAAIgDAHQgDAGgEAAQgFAAgDgGg");
	this.shape_33.setTransform(241.8,310.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.face1_btn},{t:this.btn_reset},{t:this.face2_btn}]}).wait(1));

	// Frame
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#000000").ss(2,1,1).p("Eg53gr7MBzvAAAMAAABX3MhzvAAAg");
	this.shape_34.setTransform(379,289);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F0FFFF").s().p("Eg53Ar8MAAAhX3MBzvAAAMAAABX3g");
	this.shape_35.setTransform(379,289);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(385.6,293.8,742.9,564.5);
// library properties:
lib.properties = {
	id: 'EA2F94B9C7C4D14D9FC9A7C1DE351D47',
	width: 756,
	height: 574,
	fps: 24,
	color: "#33CC66",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA2F94B9C7C4D14D9FC9A7C1DE351D47'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;