(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"AnimatedCard_YAsefa_atlas_", frames: [[0,1062,650,650],[0,0,1600,1060]]}
];


// symbols:



(lib._17577cd5689b307 = function() {
	this.spriteSheet = ss["AnimatedCard_YAsefa_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bigstockStackOfBooks70033240 = function() {
	this.spriteSheet = ss["AnimatedCard_YAsefa_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.BasicButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Text
	this.text = new cjs.Text("", "24px 'Arial-Black'", "#CC0000");
	this.text.textAlign = "center";
	this.text.lineHeight = 36;
	this.text.parent = this;
	this.text.setTransform(-884.8,-390.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMBTQgIgFgEgJQgEgJAAgVIAAgrIgSAAIAAgjIASAAIAAgXIAvgYIAAAvIAaAAIAAAjIgaAAIAAArQAAAIABADQADADAFAAQAGAAAJgDIAEAiQgSADgPAAQgRAAgJgEg");
	this.shape.setTransform(74.8,25.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAXA+IgXgoIgaAoIg0AAIAthAIgqg7IA4AAIATAiIAXgiIA0AAIgqA7IAuBAg");
	this.shape_1.setTransform(61.5,27.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgmA6QgPgHgJgPQgJgPAAgVQAAgcASgSQAUgSAgAAQAaAAAQAIQAPAIAIAQQAIAPAAAXIAAAGIheAAQABALAEAGQAIAIAJAAQAIAAAGgDQAEgDAFgFIAuAEQgLATgPAIQgPAIgcAAQgYAAgOgHgAgRgbQgFAGAAALIAuAAQgCgOgGgGQgGgGgKAAQgKAAgHAJg");
	this.shape_2.setTransform(46.2,27.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAgBWIg/hdIAABdIgyAAIAAirIAxAAIBABeIAAheIAyAAIAACrg");
	this.shape_3.setTransform(28.1,25.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.text}]}).wait(4));

	// Rounded
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("AnBj5IODAAQAyAAAAAyIAAGPQAAAygyAAIuDAAQgyAAAAgyIAAmPQAAgyAyAAg");
	this.shape_4.setTransform(50,25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_5.setTransform(50,25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF99").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_6.setTransform(50,25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AnBD6QgyAAAAgyIAAmPQAAgyAyAAIODAAQAyAAAAAyIAAGPQAAAygyAAg");
	this.shape_7.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_6},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_4}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).wait(1));

	// Squared
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("Anzj5IPnAAIAAHzIvnAAg");
	this.shape_8.setTransform(50,25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCCCC").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_9.setTransform(50,25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFF99").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_10.setTransform(50,25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AnzD6IAAnzIPnAAIAAHzg");
	this.shape_11.setTransform(50,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8}]}).to({state:[{t:this.shape_10},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_8}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-889.9,-392.3,990.9,443.4);


// stage content:
(lib.AnimatedCardYAsefa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.btn_name.addEventListener("click", fl_ClickFunctionName.bind(this));
		
		function fl_ClickFunctionName()
		this.btn_name.addEventListener("click", fl_ClickFunctionName.bind(this));
		this.play();
		function fl_ClickFunctionName()
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(30));

	// Label
	this.instance = new lib.BasicButton();
	this.instance.parent = this;
	this.instance.setTransform(773,540.9);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.BasicButton(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0099FF").s().p("AiiDpQgMgKAAgMQAAgKAJgIQAJgHAQAAQAMAAAVAEQAVAFAIABQAWAAAYgSQAggZATgjQATghAAgjQAAgxgOhDQgOhFgZgkQgOgSgOAAQgRAAghAWIgLgQIAagRQAngaAPgIQAJgEAHAAQAHAAAGAIQAfAnAVBCQAVBDAAA8IgBAaQA8htAAhAQAAgNgGgXQgHgZABgKQAAgKAGgHQAGgGAKgBQANAAAHAKQAIAJAAASQAAAtgVBEQgVBDgsBOQgsBOglAmQgkAlgiARQgiAQgfAAQgYgBgLgHg");
	this.shape.setTransform(588.4,510.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0099FF").s().p("AAJCaQgEgEAAgIQAAgFADgJIAOgwQgeAkgpAaQgaAQgVAAQgVAAgLgOQgPgUAAgfQAAglAVguQATgtAiglQAhglAkgSQAdgNAsAAIAXABIAIgNIAYgFIgaBZQgRA1gOBEQgHAmgBAKQABALAIAAQAGAAAMgHQAWgNAUgTIALANQgoAlgLAIQgXAPgUAIQgNAEgNAAQgJAAgFgEgAgahVQgXARgUAuQgUAsgBAtQAAAYAJAKQAIALANAAQAYAAAcgaQAbgbANgxIAdhtQgTgDgNAAQgfAAgYARg");
	this.shape_1.setTransform(562.4,501.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0099FF").s().p("AhDDTQgmgDgiAAIgwABIAIgRQAhgCAHgEQAIgEAGgJQAKgQASg2IAYhcIAchyQACgIAAgGQAAgGgDgDQgEgEgGAAIgKACIAEgQQAmgDAzgMQgPAngMAyIgWBhQgZBqgfA2QAeAGAXAAQA8AAAugaQAugZAbgyQAbgxAAg7QAAhPgugvQgugwhKAAQg8AAg4AeQg3AdggAxQggAwAAAuQAAAtAnAUQALAHAEAEQADAFAAAHQAAAIgHAHQgGAGgIAAQgTAAgSgZQgYgiAAgkQAAg8Akg4QAkg5BBghQBAgiBOABQBhAAA5A0QA6A0AABOQAABIgoA9QgoA8g5AaQg5Aag3AAQgTABgtgEg");
	this.shape_2.setTransform(521.9,495);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFF00").s().p("AhgCIQgVgSAAgZQAAgMAIgIQAIgIALAAQAKAAAHAHQAHAGAAAJIAAAJIgBAIQAAALAKAIQAKAIAQAAQATAAANgGQAPgHAIgNQAIgNAAgNQAAgNgIgMQgHgNgagdQgkgoAAglQAAgjAcgaQAagZArAAQAgAAARAMQARAMAAAQQAAAJgHAHQgIAHgKAAQgHAAgFgDQgEgDgKgMQgRgXgRAAQgOAAgLALQgKAMAAAQQAAAPAGANQAHAOAcAeQAnAoAAAlQAAAlgfAdQggAbgxAAQgqAAgUgQg");
	this.shape_3.setTransform(638.3,409.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFF00").s().p("AhuCcIAYheQAShEANg/IAEgTQAAgJgIAAQgFAAgLAIQgLAGgdAdIgLgNQAigjAigTQAhgSASAAQAHAAACAEQAEACAAAEQAAAGgFATIgOA/QAig4AtgoQAWgTAOAAQALABAHAGQAHAHAAAJQAAAJgHAIQgHAGgbAJQgaAJgQAMQgRANgTAZQgTAZgIASQgHASgQBGIgQBDg");
	this.shape_4.setTransform(618.9,408.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF00").s().p("AhfCIQgOgRAAglQAAhLAuhKQAzhVBHAAQAZAAANANQANAMAAAWQAAAXgQAWQgQAWgoAYQgVAMhCAdQgDATAAARQAAAZAIAKQAIAKAPAAQAPAAAQgIQAXgLAtghIALAPQhWBSg8AAQgZAAgNgRgAAFhxQgPANgMAbQgQAmgGAoQA3gZAdgdQATgUAAgUQAAgQgIgIQgIgJgMAAQgNAAgNAJg");
	this.shape_5.setTransform(592.7,409.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFF00").s().p("AAUDzQgHgKAAgVQAAgNAGgbQAFgbAbhZQAMgsABgHQgBgKgMAAQgOgBgXAPQgdAUgZAfQgOAVgKAoIgcB6Ig0AAQARg9AJgoIA0jgQAOg+AXgiQAXgiAkgUQAlgUAkAAQAQAAAIAHQAJAIAAALQAAAKgJAHQgIAHgPAAIgWgBQgegFgMAAQgQAAgKAOQgKANgKAwIgnCsQAqgqAwgeQAdgTARABQAOgBAHAJQAIAHAAAPQAAAMgCALQgFAVgRA2QgXBLgEATQgEASAAAOQAAAGACACQACADAEAAQAIABAXgVIAggaIAJAOQggAjgjAVQgWAPgQAAQgMAAgIgKg");
	this.shape_6.setTransform(565,399.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFF00").s().p("AhNC1QgHgJAAgWQAAgaANg0IAkiKIg5AAIAGgZIA5AAIAUhOIA3gUIgaBiIBJAAIgFAZIhJAAIgeB1QgPA0AAAWQAAAJAFAEQAEAEAHAAQAKAAAWgNQAegRAagWIAOARQhNA5gZAOQgaANgQgBQgNAAgIgJg");
	this.shape_7.setTransform(538.1,406);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFF00").s().p("AAJCaQgEgEAAgIQAAgFADgJIAOgwQgeAkgpAaQgaAQgWAAQgTAAgMgOQgPgUAAgfQAAglAVguQATgtAhglQAiglAkgSQAdgNAsAAQAMAAALABIAJgNIAWgFIgZBZQgRA1gOBEQgHAmgBAKQABALAIAAQAGAAAMgHQAWgNAUgTIALANQgoAlgLAIQgWAPgVAIQgNAEgNAAQgJAAgFgEgAgahVQgXARgUAuQgVAsAAAtQAAAYAJAKQAIALANAAQAYAAAcgaQAbgbANgxIAdhtQgTgDgNAAQgfAAgYARg");
	this.shape_8.setTransform(510.6,409.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFF00").s().p("AioDDQAfgHALgIQAJgHAFgLQAMgVAehwIA2jRQgwACgjATQgjAUgVAhQgWAhAAAjQABANADAPQACAHAIAOQALAUAAAGQAAAIgHAGQgFAFgKAAQgOAAgJgPQgMgTAAgkQAAhGA3g8QA4g7BaAAICGAAQAWAAAbgDIAjgHQgSBKgDAUIgTAAQAFgdAAgJQAAgMgIgFQgIgGgWAAIgWAAIgIAAIhGAAIgLApQgUBEgJAsIBEAAQAZAAAIgFQAHgFAFgUIATAAQgLAsgIAwIgTAAIACgYQAAgJgJgCQgFgDgVgBIhCAAQgKAwgRA4QgQA5gMAfQAbAFAXgBQANAAAOgCIgFAUIgSACIgxgDQgZgCgQAAQgjABgmAGg");
	this.shape_9.setTransform(478.2,403.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#009900").s().p("AiiDoQgMgIAAgNQAAgKAJgIQAKgHAPAAQAMAAAVAFQAWAEAHAAQAWABAYgTQAggYATgiQATgjAAgiQAAgwgOhEQgPhFgZgkQgMgSgPgBQgSAAgfAYIgMgRIAagSQAmgaAQgHQAIgEAIAAQAIAAAFAJQAfAnAVBCQAVBCAAA9IAAAZQA7htAAhBQAAgNgGgWQgHgYABgLQgBgKAIgHQAGgGAJAAQAMAAAJAJQAHAKAAARQAAAugVBDQgUBEgtBNQgsBOglAlQgkAmgiAQQgjARgegBQgYABgLgJg");
	this.shape_10.setTransform(617.4,249.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#009900").s().p("AhcDqQgiAAg1AFIAFgSQAagDANgMQALgMAHgeIBAkKQAShKAAgJQABgJgKAAQgPAAgrAtIgPgOQAggmAggSQAggTAWAAQAJAAAGAFQAEAEAAAJQAAAKgCALIgPAyQA3g2ATgMQAhgWAbAAQATAAAMARQAMARAAAiQAABVg1BNQg1BMhBAAQgYAAgZgOIgeB0QgDAKABAHQAAANAJAGQAQAJAvAFIgEASQg4gFggAAgAA7itQggAZgSAaQgLASgKAtIgTBLQAcAcAcAAQAqAAAfhBQAghBAAg/QAAgUgIgKQgKgLgPAAQgQAAgWARg");
	this.shape_11.setTransform(587.3,249.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#009900").s().p("AhdDqQghAAg1AFIAEgSQAbgDANgMQALgMAIgeIBAkKQARhKABgJQAAgJgJAAQgQAAgsAtIgNgOQAfgmAhgSQAfgTAWAAQAJAAAGAFQAEAEAAAJQAAAKgCALIgPAyQA2g2AUgMQAhgWAbAAQASAAANARQAMARAAAiQAABVg1BNQg1BMhAAAQgYAAgagOIgeB0QgCAKAAAHQgBANAKAGQAQAJAvAFIgEASQg4gFghAAgAA7itQggAZgRAaQgMASgLAtIgSBLQAbAcAdAAQApAAAhhBQAfhBAAg/QAAgUgJgKQgIgLgQAAQgRAAgVARg");
	this.shape_12.setTransform(555.6,249.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#009900").s().p("AAJCaQgEgEAAgIQAAgFADgJIAOgwQgdAkgqAaQgaAQgWAAQgTAAgLgOQgPgUgBgfQABglATguQAVgtAgglQAiglAkgSQAcgNAtAAQALAAAMABIAJgNIAWgFIgaBZQgQA1gOBEQgHAmgBAKQABALAIAAQAGAAAMgHQAWgNAUgTIALANQgnAlgMAIQgWAPgVAIQgNAEgNAAQgJAAgFgEgAgahVQgXARgUAuQgVAsAAAtQAAAYAJAKQAIALANAAQAYAAAcgaQAbgbANgxIAdhtQgTgDgNAAQgfAAgYARg");
	this.shape_13.setTransform(528,240.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#009900").s().p("AkoDjQgPgKAAgPQAAgJAGgGQAGgGAJAAQANAAAPATQAJAMAFADQAGAEAGAAQAcAAAYgtQAYgsAuiuIAjiBQhHAAgjAYQgjAXAAAdQAAAKAJAPQAJAOAAAJQAAAKgHAHQgGAGgKAAQgNAAgIgMQgJgLAAgXQAAgpAdgfQAegfA4gOQAhgGBgAAQgaAyggCDQBcgBA2gGQAehmAXgoQAXgpAegRQAcgTAkABQAfgBARAMQARANAAAOQAAAJgGAGQgGAGgKgBQgMAAgQgRQgPgRgNgBQgaABgZAwQguBXg8EYIARADQAUADAMAAQAOAAASgDIgEATQgSADgKAAQgPAAgZgDQgagCgTAAQgPAAgRAFQAPgpAShIIAbhpIheAEIgzADQgYBegZAtQgaAtggAWQghAUgeAAQgdABgVgOg");
	this.shape_14.setTransform(492.1,233.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFF00").ss(15,1,1).p("AVkuDMAisAzPEA4aglLMgy8Af4IxEouMgszgW6ArmuBMgspAzD");
	this.shape_15.setTransform(524,386.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#009900").ss(15,1,1).p("AAPAIIgdgP");
	this.shape_16.setTransform(161.5,149.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(1,1,1).p("Eg4Zgk7MBwzgAQMAAABKXIgKAAMhwpAAAg");
	this.shape_17.setTransform(524,386.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC0000").s().p("EA4QAlMMgisgzPMAisAzPMhwpAAAMAAAhKHMAszAW6MgszgW6MBwzgAQMgy8Af4IxEouIREIuMAy8gf4MAAABKXgEg4PAlCMAspgzDgEA4aglLg");
	this.shape_18.setTransform(524,386.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#009900").s().p("AiiDoQgMgJAAgLQAAgLAJgHQAJgIAQAAQAMAAAUAEQAWAGAJAAQAVgBAYgRQAggZATgjQATghAAgjQAAgwgOhEQgPhFgYgkQgNgTgPAAQgSAAgfAYIgLgRIAagRQAlgbAQgHQAIgEAIAAQAHAAAGAJQAfAmAVBCQAVBDAAA8IgBAZQA8hsAAhAQAAgNgGgXQgGgYgBgLQAAgKAIgHQAFgHALAAQALAAAIAKQAIAKAAARQAAAtgVBEQgVBDgsBNQgtBOgkAmQgkAmgiAQQgjAQgeABQgXAAgMgJg");
	this.shape_19.setTransform(180.4,706.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#009900").s().p("AhdDqQghAAg1AFIAEgSQAbgDAMgMQANgMAGgeIBBkKQAShKAAgJQgBgJgIAAQgQAAgsAtIgOgOQAhgmAggSQAfgTAWAAQAJAAAFAFQAFAEAAAJQAAAKgCALIgOAyQA1g2AUgMQAhgWAcAAQARAAANARQAMARAAAiQAABVg1BNQg1BMhAAAQgZAAgZgOIgeB0QgDAKAAAHQAAANAKAGQAPAJAwAFIgEASQg5gFggAAgAA7itQggAZgRAaQgLASgMAtIgSBLQAbAcAcAAQAqAAAghBQAghBAAg/QAAgUgJgKQgJgLgPAAQgQAAgWARg");
	this.shape_20.setTransform(150.3,706.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#009900").s().p("AhcDqQgiAAg1AFIAFgSQAagDAMgMQANgMAGgeIBAkKQAThKgBgJQAAgJgJAAQgPAAgrAtIgPgOQAhgmAfgSQAggTAWAAQAJAAAGAFQAEAEAAAJQAAAKgCALIgOAyQA2g2ATgMQAhgWAcAAQASAAAMARQAMARAAAiQAABVg1BNQg1BMhBAAQgYAAgZgOIgeB0QgCAKgBAHQAAANAKAGQAPAJAwAFIgEASQg5gFgfAAgAA7itQggAZgSAaQgLASgKAtIgTBLQAbAcAcAAQArAAAfhBQAghBAAg/QAAgUgIgKQgKgLgPAAQgRAAgVARg");
	this.shape_21.setTransform(118.6,706.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#009900").s().p("AAKCaQgFgEAAgIQAAgFADgJIAOgwQgeAkgpAaQgaAQgVAAQgVAAgLgOQgOgUAAgfQgBglAVguQATgtAiglQAhglAkgSQAcgNAtAAQALAAAMABIAIgNIAYgFIgaBZQgQA1gOBEQgIAmAAAKQAAALAJAAQAFAAANgHQAVgNAUgTIAMANQgoAlgMAIQgWAPgVAIQgNAEgNAAQgJAAgEgEgAgZhVQgYARgUAuQgUAsAAAtQgBAYAJAKQAIALANAAQAYAAAcgaQAagbANgxIAehtQgTgDgNAAQgfAAgXARg");
	this.shape_22.setTransform(91,697.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#009900").s().p("AkoDiQgPgJAAgPQAAgJAGgGQAGgGAJAAQANAAAPATQAJAMAFADQAGADAGAAQAcAAAYgsQAYgsAuiuIAjiAQhHAAgjAWQgjAYAAAdQAAAKAJAPQAJAOAAAJQAAAKgHAHQgGAGgKAAQgNAAgIgLQgJgNAAgWQAAgoAdggQAeggA4gNQAhgGBggBQgaA0ggCBQBcABA2gHQAehmAXgoQAXgoAegTQAcgSAkAAQAfAAARANQARAMAAAPQAAAIgGAGQgGAFgKAAQgMAAgQgRQgPgSgNAAQgaAAgZAxQguBXg8EYIARADQAUADAMAAQAOAAASgDIgEAUQgSACgKAAQgPAAgZgCQgagDgTAAQgPAAgRAFQAPgoAShIIAbhqIheADIgzAEQgYBegZAtQgaAtggAWQghAUgeABQgdgBgVgOg");
	this.shape_23.setTransform(55.1,690.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#009900").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_24.setTransform(323.2,128);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#009900").s().p("AhACXQgGgIAAgSQAAgVALgrIAeh0IgvAAIAEgVIAwAAIAQhAIAugSIgVBSIA8AAIgEAVIg8AAIgZBhQgNAtABARQAAAIADADQAEAEAFAAQAJAAASgLQAYgOAXgTIALAOQhAAwgVALQgVALgOAAQgKAAgHgIg");
	this.shape_25.setTransform(302.3,140);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#009900").s().p("AgxC4QgGgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgZAYIgOgJQAeggAYgOQAXgOARAAQAJAAAGAFQAEAEAAAHQAAAIgSA/QgeBoAAAVQAAAEACADQACADACAAQAIAAAnglIALAMQgoAlgSALQgSAKgLAAQgLAAgGgGgAAeiNQgFgHAAgJQAAgOAIgJQAJgJAMAAQAIAAAGAGQAHAGgBAJQABANgJAKQgKAKgKAAQgJAAgHgGg");
	this.shape_26.setTransform(286,136.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#009900").s().p("AhcCCIAUhOQAPg6AMg0IACgPQAAgIgGABQgEAAgKAFQgJAGgYAYIgJgKQAdgeAcgPQAbgPAPAAQAGgBABADQAEADAAAEIgEATIgMA1QAdguAlgiQASgQAMAAQAJABAGAFQAFAGABAHQgBAJgFAFQgGAFgXAIQgWAIgNAJQgNALgQAVQgQAVgHAPQgGAQgNA4IgNA5g");
	this.shape_27.setTransform(258,142.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#009900").s().p("AhVBrQgUgVAAgjQAAg8Ajg0QAshCBCAAQAcAAATAYQATAXAAAoQAABAgtA0QguAzgzABQgfAAgSgVgAgghEQgYAjAAA+QAAAmAPAVQAKARASgBQAXABAUgfQAagnAAg6QAAgsgMgSQgMgTgRAAQgZgBgWAlg");
	this.shape_28.setTransform(234.3,143.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#009900").s().p("AjGEUQgKgHAAgLQAAgJAHgEQAHgHAMABIASABQAVADASAAQAdAAAOgNQANgPANg1IA6jtIhFAAIAGgVIBFAAQARhKAWgkQAXgjAjgVQAkgUAgAAQASgBAJAIQAJAGAAALQAAAIgGAGQgHAGgKAAQgKAAgcgHQgOgCgIAAQgUAAgPAYQgQAYgJApIgPA+IBOAAIgFAVIhOAAIguC6QgVBVgvAsQgvArg3ABQgSAAgKgIg");
	this.shape_29.setTransform(211.7,142.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#009900").s().p("AAsD3QgZgRgVgjQgNgVgfhIQgPgjgMgSQgJgNgPgNIgdB+IgsAAIAnieQAch3AIgcQAJgbAMgSQAMgSATgOQASgOAVgIQAUgHARAAQAPAAAHAGQAIAFAAALQAAAHgHAGQgHAHgKgBQgNAAgagEQgIgCgGAAQgJAAgIAGQgIAHgGARQgHAQgLA0IgVBeQAcggAegRQAXgNAUAAQAPAAAKALQAKALAAAQQAAAgghAYQgfAYhDACQAXAKANAMQAOAMANAUQANAWATAxQAYA7AVATQAVAUAYgBQAPAAAJgGQAJgHAAgFQAAgFgCgHQgEgHAAgGQAAgGAGgGQAFgFAHAAQAIAAAGAHQAGAGAAALQAAAVgUAQQgTARgfAAQggAAgZgQgAhagJIgFAUQAoAAAYgIQAYgHAKgNQAKgOAAgPQAAgLgGgGQgGgIgHABQgcAAg4A9g");
	this.shape_30.setTransform(182.1,140.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#009900").s().p("AhcCCIAUhOQAPg6AMg0IACgPQAAgIgGABQgEAAgKAFQgJAGgYAYIgJgKQAdgeAcgPQAbgPAPAAQAGgBABADQAEADAAAEIgEATIgMA1QAdguAlgiQASgQAMAAQAJABAGAFQAFAGABAHQgBAJgFAFQgGAFgXAIQgWAIgNAJQgNALgQAVQgQAVgHAPQgGAQgNA4IgNA5g");
	this.shape_31.setTransform(157.2,142.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#009900").s().p("AhVBrQgUgVAAgjQAAg8Ajg0QAshCBCAAQAcAAATAYQATAXAAAoQAABAgtA0QguAzgzABQgfAAgSgVgAgghEQgYAjAAA+QAAAmAPAVQAKARASgBQAXABAUgfQAagnAAg6QAAgsgMgSQgMgTgRAAQgZgBgWAlg");
	this.shape_32.setTransform(133.5,143.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#009900").s().p("AACAoQgnApgJAHQgUAQgSAMQgSALgUAJQgCgRgHgmQgLg0AAgWQAAgeAPgeQAPgdAegWQg2ABgWALQgPAIAAAKQAAAEADAIQADAIAAADQAAAGgDAEQgEAEgGAAQgIAAgFgHQgGgHAAgMQAAgXAWgPQAegVBNABQANgKAHAAQAFAAAEAFQADADAAAFQAAAMgRAEIgWAsQgJATgEASQgEASAAATQAAAYAMA1QAsgdAmgyIAAgSQAAhAATgmQANgYAPAAQAJAAAGAIQAGAHAAAQQAAAMgFAQQgIAbgKAVQAABKALAqQAjgXAhgkQAYgbANgcQAMgdAAgTQAAgIgGgPQgIgQAAgIQAAgIAGgFQAGgFAHAAQAKgBAGAKQAGAJAAAYQAAA8g1BBQg0BChMAlQgJgggIhAg");
	this.shape_33.setTransform(101.3,143.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#009900").s().p("AgtA5QAagUAPgUQAIgNAAgIQAAgIgGgNQgHgOAAgJQAAgLAIgIQAHgIALAAQAMAAAJAKQAIAJAAAOQAAAQgIAUQgKATgRATQgXAagcASg");
	this.shape_34.setTransform(362.3,89);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#009900").s().p("AhQBxQgLgOABgfQgBg/Amg9QArhGA6AAQAVAAALAKQAMALgBASQABATgNASQgOATgiAUQgRAJg3AYQgCAQAAAPQAAAUAHAJQAGAIAMAAQAMAAAOgHQATgJAlgcIAKANQhIBEgyAAQgUAAgMgOgAAEheQgNALgJAWQgNAggGAhQAugUAYgZQAQgRAAgQQAAgNgGgHQgHgIgLAAQgKAAgLAIg");
	this.shape_35.setTransform(350.2,75.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#009900").s().p("AhQBxQgKgOgBgfQABg/Alg9QArhGA7AAQAVAAAKAKQAMALAAASQAAATgOASQgNATgiAUQgRAJg2AYQgDAQAAAPQAAAUAGAJQAHAIAMAAQANAAANgHQATgJAmgcIAJANQhHBEgzAAQgUAAgMgOgAAEheQgNALgJAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_36.setTransform(329.8,75.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#009900").s().p("AhcCDIAUhPQAQg5AKg0IADgRQAAgHgGAAQgEAAgKAHQgJAFgXAYIgJgKQAcgfAcgOQAcgQAPAAQAEAAADADQADACAAAEIgEAVIgMA0QAdguAmghQARgRAMABQAJAAAGAFQAGAGgBAIQABAHgGAGQgGAFgXAIQgVAIgOAKQgOAKgQAVQgPAVgGAPQgHAPgNA5IgNA6g");
	this.shape_37.setTransform(313.2,74.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#009900").s().p("AjGEVQgKgIAAgKQAAgKAHgFQAHgFAMgBIASACQAVADASAAQAdAAAOgOQANgOANg0IA6jvIhFAAIAGgVIBFAAQARhIAWgkQAXgkAjgUQAkgWAgAAQASABAJAGQAJAIAAAJQAAAJgGAGQgHAGgKAAQgKAAgcgGQgOgDgIAAQgUAAgPAYQgQAXgJApIgPA+IBOAAIgFAVIhOAAIguC6QgVBVgvAsQgvAtg3gBQgSAAgKgGg");
	this.shape_38.setTransform(290.9,74.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#009900").s().p("AhQBxQgRgPAAgUQAAgLAGgGQAHgHAJAAQAIAAAHAFQAFAGAAAIIAAAHIgBAGQAAAKAJAHQAIAHAOAAQAPgBALgFQAMgFAHgLQAHgMAAgKQgBgKgFgLQgHgLgVgYQgfghAAgfQAAgdAYgVQAWgWAjAAQAaAAAPALQAOAJAAANQAAAJgGAGQgGAFgJAAQgFAAgEgCQgEgDgIgKQgOgTgOAAQgMAAgKAJQgHAKgBANQAAANAFALQAGALAYAZQAgAiABAeQgBAfgaAYQgbAXgoAAQgjAAgRgOg");
	this.shape_39.setTransform(259.8,75.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#009900").s().p("AgwC4QgHgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgMgJQAdggAYgOQAXgOARAAQAJAAAGAFQAEAEAAAHQABAIgUA/QgdBoAAAVQAAAEABADQACADADAAQAIAAAnglIALAMQgoAlgRALQgTAKgMAAQgKAAgFgGgAAeiNQgFgHAAgJQAAgOAJgJQAIgJAMAAQAIAAAHAGQAFAGAAAJQAAANgJAKQgIAKgMAAQgJAAgGgGg");
	this.shape_40.setTransform(244,69.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#009900").s().p("Ah0C6QgXgTAAgYQAAgYASgUQANgQAsgVQAWgMASgMQgVALgNAAQgKAAgJgKQgIgKAAgRQAAg1Agg1QAgg1AsgbQAcgQAqAAIAUABIADgJIAYgGQgWBFgRBEQgOAygEAfQgDARAAAZQgBAqgIAbQgNAjghAWQghAXguAAQgogBgWgSgAghA9QgyAhgLAPQgLAQAAARQAAAQAPAOQAOANAWAAQAUAAASgKQASgJAOgTQAOgTAGgXQAEgYABgmIADgoQgUATg5AngAALiPQgTAOgOAjQgUAxAAAhQABANAHAJQAIAKAKAAQAMAAAPgLQASgLAKgQQAMgSALgpIAVhOQgOgCgLgBQgbAAgUAPg");
	this.shape_41.setTransform(207.8,82.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#009900").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_42.setTransform(184.7,75.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#009900").s().p("AgwC4QgHgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgMgJQAdggAYgOQAXgOARAAQAJAAAGAFQAEAEAAAHQABAIgUA/QgdBoAAAVQAAAEABADQACADADAAQAIAAAnglIALAMQgoAlgRALQgTAKgMAAQgKAAgFgGgAAeiNQgFgHAAgJQAAgOAJgJQAIgJALAAQAKAAAGAGQAFAGAAAJQAAANgJAKQgIAKgMAAQgJAAgGgGg");
	this.shape_43.setTransform(164.8,69.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#009900").s().p("AARDLQgHgIABgSQAAgLAEgXQAFgWAXhKQAKgkAAgHQAAgIgKAAQgMAAgTALQgZARgUAbQgNAQgHAiIgXBmIgsAAIAWhUIAri7QAMg0ATgcQATgcAegRQAfgRAeAAQAMAAAIAHQAHAGAAAJQAAAIgHAGQgHAHgNAAIgRgCQgagEgKAAQgNAAgIALQgJALgIAoIghCQQAjgjAogaQAYgPAPAAQALAAAHAHQAGAHAAAMQAAAKgDAJQgDARgOAtQgTA/gDAPQgEAQAAAMQAAAEACADQABACADAAQAIAAATgRIAagVIAIAKQgbAegcASQgUAMgNAAQgKAAgGgIg");
	this.shape_44.setTransform(143.5,67.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#009900").s().p("Ag/CXQgHgIAAgSQAAgVALgrIAeh0IgwAAIAFgVIAwAAIAQhAIAugSIgVBSIA9AAIgFAVIg9AAIgYBhQgNAtAAARQABAIADADQADAEAGAAQAJAAASgLQAZgOAWgTIALAOQhAAwgVALQgVALgNAAQgMAAgFgIg");
	this.shape_45.setTransform(121.1,72.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#009900").s().p("AhWBrQgTgUAAgkQAAg8Ajg1QAthBBAABQAdAAATAWQATAXAAApQAABAguA0QguA0gxgBQggABgTgVgAgghFQgYAkAAA9QAAAmAPAXQAKAQARAAQAYAAAUgfQAagoAAg5QAAgsgLgTQgMgTgTAAQgXABgXAjg");
	this.shape_46.setTransform(98.7,75.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#009900").s().p("Aj0C5QgOgIAAgPQAAgGAFgEQAFgGAHAAQAJAAALAKQATARAPAAQARABAQgQQAYgWAWhJQAbhYAZiHQgKAAgdAGQgdAGgTAKQgUALgKARQgLARAAATQAAAJADAKQACAHAFAJQAHAKAAAGQAAAHgFAFQgFAFgIAAQgLAAgIgLQgIgMAAgXQAAgoAUgcQAUgbAhgOQAVgJA8gIQAXgDATgFIAJAjQAKAuALAkQALAjAuB+IAShIQARhGAFgTQARg2APgaQAPgZATgLQATgLAXAAQATAAALAHQAKAIAAAKQAAAHgGAFQgFAGgHAAQgGAAgHgDIgRgGQgGgCgGAAQgOAAgKAKQgTARgWBEQgVBFgiCUIgKAsQghhKgMgeQgQgpgTg/IgghlQgGAkgVBSIgaBgQgOAngPAVQgPAWgTAJQgSAKgWAAQgcgBgRgMg");
	this.shape_47.setTransform(69.4,71);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#009900").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_48.setTransform(43.6,60.4);

	this.instance_1 = new lib._17577cd5689b307();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0,1.578,1.194);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFF00").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_49.setTransform(349.9,199.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFF00").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_50.setTransform(324.3,215.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFF00").s().p("AhWBrQgTgUAAgkQAAg8Ajg1QAthBBAABQAdAAATAWQATAXAAApQAABAgtA0QguA0gygBQggABgTgVgAghhFQgXAkAAA9QAAAmAOAXQALAQARAAQAYAAAUgfQAagoAAg5QAAgsgLgTQgMgTgTAAQgXABgYAjg");
	this.shape_51.setTransform(298.2,215.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFF00").s().p("AgxC4QgGgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgMgJQAdggAYgOQAXgOARAAQAJAAAGAFQAEAEAAAHQABAIgUA/QgdBoAAAVQAAAEABADQADADACAAQAIAAAnglIALAMQgoAlgRALQgTAKgMAAQgKAAgGgGgAAeiNQgFgHAAgJQAAgOAJgJQAIgJAMAAQAJAAAGAGQAFAGAAAJQABANgKAKQgIAKgLAAQgKAAgGgGg");
	this.shape_52.setTransform(280.3,208.8);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFF00").s().p("AhACXQgGgIAAgSQAAgVALgrIAeh0IgvAAIAEgVIAwAAIAQhAIAugSIgVBSIA9AAIgFAVIg8AAIgZBhQgNAtAAARQAAAIAEADQAEAEAFAAQAJAAASgLQAYgOAXgTIALAOQhAAwgVALQgVALgOAAQgKAAgHgIg");
	this.shape_53.setTransform(263.1,212);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFF00").s().p("AAICAQgEgDAAgHIACgMIAMgoQgYAfgjAVQgVAOgSAAQgRAAgJgNQgNgPAAgaQAAggARglQARgmAbgfQAcgfAegPQAYgLAlAAIATABIAHgLIATgEIgWBKQgNAsgMA5QgGAgAAAIQAAAJAHAAQAFAAAKgFQASgMARgPIAKALQgiAegJAHQgTAMgRAHQgLAEgLAAQgHAAgEgEgAgVhHQgUAOgQAnQgRAkAAAlQAAAVAGAIQAHAJALAAQAUAAAXgWQAXgWAKgoIAZhbQgQgEgLAAQgZAAgUAPg");
	this.shape_54.setTransform(240.1,214.7);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFF00").s().p("AhSBtQgMgSAAgcQAAguAYgwQAZgxAjgaQAbgUAiAAQAWAAALAIQALAIAAAMQAAAJgGAGQgFAFgLAAQgKAAgQgJQgRgKgLAAQgPAAgNANQgOANgNAmQgNAkAAAmQAAAcALAPQAIAMAOAAQAiAAAvgoIAGARQhGA2gvAAQgZAAgLgSg");
	this.shape_55.setTransform(218,215.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFF00").s().p("AAZB5QgGgHAAgOQAAgPAGgZQgZAegmAXQgaAOgSAAQgLAAgGgGQgFgHAAgPQAAgLACgOQAEgSAQg4QAThGAAgNQAAgJgGABQgFAAgJAFQgJAFgWAVIgNgLQAngiAVgMQAVgLAMABQAHAAAFAFQAEAFAAAKQAAAVgVBPQgTBHAAAJQAAAHAEAEQAEAEAFAAQAQAAAdgbQAegbAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAFACADQADAEADAAQAFAAAHgFQAJgHAbgbIAKALQg7A+gcgBQgJABgHgIg");
	this.shape_56.setTransform(193.5,215.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFF00").s().p("AgvDPQgFgEAAgFQAAgFAEgLIAKgkQgjAmgYANQgXAOgTAAQgQAAgKgOQgLgOAAgaQAAgpAdg3QAcg2AkgZQAjgaAdAAIATACQANg5AMgaQANgaAUgTQAUgTAZgLQAagKAWAAQAMAAAHAGQAHAHAAAIQAAAKgGAFQgHAGgLAAIgbgDQgVgDgHAAQgKAAgIAHQgIAGgHAVQgEANgRBHIgpCwQgHAfAAAKQAAAMAIAAQAFgBAHgEQAKgFAdgWIAIALQgnAhgTALQgaAPgPAAQgHAAgEgEgAhOAAQgTAPgRAsQgRAtAAAhQAAAPAIAJQAIAJAKAAQAMAAAQgLQAXgQANgWQAIgPANg5IAOg7QgYgFgJAAQgUAAgTAPg");
	this.shape_57.setTransform(171.5,206.9);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFF00").s().p("AhPBxQgLgOAAgfQAAg/Amg9QAqhGA6AAQAWAAALAKQALALgBASQABATgNASQgOATgiAUQgRAJg3AYQgCAQAAAPQAAAUAHAJQAGAIANAAQAMAAANgHQAUgJAkgcIAKANQhIBEgyAAQgVAAgKgOgAAEheQgMALgKAWQgNAggGAhQAugUAYgZQAQgRAAgQQAAgNgGgHQgHgIgLAAQgKAAgLAIg");
	this.shape_58.setTransform(143,215.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFF00").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_59.setTransform(412.4,147.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFF00").s().p("AAICBQgEgEAAgHIACgMIAMgnQgYAegjAVQgVANgSAAQgRABgJgMQgNgQAAgbQAAgeARgnQARgkAbggQAcgfAegOQAYgMAlAAIATACIAHgMIATgEIgWBKQgNAtgMA4QgGAfAAAKQAAAJAHAAQAFAAAKgHQASgLARgQIAKAMQgiAfgJAGQgTANgRAGQgLAEgLAAQgHAAgEgDgAgVhGQgUAOgQAlQgRAlAAAmQAAAUAGAIQAHAJALAAQAUAAAXgWQAXgWAKgpIAZhaQgQgDgLAAQgZgBgUAQg");
	this.shape_60.setTransform(385.9,147.2);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFF00").s().p("AARDLQgHgIAAgSQABgLAEgXQAFgWAXhKQAKgkAAgHQAAgIgKAAQgNAAgSALQgZARgUAbQgNAQgHAiIgXBmIgsAAIAWhUIAri7QALg0AUgcQATgcAegRQAfgRAeAAQAMAAAIAHQAHAGAAAJQAAAIgHAGQgHAHgMAAIgSgCQgagEgKAAQgNAAgIALQgJALgIAoIghCQQAjgjAogaQAYgPAPAAQALAAAHAHQAGAHAAAMQAAAKgDAJQgDARgOAtQgTA/gDAPQgEAQAAAMQAAAEACADQACACACAAQAIAAATgRIAagVIAIAKQgbAegcASQgUAMgNAAQgKAAgGgIg");
	this.shape_61.setTransform(347.2,139.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFF00").s().p("Ag/CXQgHgIAAgSQAAgVALgrIAeh0IgwAAIAGgVIAvAAIAQhAIAugSIgVBSIA9AAIgFAVIg9AAIgYBhQgNAtAAARQABAIADADQAEAEAFAAQAJAAASgLQAZgOAWgTIALAOQhAAwgVALQgWALgMAAQgMAAgFgIg");
	this.shape_62.setTransform(324.9,144.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFF00").s().p("AgwC4QgHgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgNgJQAeggAYgOQAXgOARAAQAKAAAEAFQAFAEABAHQAAAIgTA/QgfBoAAAVQAAAEACADQACADADAAQAIAAAnglIALAMQgoAlgRALQgTAKgLAAQgLAAgFgGgAAfiNQgGgHAAgJQAAgOAJgJQAIgJALAAQAJAAAHAGQAFAGABAJQgBANgIAKQgKAKgLAAQgIAAgGgGg");
	this.shape_63.setTransform(308.5,141.3);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFF00").s().p("AACAoQgnApgJAHQgUAQgSAMQgSALgUAJQgCgRgHglQgLg1AAgWQAAgeAPgdQAPgeAegWQg2ABgWALQgPAIAAAJQAAAFADAIQADAIAAADQAAAGgDAEQgEAEgGAAQgIAAgFgHQgGgHAAgMQAAgXAWgQQAegUBNABQANgKAHAAQAFAAAEAFQADADAAAFQAAAMgRAEIgWAsQgJATgEASQgEATAAASQAAAYAMA1QAsgdAmgyIAAgSQAAhAATglQANgZAPAAQAJAAAGAIQAGAHAAAQQAAAMgFAQQgIAbgKAVQAABKALAqQAjgYAhgjQAYgbANgcQAMgdAAgTQAAgJgGgOQgIgQAAgIQAAgIAGgFQAGgGAHABQAKgBAGAKQAGAJAAAXQAAA9g1BBQg0BChMAlQgJgggIhAg");
	this.shape_64.setTransform(279.9,147.9);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFF00").s().p("Ah0C6QgXgTAAgYQAAgYASgUQAOgPArgXQAWgLATgMQgWALgNAAQgLAAgIgKQgIgKAAgRQAAg1Agg1QAgg1AsgbQAcgQAqAAIAUAAIADgJIAYgEQgWBEgRBFQgOAxgEAgQgDAQAAAaQgBAqgIAZQgNAlgiAWQggAVguABQgnAAgXgTgAghA8QgxAjgMAOQgLAQAAARQAAARAPANQAPANAVAAQATAAAUgJQARgLAOgSQAOgSAGgYQAFgYAAgmIADgnQgUARg5AngAALiPQgTAPgOAiQgUAxAAAiQABAMAHAJQAIAKAKAAQAMAAAPgLQASgLAKgRQAMgQALgqIAVhOQgNgCgMAAQgbAAgUAOg");
	this.shape_65.setTransform(231.5,154.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFF00").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_66.setTransform(208.5,147.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFF00").s().p("AgxC4QgGgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgMgJQAdggAYgOQAXgOARAAQAJAAAGAFQAEAEAAAHQABAIgUA/QgdBoAAAVQAAAEABADQADADACAAQAIAAAnglIALAMQgoAlgRALQgTAKgMAAQgKAAgGgGgAAeiNQgFgHAAgJQAAgOAJgJQAIgJAMAAQAJAAAGAGQAFAGAAAJQABANgKAKQgIAKgLAAQgKAAgGgGg");
	this.shape_67.setTransform(188.5,141.3);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFF00").s().p("AARDLQgHgIAAgSQABgLAFgXQAEgWAXhKQAKgkAAgHQAAgIgKAAQgNAAgSALQgZARgUAbQgNAQgHAiIgXBmIgsAAIAWhUIAri7QALg0AUgcQATgcAegRQAfgRAeAAQAMAAAIAHQAHAGAAAJQAAAIgHAGQgHAHgMAAIgSgCQgagEgJAAQgOAAgIALQgJALgIAoIghCQQAjgjAogaQAYgPAPAAQALAAAHAHQAGAHAAAMQAAAKgDAJQgDARgOAtQgTA/gDAPQgEAQAAAMQAAAEACADQACACADAAQAHAAATgRIAagVIAIAKQgbAegcASQgUAMgMAAQgLAAgGgIg");
	this.shape_68.setTransform(167.2,139.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFF00").s().p("Ag/CXQgHgIAAgSQAAgVALgrIAeh0IgwAAIAGgVIAvAAIARhAIAtgSIgVBSIA9AAIgFAVIg9AAIgYBhQgNAtAAARQABAIADADQAEAEAFAAQAJAAASgLQAZgOAWgTIALAOQhAAwgVALQgWALgMAAQgMAAgFgIg");
	this.shape_69.setTransform(144.9,144.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFF00").s().p("AiHDBQgKgHAAgKQAAgIAIgHQAIgGANAAQAJAAASADQASAEAHABQASAAAUgPQAagUAQgdQAQgdAAgdQAAgogMg4QgMg5gUgeQgLgQgNAAQgOAAgbATIgJgOIAWgOQAfgVANgHQAIgEAGAAQAGABAEAGQAaAhASA3QARA3AAAzIAAAVQAxhbAAg1QAAgLgFgSQgFgVAAgJQAAgIAGgGQAFgFAIgBQAKABAHAHQAGAJAAAOQAAAlgRA5QgSA5glBAQglBAgeAgQgeAfgcAOQgdAOgaAAQgTAAgKgIg");
	this.shape_70.setTransform(119.5,154.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFF00").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_71.setTransform(96.9,147.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFF00").s().p("AAICBQgEgEAAgHIACgMIAMgnQgYAegjAVQgVANgSAAQgRABgJgMQgNgQAAgbQAAgeARgnQARgkAbggQAcgfAegOQAYgMAlAAIATACIAHgMIATgEIgWBKQgNAtgMA4QgGAfAAAKQAAAJAHAAQAFAAAKgHQASgLARgQIAKAMQgiAfgJAGQgTANgRAGQgLAEgLAAQgHAAgEgDgAgVhGQgUAOgQAlQgRAlAAAmQAAAUAGAIQAHAJALAAQAUAAAXgWQAXgWAKgpIAZhaQgQgDgLAAQgZgBgUAQg");
	this.shape_72.setTransform(70.3,147.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFF00").s().p("AhWBrQgTgUAAgkQAAg8Ajg1QAthBBAABQAdAAATAWQATAYAAAoQAABAgtA0QguA0gygBQggABgTgVgAghhFQgXAkAAA9QAAAmAOAXQALAQARAAQAYAAAUgfQAagoAAg5QAAgsgLgTQgMgSgTgBQgXABgYAjg");
	this.shape_73.setTransform(354,80.1);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFF00").s().p("AgvDPQgFgEAAgFQAAgFAEgMIAKgjQgjAmgYANQgXAOgTAAQgQAAgKgOQgLgNAAgbQAAgpAdg3QAcg2AkgZQAjgaAdAAIATACQANg5AMgaQANgaAUgTQAUgTAZgLQAagKAWAAQAMAAAHAGQAHAHAAAIQAAAKgGAGQgHAFgLAAIgbgDQgVgCgHAAQgKgBgIAHQgIAGgHAVQgEANgRBHIgpCwQgHAfAAAKQAAALAIAAQAFAAAHgDQAKgGAdgWIAIALQgnAhgTALQgaAPgPAAQgHAAgEgEgAhOAAQgTAPgRAsQgRAtAAAgQAAAQAIAJQAIAJAKAAQAMABAQgMQAXgQANgWQAIgPANg5IAOg7QgYgFgJAAQgUAAgTAPg");
	this.shape_74.setTransform(334.1,71.8);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFF00").s().p("AAYB4QgGgIAAgSQAAgaAghnQAKglAAgGQAAgJgKAAQgMAAgTAMQgaASgTAZQgLAQgIAiIgYBmIgsAAQANgsAJgoIAahvIABgKQAAgIgGAAQgEAAgJAHQgSAMgQARIgKgKQAmgkAWgMQAWgMAQAAQAGAAAEADQADADAAADIgBAKIgOA7QAegiAsgcQAYgPAQAAQALAAAHAHQAGAHAAAOQAAAJgDAMQgEATgUA/QgTA7AAAUQAAAGACADQACADADAAQAJAAASgQIAZgWIAIAKQgbAegdASQgTAMgMAAQgLAAgGgIg");
	this.shape_75.setTransform(288.9,80);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFF00").s().p("AAICAQgEgDAAgHIACgMIAMgoQgYAfgjAVQgVAOgSAAQgRAAgJgNQgNgQAAgZQAAggARglQARgmAbgfQAcgfAegPQAYgLAlABIATAAIAHgLIATgEIgWBKQgNAsgMA5QgGAgAAAIQAAAJAHAAQAFAAAKgFQASgLARgQIAKALQgiAfgJAGQgTAMgRAHQgLAEgLAAQgHAAgEgEgAgVhHQgUAOgQAnQgRAkAAAlQAAAVAGAIQAHAJALAAQAUAAAXgVQAXgXAKgoIAZhbQgQgEgLAAQgZAAgUAPg");
	this.shape_76.setTransform(262.3,79.6);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFF00").s().p("AhSBtQgMgSAAgcQAAguAYgwQAZgxAjgaQAbgUAiAAQAWAAALAIQALAIAAAMQAAAJgGAGQgFAFgLAAQgKAAgQgJQgRgKgLAAQgPAAgNANQgOANgNAmQgNAkAAAmQAAAcALAPQAIAMAOAAQAiAAAvgoIAGARQhGA2gvAAQgZAAgLgSg");
	this.shape_77.setTransform(240.2,80);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFF00").s().p("AAZB5QgGgHAAgOQAAgPAGgZQgZAegmAXQgaAPgSgBQgLABgGgIQgFgGAAgPQAAgLACgOQAEgSAQg4QAThGAAgNQAAgJgGABQgFgBgJAGQgJAFgWAVIgNgLQAngiAVgLQAVgMAMABQAHgBAFAGQAEAFAAAKQAAAVgVBPQgTBGAAAKQAAAHAEAEQAEAEAFABQAQAAAdgbQAegcAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAFACADQADADADABQAFAAAHgFQAJgHAbgbIAKALQg7A+gcgBQgJABgHgIg");
	this.shape_78.setTransform(202.5,80.2);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFF00").s().p("AhWBrQgTgUAAgkQAAg8Ajg1QAthBBAABQAdAAATAWQATAYAAAoQAABAgtA0QgvA0gxgBQgfABgUgVgAghhFQgXAkAAA9QAAAmAOAXQALAQARAAQAYAAAUgfQAagoAAg5QAAgsgMgTQgMgSgRgBQgYABgYAjg");
	this.shape_79.setTransform(176.5,80.1);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFF00").s().p("AgZDFQgVgDgNAAQgRAAgmAEIAGgPQAbgHAHgIQAHgIAQg+QARg+AAgUQAAgmgQgpQgOgpgYgaQgrAQgSAOQgTAOgLAUQgLAUAAAPQAAAPANANQALAKAAAJQAAAHgEAFQgEAFgHAAQgMAAgJgLQgKgQgBgWQABggARgdQATgdAhgTQASgMAsgNIAdgJQAYAdAQAoQAOAoAGA7QA2hyAxguQAxgvAfAAQAKAAAGAGQAHAFAAAIQAAAJgIAFQgHAFgVACQgUABgMAHQgVAOgfAkQgdAkgdA3QgdA2gOA7QgQA7gBARQAOADAMAAQAWAAAYgGIgGARQgSAFgNAAQgNAAgXgCg");
	this.shape_80.setTransform(154.3,72.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFF00").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_81.setTransform(129.8,64.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFF00").s().p("AhuCcIAYheQAShEANhAIAEgSQAAgJgIAAQgFAAgLAIQgLAGgdAdIgLgNQAigjAigTQAhgSASAAQAHAAACAEQAEACAAAEQAAAGgFATIgOA/QAig3AtgpQAWgSAOgBQALABAHAGQAHAHAAAJQAAAJgHAIQgHAGgbAJQgaAJgQAMQgRAMgTAaQgTAZgIASQgHATgQBFIgQBDg");
	this.shape_82.setTransform(188.9,703.7);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFF00").s().p("AAUDzQgHgKAAgVQAAgOAGgaQAGgbAbhZQAMgsAAgHQAAgLgMAAQgPABgWAOQgfAUgYAfQgPAVgJAnIgbB7Ig1AAQARg+AJgmIA0jhQAOg/AXghQAXgiAkgUQAlgUAkAAQAQAAAIAHQAJAIAAAMQAAAJgJAHQgIAHgPAAIgWgBQgegFgMAAQgQAAgKAOQgKANgLAwIgmCsQApgrAxgdQAcgSASAAQAOgBAHAJQAIAHAAAPQAAAMgDALQgEAVgRA2QgXBLgEATQgEASAAAOQAAAGACACQACADADABQAJAAAYgVIAfgaIAJAOQggAkgiAUQgXAPgQAAQgMAAgIgKg");
	this.shape_83.setTransform(135,695);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFF00").s().p("AhNC1QgHgJAAgWQAAgaANg0IAkiKIg5AAIAGgZIA5AAIAUhOIA3gUIgaBiIBJAAIgFAZIhJAAIgeB1QgPA0AAAWQAAAJAFAEQAEAEAHAAQAKAAAWgNQAegRAagWIAOAQQhNA6gZAOQgaAMgQAAQgNAAgIgJg");
	this.shape_84.setTransform(108.1,701.3);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFF00").s().p("AAKCaQgFgEAAgIQAAgFADgJIAOgwQgdAkgqAaQgaAQgVAAQgVAAgLgOQgOgUAAgfQgBglAVguQATgtAiglQAhglAkgSQAdgNAsAAIAXABIAIgNIAYgFIgaBZQgRA1gOBEQgHAmAAAKQAAALAJAAQAFAAANgHQAVgNAUgTIALANQgoAlgLAIQgWAPgVAIQgNAEgNAAQgJAAgEgEgAgZhVQgYARgUAuQgUAsgBAtQAAAYAJAKQAIALANAAQAYAAAcgaQAagbANgxIAehtQgTgDgNAAQgfAAgXARg");
	this.shape_85.setTransform(80.6,704.5);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFF00").s().p("AioDDQAfgHALgIQAKgHAFgLQAKgVAehwIA2jRQgvABgjAUQgjAUgVAhQgVAhgBAjQAAANAEAPQACAHAIAOQAKAUAAAGQABAIgHAGQgFAFgKAAQgOAAgJgPQgMgUAAgiQAAhIA3g7QA3g7BbAAICGAAQAWAAAcgDIAigHQgSBJgEAVIgSAAQAFgdABgJQgBgMgHgFQgJgGgWAAIgWAAIgIAAIhGAAIgLApQgUBEgIAsIBDAAQAZAAAIgFQAHgFAFgUIATAAQgLAtgIAvIgUAAIADgYQAAgJgJgDQgEgCgWgBIhCAAQgKAwgRA4QgRA5gLAfQAbAFAXAAQANgBAPgCIgHAVIgRABIgxgDQgZgCgQAAQgjABgmAGg");
	this.shape_86.setTransform(48.2,698.6);

	this.instance_2 = new lib.bigstockStackOfBooks70033240();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-4,-12,0.642,0.736);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FF3300").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_87.setTransform(803.4,179.6);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FF3300").s().p("AhqDMQgHgHABgMQAAgYAShKIAfh/QAShGAMgYQASgkAfgTQAhgUAlAAQANAAAHAGQAIAGgBAIQABAKgIAGQgGAGgOAAQgIAAgRgDQgOgCgMAAQgLAAgHAFQgIAHgHAWQgGAXgQBCIgdB5QgWBdABAEQAAAJAGAAQAHAAAMgHQAYgQAYgXIAKAKQgWAagfAVQgfAVgVAAQgIAAgGgGg");
	this.shape_88.setTransform(790.2,186.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FF3300").s().p("AAZB5QgGgHAAgNQAAgPAGgaQgZAegmAWQgaAPgSABQgLAAgGgHQgFgHAAgOQAAgMACgNQAEgTAQg4QAThGAAgOQAAgHgGgBQgFAAgJAGQgJAFgWAVIgNgKQAngkAVgKQAVgMAMAAQAHAAAFAGQAEAFAAALQAAAUgVBQQgTBFAAALQAAAFAEAFQAEAFAFgBQAQAAAdgbQAegbAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAGACADQADACADAAQAFAAAHgEQAJgGAbgcIAKALQg7A9gcABQgJgBgHgHg");
	this.shape_89.setTransform(763.3,195);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FF3300").s().p("AjGEUQgKgHAAgLQAAgJAHgFQAHgFAMAAIASABQAVADASAAQAdAAAOgNQANgOANg2IA6jtIhFAAIAGgWIBFAAQARhIAWglQAXgjAjgVQAkgUAgAAQASgBAJAIQAJAHAAAJQAAAJgGAGQgHAGgKAAQgKAAgcgHQgOgCgIAAQgUAAgPAYQgQAYgJApIgPA9IBOAAIgFAWIhOAAIguC6QgVBVgvAsQgvArg3ABQgSAAgKgIg");
	this.shape_90.setTransform(738.7,193.8);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FF3300").s().p("AhPBxQgMgOAAgfQAAg/Ang9QAqhGA7AAQAVAAAKAKQAMALAAASQAAATgOASQgNATgiAUQgRAJg2AYQgDAQAAAPQAAAUAGAJQAHAIAMAAQAMAAAOgHQATgJAmgcIAJANQhIBEgyAAQgVAAgKgOgAAEheQgMALgKAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_91.setTransform(720,194.8);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FF3300").s().p("AgvDPQgFgEAAgFQAAgFAEgLIAKgkQgjAlgYAOQgXANgTAAQgQAAgKgNQgLgNAAgbQAAgpAdg3QAcg2AkgZQAjgaAdAAIATACQANg5AMgaQANgaAUgTQAUgTAZgKQAagLAWAAQAMAAAHAGQAHAGAAAKQAAAJgGAFQgHAGgLAAIgbgCQgVgDgHgBQgKABgIAFQgIAHgHAUQgEAOgRBHIgpCwQgHAfAAALQAAALAIgBQAFAAAHgDQAKgGAdgWIAIALQgnAhgTALQgaAPgPAAQgHAAgEgEgAhOAAQgTAPgRAsQgRAtAAAhQAAAPAIAJQAIAKAKAAQAMgBAQgKQAXgRANgXQAIgPANg5IAOg5QgYgGgJAAQgUAAgTAPg");
	this.shape_92.setTransform(701.8,186.6);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FF3300").s().p("AgwC4QgHgGAAgMQAAgkAsiOQACgHAAgFQAAgGgFAAQgGAAgHAFQgIAFgaAYIgMgJQAdggAYgOQAXgOARAAQAKAAAEAFQAFAEABAHQAAAIgUA/QgeBoAAAVQAAAEACADQACADADAAQAIAAAnglIALAMQgoAlgRALQgTAKgMAAQgKAAgFgGgAAfiNQgGgHAAgJQAAgOAJgJQAIgJALAAQAJAAAHAGQAFAGAAAJQAAANgJAKQgIAKgMAAQgIAAgGgGg");
	this.shape_93.setTransform(677.4,188.5);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FF3300").s().p("AhcCCIAUhPQAPg4ALg1IADgQQAAgGgGAAQgEAAgKAFQgJAGgXAYIgJgKQAcgeAcgPQAbgPAQAAQAEgBACADQAEACAAAFIgEATIgMA2QAdgwAlggQASgQAMgBQAJAAAGAHQAFAFABAHQgBAJgFAFQgGAGgXAHQgVAHgOAKQgOALgQAVQgPAVgHAPQgGAPgNA6IgNA4g");
	this.shape_94.setTransform(662.7,193.7);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FF3300").s().p("AhNDDQgcAAgsAEIAEgOQAWgDAKgKQAKgKAGgaIA1jdQAPg+AAgHQAAgIgHAAQgNABgkAlIgMgMQAbgfAagPQAbgQASAAQAHAAAFAEQAEADAAAIQAAAIgCAJIgMAqQAtgsAQgLQAcgSAXAAQAPAAAKAOQAKAOAAAdQAABHgsBAQgsA+g2AAQgUAAgVgLIgZBgQgCAJAAAGQAAALAIAEQAMAHAoAGIgDAOQgvgEgbAAgAAxiQQgbAVgOAVQgJAPgJAmIgQA/QAXAWAXAAQAjAAAbg1QAag3AAg0QAAgQgHgJQgHgJgNAAQgOAAgSAOg");
	this.shape_95.setTransform(635,201.9);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FF3300").s().p("AhQBxQgKgOgBgfQABg/Alg9QArhGA7AAQAUAAALAKQAMALAAASQAAATgOASQgNATgiAUQgRAJg2AYQgDAQAAAPQAAAUAGAJQAHAIAMAAQANAAANgHQATgJAmgcIAJANQhHBEgzAAQgUAAgMgOgAAEheQgNALgJAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgKAAgLAIg");
	this.shape_96.setTransform(948.5,127.2);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FF3300").s().p("AhbDCQgQgPAAgaQAAgUAIgkIAjiaQAMg5ATgeQATgdAegSQAggSAbAAQARAAAIAGQAIAGAAAJQAAAJgHAGQgHAGgNAAQgKAAgYgFQgKgBgIAAQgPAAgJAPQgGAMgMAzIgYBlQAYgYAWgMQAXgNASAAQAUAAAMAQQANARAAAgQAAAwgXAuQgWAugiAYQggAYggAAQgbAAgQgQgAgNAGQgUARgRAsQgSArAAArQAAAPAKALQAKALAOAAQAgAAAZgzQAZg0AAgzQAAgXgKgOQgGgKgMABQgOAAgTAQg");
	this.shape_97.setTransform(927.1,119.1);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FF3300").s().p("AhQBxQgRgPAAgUQAAgLAGgGQAHgHAJAAQAJAAAGAFQAFAGAAAHIAAAIIgBAGQAAAKAJAHQAIAHAOAAQAPgBALgFQAMgGAHgKQAHgLgBgLQAAgLgFgKQgHgLgVgYQgeghgBgfQAAgdAYgVQAWgWAjAAQAaAAAPAKQAOAKAAAOQAAAIgGAGQgGAFgJAAQgFAAgEgCQgEgDgIgKQgOgTgOAAQgMAAgKAJQgHAKgBANQABANAEALQAGALAYAZQAgAiABAfQgBAfgaAXQgbAXgoAAQgjAAgRgOg");
	this.shape_98.setTransform(890.6,127.3);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FF3300").s().p("AiHDBQgKgHAAgKQAAgJAIgFQAIgHANAAQAJAAASAEQASADAHABQASgBAUgOQAagUAQgdQAQgdAAgcQAAgpgMg4QgMg6gUgdQgLgQgNAAQgOAAgbATIgJgNIAWgPQAfgWANgGQAIgEAGABQAGgBAEAIQAaAgASA3QARA4AAAyIAAAUQAxhZAAg2QAAgLgFgTQgFgUAAgJQAAgIAGgGQAFgGAIABQAKAAAHAIQAGAHAAAPQAAAlgRA5QgSA4glBBQglBBgeAfQgeAggcANQgdANgaAAQgTABgKgIg");
	this.shape_99.setTransform(865.7,134.5);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FF3300").s().p("AAICAQgEgDAAgHIACgMIAMgoQgYAfgjAVQgVAOgSAAQgRAAgJgNQgNgQAAgZQAAggARglQARgmAbgfQAcgfAegPQAYgLAlABIATAAIAHgLIATgEIgWBKQgNAsgMA5QgGAgAAAIQAAAJAHAAQAFAAAKgFQASgLARgQIAKALQgiAfgJAGQgTAMgRAHQgLAEgLAAQgHAAgEgEgAgVhHQgUAOgQAnQgRAkAAAlQAAAVAGAIQAHAJALAAQAUAAAXgVQAXgXAKgoIAZhbQgQgEgLAAQgZAAgUAPg");
	this.shape_100.setTransform(844.2,126.9);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FF3300").s().p("AACApQgnAogJAHQgUAQgSALQgSAMgUAIQgCgQgHgmQgLg0AAgWQAAgeAPgeQAPgdAegWQg2ACgWAKQgPAHAAALQAAADADAJQADAIAAAEQAAAFgDAEQgEADgGABQgIgBgFgGQgGgHAAgMQAAgYAWgOQAegWBNACQANgJAHAAQAFAAAEADQADAEAAAFQAAALgRAFIgWAsQgJATgEASQgEATAAASQAAAYAMA2QAsgeAmgyIAAgRQAAhBATgmQANgYAPAAQAJAAAGAIQAGAIAAAPQAAAMgFAQQgIAbgKAWQAABIALAsQAjgYAhglQAYgbANgbQAMgdAAgSQAAgJgGgPQgIgRAAgHQAAgIAGgFQAGgFAHgBQAKABAGAIQAGAKAAAYQAAA8g1BBQg0BDhMAjQgJgggIg+g");
	this.shape_101.setTransform(811.4,127.6);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FF3300").s().p("AhqDMQgHgHAAgMQABgYARhKIAhh/QAQhGAMgYQASgkAhgTQAhgUAkAAQANAAAIAGQAGAGAAAIQAAAKgGAGQgIAGgNAAQgJAAgPgDQgOgCgMAAQgMAAgHAFQgIAHgHAWQgGAXgPBCIgeB5QgVBdAAAEQgBAJAIAAQAGAAAMgHQAZgQAXgXIAKAKQgWAagfAVQggAVgTAAQgKAAgFgGg");
	this.shape_102.setTransform(789.6,119);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#FF3300").s().p("AAICAQgEgDAAgHIACgMIAMgoQgYAfgjAVQgVAOgSAAQgRAAgJgNQgNgQAAgZQAAggARglQARgmAbgfQAcgfAegPQAYgLAlABIATAAIAHgLIATgEIgWBKQgNAsgMA5QgGAgAAAIQAAAJAHAAQAFAAAKgFQASgLARgQIAKALQgiAfgJAGQgTAMgRAHQgLAEgLAAQgHAAgEgEgAgVhHQgUAOgQAnQgRAkAAAlQAAAVAGAIQAHAJALAAQAUAAAXgVQAXgXAKgoIAZhbQgQgEgLAAQgZAAgUAPg");
	this.shape_103.setTransform(763.8,126.9);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FF3300").s().p("AgtA5QAagUAPgUQAIgNAAgIQAAgIgGgNQgHgOAAgJQAAgLAIgIQAHgIALAAQAMAAAJAKQAIAJAAAOQAAAQgIAUQgKATgRATQgYAagaASg");
	this.shape_104.setTransform(726.8,140.7);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#FF3300").s().p("AhQBxQgLgOABgfQgBg/Amg9QArhGA6AAQAVAAAMAKQALALgBASQABATgNASQgOATgiAUQgRAJg3AYQgCAQAAAPQAAAUAHAJQAGAIAMAAQAMAAAOgHQATgJAlgcIAKANQhIBEgyAAQgUAAgMgOgAAEheQgNALgJAWQgNAggGAhQAugUAYgZQAQgRAAgQQAAgNgGgHQgHgIgLAAQgKAAgLAIg");
	this.shape_105.setTransform(714.7,127.2);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FF3300").s().p("AhcCDIAUhPQAPg5AMg0IACgQQAAgIgGAAQgEAAgKAHQgJAFgYAYIgJgKQAdgeAcgPQAbgQAPAAQAGABABACQAEACAAAEIgEAUIgMA1QAdguAlgiQASgPAMAAQAJAAAGAFQAFAGABAIQgBAHgFAGQgGAGgXAHQgWAIgNAKQgNAKgQAVQgQAVgHAPQgGAPgNA5IgNA6g");
	this.shape_106.setTransform(698.1,126.2);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#FF3300").s().p("AAZB5QgGgHAAgOQAAgPAGgZQgZAegmAXQgaAPgSgBQgLABgGgIQgFgGAAgPQAAgLACgOQAEgSAQg4QAThGAAgNQAAgJgGABQgFgBgJAGQgJAFgWAVIgNgLQAngiAVgLQAVgMAMABQAHgBAFAGQAEAFAAAKQAAAVgVBPQgTBGAAAKQAAAHAEAEQAEAEAFABQAQAAAdgbQAegcAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAFACADQADADADABQAFAAAHgFQAJgHAbgbIAKALQg7A+gcgBQgJABgHgIg");
	this.shape_107.setTransform(672.8,127.4);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FF3300").s().p("Ag/CXQgHgIAAgSQAAgVALgrIAeh0IgwAAIAGgVIAvAAIARhAIAtgSIgVBSIA8AAIgEAVIg9AAIgYBhQgMAtAAARQgBAIAEADQADAEAGAAQAJAAASgLQAYgOAXgTIALAOQhAAwgVALQgWALgNAAQgKAAgGgIg");
	this.shape_108.setTransform(650,124.1);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#FF3300").s().p("AhrDMQgFgHAAgMQgBgYAThKIAfh/QAShGAMgYQASgkAfgTQAigUAkAAQANAAAHAGQAIAGgBAIQABAKgIAGQgGAGgOAAQgJAAgQgDQgOgCgMAAQgMAAgGAFQgIAHgHAWQgGAXgQBCIgcB5QgXBdAAAEQABAJAGAAQAHAAAMgHQAZgQAXgXIAKAKQgWAagfAVQgfAVgVAAQgJAAgGgGg");
	this.shape_109.setTransform(638.5,119);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#FF3300").s().p("AAZB5QgGgHAAgOQAAgPAGgZQgZAegmAXQgaAPgSgBQgLABgGgIQgFgGAAgPQAAgLACgOQAEgSAQg4QAThGAAgNQAAgJgGABQgFgBgJAGQgJAFgWAVIgNgLQAngiAVgLQAVgMAMABQAHgBAFAGQAEAFAAAKQAAAVgVBPQgTBGAAAKQAAAHAEAEQAEAEAFABQAQAAAdgbQAegcAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAFACADQADADADABQAFAAAHgFQAJgHAbgbIAKALQg7A+gcgBQgJABgHgIg");
	this.shape_110.setTransform(611.6,127.4);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#FF3300").s().p("AhSBtQgMgSAAgcQAAguAYgwQAZgxAjgaQAbgUAiAAQAWAAALAIQALAIAAAMQAAAJgGAGQgFAFgLAAQgKAAgQgJQgRgKgLAAQgPAAgNANQgOANgNAmQgNAkAAAmQAAAcALAPQAIAMAOAAQAiAAAvgoIAGARQhGA2gvAAQgZAAgLgSg");
	this.shape_111.setTransform(588.1,127.3);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#FF3300").s().p("AhcCDIAUhPQAPg5ALg0IADgQQAAgIgGAAQgEAAgKAHQgJAFgYAYIgJgKQAcgeAdgPQAbgQAPAAQAGABABACQAEACAAAEIgEAUIgMA1QAdguAlgiQASgPAMAAQAJAAAGAFQAFAGABAIQgBAHgFAGQgGAGgXAHQgWAIgNAKQgNAKgQAVQgQAVgHAPQgGAPgNA5IgNA6g");
	this.shape_112.setTransform(557.7,126.2);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#FF3300").s().p("AAZB5QgGgHAAgOQAAgPAGgZQgZAegmAXQgaAPgSgBQgLABgGgIQgFgGAAgPQAAgLACgOQAEgSAQg4QAThGAAgNQAAgJgGABQgFgBgJAGQgJAFgWAVIgNgLQAngiAVgLQAVgMAMABQAHgBAFAGQAEAFAAAKQAAAVgVBPQgTBGAAAKQAAAHAEAEQAEAEAFABQAQAAAdgbQAegcAKgiIAgh4IApAAIgbBnQgYBYAAAMQAAAFACADQADADADABQAFAAAHgFQAJgHAbgbIAKALQg7A+gcgBQgJABgHgIg");
	this.shape_113.setTransform(532.4,127.4);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#FF3300").s().p("AhWBrQgTgUAAgkQAAg8Ajg1QAthBBAABQAdAAATAWQATAYAAAoQAABAguA0QguA0gxgBQggABgTgVgAgghFQgYAkAAA9QAAAmAPAXQAKAQARAAQAYAAAUgfQAagoAAg5QAAgsgLgTQgMgSgTgBQgXABgXAjg");
	this.shape_114.setTransform(506.4,127.3);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#FF3300").s().p("AiHDBQgKgHAAgKQAAgJAIgFQAIgHANAAQAJAAASAEQASADAHABQASgBAUgOQAagUAQgdQAQgdAAgcQAAgpgMg4QgMg6gUgdQgLgQgNAAQgOAAgbATIgJgNIAWgPQAfgWANgGQAIgEAGABQAGgBAEAIQAaAgASA3QARA4AAAyIAAAUQAxhZAAg2QAAgLgFgTQgFgUAAgJQAAgIAGgGQAFgGAIABQAKAAAHAIQAGAHAAAPQAAAlgRA5QgSA4glBBQglBBgeAfQgeAggcANQgdANgaAAQgTABgKgIg");
	this.shape_115.setTransform(479.4,134.5);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#FF3300").s().p("AjGEVQgKgIAAgKQAAgJAHgGQAHgFAMAAIASABQAVADASAAQAdAAAOgNQANgOANg2IA6jtIhFAAIAGgWIBFAAQARhIAWglQAXgjAjgVQAkgVAgABQASAAAJAGQAJAIAAAJQAAAJgGAGQgHAGgKAAQgKAAgcgGQgOgDgIAAQgUAAgPAYQgQAYgJAoIgPA+IBOAAIgFAWIhOAAIguC5QgVBWgvAsQgvAsg3AAQgSgBgKgGg");
	this.shape_116.setTransform(965.4,58.7);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#FF3300").s().p("AhVBrQgUgVAAgjQAAg9Ajg0QAshABCgBQAcAAATAYQATAWAAApQAABAguA0QgtA0gzAAQgfgBgSgUgAgghEQgYAjAAA+QAAAlAPAWQAKAQASAAQAXAAAUgeQAagnAAg6QAAgsgMgSQgMgUgRABQgZAAgWAkg");
	this.shape_117.setTransform(944.8,59.8);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#FF3300").s().p("AgvDPQgFgEAAgFQAAgFAEgLIAKgkQgjAlgYAOQgXANgTAAQgQAAgKgNQgLgNAAgbQAAgpAdg3QAcg2AkgZQAjgaAdAAIATACQANg5AMgaQANgaAUgTQAUgTAZgLQAagKAWAAQAMAAAHAGQAHAHAAAJQAAAJgGAFQgHAGgLAAIgbgCQgVgEgHAAQgKABgIAFQgIAHgHAUQgEAOgRBHIgpCwQgHAfAAALQAAAKAIABQAFAAAHgFQAKgFAdgWIAIALQgnAhgTALQgaAPgPAAQgHAAgEgEgAhOAAQgTAPgRAsQgRAsAAAiQAAAOAIAKQAIAKAKAAQAMAAAQgMQAXgPANgYQAIgPANg5IAOg5QgYgGgJAAQgUAAgTAPg");
	this.shape_118.setTransform(911.7,51.5);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#FF3300").s().p("AhPBxQgLgOAAgfQAAg/Amg9QAqhGA6AAQAWAAALAKQAKALABASQgBATgNASQgNATgiAUQgRAJg3AYQgCAQAAAPQAAAUAHAJQAGAIANAAQAMAAANgHQAUgJAlgcIAJANQhHBEgzAAQgVAAgKgOgAAEheQgMALgKAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_119.setTransform(883.1,59.7);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#FF3300").s().p("AhQBxQgRgOAAgVQAAgKAHgHQAGgHAKAAQAIAAAFAFQAHAGAAAIIgBAHIAAAGQgBAKAJAHQAIAGANABQAQAAALgGQAMgFAHgLQAGgMABgKQAAgLgHgKQgGgLgVgYQgfghABgfQAAgdAWgWQAXgVAkAAQAaAAAOALQAOAJAAANQAAAJgGAFQgGAGgIAAQgGAAgEgCQgEgDgIgKQgOgTgOAAQgMAAgJAJQgIAJAAAOQgBAMAFAMQAGALAYAZQAhAhgBAfQABAggbAXQgbAXgoAAQgjAAgRgOg");
	this.shape_120.setTransform(863.5,59.7);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#FF3300").s().p("AhQBxQgRgOAAgVQAAgKAGgHQAHgHAJAAQAIAAAHAFQAFAGAAAIIAAAHIgBAGQAAAKAJAHQAIAGAOABQAPAAALgGQAMgFAHgLQAHgMAAgKQgBgLgFgKQgHgLgVgYQgfghAAgfQAAgdAYgWQAWgVAjAAQAaAAAPALQAOAJAAANQAAAJgGAFQgGAGgJAAQgFAAgEgCQgEgDgIgKQgOgTgOAAQgMAAgKAJQgHAJgBAOQAAAMAFAMQAGALAYAZQAgAhABAfQgBAggaAXQgbAXgoAAQgjAAgRgOg");
	this.shape_121.setTransform(844.3,59.7);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#FF3300").s().p("AAICBQgEgEAAgHIACgMIAMgnQgYAdgjAWQgVANgSAAQgRABgJgMQgNgRAAgaQAAgeARgnQARgkAbggQAcgfAegOQAYgMAlAAIATABIAHgLIATgEIgWBKQgNAtgMA4QgGAfAAAKQAAAIAHABQAFAAAKgHQASgLARgQIAKAMQgiAfgJAGQgTANgRAGQgLAEgLAAQgHAAgEgDgAgVhHQgUAOgQAmQgRAlAAAmQAAAUAGAIQAHAJALAAQAUAAAXgWQAXgVAKgqIAZhaQgQgEgLABQgZgBgUAPg");
	this.shape_122.setTransform(821.9,59.3);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#FF3300").s().p("AhcCCIAVhPQAPg4ALg1IACgQQAAgGgGAAQgFAAgIAFQgKAHgYAXIgIgKQAbgeAcgPQAcgPAPAAQAFAAADACQADADAAAEIgEAUIgMA1QAdgwAmggQARgQAMgBQAJAAAGAHQAGAFgBAHQABAJgGAFQgGAGgWAHQgXAHgNAKQgNALgRAVQgPAVgGAPQgHAQgNA5IgOA4g");
	this.shape_123.setTransform(803,58.6);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#FF3300").s().p("AhcCCIAVhPQAPg4ALg1IACgQQAAgGgGAAQgFAAgIAFQgKAHgYAXIgIgKQAbgeAcgPQAcgPAPAAQAFAAADACQADADAAAEIgEAUIgMA1QAdgwAmggQARgQAMgBQAJAAAGAHQAGAFgBAHQABAJgGAFQgGAGgWAHQgXAHgNAKQgNALgRAVQgPAVgGAPQgHAQgNA5IgOA4g");
	this.shape_124.setTransform(785,58.6);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#FF3300").s().p("AAICBQgEgEAAgHIACgMIAMgnQgYAdgjAWQgVANgSAAQgRABgJgMQgNgRAAgaQAAgeARgnQARgkAbggQAcgfAegOQAYgMAlAAIATABIAHgLIATgEIgWBKQgNAtgMA4QgGAfAAAKQAAAIAHABQAFAAAKgHQASgLARgQIAKAMQgiAfgJAGQgTANgRAGQgLAEgLAAQgHAAgEgDgAgVhHQgUAOgQAmQgRAlAAAmQAAAUAGAIQAHAJALAAQAUAAAXgWQAXgVAKgqIAZhaQgQgEgLABQgZgBgUAPg");
	this.shape_125.setTransform(760.8,59.3);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#FF3300").s().p("AhbDCQgQgPAAgaQAAgUAIgkIAjiaQAMg5ATgdQATgfAegRQAggSAbAAQARAAAIAGQAIAFAAALQAAAIgHAGQgHAGgNAAQgKAAgYgEQgKgDgIAAQgPAAgJAQQgGAMgMAyIgYBmQAYgYAWgNQAXgMASAAQAUAAAMARQANAQAAAgQAAAwgXAuQgWAugiAYQggAYggAAQgbAAgQgQgAgNAGQgUARgRAsQgSAsAAAqQAAAPAKAMQAKAKAOAAQAgAAAZgzQAZg0AAgyQAAgYgKgNQgGgLgMAAQgOABgTAQg");
	this.shape_126.setTransform(737,51.5);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#FF3300").s().p("ABMB4QgGgJAAgPQAAgOAEgTQAEgTAUhBQAPgxAAgLQAAgKgJAAQgHAAgNAHQgZAPgRAWQgMAQgIAgQgUBIgJAuIgpAAIAriyIAFgXQAAgEgCgDQgDgCgEAAQgIAAgRANQgdAUgMAUQgNATgJAnIgXBjIgqAAIAhiLQAPg8AAgFQAAgIgFAAQgMABgjAhIgJgMQAdgcAagOQAbgOAPgBQAGAAADADQADADAAAEQAAAHgFARIgJAmQBGhIAkAAQAKABAFAFQAFAGAAALQAAAMgJAdQAhgiAZgOQAZgPANgBQANABAGAHQAHAHAAAOQAAAJgDAMIgVBKQgXBKAAAPQAAAKAIAAQAGAAAFgDQARgNASgSIAKAKIgXAVQgYAVgIAGQgRAJgMABQgJAAgHgJg");
	this.shape_127.setTransform(704.6,59.8);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#FF3300").s().p("AhPBxQgLgOAAgfQAAg/Amg9QAqhGA6AAQAWAAALAKQAKALABASQgBATgNASQgNATgiAUQgRAJg3AYQgCAQAAAPQAAAUAHAJQAGAIANAAQAMAAANgHQAUgJAlgcIAJANQhHBEgzAAQgVAAgKgOgAAEheQgMALgKAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_128.setTransform(675.7,59.7);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#FF3300").s().p("AhQBxQgKgOgBgfQABg/Alg9QArhGA7AAQAUAAALAKQAMALAAASQAAATgOASQgNATgiAUQgRAJg2AYQgDAQAAAPQAAAUAGAJQAHAIAMAAQANAAANgHQATgJAmgcIAJANQhHBEgzAAQgUAAgMgOgAAEheQgNALgJAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgKAAgLAIg");
	this.shape_129.setTransform(642.1,59.7);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#FF3300").s().p("AhbDCQgQgPAAgaQAAgUAIgkIAjiaQAMg5ATgdQATgfAegRQAggSAbAAQARAAAIAGQAIAFAAALQAAAIgHAGQgHAGgNAAQgKAAgYgEQgKgDgIAAQgPAAgJAQQgGAMgMAyIgYBmQAYgYAWgNQAXgMASAAQAUAAAMARQANAQAAAgQAAAwgXAuQgWAugiAYQggAYggAAQgbAAgQgQgAgNAGQgUARgRAsQgSAsAAAqQAAAPAKAMQAKAKAOAAQAgAAAZgzQAZg0AAgyQAAgYgKgNQgGgLgMAAQgOABgTAQg");
	this.shape_130.setTransform(620.7,51.5);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#FF3300").s().p("AhcCCIAUhPQAPg4ALg1IADgQQAAgGgGAAQgEAAgKAFQgJAHgXAXIgJgKQAcgeAcgPQAcgPAPAAQAEAAADACQADADAAAEIgEAUIgMA1QAdgwAmggQARgQAMgBQAJAAAGAHQAFAFAAAHQAAAJgFAFQgGAGgXAHQgVAHgOAKQgOALgQAVQgPAVgGAPQgHAQgNA5IgNA4g");
	this.shape_131.setTransform(587.2,58.6);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#FF3300").s().p("AhPBxQgMgOAAgfQAAg/Ang9QAqhGA6AAQAWAAALAKQAKALABASQgBATgNASQgNATgiAUQgRAJg3AYQgCAQAAAPQAAAUAGAJQAHAIANAAQALAAAOgHQATgJAmgcIAJANQhIBEgyAAQgVAAgKgOgAAEheQgMALgKAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_132.setTransform(565.3,59.7);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#FF3300").s().p("Ag7BbQgMg8AAgZQAAgeAOgdQAPgeAdgVQg0ABgWAKQgQAIAAAKQAAAEAEAKQADAHAAAEQAAAFgEAEQgEADgGAAQgIABgFgHQgFgGAAgLQAAgRALgPQAMgOAcgHQAcgJAuABQASgIAFAAQAFAAADAEQAEAEAAAEQAAAJgSAHQgVAlgJAbQgJAcAAAaQAAAZAMA1QA/gwAbgsQAbgpAAgfQAAgKgHgOQgHgOAAgHQAAgIAFgFQAGgGAHAAQAKAAAGAJQAFAHAAAVQAAA+gsA6Qg2BJhSAnIgIgsg");
	this.shape_133.setTransform(542.1,60.1);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#FF3300").s().p("AhPBxQgMgOAAgfQAAg/Ang9QAqhGA6AAQAWAAALAKQAKALABASQgBATgNASQgNATgiAUQgRAJg3AYQgCAQAAAPQAAAUAGAJQAHAIANAAQALAAAOgHQATgJAmgcIAJANQhIBEgyAAQgVAAgKgOgAAEheQgMALgKAWQgOAggFAhQAugUAYgZQAQgRAAgQQAAgNgHgHQgGgIgLAAQgLAAgKAIg");
	this.shape_134.setTransform(518.5,59.7);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#FF3300").s().p("Aj0C6QgOgKAAgOQAAgGAFgFQAFgEAHgBQAJAAALAKQATARAPAAQARAAAQgOQAYgXAWhKQAbhWAZiIQgKAAgdAGQgdAFgTAMQgUAKgKARQgLARAAATQAAAKADAJQACAHAFAJQAHALAAAFQAAAHgFAFQgFAFgIAAQgLAAgIgMQgIgLAAgYQAAgnAUgbQAUgcAhgOQAVgJA8gIQAXgDATgFIAJAiQAKAwALAiQALAjAuB/IAShIQARhHAFgSQARg2APgZQAPgaATgLQATgMAXAAQATAAALAIQAKAHAAAKQAAAIgGAFQgFAGgHAAQgGAAgHgDIgRgGQgGgCgGAAQgOAAgKAKQgTARgWBEQgVBFgiCVIgKArQghhJgMgfQgQgqgTg+IgghlQgGAjgVBTIgaBgQgOAngPAVQgPAWgTAJQgSAJgWAAQgcABgRgMg");
	this.shape_135.setTransform(491,55.1);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#FF3300").s().p("AAHBHIAXhvQAFgXAGgIQAHgHAIAAQAGAAAEADQADADAAAGQAAAEgGARIgoByQgDAKgGAAQgIAAABgIgAhEBHIAXhvQAFgXAGgIQAHgHAJAAQAFAAAEADQADADAAAGQAAAEgGARIgnByQgEAKgGAAQgIAAABgIg");
	this.shape_136.setTransform(465.1,44.5);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#FF3300").s().p("AiHDCQgKgIAAgKQAAgIAIgHQAIgGANAAQAJAAASAEQASADAHAAQASAAAUgOQAagUAQgdQAQgcAAgdQAAgpgMg4QgMg6gUgeQgLgPgNAAQgOAAgbAUIgJgPIAWgOQAfgWANgGQAIgDAGAAQAGgBAEAIQAaAgASA3QARA3AAAzIAAAVQAxhbAAg1QAAgLgFgTQgFgUAAgJQAAgJAGgFQAFgFAIAAQAKgBAHAJQAGAHAAAPQAAAmgRA4QgSA4glBAQglBCgeAfQgeAggcANQgdANgaAAQgTAAgKgGg");
	this.shape_137.setTransform(82,478.1);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#FF3300").s().p("AAICAQgEgDAAgHIACgMIAMgnQgYAdgjAWQgVAOgSAAQgRgBgJgMQgNgPAAgaQAAggARgmQARglAbgfQAcgfAegPQAYgKAlgBIATABIAHgLIATgEIgWBKQgNAtgMA4QgGAfAAAKQAAAIAHABQAFgBAKgFQASgMARgPIAKALQgiAegJAHQgTAMgRAHQgLAEgLAAQgHAAgEgEgAgVhHQgUAOgQAmQgRAlAAAlQAAAUAGAJQAHAJALAAQAUAAAXgWQAXgWAKgpIAZhaQgQgDgLAAQgZAAgUAOg");
	this.shape_138.setTransform(60.4,470.4);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#FF3300").s().p("Ag3CwQgggDgcAAIgoABIAGgOQAbgCAHgDQAHgDAEgIQAJgNAOgtIAVhNIAXhfIACgMQAAgEgDgDQgDgCgFgBIgJABIADgMQAggDArgLQgNAhgKApIgSBRQgVBYgaAuQAZAFAUAAQAyAAAmgVQAmgWAWgpQAXgqAAgxQAAhBgmgnQgmgpg+AAQgzAAguAZQguAZgaAoQgbApAAAlQAAAmAhARQAJAGADADQADAFAAAFQAAAHgGAGQgFAFgHAAQgQAAgPgVQgUgcAAgfQAAgxAfgvQAdgvA2gcQA2gbBAgBQBRABAwAqQAwArAABCQAAA8ghAyQgiAzgvAWQgwAWgtAAQgQAAglgDg");
	this.shape_139.setTransform(26.7,465.4);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f().s("#0099FF").ss(15,1,1).p("AP+s7IhKABIreADIDrH6IKBVhQgJgIgJgHQoTnLoTnIQgHgGgFgGQjFioigiKQgUgRgTgQQpooShDg0QgJgHABABAPOtVIgaAbInzH9IgqAsImNGTIgEAEIrlL1Ij0D5AiLs2IACgGIB6kbIAUgwIAZg8IAcA8IAAABICcFPIhVAAIkMABIAAAAIuZADAv7TEIAihPIJI1MIADgGIEDpZ");
	this.shape_140.setTransform(584,367.9);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f().s("#FFFFFF").ss(15,1,1).p("Aw1uuQABgBAAAAQAKgIALgIQFOkAGvhAQB3gRB9gDQAXAAAXAAQAFAAAFAAQASAAATAAQAIABAIAAQB1ADBvAQQB7ATDzBtQCXBECrBbIAvAZQAyAeAeATQHLF9AAIZQAAIbnLF8QjrDEkeBfQhaAehfAUQi+AojSAAQjRAAi+goQhfgUhageQhgggilhfQhBglhGgtQgYgOgYgQIhOg0QnKl8AAobQAAoZHKl9QAPgNAOgLIgHgGAlllCIADgGIDcp6IACgGIBsk3IAOAcICQEgIEVImIKaUmIAIAPIwzucIlvk+IgnghIqppLAtNQ7IBzlMIF1wx");
	this.shape_141.setTransform(583.5,381.9);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f().s("#FF0000").ss(15,1,1).p("EBrbgXqIAeAAIAAEZEBr5gQlIAAD/EBr5AOtIAAI+MjXxAAAIAAh4");
	this.shape_142.setTransform(578.5,671.4);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f().s("#FFFF00").ss(15,1,1).p("APozcMBASAAAEBQLATdMg78AAAEhQKgTcMBWtAAAAB8TdMhSDAAA");
	this.shape_143.setTransform(512.5,378.4);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f().s("#009900").ss(15,1,1).p("EBP9ASwMhD6AAAIgQAAEhP1gSvMCgCAAAAKVSwMhahAAA");
	this.shape_144.setTransform(512.7,132);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#FFFFFF").s().p("AmPTsQhfgUhageQhgggilhfIBzlMILkr0IQzOdIgIgPIASAPIqB1hIHzn9IreADILegDInzH9IKBVhIgSgPIqZ0mIAqgsIjrn6IiclPICcFPIhVAAIiQkgIAUgwIgUAwIgOgbIhsE2IgCAGIAAAAIjdJ6IgmghIEDpZIuaADIOagDIkDJZIAmAhIgCAGIgnghIADgGQpooRhDg1QBDA1JoIRIgDAGIqppLIABgBIAUgQQFPkAGvg/QB3gSB9gDIAuAAIAKAAIAlAAIAQABQB1ADBvARQB7ARDzBuQCXBECrBaIAwAaQAyAdAeAUQHKF8AAIaQAAIanKF9QjsDEkeBfQhaAehfAUQi+AojSAAQjRAAi+gogAO5vGIBKgBIhKABIAagbIgaAbgAvUPpIJI1MIAnAhIl1QxIj0D5ID0j5IhzFMQhBglhGgtgAvUPpIgvgeIhPg0QnKl9AAoaQAAoaHKl8IAdgYIKpJLIpIVMIAAAAgAAKgFIAFgEIQmOSIAIAPgAQ1OJIAAAAgAQ1OJIwmuSIGNmUIKZUmIAAAAgAraLvIF1wxIFvE9IrkL0gAAKgFIlvk9IACgGIFkEzIAOAMIgFAEgAAPgJIAAAAgAABgVIlkkzIDdp6IEMgBIEWImImNGUIgOgMgAAPgJIAAAAgAlllCgAljlIIAAAAgAGcmdIkWomIBVAAIDrH6IgqAsgAw1uugAiGvCgAiGvCIACgGIB6kbICQEgIkMABgAiGvCIACgGIgCAGgADbvDgAO5vGgAiEvIIBsk2IAOAbIh6EbgAgKzjg");
	this.shape_145.setTransform(583.5,381.9);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#FF0000").s().p("EhqeAXrIhaAAIAAmeIAaACIgCiAIAKB8QBkAEBggMQAZARAbgGQAFgcAbgLIgDAkIAvADQAMhDgChdIAAgPQBcBwBQB+QgGBTBDAlIBkAAQBbg8BahAQCmh0BIidIAAACQgCApASAOQAOAMAUgGQAUgHAKgRQAIgOAEgVQABgNAAgZQgBiPAEhIQADgkATiYQAOhzgChKQgBg9gLhiQgRh9gCghQgGhRACiPIAIksQAGj0ABiVQACkvgUjvMBU5AAAQC+AoDRAAQDSAAC+goMA+0AAAQAAArAEAvQACAUgCAUIAJg8IABACIgUIkIAHAKIgCAMQgHBHAHCGQgICgAHCcIgIA6QgIBEAEAuQACAeAJAoIANA6IgDAQQgBAIABASQABAPgBAKQgCAMgHAWQgCAKABAPIABAYIgBAZQgBANADAKQACAJAFAJIAGDtIgGCdIgFBgQgCAlgEASQgCANgZBIQgRAzAFAiQACAMAGAKQAIALAKgBQAJAAAHgIQAEgFACgHQAEA7AFA7QACAPAGAFQAGAEAIgBQAIgDAFgGQAGgJABgVIABgTIBYAKIARgJQATA0AZAvQHbgnHkgOQHwgZHdBCQBpAOBmgHIAAG9gEhpBAOGQAEACAIgCQAJgCADABQAIACAEAOIAJAhQAFAUABAJQACAYgPAVQgPAVgXAHgEhr4AEWIAPAXQgJAFgGAJgEhZrgH3IAAAEQADArgBAhIgCAUIAAhkgEhZ1gONIACALQAAALAAARIgCgng");
	this.shape_146.setTransform(569.5,659.4);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#009900").s().p("AMJSwIgcg8IgZA8IgKAAIgvAAMhagAAAQgBg6gHguIgHguQAIlaAEliQADl8AKmFQAEikACikQAHgRANgPQgBhVgShNIAAgbIAJgLQAIhwgMhsMCgBAAAIAAFKQgvEQAlEWIgKg8IAOE0QgIAigDAnQgDAnABBMQAEDxgEHjQABAuAGAWQAGAOAJAMQgFA6gIA5IAFBzQgGARgEASgAL5SwIglAAIAZg8IAcA8g");
	this.shape_147.setTransform(512.1,132);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.f("#FFFF00").s().p("AUUTdQEehfDsjEQHKl9AAoaQAAoanKl9QgegTgygdIgwgaQirhaiXhEQjzhuh7gSMBASAAAQgKA5AJA/IABAKIACAAIAACRQgBAlALARIAEAFIgHBWQgIBegCAwQgEBFgBBoIgCCbQgGF2AAC8QAAE4AKD6QADBHAEAlQAEAuAKAmQgCCBACCKIgBAQgEhQBATdIgHhCIACgRQAChDgChCQgBgRADgKIAKgTQAHgLgBgIQgBgHgFgFQAFgGAAgJIgBgGIACgKQAKgpADgeQAEgqgEg1IgLheIgJhRIACgBQALgEADgJQACgHgGgUQgFgSACgiQABglgCgPIgGgYIgGgWIgEgYIgBhuIgCimQALg/AQhuQAHgzAAgaQgBgYgHgkIgMg8QgFgjAAguIABhSQAEingMiiIAAgGQgBgagDggQgIhXAAgaQAAguAPhLQAEgZgCgKQgDgKgIgFIgBgBQAEgLABgUIAChbMBWsAAAQmuA/lOEBIgVAQIgBgBIgBAAIgBgBIgFgEIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIAFAEIABABIABAAIABABIgBABIgHgHIAHAHIgdAXQnKF9AAIaQAAIaHKF9IBPA0IAvAeQBGAsBBAmQCkBfBgAggAkrRbIAihPgAlpuMIAAAAg");
	this.shape_148.setTransform(512,378.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5,p:{x:592.7,y:409.6}},{t:this.shape_4},{t:this.shape_3,p:{x:638.3,y:409.7}},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).to({state:[{t:this.instance_1},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19}]},10).to({state:[{t:this.instance_2},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_5,p:{x:162.7,y:704.9}},{t:this.shape_82},{t:this.shape_3,p:{x:208.3,y:705}},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49}]},10).to({state:[{t:this.shape_148},{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87}]},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(395.1,525.5,1009.4,491);
// library properties:
lib.properties = {
	id: '4B0722EC2C02AB4C90BD02142E4F170A',
	width: 1024,
	height: 768,
	fps: 10,
	color: "#444444",
	opacity: 1.00,
	manifest: [
		{src:"images/AnimatedCard_YAsefa_atlas_.png?1525131777384", id:"AnimatedCard_YAsefa_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4B0722EC2C02AB4C90BD02142E4F170A'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;